crowbar/crowbar-openstack

chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/cookbooks/neutron/recipes/cisco_apic_support.rb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb

This commit fixes minor issues encountered while testing ACI
integration with SUSE OpenStack Cloud 7. The ACI changes were
so far only being tested for Cloud 6 on the Cisco Lab.
Also recent changes in the crowbar framework caused failures while
applying the barclamp by enabling APIC as the ML2 backend.
The fixes include:
- config setting for of_interface
- modified path for linking ml2_conf_cisco_apic.ini
These changes were tested with Cloud7 on the Cisco ACI lab for L2 and L3
functionality and also shared with the Sales Engineering team.
So the commit needs to be merged with Cloud7 so PTFs can be
generated if required by customers wanting to upgrade from
Cloud6 to Cloud7. The changes are not tested against Cloud8

neutron: Fixes for ACI integration - updates for Newton and later

---

chef/cookbooks/aodh/metadata.rb
chef/cookbooks/ceilometer/metadata.rb
chef/cookbooks/heat/metadata.rb
chef/cookbooks/horizon/metadata.rb
chef/cookbooks/memcached/metadata.rb
chef/cookbooks/mysql/metadata.rb
chef/cookbooks/nova/metadata.rb
chef/cookbooks/rabbitmq/metadata.rb
chef/cookbooks/swift/metadata.rb
chef/cookbooks/tempest/metadata.rb

There is no reason to not have the name in all the cookbooks metadata
and it collides when using tools as some tools use the metadata name for
identification instead of just resorting to the directory name.
Plus it makes all cookbooks have the similar base metadata
Also removes 2 instances of recommends in the metadata as they are
useless. recommends and suggests do nothing on anything related to
chef-client or chef-server and they are deprecated due to this[0]
[0] https://chef.github.io/chef-rfc/rfc085-remove-unused-metadata.html

chef: add name to metadata and remove recommends

---

chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/cookbooks/neutron/recipes/cisco_apic_support.rb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb

This commit fixes minor issues encountered while testing ACI
integration with SUSE OpenStack Cloud 7. The ACI changes were
so far only being tested for Cloud 6 on the Cisco Lab.
Also recent changes in the crowbar framework caused failures while
applying the barclamp by enabling APIC as the ML2 backend.
The fixes include:
- config setting for of_interface
- modified path for linking ml2_conf_cisco_apic.ini
These changes were tested with Cloud7 on the Cisco ACI lab for L2 and L3
functionality and also shared with the Sales Engineering team.
So the commit needs to be merged with Cloud7 so PTFs can be
generated if required by customers wanting to upgrade from
Cloud6 to Cloud7.
(cherry picked from commit b495b6f5312a1823566e530db1195001b2611138)

neutron: Fixes for ACI integration with SOC7 (backport from #1323)

---

chef/cookbooks/keystone/recipes/server.rb

Increase the timeout of the keystone_register sync mark
from 90 to 150 seconds, to fix the timeout errors occurring
during the deployment of the keystone barclamp in HA configurations.
This fixes some of the HA failures occurring intermittently in the cloud 8 HA
Jenkins jobs (e.g. [cloud-mkcloud8-job-ha-compute-x86_64 #88028](https://ci.suse.de/job/openstack-mkcloud/88028/) - during which, the time it took the founder node to configure the keystone resources was ~ 110 sec)

keystone: increase keystone_register timeout

---

chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/data_bags/crowbar/migrate/ceilometer/203_add_default_api_return_limit.rb
chef/data_bags/crowbar/template-ceilometer.json
chef/data_bags/crowbar/template-ceilometer.schema

The ceilometer admin dashboard in horizon doesn't specify a limit for the number of entries returned by ceilometer API calls, in which case the `[api]/default_api_return_limit` configuration option is used to limit the number of returned entries.
The default value of this option is 100, which may be too small in cases where the ceilometer database has a large number of entries (meters, samples, etc).
Making this option configurable as a raw attribute gives the crowbar admin another parameter that can be used to adjust ceilometer to larger environments.
Fixes [bsc#1046787](https://bugzilla.suse.com/show_bug.cgi?id=1046787)
NOTE: this option doesn't actually impact the horizon UI in SOC8 because the ceilometer dashboard has been removed in Pike.

ceilometer: configurable default_api_return_limit (bsc#1046787)

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/data_bags/crowbar/migrate/database/206_add_bootstrap_timeout.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

Some system (especially with a huge amount of RAM) need more time for
bootstrapping. Increase the default timeout and make it configurable as
a barclamp attribute.

galera: Turn boostrap timeout into a proposal attribute

---

chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/data_bags/crowbar/migrate/ceilometer/106_add_default_api_return_limit.rb
chef/data_bags/crowbar/template-ceilometer.json
chef/data_bags/crowbar/template-ceilometer.schema

(backports #1409)
The ceilometer admin dashboard in horizon doesn't specify a limit for the number of entries returned by ceilometer API calls, in which case the `[api]/default_api_return_limit` configuration option is used to limit the number of returned entries.
The default value of this option is 100, which may be too small in cases where the ceilometer database has a large number of entries (meters, samples, etc).
Making this option configurable as a raw attribute gives the crowbar admin another parameter that can be used to adjust ceilometer to larger environments.
Fixes [bsc#1046787](https://bugzilla.suse.com/show_bug.cgi?id=1046787)

[4.0] ceilometer: configurable default_api_return_limit

---

chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/barbican/recipes/common.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/cinder/recipes/sql.rb
chef/cookbooks/database/libraries/provider_database_mysql.rb
chef/cookbooks/database/libraries/provider_database_mysql_user.rb
chef/cookbooks/ec2-api/recipes/ec2api.rb
chef/cookbooks/glance/recipes/common.rb
chef/cookbooks/heat/recipes/server.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb
chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/magnum/recipes/sql.rb
chef/cookbooks/manila/recipes/sql.rb
chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/neutron/recipes/database.rb
chef/cookbooks/nova/recipes/database.rb
chef/cookbooks/sahara/recipes/sql.rb
chef/cookbooks/trove/recipes/sql.rb

With this settings, non-SSL access is forbidden for the affected
users.
This is based on @s-t-e-v-e-n-k patch. 
**NOTE**: 
- db_maker access does not work for insecure connection, requires this fix in rubygem-mysql2:
https://github.com/brianmario/mysql2/pull/889
- currently present in our rubygem package

Require SSL connection to database if MariaDB SSL is configured

---

chef/cookbooks/neutron/recipes/common_agent.rb

On compute nodes, the `additional_external_networks` barclamp attribute used to configure custom neutron external networks was improperly taken from the local chef node instead of the remote 'neutron-network' node.
When used in combination with a DVR enabled setup, which requires the external networks to be present on compute nodes too, this mishap basically caused the custom external networks to be unreachable without a clear error indication in the neutron logs.
Fixes: [bsc#1066171](https://bugzilla.suse.com/show_bug.cgi?id=1066171)

neutron: fix additional external nets on compute nodes

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/data_bags/crowbar/migrate/database/106_add_bootstrap_timeout.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

Some system (especially with a huge amount of RAM) need more time for
bootstrapping. Increase the default timeout and make it configurable as
a barclamp attribute.
(cherry picked from commit edd60a151069b6a730f5b8d1bb3a0af987c0d2ec)
Backport of: https://github.com/crowbar/crowbar-openstack/pull/1407

[stable/4.0] galera: Turn boostrap timeout into a proposal attribute

---

chef/cookbooks/manila/recipes/api.rb
chef/cookbooks/manila/recipes/controller_ha.rb

The current release of manila no longer supports running the API service
directly while using SSL, and instead requires the use of WSGI.
---
I'm not certain this correct for HA, it deploys, but only one of the clone sets runs successfully because it binds to the VIP.

manila: Switch manila-api to run under WSGI

---

chef/cookbooks/neutron/recipes/common_agent.rb

(backports #1411)
On compute nodes, the `additional_external_networks` barclamp attribute used to configure custom neutron external networks was improperly taken from the local chef node instead of the remote 'neutron-network' node.
When used in combination with a DVR enabled setup, which requires the external networks to be present on compute nodes too, this mishap basically caused the custom external networks to be unreachable without a clear error indication in the neutron logs.
Fixes: [bsc#1066171](https://bugzilla.suse.com/show_bug.cgi?id=1066171)

[3.0] neutron: fix additional external nets on compute nodes

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/definitions/neutron_metadata.rb
chef/cookbooks/neutron/recipes/network_agents.rb

Because the dhcp/lbaasv2/metadata agents are started with an explicit
"--config-file /etc/neutron/$foo_agent.ini" flag, options in this file
will override everything that is being set in config snippets.
So do not generate /etc/neutron/$foo_agent.ini files, but instead config
snippets.
Co-Authored-By: Tom Patzig <tom.patzig@sap.com>

neutron: Fix config snippet support for neutron agents

---

chef/cookbooks/neutron/recipes/common_agent.rb

(backports #1411)
On compute nodes, the `additional_external_networks` barclamp attribute used to configure custom neutron external networks was improperly taken from the local chef node instead of the remote 'neutron-network' node.
When used in combination with a DVR enabled setup, which requires the external networks to be present on compute nodes too, this mishap basically caused the custom external networks to be unreachable without a clear error indication in the neutron logs.
Fixes: [bsc#1066171](https://bugzilla.suse.com/show_bug.cgi?id=1066171)

[4.0] neutron: fix additional external nets on compute nodes

---

chef/cookbooks/nova/recipes/flavors.rb

**nova: improve flavors creation performance**
- reusing the output of flavor-list
- subscribes and not_if are independent
as a result the block will always try to create the flavors even if
they exist
This saves about 15-20 secs on non-shared hardware and about 1min on a
loaded CI
**nova: create flavors via the internal endpoint**
This is consistent with every other openstack related usage
in the chef recipies. we want to avoid traffic going over
public unnecessary in case public is unreachable or broken.
Backport of https://github.com/crowbar/crowbar-openstack/pull/1348 and https://github.com/crowbar/crowbar-openstack/pull/1400

[4.0] Backport flavor creation fixes / improvements

---

crowbar_framework/app/models/nova_service.rb

By using skip_batch_for_node? we can avoid running chef on nodes that do
not change role and if there is no attribute change for the barclamp.
Does not skip remote HA nodes, nodes that have changed roles, all nodes if
attributes have changed and when deploying the barclamp for the first
time.
Stolen from https://github.com/vuntz/crowbar-openstack/commit/5cf4e69dadfd1ac804b75b4a8bd2a0f4b2248277
Requires https://github.com/crowbar/crowbar-core/pull/1374

nova: skip unchanged nodes chef-run

---

Rakefile

Looks like travis installs all gems to the vendor dir,
that means that the syntaxcheck will check all the ruby files
under that directory, slowing down the travis work for no reason.
This removes any rb files coming from under the vendor directory
(cherry picked from commit 1259a87bd6908ef6528fdfb52f1035a2a857e017)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1076

[4.0] rakefile: avoid doing the syntaxcheck on vendor dir

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/definitions/neutron_metadata.rb
chef/cookbooks/neutron/recipes/network_agents.rb

Because the dhcp/lbaasv2/metadata agents are started with an explicit
"--config-file /etc/neutron/$foo_agent.ini" flag, options in this file
will override everything that is being set in config snippets.
So do not generate /etc/neutron/$foo_agent.ini files, but instead config
snippets.
Backport of https://github.com/crowbar/crowbar-openstack/pull/1419

[4.0] Fix config snippet support for neutron agents

---

chef/cookbooks/aodh/templates/default/aodh.conf.erb
chef/cookbooks/barbican/templates/default/barbican.conf.erb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/glance/templates/default/glance-registry.conf.erb
chef/cookbooks/heat/templates/default/heat.conf.erb
chef/cookbooks/ironic/templates/default/ironic.conf.erb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/manila/templates/default/manila.conf.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/cookbooks/sahara/templates/default/sahara.conf.erb
chef/cookbooks/trove/templates/default/trove.conf.erb

The default is 3 seconds, which is very high. When one memcached server
goes down, then every connection pool for memcached (in each process, on
each node) need to identify that this server is down, and that has some
dramatic impact on performance.
Lowering this to 1 second, while still being a reasonable value, helps
quite a bit. I would even consider lowering this to 0.25, but oslo.cache
doesn't support float values there (see
https://bugs.launchpad.net/oslo.cache/+bug/1731921).
Helps with https://bugzilla.suse.com/show_bug.cgi?id=1038223

Set socket_timeout for memcached connections to 1s

---

crowbar_framework/app/views/barclamp/neutron/_edit_attributes.html.haml
crowbar_framework/config/locales/neutron/en.yml

dhcp_domain got renamed to dns_domain in 05eb713d, but the UI was not
updated.

neutron: Complete renaming to dns_domain

---

chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/mysql/templates/default/galera-python-clustercheck-my.cnf.erb
chef/cookbooks/mysql/templates/default/galera-python-clustercheck.conf.erb

By using a script provided in the galera-python-clustercheck package we
are able to ensure a node is in sync with the galera cluster rather
than the previously superficial check of just ensuring mysql is running.
Install the package and configure it to use the monitoring user.
This depends on https://github.com/crowbar/crowbar-ha/pull/277.
This is not usable in this branch until the galera-python-clustercheck
package is made available. However, some people may want to manually
install that package from OBS, and they can do so by simply setting an
attribute (not in the barclamp, but as an override attribute in the
cookbook).
Backport of https://github.com/crowbar/crowbar-openstack/pull/1277 with an additional commit to block the feature unless explicitly enabled.

[4.0] Use httpchk in haproxy for galera (requires manual enablement from user)

---

chef/cookbooks/nova/recipes/database.rb

This can take several seconds on slow systems, and there's another
condition in the if statement after this one that can be false and that
doesn't require some program to run, so put this condition last.

nova: Don't uselessly run "nova-manage db version"

---

chef/cookbooks/neutron/files/default/sysctl-neighbour-table-overflow.conf

On very large deployments, we hit limits in the ARP table again, so
let's bump the settings again. We don't bump gc_thresh1 as it's about
the minimum number of entries to keep and the value there is already
high.
For original background on these settings, see 0583a0c9.

neutron: Bump gc_thresh2 and gc_thresh3 sysctl

---

chef/cookbooks/nova/recipes/database.rb

This can take several seconds on slow systems, and there's another
condition in the if statement after this one that can be false and that
doesn't require some program to run, so put this condition last.
(cherry picked from commit 00b13e017b8c976a4477d0d23799f9218026bd79)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1433

[4.0] nova: Don't uselessly run "nova-manage db version"

---

chef/cookbooks/neutron/files/default/sysctl-neighbour-table-overflow.conf

On very large deployments, we hit limits in the ARP table again, so
let's bump the settings again. We don't bump gc_thresh1 as it's about
the minimum number of entries to keep and the value there is already
high.
For original background on these settings, see 0583a0c9.
(cherry picked from commit 3dd21ea62ac152e40bfdfee4b8e25a528c82a79f)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1430

[4.0] neutron: Bump gc_thresh2 and gc_thresh3 sysctl

---

chef/cookbooks/keystone/templates/default/keystone.conf.erb

The default is 3 seconds, which is very high. When one memcached server
goes down, then every connection pool for memcached (in each process, on
each node) need to identify that this server is down, and that has some
dramatic impact on performance.
Lowering this to 1 second, while still being a reasonable value, helps
quite a bit. I would even consider lowering this to 0.25, but oslo.cache
doesn't support float values there (see
https://bugs.launchpad.net/oslo.cache/+bug/1731921).
Helps with https://bugzilla.suse.com/show_bug.cgi?id=1038223
(cherry picked from commit 1c2bfed21f6e58643a82880c89356bbc7336e2a1)
Partial backport of https://github.com/crowbar/crowbar-openstack/pull/1429 (the other commit is not relevant for stable/4.0)

[4.0] keystone: Set cache/memcache_socket_timeout = 1

---

chef/cookbooks/aodh/templates/default/aodh.conf.erb
chef/cookbooks/barbican/templates/default/barbican.conf.erb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/glance/templates/default/glance-registry.conf.erb
chef/cookbooks/heat/templates/default/heat.conf.erb
chef/cookbooks/ironic/templates/default/ironic.conf.erb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/manila/templates/default/manila.conf.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/cookbooks/sahara/templates/default/sahara.conf.erb
chef/cookbooks/trove/templates/default/trove-conductor.conf.erb
chef/cookbooks/trove/templates/default/trove-taskmanager.conf.erb
chef/cookbooks/trove/templates/default/trove.conf.erb
chef/data_bags/crowbar/migrate/rabbitmq/201_heartbeat_timeout.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

This will be used to configure the heartbeat timeout for clients
connecting to rabbitmq. See https://www.rabbitmq.com/heartbeats.html for
details about heartbeats.
The default used by oslo.messaging is 60 seconds, which is extremely
high. There are various recommendations out there, the rabbitmq website
has two different ranges: 5-20s [1] and 8-20s [2]. Another
recommendation is 6-12s. 10s is within these ranges, so it's a good pick
for now. Some setups may want to be more aggressive here, hence the
attribute to allow this.
[1] https://www.rabbitmq.com/heartbeats.html
[2] https://www.rabbitmq.com/networking.html
[3] http://openstack-qe-guy.blogspot.fr/2015/11/rabbitmq-best-practices.html

Set heartbeat_timeout_threshold to improve recovery when one rabbitmq node goes down

---

chef/cookbooks/aodh/templates/default/aodh.conf.erb
chef/cookbooks/barbican/templates/default/barbican.conf.erb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/glance/templates/default/glance-registry.conf.erb
chef/cookbooks/heat/templates/default/heat.conf.erb
chef/cookbooks/ironic/templates/default/ironic.conf.erb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/manila/templates/default/manila.conf.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/cookbooks/sahara/templates/default/sahara.conf.erb
chef/cookbooks/trove/templates/default/trove-conductor.conf.erb
chef/cookbooks/trove/templates/default/trove-taskmanager.conf.erb
chef/cookbooks/trove/templates/default/trove.conf.erb
chef/data_bags/crowbar/migrate/rabbitmq/103_heartbeat_timeout.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

This will be used to configure the heartbeat timeout for clients
connecting to rabbitmq. See https://www.rabbitmq.com/heartbeats.html for
details about heartbeats.
The default used by oslo.messaging is 60 seconds, which is extremely
high. There are various recommendations out there, the rabbitmq website
has two different ranges: 5-20s [1] and 8-20s [2]. Another
recommendation is 6-12s. 10s is within these ranges, so it's a good pick
for now. Some setups may want to be more aggressive here, hence the
attribute to allow this.
[1] https://www.rabbitmq.com/heartbeats.html
[2] https://www.rabbitmq.com/networking.html
[3] http://openstack-qe-guy.blogspot.fr/2015/11/rabbitmq-best-practices.html
Backport of https://github.com/crowbar/crowbar-openstack/pull/1434

[4.0] Set heartbeat_timeout_threshold to improve recovery when one rabbitmq node goes down

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/templates/default/galera.cnf.erb

(bsc#1068393)
(cherry picked from commit 427f9c85b1e9d7a84becff1cbe4bb6cc0bc90ee1)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1442

[4.0] mysql: Make sure mysqld listens on admin ip for cluster traffic

---

chef/cookbooks/barbican/recipes/ha.rb

Fixes misspelling of keystone-listener in barbican services list
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1444

[4.0] barbican: Fixes misspelling of keystone-listener

---

chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
chef/cookbooks/rabbitmq/templates/default/ocf-promote.erb
chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

**rabbitmq: Create a definitions file to load on startup**
This ensures we always have the right user/password, vhost, policies,
etc. on startup.
The benefit is mostly visible with clustered rabbitmq, because in case
of bad failures, the OCF resource agent can reset everything, which
leads to a setup without the expected setup.
**rabbitmq: Set policy_file for OCF resource agent**
We use a file that is sourced from the OCF resource agent on promote to
ensure the cluster name is correctly set. This can matter when
everything has been completely reset after some critical failure.

rabbitmq: Add more persistence for critical data

---

chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
chef/cookbooks/rabbitmq/templates/default/ocf-promote.erb
chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

**rabbitmq: Create a definitions file to load on startup**
This ensures we always have the right user/password, vhost, policies,
etc. on startup.
The benefit is mostly visible with clustered rabbitmq, because in case
of bad failures, the OCF resource agent can reset everything, which
leads to a setup without the expected setup.
**rabbitmq: Set policy_file for OCF resource agent**
We use a file that is sourced from the OCF resource agent on promote to
ensure the cluster name is correctly set. This can matter when
everything has been completely reset after some critical failure.
Backport of https://github.com/crowbar/crowbar-openstack/pull/1448

[4.0] rabbitmq: Add more persistence for critical data

---

chef/cookbooks/cinder/recipes/api.rb
chef/cookbooks/cinder/recipes/scheduler.rb
chef/cookbooks/cinder/recipes/volume.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/postgresql/recipes/server.rb
chef/cookbooks/postgresql/templates/default/limits.erb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/limits.erb
chef/data_bags/crowbar/migrate/cinder/052_add_resource_limits.rb
chef/data_bags/crowbar/migrate/database/005_add_resource_limits.rb
chef/data_bags/crowbar/migrate/horizon/039_add_resource_limits.rb
chef/data_bags/crowbar/migrate/keystone/036_add_resource_limits.rb
chef/data_bags/crowbar/migrate/rabbitmq/012_add_resource_limits.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema
chef/data_bags/crowbar/template-horizon.json
chef/data_bags/crowbar/template-horizon.schema
chef/data_bags/crowbar/template-keystone.json
chef/data_bags/crowbar/template-keystone.schema
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

Some services require modifications to the system resource limits, such
as the maximum number of open files, that we cannot necessarily predict
a reasonable default for. Without this patch, there is no way to control
those limits from crowbar and they must be changed manually. This patch
adds a resource_limits parameter to a few barclamps to allow
administrators to set these limits for specific services from the
barclamp that controls those services. Currently only the LimitNOFILE
(systemd's name for the maximum number of open files) limit is supported.
This pull request is split into four commits and it will be easiest to review them each one at a time.
1. Create a systemd_override LWRP and use it in the cinder barclamp.
2. Use the same LWRP in the keystone and horizon barclamps to …

[3.0] Add resource limit controls (bsc#1020922)

---

crowbar_framework/app/models/nova_service.rb

Using the wrong attribute name node_name instead of node

nova: fix wrong attribute

---

crowbar_framework/app/models/nova_service.rb

Using the wrong attribute name node_name instead of node
(cherry picked from commit 98dcf36d622350884ac5c52c66a38ced5bc3c668)
backport-of: https://github.com/crowbar/crowbar-openstack/pull/1454

[4.0] nova: fix wrong attribute

---

chef/cookbooks/barbican/attributes/default.rb

Removes unreferenced pacemaker monitor interval from the barbican
cookbook
Follow up to the code removal in 722dfb098aed3fa503b7f41f07627b90a5914d4a

barbican: Removes unreferenced monitor interval

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/mysql/templates/default/galera.cnf.erb
chef/cookbooks/mysql/templates/default/tuning.cnf.erb
chef/data_bags/crowbar/migrate/database/107_add_more_tuning.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

mysqltuner suggests some configuration changes for better performance,
but they might not be best for everyone. So we add new proposal
variables for the users to tune the config.
- InnoDB flush log at each commit might be disabled.
- For wsrep_slave_threads, documentation says
"as a rough guideline consider using twice the number of CPU cores"
but that might not make sense for single writer setup we're offering.
So let's keep the default and let user decide
- gcs.limit should be equal to 5 * wsrep_slave_threads (mysqltuner.pl)
- skip_name_resolve to avoid DNS resolution on connection.
(cherry picked from commit cf8ff9d8cf78439b371c37f1994bd762e137e336)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1410

[4.0] mysql: Further config file tuning based on mysqltuner suggestions

---

crowbar_framework/app/models/nova_service.rb

**nova: Fix apply with skip_unchanged_nodes**
When there's absolutely no node impacted by the "apply" thanks to
skip_unchanged_nodes, then we hit some old micro-optimization in
apply_role_pre_chef_call that was not intended to be used that way: we
skip the whole method.
Unfortunately, we do need to run the method even with
skip_unchanged_nodes because we need to ensure that attributes, like the
HA related ones, are set.
**nova: Do not reset sync marks uselessly with skip_unchanged_nodes**
If skip_unchanged_nodes results in some control nodes to be skipped,
then we don't want to reset the sync marks as we will not run chef
through the apply. If we do the reset, then we will rely on periodic
chef runs to set the sync marks, which will take time to converge as
there's no guarantee that the …

nova: Fix issues related to the use of skip_unchanged_nodes

---

chef/cookbooks/postgresql/recipes/ha_storage.rb
chef/cookbooks/rabbitmq/recipes/ha.rb

As explained in [1][2], we need to set a different monitor interval for the
slaves and the master, otherwise one of them won't be monitored.
[1] https://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/_monitoring_multi_state_resources.html
[2] https://www.linbit.com/en/drbd-monitor-intervals/
Requires https://github.com/crowbar/crowbar-ha/pull/282

postgresql/rabbitmq: Fix drbd setup to monitor master and slaves

---

chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

First commit ensures that we monitor both the master and the slaves.
Second commit adjusts the resource configuration to match what is documented upstream.

rabbitmq: Improvements for clustered HA

---

chef/cookbooks/postgresql/recipes/ha_storage.rb
chef/cookbooks/rabbitmq/recipes/ha.rb

As explained in [1][2], we need to set a different monitor interval for the
slaves and the master, otherwise one of them won't be monitored.
[1] https://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/_monitoring_multi_state_resources.html
[2] https://www.linbit.com/en/drbd-monitor-intervals/
Requires https://github.com/crowbar/crowbar-ha/pull/283
Backport of https://github.com/crowbar/crowbar-openstack/pull/1464

[4.0] postgresql/rabbitmq: Fix drbd setup to monitor master and slaves

---

crowbar_framework/app/models/nova_service.rb

**nova: Fix apply with skip_unchanged_nodes**
When there's absolutely no node impacted by the "apply" thanks to
skip_unchanged_nodes, then we hit some old micro-optimization in
apply_role_pre_chef_call that was not intended to be used that way: we
skip the whole method.
Unfortunately, we do need to run the method even with
skip_unchanged_nodes because we need to ensure that attributes, like the
HA related ones, are set.
**nova: Do not reset sync marks uselessly with skip_unchanged_nodes**
If skip_unchanged_nodes results in some control nodes to be skipped,
then we don't want to reset the sync marks as we will not run chef
through the apply. If we do the reset, then we will rely on periodic
chef runs to set the sync marks, which will take time to converge as
there's no guarantee that the …

[4.0] nova: Fix issues related to the use of skip_unchanged_nodes

---

chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

First commit ensures that we monitor both the master and the slaves.
Second commit adjusts the resource configuration to match what is documented upstream.
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1463

[4.0] rabbitmq: Improvements for clustered HA

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/templates/default/neutron-server.erb

With ml2_conf.ini explicitly passed to neutron-server (via plugin.ini
symlink) it was impossible to change some ml2 settings using config snippets.
Same file is used in other commands e.g. neutron-ovs-cleanup.
With this change, the original file is empty and the contents is moved
to /etc/neutron/neutron.conf.d/ for easier overriding.
Second commit includes similar change for nsx.ini and cleanup of plugin.ini logic.

neutron: Move ml2_conf.ini to config snippet + remove plugin.ini

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/templates/default/neutron-server.erb

With ml2_conf.ini explicitly passed to neutron-server (via plugin.ini
symlink) it was impossible to change some ml2 settings using config snippets.
Same file is used in other commands e.g. neutron-ovs-cleanup.
With this change, the original file is empty and the contents is moved
to /etc/neutron/neutron.conf.d/ for easier overriding.
Second commit includes similar change for nsx.ini and cleanup of plugin.ini logic.
Backport from https://github.com/crowbar/crowbar-openstack/pull/1466

[4.0] neutron: Move ml2_conf.ini to config snippet + remove plugin.ini

---

chef/cookbooks/horizon/files/default/grafana-monasca.json
chef/cookbooks/horizon/files/default/grafana-openstack.json
chef/cookbooks/horizon/libraries/helper.rb
chef/cookbooks/horizon/providers/grafana_datasource.rb
chef/cookbooks/horizon/recipes/monasca_ui.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/resources/grafana_datasource.rb
chef/cookbooks/horizon/templates/default/_80_monasca_ui_settings.py.erb
chef/cookbooks/horizon/templates/default/grafana.ini.erb
chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb

This commit adds support for Grafana 4 to the Horizon barclamp.
This allows us to switch from our local Grafana 1.5 fork to
upstream Grafana 4 for the Monasca metrics dashboards.
It makes the following changes:
* Configure and deploy standalone grafana service
* Create a ProxyPass path on the Apache server to transparently
proxy requests to standalone Grafana
* Add a new dashboard_fqdn setting for the Horizon barclamp that
allows users to communicate the public Horizon endpoint's FQDN to
Grafana (needed for proxying to work). If this is not set,
Crowbar will fall back to the public cluster IP address in an HA
cloud and to the dashboard node's public IP address.
Note: while basic functionality is there already, this still needs some more work, notably a mechanism for configuring the …

horizon: use Grafana 4

---

chef/cookbooks/monasca/attributes/default.rb
chef/cookbooks/monasca/providers/agent_plugin_libvirt.rb
chef/cookbooks/monasca/recipes/master.rb
chef/cookbooks/monasca/recipes/server.rb
chef/cookbooks/monasca/resources/agent_plugin_libvirt.rb
chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
chef/cookbooks/nova/recipes/monitor_monasca.rb
chef/cookbooks/nova/recipes/role_nova_compute_kvm.rb
chef/cookbooks/nova/recipes/role_nova_compute_qemu.rb
chef/cookbooks/nova/recipes/role_nova_compute_xen.rb
chef/data_bags/crowbar/migrate/monasca/200_add_libvirt_plugin_settings.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema
crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
crowbar_framework/config/locales/monasca/en.yml

This pull request enables libvirt monitoring for `monasca-agent`. I haven't tested it, yet (first I need to get monasca-setup working on `stable/ocata`...), so very much WIP for now...

monasca: enable libvirt monitoring

---

chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb
chef/data_bags/crowbar/migrate/rabbitmq/202_add_mnesia_dump_log.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

As shown on big deployments, we sometimes get the warning
that mnesia is overloaded. This usually occurs when we are
dumping the log too fast and mnesia is receiving too many
messages so it cant catch up.
To fix this, we should increase the number of writes to the
transaction log before a dump is done (default is 100).
Together with this we also want to configure the maximum dump
log interval, in case the write treshold is set too high, this
will trigger a dump every X milliseconds, so we can be sure
that we are not losing anything if there is a period of low
writes or the treshold is set to high (default is 3 minutes)
Increasing the write treshold and reducing a bit the dump time
should help with mnesia being overloaded and prevent any
unintended consecuences from the overload.

rabbit: add mnesia dump log config

---

chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

We do care about data integrity, and the default setting is "ignore"
which can result in inconsistencies when the partition is over.
For two-node clusters, "pause_minority" doesn't work as it would require
the two nodes to always be up, which prevents any maintenance on a node.
But pacemaker should help here (with the fencing), so we keep the default
behavior and we don't add any safety net at the rabbitmq level.
See https://www.rabbitmq.com/partitions.html for more details
(cherry picked from commit a4aaeccc1ffcf480dcde14ccd1b430e1621e6f98)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1477

[4.0] rabbitmq: Use pause_minority setting to deal with partitions better

---

chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb
chef/data_bags/crowbar/migrate/rabbitmq/104_add_mnesia_dump_log.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

As shown on big deployments, we sometimes get the warning
that mnesia is overloaded. This usually occurs when we are
dumping the log too fast and mnesia is receiving too many
messages so it cant catch up.
To fix this, we should increase the number of writes to the
transaction log before a dump is done (default is 100).
Together with this we also want to configure the maximum dump
log interval, in case the write treshold is set too high, this
will trigger a dump every X milliseconds, so we can be sure
that we are not losing anything if there is a period of low
writes or the treshold is set to high (default is 3 minutes)
Increasing the write treshold and reducing a bit the dump time
should help with mnesia being overloaded and prevent any
unintended consecuences from the overload.
(cherry …

[4.0] rabbit: add mnesia dump log config

---

chef/cookbooks/mysql/recipes/ha_galera.rb

Without this, haproxy is always limiting us to 1000 connections, not
exposing the full capabilities if db connections is set to 1000. Also
if db connections is set  < 1000, this allows the openstack services
to exceed the number of db connections, causing db healthcheck to fail
and pacemaker to go nuts. always reserve some spare connections
to avoid this from happening.
Requires https://github.com/crowbar/crowbar-ha/pull/279 to be merged first.

galera: raise haproxy limit depending on max_connections (bsc#1068962)

---

chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

We do care about data integrity, and the default setting is "ignore"
which can result in inconsistencies when the partition is over.
For two-node clusters, it could be argued that this wouldn't work nicely
as this more or less means that as soon as there's a partition, rabbitmq
stop working. But pacemaker should help here (with the fencing) and it's
really better to fail than to have inconsistencies later on.
See https://www.rabbitmq.com/partitions.html for more details

rabbitmq: Use pause_minority setting to deal with partitions better

---

chef/cookbooks/nova/recipes/database.rb

`nova-manage db version` in chef's condition is run as root and
touches /var/log/nova/nova-manage.log. With --log-file argument it
will not do it and save us some permission problems.

nova: Fix problem with log permissions

---

chef/cookbooks/nova/recipes/database.rb

`nova-manage db version` in chef's condition is run as root and
touches /var/log/nova/nova-manage.log. With --log-file argument it
will not do it and save us some permission problems.
(cherry picked from commit b373cefdc0072ffc2756f58172a81e4f0ea66b79)
backport of #1481

[4.0] nova: Fix problem with log permissions

---

chef/cookbooks/rabbitmq/recipes/ha.rb
chef/data_bags/crowbar/template-rabbitmq.json

While there's been quite some work on the clustered rabbitmq, it is
safer to keep the default with the old non-clustered way of doing HA for 
the stable branch.
People can still enable the feature if desired.

rabbitmq: Change default HA to non-clustered

---

chef/cookbooks/rabbitmq/recipes/ha.rb

The /etc/rabbitmq/definitions.json file is not readable by the rabbitmq
group, since we change the GID of that group when using shared storage.

rabbitmq: Fix HA with shared storage

---

chef/cookbooks/mysql/recipes/ha_galera.rb

Without this, haproxy is always limiting us to 1000 connections, not
exposing the full capabilities if db connections is set to 1000. Also
if db connections is set  < 1000, this allows the openstack services
to exceed the number of db connections, causing db healthcheck to fail
and pacemaker to go nuts. always reserve some spare connections
to avoid this from happening.
(cherry picked from commit 7c0d98190392b3fb33efde81f61d41d9fedfe0a4)

[4.0] galera: raise haproxy limit depending on max_connections (bsc#1068962)

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/nova/templates/default/nova.conf.erb

We raised this to a high value to workaround a scalability
issue in icehouse, but we don't need this anymore with newton+ it
seems. this higher value cloggs up a large amount of resources
without seeing a whole lot of performance benefit.

nova: set executor_thread_pool_size back to default

---

chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb

This is the more production recommended setup especially for
eventlet/multithreaded services.

nova: use oslo.cache memcache_pool by default for caching

---

chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb

The checks in openvswitch_agent.ini.erb were wrongly using
ml2_type_drivers instead of ml2_mechanism_drivers. This was corrected
in this commit and also removed redundant assignment lines in the
recipe

neutron: Fix conditional statement in template.

---

chef/cookbooks/monasca/attributes/default.rb
chef/cookbooks/monasca/providers/agent_plugin_libvirt.rb
chef/cookbooks/monasca/recipes/master.rb
chef/cookbooks/monasca/recipes/server.rb
chef/cookbooks/monasca/resources/agent_plugin_libvirt.rb
chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
chef/cookbooks/nova/recipes/monitor_monasca.rb
chef/cookbooks/nova/recipes/role_nova_compute_kvm.rb
chef/cookbooks/nova/recipes/role_nova_compute_qemu.rb
chef/cookbooks/nova/recipes/role_nova_compute_xen.rb
chef/data_bags/crowbar/migrate/monasca/101_add_libvirt_plugin_settings.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema
crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
crowbar_framework/config/locales/monasca/en.yml

This change enables Monasca's libvirt monitoring for compute nodes. This plugin
gathers various metrics on running VMs, such as their state, the tenant they
reside in, or their resource consumption. Change summary:
monasca:
* Added schema and, migrations and UI integration for libvirt agent plugin.
* Added resource/provider for generating libvirt agent plugin
configuration.
nova:
* monitor_monasca: write libvirt agent plugin configuration on compute
nodes.
* added monitor_monasca recipe for libvirt based compute nodes.
(cherry picked from commit e27d3ab2496cfc0958c4bb2a26648576fe40d754)

monasca/nova: enable libvirt monitoring

---

crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml

The file _edit_attributes.html.haml, for the NFS section, define
a single field (according to documentation) to list the NFS exports.
Somehow a ghost string field without title is presented in the UI,
and this patch remove it.

cinder: remove unused string field in the webui (bsc#1061298)

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/data_bags/crowbar/migrate/cinder/206_add_nfs_snapshot.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema

Add a new parameter in the UI to allow volume snapshots in NFS. This
feature must also disable the parameter `nas_secure_file_operations`.
This is configuration have some security implications[1] and a
warning text is added as a help hint in the UI.
[1] https://docs.openstack.org/security-guide/block-storage/checklist.html#check-block-07-is-nas-operating-in-a-secure-environment

cinder: volume snapshots for NFS (bsc#1053414)

---

chef/cookbooks/horizon/files/default/grafana-monasca.json
chef/cookbooks/horizon/files/default/grafana-openstack.json
chef/cookbooks/horizon/libraries/helper.rb
chef/cookbooks/horizon/providers/grafana_datasource.rb
chef/cookbooks/horizon/recipes/monasca_ui.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/resources/grafana_datasource.rb
chef/cookbooks/horizon/templates/default/_80_monasca_ui_settings.py.erb
chef/cookbooks/horizon/templates/default/grafana.ini.erb
chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb

This commit adds support for Grafana 4 to the Horizon barclamp.
This allows us to switch from our local Grafana 1.5 fork to
upstream Grafana 4 for the Monasca metrics dashboards.
It makes the following changes:
* Configure and deploy standalone grafana service
* Enable mod_proxy in Apache if monasca is active.
* Create a ProxyPass path on the Apache server to transparently
proxy requests to standalone Grafana
* Add resource/provider for creating Grafana datasource
* Use grafana_datasource resource to create default Grafana data
source.
* Add Grafana 4 compatible Monasca dashboard.
* Add Grafana 4 compatible dashboard for OpenStack metrics.
* Add Ceph monitoring panels to OpenStack dashboards
* Install Discrete Grafana panel plugin
* Adjust GRAFANA_LINKS
* Adjust alarm drilldown links for …

[4.0] horizon: use Grafana 4

---

chef/cookbooks/monasca/templates/default/monasca-reconfigure-server.erb
chef/cookbooks/monasca/templates/default/monasca-reconfigure.erb

Currently monasca-reconfigure just forges on if one of its monasca-setup
invocations fails. This commit changes both monasca-setup scripts to run
with -e so they abort with a non-zero exit status if monasca-setup exits
non-zero.

monasca: use exit status from monasca-setup

---

chef/cookbooks/keystone/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/templates/default/hacluster_sudoers.erb
chef/cookbooks/keystone/templates/default/keystone-fernet-keys-push.sh
chef/cookbooks/keystone/templates/default/keystone-fernet-keys-sync.sh

Newly (re)installed node will not have fernet keys causing failure
when starting keystone services. Cluster founder rotates the keys
and pushes new ones to cluster member on a regular basis.
This change creates pacemaker alert to notify founder about new node.
Keys are then pushed from founder to the node.
Preconditions:
~~https://github.com/crowbar/crowbar-core/pull/1451~~
~~https://github.com/crowbar/crowbar-ha/pull/285~~
~~https://github.com/crowbar/crowbar-ha/pull/284~~
~~https://github.com/crowbar/crowbar-ha/pull/287~~

keystone: Sync fernet keys when joining cluster

---

chef/cookbooks/monasca/providers/agent_plugin_ceph.rb
chef/cookbooks/monasca/resources/agent_plugin_ceph.rb
chef/data_bags/crowbar/migrate/monasca/201_add_ceph_plugin_settings.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema

This pull request adds:
* a monasca-agent check configuration resource provider for
* monasca-agent's ceph plugin
* the Monasca barclamp configuration option `monitor_ceph` that controls
whether the Monasca agent should monitor Ceph.
Note: this code requires a companion change in crowbar-ceph that uses
the resource provider added here.

Add ceph monitoring

---

chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/compute.rb
chef/data_bags/crowbar/migrate/nova/207_add_resource_limits.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

Based on exising work for allowing modification of system resource
limits, extend it to allow changing the open file limits for the
nova-api and nova-compute services.

nova: Add resource limits for api and compute (bsc#1057086)

---

chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb
chef/cookbooks/rabbitmq/templates/suse/epmd.socket-port.conf.erb

We need to adapt to how rabbitmq packages now use the systemwide epmd service, and then we can enjoy some new features from rabbitmq 3.6.x.

rabbitmq: Various changes to enable the use of rabbitmq 3.6.x

---

chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb

Mirroring queues is known to have an impact on performance [1] [2]. We
were looking at mirroring queues to all nodes, but what we really need
is to mirror to a quorum of nodes. This should improve things a bit as a
first step. We may choose to not mirror some queues as a later step.
[1] "To How Many Nodes to Mirror?" in https://www.rabbitmq.com/ha.html
[2] http://fuel-ccp.readthedocs.io/en/latest/design/ref_arch_1000_nodes.html#replication

rabbitmq: Do not mirror queues to all nodes

---

chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/compute.rb
chef/data_bags/crowbar/migrate/nova/121_add_resource_limits.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

Based on exising work for allowing modification of system resource
limits, extend it to allow changing the open file limits for the
nova-api and nova-compute services.
(cherry picked from commit 650e08f80a2c51646d22128a4a85fc1e3dd70397)

[4.0] nova: Add resource limits for api and compute (bsc#1057086)

---

chef/cookbooks/rabbitmq/recipes/default.rb

This is a followup to https://github.com/crowbar/crowbar-openstack/pull/1519 to fix the CI (we hadn't tested the non-HA mode, and for some reason HA is significantly slower in the CI than with our own mkcloud).

rabbitmq: Fixes to changes for rabbitmq 3.6.x support

---

chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

Instead of using the default client-local config for ha queues,
lets use min-masters which Pick the node hosting the minimum number
of masters to create master queues

rabbitmq: tweak queue_master_locator for ha queues

---

chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

Instead of using the default client-local config for ha queues,
lets use min-masters which Pick the node hosting the minimum number
of masters to create master queues
(cherry picked from commit 01f18d401f06438d788414c228da3c75d9251087)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1522

[4.0] rabbitmq: tweak queue_master_locator for ha queues

---

chef/cookbooks/tempest/recipes/config.rb

With the added support for cinder snapshot when using a NFS
backend, this change enables cinder snapshot tempest tests
when 'nfs_snapshot' is set to True.

Enable tempest cinder snapshot tests for NFS backend

---

chef/cookbooks/monasca/providers/agent_plugin_ceph.rb
chef/cookbooks/monasca/resources/agent_plugin_ceph.rb
chef/data_bags/crowbar/migrate/monasca/102_add_ceph_plugin_settings.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema

This commit adds:
* A monasca-agent check configuration resource provider for
* monasca-agent's ceph plugin
* The Monasca barclamp configuration option `monitor_ceph` that controls
whether the Monasca agent should monitor Ceph.
Note: this code requires a companion change in crowbar-ceph that uses
the resource provider added here.
(cherry picked from commit 6b687fe54b3faf61b4335f9b01b6db574ef8f64e)
Backport: schema revision adjusted for stable/4.0

monasca: add ceph monitoring

---

chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb

Mirroring queues is known to have an impact on performance [1] [2]. We
were looking at mirroring queues to all nodes, but what we really need
is to mirror to a quorum of nodes. This should improve things a bit as a
first step. We may choose to not mirror some queues as a later step.
[1] "To How Many Nodes to Mirror?" in https://www.rabbitmq.com/ha.html
[2] http://fuel-ccp.readthedocs.io/en/latest/design/ref_arch_1000_nodes.html#replication
(cherry picked from commit 78e51e4a9a47dbf99ee9c2df8a222fa6283182be)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1520

[4.0] rabbitmq: Do not mirror queues to all nodes

---

chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb
chef/cookbooks/rabbitmq/templates/suse/epmd.socket-port.conf.erb

This is still compatible with current behavior (as in "no change") for old rabbitmq, but enables people to play with rabbitmq 3.6.x on that branch.
Backport of https://github.com/crowbar/crowbar-openstack/pull/1519, https://github.com/crowbar/crowbar-openstack/pull/1525, https://github.com/crowbar/crowbar-openstack/pull/1527.

[4.0] rabbitmq: Various changes to enable the use of rabbitmq 3.6.x

---

chef/cookbooks/keystone/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/templates/default/hacluster_sudoers.erb
chef/cookbooks/keystone/templates/default/keystone-fernet-keys-push.sh
chef/cookbooks/keystone/templates/default/keystone-fernet-keys-sync.sh

Newly (re)installed node will not have fernet keys causing failure
when starting keystone services. Cluster founder rotates the keys
and pushes new ones to cluster member on a regular basis.
This change creates pacemaker alert to notify all nodes about about
new member. Keys are then pushed to the new node from all other nodes
to the new node (with some random time offset).
not cherry-picked directly because of different attribute schema around `token_format`.
backport of #1474 
Preconditions:
https://github.com/crowbar/crowbar-core/pull/1457
https://github.com/crowbar/crowbar-ha/pull/288
https://github.com/crowbar/crowbar-ha/pull/289

[4.0] keystone: Sync fernet keys when joining cluster

---

chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

This specific options needs to be an erlang binary string in
the config as mentioned on the docs[0]
[0] http://previous.rabbitmq.com/v3_6_x/configure.html

rabbitmq: fix queue_master_locator value

---

chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

It needs to be an erlang binary
(cherry picked from commit 5f266b46e9f1e36cd605a6b4046accd3a0b3c20e)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1536

[4.0] rabbitmq: fix queue_master_locator value

---

chef/cookbooks/monasca/recipes/agent.rb
chef/cookbooks/monasca/recipes/master.rb

This commit fixes a race condition where monasca-reconfigure
would otherwise run too early (before monasca-installer
concludes) on the monasca-server node, thus causing it to
fail. To prevent this situation, it introduces a node
attribute that denotes at least one successful
monasca-installer run has occured in the past.

monasca: fix bsc#1076594

---

chef/cookbooks/nova/recipes/config.rb

The config drive is not mandatory for ironic. It can still be forced in nova barclamp.

nova: Don't force config drive if using ironic

---

chef/cookbooks/keystone/libraries/helpers.rb
chef/cookbooks/keystone/providers/register.rb

_find_id makes many redundant calls to keystone for listing users,
tenants... during one chef-client, but would return only what is
required right now.
This patch changes that behaviour, instead of throwing away all the
additional data, _find_id would cache the data in KeystoneHelper allowing
the listing (user, tenants...) to be reused, bypassing the need to
actually create a socket, connect and so.

Local cache for keystoneHelper

---

chef/cookbooks/neutron/files/default/neutron-l3-ha-service.rb

The insecure flag was missing from the status command which was causing the neutron-l3-ha-service to
fail.

neutron-ha-tool: Add insecure flag (bsc#1075394)

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/data_bags/crowbar/migrate/neutron/114_add_cisco_apic_multipod.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This PR adds multi-pod support to cisco_aci. More information on [bug 1066920](https://bugzilla.novell.com/show_bug.cgi?id=1066920).
Note: The intended target of this PR is Cloud 7 and is updated here due to the standard process being followed for all PRs (master-update followed by cloud 7 backport). The tests were only done for Cloud 7 based deployments.

neutron[cisco_aci]: backport of #1502

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/ml2_conf_cisco_apic.ini.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/data_bags/crowbar/migrate/neutron/206_add_apic_optimized_dhcp_metadata.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This PR enables two features for Cisco ACI:
1. Allows usage of "apic_gbp" as ml2_mechanism_drivers and fixes the authentication for the latest version of ACI firmware + group-based-policy library combination.
2. Allows Crowbar configuration for enabling "optimized_metadata" and "optimized_dhcp" features for ACI. Until now these features were enabled by default. But since certain customer deployments wanted to test without enabling these features, it made sense to provide it as a configurable option. It was painful for the customer to change in the config file manually and avoid the chef-client from overriding the config. 
Note: The intended target of this PR is Cloud 7 and is updated here due to the standard process being followed for all PRs (master-update followed by cloud 7 backport). …

neutron[cisco_aci]: Authentification fixes and additional options for ACI GBP

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/ml2_conf_cisco_apic.ini.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/data_bags/crowbar/migrate/neutron/115_add_apic_optimized_dhcp_metadata.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This PR enables two features for Cisco ACI:
1. Allows usage of "apic_gbp" as ml2_mechanism_drivers and fixes the authentication for the latest version of ACI firmware + group-based-policy library combination.
2. Allows Crowbar configuration for enabling "optimized_metadata" and "optimized_dhcp" features for ACI. Until now these features were enabled by default. But since certain customer deployments wanted to test without enabling these features, it made sense to provide it as a configurable option. It was painful for the customer to change in the config file manually and avoid the chef-client from overriding the config. 
Note: The intended target of this PR is Cloud 7 and is updated here due to the standard process being followed for all PRs (master-update followed by cloud 7 backport). …

[4.0]neutron[Cisco_ACI]: Backport from #1490

---

chef/cookbooks/ironic/attributes/default.rb
chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/ironic/templates/default/ironic.conf.erb
chef/data_bags/crowbar/migrate/ironic/202_add_pxe_append_params.rb
chef/data_bags/crowbar/template-ironic.json
chef/data_bags/crowbar/template-ironic.schema
crowbar_framework/app/models/ironic_service.rb

pxe_append_params option is used to add extra kernel parameters to IPA runs.
Example use:
`sshkey="<public key>"` param gives ssh access to running IPA image.
`coreos.autologin` enables console auto login (CoreOS based image)
`ipa-debug=1` enables debug logging in IPA
Great for troubleshooting.
EDIT: additional commit fixes small bug causing migrations to fail.

ironic: Expose pxe_append_params as attribute + migration fix

---

crowbar_framework/app/models/keystone_service.rb

Without this change we run into scenarios where if the chef run fails for any reason
when we modify the endpoints in keystone the data is not updated/saved as apply_role_post_chef_call
is only called after the chef run. To avoid this case we should save the endpoint data in
apply_role_pre_chef_call as well.

keystone: Update endpoint before chef run

---

chef/cookbooks/ironic/recipes/tftp.rb
chef/cookbooks/ironic/templates/default/grub.cfg.erb

To manage baremetal nodes which boot using UEFI, ironic requires additional packages and configuration.

ironic: Add UEFI support to tftp config

---

chef/cookbooks/heat/recipes/server.rb

This bug got fixed in magnum directly, the in-place
modification is no longer necessary
(see https://review.openstack.org/#/c/326428/ )

heat: stop modifying policy.json for magnum

---

chef/cookbooks/magnum/templates/default/magnum.conf.erb

This adds the domain_names to the keystone_auth section as well as this is needed when magnum uses
barbican as the cert-manager.

magnum: Add domain name to keystone_auth (bsc#1080335)

---

chef/data_bags/crowbar/template-rabbitmq.json

For some reason we set the default vhost for rabbit to
contain a slash. Its not that its worng but it makes no sense
to include a slash in the name and it makes it seem like the
slash is required for a vhost, but its not. Plus we end up with
rabbit urls with 2 slashes at the end wich further confuses
the proper way of writing them (i.e. guest:guest@IP:5672//nova)
So this sets the normal name minus slash to the nova+trove vhosts

rabbitmq: remove slash from default vhost

---

chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb
chef/data_bags/crowbar/migrate/rabbitmq/203_add_performance_config.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

Adds some performance configs to tweak rabbitmq:
- backlog: number of connections that can be initialized at the
same time. Useful for a high number of connections or for a temporal
high numbers of connections, like in a server restart. Default is 128,
recommended is 4096.
- sndbuf: increase buffer for TCP connections of consumers, on linux
this value is set automatically between 80KB and 120 KB.
The higher this value is, the higher the throughput and the RAM consumed.
Recommended values for this config depend on the number of connections
and the amount of RAM available.
- recbuf: same as sndbuf but for publishers and protocol operations.
- collect_statistics_interval: the interval in milliseconds to collect
statistics, mainly by the management plugin. Increasing it will reduce
the load …

rabbitmq: add some performance configs

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/data_bags/crowbar/migrate/neutron/207_add_cisco_apic_multipod.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This PR adds multi-pod support to cisco_aci. More information on [bug 1066920](https://bugzilla.novell.com/show_bug.cgi?id=1066920).
Note: The intended target of this PR is Cloud 7 and is updated here due to the standard process being followed for all PRs (master-update followed by cloud 7 backport). The tests were only done for Cloud 7 based deployments.

neutron[cisco_aci]: add support for apic multi-pod

---

crowbar_framework/app/models/ironic_service.rb

During migration service objects are created without logger parameter.
Missing default value caused the process to fail.
(cherry picked from commit 3e6a24b82517b5c5c8777f1c69d631848318fabf)
partial backport of #1544 (fix part only)

[4.0] ironic: Fix failing migrations

---

chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/openstack-dashboard.conf.erb
chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/nova/recipes/placement_api.rb

The listen_ports_crowbar attribute controls which ports are added
as Listen directives to the /etc/apache2/listen.conf file.
However, all wsgi vhosts aside from horizon already have an explicit
Listen directive in the vhost configuration file, so there's no need
to add these ports to the /etc/apache2/listen.conf file.
To align horizon to the other WSGI vhosts, Listen directives are
added to the horizon WSGI vhost configuration file. Since these don't
also have to be added to the /etc/apache2/listen.conf file anymore, the
usage of listen_ports_crowbar can be removed altogether.
Fixes [bsc#1077234](https://bugzilla.suse.com/show_bug.cgi?id=1077234)
Additional notes:
- `listen_ports_crowbar` is still being used by the HA apache recipe [1] to determine which port to use for the status URL. If …

apache: don't collect Listen ports from wsgi vhosts (bsc#1077234)

---

chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/openstack-dashboard.conf.erb
chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
chef/cookbooks/keystone/recipes/server.rb

(backports #1533 to 4.0)
The listen_ports_crowbar attribute controls which ports are added
as Listen directives to the /etc/apache2/listen.conf file.
However, all wsgi vhosts aside from horizon already have an explicit
Listen directive in the vhost configuration file, so there's no need
to add these ports to the /etc/apache2/listen.conf file.
To align horizon to the other WSGI vhosts, Listen directives are
added to the horizon WSGI vhost configuration file. Since these don't
also have to be added to the /etc/apache2/listen.conf file anymore, the
usage of listen_ports_crowbar can be removed altogether.
Fixes [bsc#1077234](https://bugzilla.suse.com/show_bug.cgi?id=1077234)

[4.0] apache: don't collect Listen ports from wsgi vhosts (bsc#1077234)

---

chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/compute.rb
chef/data_bags/crowbar/migrate/nova/049_add_resource_limits.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

Based on exising work for allowing modification of system resource
limits, extend it to allow changing the open file limits for the
nova-api and nova-compute services.
(cherry picked from commit 650e08f80a2c51646d22128a4a85fc1e3dd70397)

[3.0] nova: Add resource limits for api and compute (bsc#1057086)

---

chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/templates/default/my.cnf.erb
chef/cookbooks/mysql/templates/default/tuning.cnf.erb

After the MariaDB 10.2 switch the new defaults make these entries
redundant so they are not needed anymore.

MariaDB 10.2 cleanups

---

chef/cookbooks/rabbitmq/recipes/default.rb

Revert a commit that its not necessary anymore ( rabbitmq: dont let the template changes restart if in cluster mode )
Fixes: rabbitmq: use proper stop/start cmd for cluster
Backport of https://github.com/crowbar/crowbar-openstack/pull/1264

[4.0] Backport rabbit cleanup

---

chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
chef/data_bags/crowbar/migrate/rabbitmq/204_add_extra_users.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema
crowbar_framework/app/models/rabbitmq_service.rb
crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml
crowbar_framework/config/locales/rabbitmq/en.yml

With the introduction of the definitions file it looks like
rabbit will disregard any existing users when restarting,
using the definitions file as the blank slate to start from.
This gets in the middle of having any extra users for other
tasks like monitoring and there is no mechanism to add users.
This PR adds an method to crowbar to add a list of users
that will get written into the definitions file, allowing
us to specify extra users to be created

RabbitMQ allow to add extra users to rabbit

---

chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

There should be no need to create the erlang cookie file for rabbit as
the pacemaker resource agent already creates it for us

rabbitmq: do not create the erlang cookie file

---

chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
chef/data_bags/crowbar/migrate/rabbitmq/105_add_extra_users.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema
crowbar_framework/app/models/rabbitmq_service.rb
crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml
crowbar_framework/config/locales/rabbitmq/en.yml

With the introduction of the definitions file it looks like
rabbit will disregard any existing users when restarting,
using the definitions file as the blank slate to start from.
This gets in the middle of having any extra users for other
tasks like monitoring and there is no mechanism to add users.
This PR adds an method to crowbar to add a list of users
that will get written into the definitions file, allowing
us to specify extra users to be created
(cherry picked from commit 1ade84888fd3da0c606d4421986973c3e401c6b5)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1506

[4.0] Rabbitmq allow to add extra users to rabbit backport

---

chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

There should be no need to create the erlang cookie file for rabbit on
cluster deployments as the pacemaker resource agent already creates
it for us.
(cherry picked from commit 0a00afc7cc23d18769a0febfe52555ceb8455456)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1278

[4.0] rabbitmq: do not create the erlang cookie file on cluster deployment

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb

When the privileged user is not set, cinder does not provide
correct credentials to nova client and migration of attached
volumes fails.
See https://bugs.launchpad.net/cinder/+bug/1614344 for upstream bug.
The relevant code was rewritten for Pike so providing those options
won't be necessary in newer releases. But as the work was not
backported, we have to provide os_privileged values in Newton codebase
if we want to make the migration work (bsc#1079763).

[4.0] cinder: Set os_privileged_* values

---

chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/templates/default/lbaas_agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/208_add_allow_automatic_lbass_agent_failover.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

Enable the ability to automatically reschedule load balancers from LBaaS
agents the server detects to have died.
Previously, load balancers could be scheduled and realized across
multiple LBaaS agents, however if a hypervisor died, the load
balancers scheduled to that node would cease operation.
Now, these load balancers will be automatically rescheduled to a
different agent.

neutron: enable automatic lbaas reschedule

---

chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/recipes/ha_galera.rb

Revert the temporary disable galera-clustercheck commit to make backporting easier (the package is released so this is not needed anymore) and add the missing backports to make MariaDB 10.2 work.

[4.0] Switch to MariaDB 10.2

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/208_add_scheduler_enabled_filters.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

In some cases user needs to modify enabled filters, e.g. remove
DiskFilter when instances are only booted from volumes (bsc#1080997)
This is partial forward-port of https://github.com/crowbar/crowbar-openstack/pull/1568 . The change is that Newton uses `scheduler_default_filters`, while Pike has `enabled_filters`

nova: Add option to modify scheduler's enabled_filters

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/122_add_scheduler_default_filters.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

In some cases user needs to modify default filters, e.g. remove
DiskFilter when instances are only booted from volumes (bsc#1080997)
See https://github.com/crowbar/crowbar-openstack/pull/1578 for master version

[4.0] nova: Add option to modify scheduler_default_filters

---

chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/templates/default/lbaas_agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/116_add_allow_automatic_lbass_agent_failover.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

Enable the ability to automatically reschedule load balancers from LBaaS
agents the server detects to have died.
Previously, load balancers could be scheduled and realized across
multiple LBaaS agents, however if a hypervisor died, the load
balancers scheduled to that node would cease operation.
Now, these load balancers will be automatically rescheduled to a
different agent.
(cherry picked from commit 40744d5f1bee5fd87c82677ad652241eafe03b2e)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1575

[4.0] neutron: enable automatic lbaas reschedule

---

chef/cookbooks/rabbitmq/recipes/default.rb

Up until now we were relaying on the restart for rabbit while on
HA to silently fail due to the resource service name called
rabbitmq-server while the pacemaker reasource is called rabbitmq.
This triggered a restart but it silently failed. Instead pass the
correct service name to allow for the services to be properly
promoted/demoted/restarted even on HA.

rabbitmq: allow pacemaker restart

---

chef/cookbooks/memcached/templates/default/memcached.sysconfig.erb

This reduces the ability to mis-use it for cache
amplification attacks, and we don't really need it.

memcached: Disable UDP by default (bsc#1083903)

---

chef/cookbooks/memcached/templates/default/memcached.sysconfig.erb

This reduces the ability to mis-use it for cache
amplification attacks, and we don't really need it.
(cherry picked from commit 07f036903c5fbf95d2f7bb95e1c26dc61b62ec14)

[4.0] memcached: Disable UDP by default (bsc#1083903)

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb

All default MariaDB configs have now a prefix to allow overwriting of
the options. Let's follow the same to not conflict with the defaults.

mariadb: Add prefix to configs

---

chef/cookbooks/rabbitmq/recipes/default.rb

Up until now we were relaying on the restart for rabbit while on
HA to silently fail due to the resource service name called
rabbitmq-server while the pacemaker reasource is called rabbitmq.
This triggered a restart but it silently failed. Instead pass the
correct service name to allow for the services to be properly
promoted/demoted/restarted even on HA.
(cherry picked from commit 00c9abd8c4f0067090a8a25faf268edcaa0b71b4)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1579

[4.0] rabbitmq: allow pacemaker service restart

---

chef/cookbooks/swift/libraries/rack_awareness.rb

1. The addresses in `crowbar_wall` are full CIDR entries so netmask
needs to be removed before comparing to plain `storage_ip`.
2. Sometimes switch_config is not fully populated for all nodes (yet).
Fall back to default in such cases.
(cherry picked from commit 186ebc0213234ff40f32408dd4bc28692e1812e6)
backport of #1538

[4.0] swift: Fix switch detection (bsc#1075015)

---

chef/cookbooks/swift/libraries/rack_awareness.rb

1. The addresses in `crowbar_wall` are full CIDR entries so netmask
needs to be removed before comparing to plain `storage_ip`.
2. Sometimes switch_config is not fully populated for all nodes (yet).
Fall back to default in such cases.
EDIT: the second problem self-healed somehow in my setup so I removed the fix for that.
EDIT2: re-enabled second fix. When deploying swift on given node the code checks for `switch_config` on all swift nodes. This can lead to race condition where chef-client didn't fill the attributes for some of the nodes yet.

swift: Fix switch detection (bsc#1075015)

---

chef/cookbooks/ironic/attributes/default.rb
chef/cookbooks/ironic/libraries/helpers.rb
chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/ironic/templates/default/ironic.conf.erb
chef/data_bags/crowbar/migrate/ironic/203_add_configdrive_use_object_store.rb
chef/data_bags/crowbar/template-ironic.json
chef/data_bags/crowbar/template-ironic.schema

Allow storage of configdrive in Swift if it is available.
If Swift is available but user doesn't want to store the configdrive there it can be disabled using added attribute. It's value is ignored if Swift is not available.
Additional commit fixes username/password fields in swift settings.

ironic: Store configdrive in Swift if possible

---

chef/cookbooks/barbican/recipes/api.rb

Add the key-manager:service-admin, observer and audit roles. These roles
are used in the policy.json file for the barbican API.

barbican: Add missing roles used in policy.json (bsc#1081573)

---

chef/cookbooks/barbican/recipes/api.rb

Barbican defaults assume that a creator role exists, which allows:
creation of resources, reading all resources, deleting resources one
owns, but not deleting resources owned by others.
(cherry picked from commit a097f888e6b6d1468534d27cbf6758465e6512ed)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1566

[4.0] barbican: Add creator role (bsc#1081573)

---

chef/cookbooks/horizon/templates/default/openstack-dashboard.logrotate.erb

/etc/init.d/apache2 does not exist anymore since SLE12

horizon: fix apache logrotate

---

chef/cookbooks/neutron/recipes/cisco_apic_support.rb
chef/cookbooks/neutron/templates/default/ml2_conf_cisco_apic.ini.erb
chef/data_bags/crowbar/template-neutron.schema

Cisco ACI supports connecting to the fabric either through direct port mappings that in which case, we need to specify the exact ports under [apic-switches] configuration. The pattern usually looks like "1/34" for interface Eth1 and Port 34. Associating these ports creates new policy profiles and groups for the integration. This is not feasible if the ACI is already running another production cloud and we need to integrate openstack as a supplement (which is the case with most ACI customers).
However, ACI also allows for associating pre-existing profiles using VPC_Pairs. This can be configured by specifying the apic_vpc_pairs in ml2_conf_cisco_apic.ini.
This commit provides an option to test with either modes (VPC Pairs or direct connection) as the use-case may be.
Backport: …

neutron: [cisco-aci]: Add support for vpc_pairs.

---

chef/cookbooks/neutron/recipes/cisco_apic_support.rb
chef/cookbooks/neutron/templates/default/ml2_conf_cisco_apic.ini.erb
chef/data_bags/crowbar/template-neutron.schema

Cisco ACI supports connecting to the fabric either through direct port mappings that in which case, we need to specify the exact ports under [apic-switches] configuration. The pattern usually looks like "1/34" for interface Eth1 and Port 34. Associating these ports creates new policy profiles and groups for the integration. This is not feasible if the ACI is already running another production cloud and we need to integrate openstack as a supplement (which is the case with most ACI customers).
However, ACI also allows for associating pre-existing profiles using VPC_Pairs. This can be configured by specifying the apic_vpc_pairs in ml2_conf_cisco_apic.ini.
This commit provides an option to test with either modes (VPC Pairs or direct connection) as the use-case may be.

[4.0]neutron: [cisco-aci]: Backport from #1599

---

chef/cookbooks/magnum/templates/default/magnum.conf.erb

This is needed when ssl is enabled. Just having it in the keystone_auth section
is not enough.

magnum: Set insecure option in keystone_authtoken

---

crowbar_framework/app/models/database_service.rb
crowbar_framework/app/models/rabbitmq_service.rb
crowbar_framework/config/locales/database/en.yml
crowbar_framework/config/locales/rabbitmq/en.yml

We don't want new deployments to use these old ways of deploying the database and rabbitmq.
Old deployments will still work fine, as the check is only done when the barclamp is not applied yet.

Disallow postgresql and unclustered HA for rabbitmq for new deployments

---

chef/cookbooks/rabbitmq/recipes/default.rb

Reverts crowbar/crowbar-openstack#1579
Restarting rabbit seems to bring instability to the rest of the services so we better not restart.

Revert "rabbitmq: allow pacemaker restart"

---

chef/cookbooks/rabbitmq/recipes/default.rb

Reverts crowbar/crowbar-openstack#1580
Restarting rabbit seems to bring instability to the rest of the services so we better not restart.

Revert "[4.0] rabbitmq: allow pacemaker service restart"

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb

glance_api_version is defaulting to 2, we don't need to
explicitely set it. Found while looking for something else

glance: micro config template cleanup

---

chef/cookbooks/neutron/recipes/cisco_apic_support.rb
chef/cookbooks/neutron/templates/default/ml2_conf_cisco_apic.ini.erb
chef/data_bags/crowbar/migrate/neutron/117_add_apic_external_network_attributes.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This commit provides a way to configure external connectivity
to the opnenstack instances by allowing the user to provide
ml2 config file with the L3 Out network and EPG details.
The commit adds a new section [apic_external_network] in
ml2_conf_cisco_apic.ini. The name of the section and the EPG provided
in the input reflects the Bridge domain, EPG and the External
Routed Network elements created on the ACI fabric.
When the external network of the ACI fabric is mapped to ML2,
the creation of neutron subnets get mapped to the subnets on the ACI
fabric and therefore will be subject to the Contracts and Policies
defined on the tenant. 
(cherry picked from commit 3dda51f62e0322138a1740d04d362ea8e7a2feb2)

[cisco_aci]neutron: External L3Out connectivity. Backport #1603

---

chef/cookbooks/neutron/recipes/cisco_apic_support.rb
chef/cookbooks/neutron/templates/default/ml2_conf_cisco_apic.ini.erb
chef/data_bags/crowbar/migrate/neutron/209_add_apic_external_network_attributes.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This commit provides a way to configure external connectivity
to the opnenstack instances by allowing the user to provide
ml2 config file with the L3 Out network and EPG details.
The commit adds a new section [apic_external_network] in
ml2_conf_cisco_apic.ini. The name of the section and the EPG provided
in the input reflects the Bridge domain, EPG and the External
Routed Network elements created on the ACI fabric.
When the external network of the ACI fabric is mapped to ML2,
the creation of neutron subnets get mapped to the subnets on the ACI
fabric and therefore will be subject to the Contracts and Policies
defined on the tenant. 
.

[cisco_aci]neutron: Add support for L3Out External Connectivity

---

chef/cookbooks/keystone/recipes/server.rb

Some keystone requests can be incredibly timeconsuming in real world
environmentes with large, slow LDAP servers. Increase timeout
from the default of 60 seconds.

keystone: Increase WSGI request timeout to 10 minutes

---

chef/cookbooks/tempest/recipes/config.rb

This is probably not a good idea, it contains passwords.

tempest: remove world-readable permission from tempest.conf

---

chef/cookbooks/mysql/recipes/ha_galera.rb

This wasn't set and the default is 0, which means it wasn't monitored at
all.
(cherry picked from commit ee9b6ea7f4985d7f78655da0a89a9a113bb040fc)

mysql: Set monitor to 10s for galera-python-clustercheck

---

chef/cookbooks/nova/templates/default/nova.conf.erb

The progress timeout is unreliable and was already disabled
by default in pike, however it is still enabled in Newton, hence
this is going to be backported. Also be a little bit more generous
to slow compute nodes and allow migration to as slow as 1MByte/s
before aborting it. this tremendeously helps live migration to
succeed on very busy compute nodes (where migrating away busy
workload is the best thing to do)
Also remove an outdated setting that is defaulting to 30 already.
(cherry picked from commit 4e1feb7cea89092f17e838f8df3b7993ed6bc539)

nova: disable progress timeout for live migration

---

crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml

The translations for HA UI were removed but UI file still referenced
them. The "Custom" barclamp UI didn't work because of this.
Followup for https://github.com/crowbar/crowbar-openstack/pull/1545

rabbitmq: Remove unused HA parameters from UI

---

chef/cookbooks/neutron/recipes/common_agent.rb
crowbar_framework/app/models/cinder_service.rb
crowbar_framework/lib/openstack/ha.rb

These are various bits found during testing the case of new node being added to existing pacemaker cluster (bsc#1083427)
- At least in the special case of adding new member to existing cluster,  Openstack::HA.set_controller_role is called and node[:pacemaker] accessed.
- cinder: Do not access role attributes with symbol keys 
- neutron: Check network presence before accessing it

Fixes needed for adding a node into existing cluster

---

chef/cookbooks/monasca/recipes/master.rb
chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
chef/cookbooks/monasca/templates/default/monasca-hosts-single.erb
chef/data_bags/crowbar/migrate/monasca/203_add_cassandra_support.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema
crowbar_framework/app/helpers/barclamp/monasca_helper.rb
crowbar_framework/app/models/monasca_service.rb
crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
crowbar_framework/config/locales/monasca/en.yml

This commit adds support for Cassandra to the Monasca
barclamp. It introduces various new parameters required for
Cassandra and passes them to monasca-installer. Details:
* New parameters:
* tsdb
* cassandra_admin_password parameter.
* Renamed parameters:
* influxdb_mon_api_password -> tsdb_mon_api_password
* influxdb_mon_persister_password -> tsdb_mon_persister_password
* Parametrize monasca-installer for Cassandra setup.
* Generate cassandra_admin_password

monasca: add Cassandra support

---

chef/cookbooks/rabbitmq/recipes/default.rb

Epmd service could very well be active by the time we add the new
port.conf config so it would ignore the setting.
This just adds a subscribe event to that config file which will fire
a restart of the service if the file is changed.
This may or may not be affecting the nodes upgrade, in which after upgrading the OS and restarting, makes epmd be up and running, so the new ports config will not be applied.

rabbitmq: restart epmd on config change

---

chef/cookbooks/monasca/templates/default/monasca-hosts-single.erb

monasca-installer chokes on there not being a cassandra
Ansible group defined if InfluxDB is the time series database
being used. This commit removes the conditionals in the
template that prevent this group from being defined in the
InfluxDB scenario.

monasca: fix monasca-installer for InfluxDB (bsc#1090413)

---

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

pre-upgrade attribute is set to true to indicate the case that the upgrade of the node has
not been finished yet. In such case, services cannot start on the node
(there's a location constraint that prevents that).
See disable_pre_upgrade_attribute_for method in models/api/node.rb for more info

rabbitmq: Do not check if service is running when it is not supposed to run

---

chef/cookbooks/keystone/providers/register.rb

Sometimes _get_token fails with 502 HTTP code because Apache is being
restarted while chef-client tries to access it. Small retry loop will
give it a bit more chance to complete the operation.

keystone: Add retry loop to _get_token (bsc#1087466)

---

chef/cookbooks/mysql/recipes/ha_galera.rb

As we are upgrading to the same database version, we can keep it
running at all nodes in galera cluster.
**Not fully tested.** update: actually seems to work well...

upgrade: Keep mariadb running at all nodes during the upgrade

---

chef/cookbooks/rabbitmq/attributes/default.rb

(cherry picked from commit 2787b72e40c5b6a2f48fc2af94075711b9dda507)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1652

rabbitmq: create empty users list which is expected by some recipes

---

chef/cookbooks/rabbitmq/files/default/rabbitmq.tmpfiles
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
chef/cookbooks/rabbitmq/templates/default/hacluster_sudoers.erb
chef/cookbooks/rabbitmq/templates/default/rabbitmq-alert-handler.erb
chef/cookbooks/rabbitmq/templates/default/rabbitmq-port-blocker.erb

This script blocks the connection to the rabbitmq cluster in case the number of nodes decay bellow the half of the total. In this case the remain rabbit nodes won't accept new connections. The problem to solve is that when a rabbit node has too much clients with low timeout, the final scenario could be a DOS when the clients try to constantly reconnect to rabbitmq and forcing more timeouts.
It takes advantage of the pacemaker notifications that notify when a rabbitmq has failed or has restored. All nodes rabbitmq ports will be blocked if the total number of alive nodes are below to the half of nodes of the cluster, or unblock if its over this value. This prevents the overload of alive nodes and the total block of service.
Only the node that have problems will receive the alert, so it is …

rabbitmq: block client port on startup

---

chef/cookbooks/rabbitmq/files/default/rabbitmq.tmpfiles
chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
chef/cookbooks/rabbitmq/templates/default/hacluster_sudoers.erb
chef/cookbooks/rabbitmq/templates/default/rabbitmq-alert-handler.erb
chef/cookbooks/rabbitmq/templates/default/rabbitmq-port-blocker.erb

This script blocks the connection to the rabbitmq cluster in case the number of nodes decay bellow the half of the total. In this case the remain rabbit nodes won't accept new connections. The problem to solve is that when a rabbit node has too much clients with low timeout, the final scenario could be a DOS when the clients try to constantly reconnect to rabbitmq and forcing more timeouts.
It takes advantage of the pacemaker notifications that notify when a rabbitmq has failed or has restored. All nodes rabbitmq ports will be blocked if the total number of alive nodes are below to the half of nodes of the cluster, or unblock if its over this value. This prevents the overload of alive nodes and the total block of service.
Only the node that have problems will receive the alert, so it is …

[4.0] rabbitmq: block client port on startup

---

chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/209_add_cachemodes.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

Also default to writeback for network, which is improving
the performance quite a bit for ceph backed volumes and is safe
to enable (and recommended by almost every openstack install guide)

nova: make disk_cachemodes configurable

---

chef/cookbooks/tempest/recipes/config.rb

This is probably not a good idea, it contains passwords.
(cherry picked from commit bfbcc2d0c43dd99698d1caa664acef8e77e465e2)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1363

[4.0] tempest: remove world-readable permission from tempest.conf

---

chef/cookbooks/keystone/providers/register.rb

Sometimes _get_token fails with 502 HTTP code because Apache is being
restarted while chef-client tries to access it. Small retry loop will
give it a bit more chance to complete the operation.
(backported from commit 9ee935f86f5e085eba10cc5ed802f8515d361b00)
NOTE: direct cherry-pick was not possible because keystone provider was modified to use v3 API since stable/4.0
backport of #1639

[4.0] keystone: Add retry loop to _get_token (bsc#1087466)

---

chef/cookbooks/keystone/providers/register.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/resources/register.rb

Workaround for: https://bugzilla.suse.com/show_bug.cgi?id=1091829
Calling the keystone_register 'wakeup' action immediately after
the admin password has been updated can sometimes result in timeout
errors on non-founder nodes, while the founder node is stuck doing
retry iterations with an expired token due to bsc#1091829.
As a workaround for bsc#1091829, a small time delay is inserted after
the admin password is changed, to give keystone time to expire all the
admin tokens already issued before creating new ones.

keystone: avoid race condition during admin password change

---

chef/cookbooks/keystone/providers/register.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/resources/register.rb

(backports #1668 to 4.0)
Workaround for: https://bugzilla.suse.com/show_bug.cgi?id=1091829
Calling the keystone_register 'wakeup' action immediately after
the admin password has been updated can sometimes result in timeout
errors on non-founder nodes, while the founder node is stuck doing
retry iterations with an expired token due to bsc#1091829.
As a workaround for bsc#1091829, a small time delay is inserted after
the admin password is changed, to give keystone time to expire all the
admin tokens already issued before creating new ones.

[4.0] keystone: avoid race condition during admin password change

---

chef/cookbooks/nova/recipes/compute.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

because it defaults to off
but a lot of people rely on nested virt being available
While in https://fate.suse.com/320082 the virtualisation team
declined to promote nested virt to fully supported status for SLE12,
we are using this since 2012 in all kinds of places without problems.
same as #1261

nova: enable nested virt on Intel

---

chef/cookbooks/nova/templates/default/nova.conf.erb

The progress timeout is unreliable and was already disabled
by default in pike, however it is still enabled in Newton, hence
this is going to be backported. Also be a little bit more generous
to slow compute nodes and allow migration to as slow as 1MByte/s
before aborting it. this tremendeously helps live migration to
succeed on very busy compute nodes (where migrating away busy
workload is the best thing to do)
Also remove an outdated setting that is defaulting to 30 already.

nova: disable progress timeout for live migration (bsc#1091190)

---

chef/cookbooks/nova/recipes/database.rb

Current code applies only to Pike already.

nova: Remove the checks that were testing if we're not running Newton

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb

This allows the administrator to select flavors or images
to pass through entropy devices to the guest to give them
a chance of securely generating crypto nounces. Note
the default seems to be off, it needs to be enabled in the
nova flavor via an "hw_rng:allowed=True" extra specs

nova: Configure a rng device for guest VM entropy (bsc#985882)

---

chef/cookbooks/nova/recipes/compute.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

because it defaults to off
but a lot of people rely on nested virt being available
While in https://fate.suse.com/320082 the virtualisation team
declined to promote nested virt to fully supported status for SLE12,
we are using this since 2012 in all kinds of places without problems.
(cherry picked from commit afbcc5c3a4f4e552e2f130b45fe70932f82094be)
backport of #1304

nova: allow to enable nested virt on Intel

---

chef/cookbooks/ironic/attributes/default.rb
chef/data_bags/crowbar/migrate/ironic/204_remove_ssh_based_drivers.rb
chef/data_bags/crowbar/template-ironic.json
crowbar_framework/app/models/ironic_service.rb
crowbar_framework/config/locales/ironic/en.yml

Removing all SSH based drivers from config file and added validaion from ironic
proposal to not allow these drivers.

Remove SSH-based drivers from ironic (bsc#1087472)

---

chef/cookbooks/glance/recipes/ha.rb
chef/data_bags/crowbar/migrate/glance/202_add_rate_limit.rb
chef/data_bags/crowbar/template-glance.json
chef/data_bags/crowbar/template-glance.schema

Disabled by default default. It can be set to avoid filling up image related tables.
Though the tables are only filled by POST requests this limit is for all
request types.
See https://wiki.openstack.org/wiki/OSSN/OSSN-0076 for details.

Add rate limiting for glance api (bsc#1005886)

---

chef/cookbooks/rabbitmq/recipes/default.rb

Previous check was grepping systemd unit files in /usr. There are many
other places which might override these. Better use systemctl to ask
systemd about it's view of the system and service dependencies.

rabbitmq: Better dependency check

---

chef/cookbooks/glance/recipes/ha.rb
chef/data_bags/crowbar/migrate/glance/105_add_rate_limit.rb
chef/data_bags/crowbar/template-glance.json
chef/data_bags/crowbar/template-glance.schema

Disabled by default default. It can be set to avoid filling up image
related tables.
Though the tables are only filled by POST requests this limit is for all
request types.
See https://wiki.openstack.org/wiki/OSSN/OSSN-0076 for details.
(cherry picked from commit c4c1b8e0f27489dbeaa7503b920051b67a4523d1)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1677

[4.0] Add rate limiting for glance api (bsc#1005886)

---

chef/cookbooks/aodh/attributes/default.rb
chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/aodh/templates/default/aodh.conf.erb
chef/data_bags/crowbar/migrate/aodh/202_add_alarm_history_ttl.rb
chef/data_bags/crowbar/template-aodh.json
chef/data_bags/crowbar/template-aodh.schema
crowbar_framework/app/views/barclamp/aodh/_edit_attributes.html.haml
crowbar_framework/config/locales/aodh/en.yml

The alarm_history_ttl config option for aodh was
not previously configurable.

aodh: Add config for alarm_history_ttl (bsc#1073703)

---

chef/cookbooks/monasca/recipes/master.rb
chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
chef/data_bags/crowbar/migrate/monasca/204_add_elasticsearch_tunables.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema

This commits exposes various `elasticsearch` tunables that have recently been added to `monasca-installer`. Please do not merge, yet. I'm still adapting this and `monasca-installer` to each other. Also, I'll rebase and clean up the commit message once it actually works :-)

Add elasticsearch tunables

---

chef/cookbooks/horizon/templates/default/openstack-dashboard.logrotate.erb

apache2 reload causes responses 406 from keystone. This change was
verified on a customer's setup.
bsc#1083093

horizon: copytruncate apache logs bsc#1083093

---

chef/cookbooks/nova/recipes/database.rb

We needed to do step by step upgrade (sync up to certain version + online migrations + new synce + new online migrations) when upgrading
to Newton. This code should not be needed any more in master branch.
I *think* this is correct, but it's not yet tested neither during installation nor during upgrade... 
**UPDATE** gating success confirms that it does not break normal installation...

nova: Do not do partial online migrations, that was Newton specific

---

crowbar_framework/app/views/barclamp/manila/_edit_attributes.html.haml
crowbar_framework/config/locales/manila/en.yml

The correct field name for the Ceph cluster name is cephfs_cluster_name,
correct it for the custom view so configurations using CephFS can be
successfully applied.

manila: Correct field name for cluster name

---

chef/cookbooks/monasca/recipes/master.rb
chef/cookbooks/monasca/templates/default/run-monasca-installer.erb

This pull request consists of two commits:
1) Various improvements to how monasca-installer is run.
2) A Cloud 8 specific fix for https://bugzilla.suse.com/show_bug.cgi?id=1096043
(1) can and should be backported to Cloud 7.

Fix monasca installer

---

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

As the resource agent for rabbitmq with cluster HA restart the rabbitmq
service several times, the current check can fail to validate rabbitmq
status, as it could do the check just on one of those times that rabbit
is up while creating/joining the cluster. Then if the check passed and
continued the chef execution, the next steps could fail as they are
dependant on having a running rabbitmq, while the rabbitmq server may
still be restarting.
Instead expand the checks to first look for a rabbit master for the
resource and expand the check for a local runing rabbit to make sure
we are checking for the local copy.

rabbitmq: Make sure rabbitmq is running on cluster HA

---

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

As the resource agent for rabbitmq with cluster HA restart the rabbitmq
service several times, the current check can fail to validate rabbitmq
status, as it could do the check just on one of those times that rabbit
is up while creating/joining the cluster. Then if the check passed and
continued the chef execution, the next steps could fail as they are
dependant on having a running rabbitmq, while the rabbitmq server may
still be restarting.
Instead expand the checks to first look for a rabbit master for the
resource and expand the check for a local runing rabbit to make sure
we are checking for the local copy.
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1396

[4.0]  rabbitmq: Make sure rabbitmq is running on cluster HA

---

chef/cookbooks/neutron/recipes/network_agents.rb

We should really use the direct file instead of relying on a symlink.

/etc/sysctl.d/99-sysctl.conf is a symlink to /etc/sysctl.conf

---

chef/data_bags/crowbar/template-rabbitmq.json

A very low client timeout can lead to multiple disconnections of
the clients due to missing heartbeats, depending on the load on the
rabbit nodes. Instead of configuring the clients with a very low
value, lets just use the default openstack values for safety

rabbitmq: set client timout to default value

---

chef/data_bags/crowbar/template-rabbitmq.json

A very low client timeout can lead to multiple disconnections of
the clients due to missing heartbeats, depending on the load on the
rabbit nodes. Instead of configuring the clients with a very low
value, lets just use the default openstack values for safety
(cherry picked from commit ebc4922866eae1ae714ee30875847563b6c2d50c)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1714

[4.0] rabbitmq: set client timout to default value

---

chef/cookbooks/horizon/templates/default/openstack-dashboard.logrotate.erb

apache2 reload causes responses 406 from keystone
bso#1083093
(cherry picked from commit cfda2347d15a16dfccbd69f0cdd08cbf0a9e31de)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1581

[4.0] copytruncate apache logs instead of creating

---

chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/210_add_force_metadata_attributes.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This changes allows to force_metadata from the proposal. Previously, if this attribute was added directly to configuration in neutron network nodes, it was removed from the config in each chef-client execution

neutron: add force_metadata attribute

---

chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/118_add_force_metadata_attributes.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This changes allows to force_metadata from the proposal. Previously
if this was changed directly in neutron network nodes it was removed
in each chef-client execution
(cherry picked from commit b25af4c8b95ccbeef93685c359209b429634c758)
Backported from #1720

[4.0] Neutron force metadata feature backend

---

chef/cookbooks/horizon/recipes/server.rb

When Horizon in deployed via a autogenerated self certificate, the
current code will generate a different one of each node in the
cluster.
This patch will generate a single certificate in the founder, and
share it with the rest of the cluster via `rsync`.
(cherry picked from commit b264c759f862d4b81e0a67095032e156965a17e3)

[4.0] Synchronize SSL in the cluster (bsc#1081518)

---

chef/cookbooks/nova/recipes/config.rb

nova-placement-api service is behing WGSI (apache2), and in order
to reload it when nova-placement.conf file change, we need to
create a proxy service.
This proxy will signal the WSGI apache modules for a reload,
without a full restart of apache service.

nova: reload nova-placement-api (bsc#1103383)

---

chef/cookbooks/heat/recipes/server.rb

There is an intermittent update and HA ci failure that originates
from the heat::server recipe. It has been observed in manual upgrade
tests and in ci.
The problem goes something like this. The founder set's a wait pacemaker
sync mark:
crowbar_pacemaker_sync_mark "wait-heat_register" if ha_enabled
And then goes off and registers heat with keystone. The non-founders
happily sit and wait for the founder to finish and set the create mark.
When the non-founders finally start, none of the register jobs that the
founder has just completed has "only_if's" attached so the non-founders
happily go and re-run them.
The problem is, these register jobs can take time. In the failures I've
seen the `register heat domain` block can take up to 40-50 seconds. This places
the non-founders well behind the …

Heat: Make non-founder HA nodes do less work

---

chef/cookbooks/heat/recipes/server.rb

There is an intermittent update and HA ci failure that is originates
from the heat::server recipe. It has been observed in manual upgrade
tests and in ci.
The problem goes something like this. The founder set's a wait pacemaker
sync mark:
crowbar_pacemaker_sync_mark "wait-heat_register" if ha_enabled
And then goes off and registers heat with keystone. The non-founders
happily sit and wait for the founder to finish and set the create mark.
When the non-founders finally start, none of the register jobs that the
founder has just completed has "only_if's" attached so the non-founders
happily go and re-run them.
The problem is, these register jobs can take time. In the failures I've
seen the `register heat domain` block take up to 40-50 seconds. This places
the non-founders well behind the …

[5.0] Heat: Make non-founder HA nodes do less work

---

crowbar_framework/app/models/rabbitmq_service.rb

Every time the rabbitmq proposal was applied the extra users
passwords was regenerated. Featured introduced in #1506
This fix mantain the paswords.

rabbitmq: fix extra users password regeneration

---

crowbar_framework/app/models/rabbitmq_service.rb

Every time the rabbitmq proposal was applied the extra users
passwords was regenerated.  Featured introduced in #1511
This fix mantain the paswords.
(cherry picked from commit a2f7ac68262a5f02665c671a6b90a91b06bf0f6e)
Backported from #1723

[4.0] rabbitmq: fix extra users password regeneration

---

chef/data_bags/crowbar/migrate/keystone/114_remove_updated_password.rb
chef/data_bags/crowbar/template-keystone.json

The removal of the update_password was landed under revision 113, so
the migration was never executed. Rename to 114 and make it idempotent

keystone: Fix missing keystone migration (bsc#1104182)

---

chef/cookbooks/keystone/providers/register.rb

In order to decide whether we need to create a particular
endpoint we need to compare the interface, not if there
is any interface.

keystone: avoid creating duplicate catalog endpoints

---

chef/cookbooks/heat/recipes/server.rb

There is an intermittent update and HA ci failure that is originates
from the heat::server recipe. It has been observed in manual upgrade
tests and in ci.
The problem goes something like this. The founder set's a wait pacemaker
sync mark:
crowbar_pacemaker_sync_mark "wait-heat_register" if ha_enabled
And then goes off and registers heat with keystone. The non-founders
happily sit and wait for the founder to finish and set the create mark.
When the non-founders finally start, none of the register jobs that the
founder has just completed has "only_if's" attached so the non-founders
happily go and re-run them.
The problem is, these register jobs can take time. In the failures I've
seen the `register heat domain` block take up to 40-50 seconds. This places
the non-founders well behind the …

[4.0] Heat: Make non-founder HA nodes do less work

---

chef/cookbooks/crowbar-openstack/libraries/provider_ssl_setup.rb

If the user is sharing a certificate between different OpenStack
services, this needs to be readed for different system users.  For
example, if the client store the certificate in /etc/apache2/ssl.key,
this directory and all the parents needs to be read for all the
OpenStack service users, and also the certificates contained there.
To address that we use the ACL from the operating system, via the
`setfacl` command.

Set a proper ACL for shared certificates (bsc#1101154)

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

The cloud-mkcloud8-job-upgrade-nondisruptive-ha-mariadb-x86_64 job has
failed on multiple occasions due to the default timeout of 60 seconds
timing out for the `wait-neutron-agents_ha_resources` pacemaker sync
mark.
Runs 188 and 185 are 2 such examples.
Looking at the chef-agent logs on the crowbar node we see the following:
node1 - founder
[2018-08-28T06:29:53+00:00] INFO: Processing crowbar-pacemaker_sync_mark[wait-neutron-agents_ha_resources] action guess (neutron::network_agents_ha line 125)
....
[2018-08-28T06:31:02+00:00] INFO: Processing crowbar-pacemaker_sync_mark[create-neutron-agents_ha_resources] action guess (neutron::network_agents_ha line 302)
node 2
[2018-08-28T06:29:57+00:00] INFO: Processing crowbar-pacemaker_sync_mark[wait-neutron-agents_ha_resources] action guess …

neutron: Increase wait_neutron-agents_ha_resources timeout

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/database/attributes/default.rb
chef/cookbooks/database/libraries/crowbar.rb
chef/cookbooks/database/libraries/database_library.rb
chef/cookbooks/database/recipes/role_database_server.rb
chef/cookbooks/database/recipes/role_mysql_server.rb
chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/postgresql/recipes/ha.rb
chef/cookbooks/postgresql/recipes/ha_storage.rb
chef/cookbooks/postgresql/recipes/server.rb
chef/cookbooks/postgresql/recipes/server_debian.rb
chef/cookbooks/postgresql/recipes/server_redhat.rb
chef/data_bags/crowbar/migrate/database/109_separate_db_roles.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema
chef/roles/database-server.rb
chef/roles/mysql-server.rb
crowbar_framework/app/helpers/barclamp/database_helper.rb
crowbar_framework/app/models/database_service.rb
crowbar_framework/app/models/monasca_service.rb
crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
crowbar_framework/config/locales/database/en.yml

New PR created after the revert of https://github.com/crowbar/crowbar-openstack/pull/1713
(original is https://github.com/crowbar/crowbar-openstack/pull/1691)
https://github.com/SUSE-Cloud/automation/pull/2600 is required for correct roles assignement in HA setup

[4.0] split database-server role into backend specific roles

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

The cloud-mkcloud8-job-upgrade-nondisruptive-ha-mariadb-x86_64 job has
failed on multiple occasions due to the default timeout of 60 seconds
timing out for the `wait-neutron-agents_ha_resources` pacemaker sync
mark.
Runs 188 and 185 are 2 such examples.
Looking at the chef-agent logs on the crowbar node we see the following:
node1 - founder
[2018-08-28T06:29:53+00:00] INFO: Processing crowbar-pacemaker_sync_mark[wait-neutron-agents_ha_resources] action guess (neutron::network_agents_ha line 125)
....
[2018-08-28T06:31:02+00:00] INFO: Processing crowbar-pacemaker_sync_mark[create-neutron-agents_ha_resources] action guess (neutron::network_agents_ha line 302)
node 2
[2018-08-28T06:29:57+00:00] INFO: Processing crowbar-pacemaker_sync_mark[wait-neutron-agents_ha_resources] action guess …

[5.0] neutron: Increase wait_neutron-agents_ha_resources timeout

---

chef/data_bags/crowbar/migrate/database/209_merge_db_roles.rb
chef/data_bags/crowbar/template-database.json

During upgrade there was a time where both different database engines
were deployed to the same noes and we needed extra role.
Once back on SOC8, there's again need for only one database role.
See https://github.com/crowbar/crowbar-openstack/pull/1746 for spliting the roles in SOC7

database: Drop temporary mysql-server role, used for upgrade only

---

chef/data_bags/crowbar/migrate/database/209_merge_db_roles.rb
chef/data_bags/crowbar/template-database.json

During upgrade there was a time where both different database engines
were deployed to the same noes and we needed extra role.
Once back on SOC8, there's again need for only one database role.
(cherry picked from commit 27f272456b684e8f74b08a8d7172cf1206782b24)
backport of https://github.com/crowbar/crowbar-openstack/pull/1712

[5.0] database: Drop temporary mysql-server role, used for upgrade only

---

chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

nodelay is already on by default and keepalive is off by default,
but some env might want to be able to configure it.

rabbitmq: allow tuning tcpnodelay and keepalive

---

chef/cookbooks/horizon/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/nova/recipes/controller_ha.rb

When adding new node to existing cluster, fernet keys need to be pushed from
the founder to keep all keystone nodes in sync. Before this change the keys
were pushed to all nodes when cluster was initially set up and then rotated
periodically.
This commit introduces internal node attribute which indicates that the keys
are already in place. Founder pushes the fernet keys to all nodes which don't
have this attribute set. The same code covers initial cluster setup as well
as adding new node to existing cluster.
In addition the lookup of cluster member nodes was changed. Helper function
from crowbar-pacemaker cookbook which was based on Chef search was replaced
with direct lookup of `elements` attribute (based on deployment part of
proposal). This way, new soon-to-be-cluster-member node will …

[4.0] keystone: Always try to rsync keys to new nodes

---

chef/cookbooks/crowbar-openstack/definitions/openstack_pacemaker_drbd_controller_only_location_for.rb
chef/cookbooks/crowbar-openstack/libraries/ha_helpers.rb
chef/cookbooks/postgresql/recipes/ha.rb
chef/cookbooks/postgresql/recipes/ha_storage.rb
chef/cookbooks/rabbitmq/recipes/ha.rb

We have to allow user to add a new node into 2-node DRBD cluster, so that such cluster can hold (3-node) galera configuration later.
But as (our version of) DRBD needs exactly 2 nodes, there are some tweaks necessary so that the extra node does not have DRBD configured, although it is part of the pacemaker cluster.
This part handles necessary changes for DRBD-enabled services (postgresql, rabbitmq)
Requires https://github.com/crowbar/crowbar-ha/pull/327

Correct configuration of DRBD resources in 3-node cluster

---

crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml

This is a replacement for package patch to simplify future modifications
to the sources without causing conflicts.
Original patch: https://build.suse.de/package/view_file/Devel:Cloud:7:Staging/crowbar-openstack/hide-mysql-ssl.patch?expand=1
Package revert: https://build.suse.de/request/show/171784

database: Hide SSL options from database UI

---

chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/recipes/client.rb
chef/cookbooks/mysql/recipes/server.rb

For reasons that are hard to understand, the SLES team decided
to rename mariadb* packages to mariadb-102 in addition to keeping
the mariadb-* (which are old) around. Because we need the version
with galera support, pull the newer version in.

database: switch to mariadb-102 packages

---

chef/cookbooks/horizon/templates/default/local_settings.py.erb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/swift/templates/default/proxy-server.conf.erb
chef/cookbooks/tempest/recipes/config.rb
chef/data_bags/crowbar/migrate/heat/100_add_trusts_delegated_roles.rb
chef/data_bags/crowbar/template-heat.json

Roles are case insensitive, and OpenStack Rocky generates a "member"
role by default, so it conflicts with the default role "Member" that
we create. As both are considered equal by Keystone, we can just switch
our defaults to it.

openstack: Switch to Rocky+ default member role name spelling

---

crowbar_framework/app/assets/javascripts/barclamps/database/application.js
crowbar_framework/app/models/database_service.rb
crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
crowbar_framework/config/locales/database/en.yml

Barclamp UI was modified to show custom view of MySQL and/or
PostgreSQL depending on assigned roles.
Extra features:
- automatic assignment of active sql engine based on roles (new proposals only)
- model validation on save
- added borders around each engine parameters section to avoid confusion

[4.0] database: UI for mysql and/or postgresql

---

chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/role_neutron_sdn_cisco_aci_agents.rb
chef/data_bags/crowbar/migrate/neutron/119_add_cisco_aci_role.rb
chef/data_bags/crowbar/template-neutron.json
chef/roles/neutron-sdn-cisco-aci-agents.rb
crowbar_framework/app/models/neutron_service.rb

So far, the implementation assumed that only compute nodes
would be attached to the ACI leaf ports and the controller
nodes are independently attached to the network not connected
to the ACI fabric itself. The only form of communication from
the controller to the ACI is through the agents. However,
recent customer POCs have changed our assumption since these
setups expect all or most of the nodes attached the ACI leaf
as the ACI fabric forms the central network infrastructure
of the entire deployment. In such scenarios, we need a mechanism
where we can know which of the nodes are attached to the ACI
leaf and which nodes are not. The agents should be enabled
and run on each node attached to the ACI leaf ports.
This commit tries to achieve exactly this result, so that
future deployments can …

[neutron:cisco-aci] Backport from #1699

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

When fetch_database_settings is called by one of the database specific
cookbooks it is supposed to lookup the settings for the respective
backend instead of for the currently selected default backend.

helpers: Pass sql_engine into get_listen_address

---

chef/cookbooks/mysql/attributes/server.rb

In a Galera HA environment the pacemaker primitive op monitor is only
set for master mode. This is not a problem because all galera resources
are in master mode.
The problem comes when changing the pacemaker primitive and the masters
can become slaves, i.e. when shrinking the cluster. In such case the
slaves never get promoted to masters because they are not monitored.
Adding the monitor operation for slaves solves this situation.

mysql: ha galera needs op monitor for slaves

---

chef/cookbooks/mysql/attributes/server.rb

Backport from: https://github.com/crowbar/crowbar-openstack/pull/1731
In a Galera HA environment the pacemaker primitive op monitor is only
set for master mode. This is not a problem because all galera resources
are in master mode.
The problem comes when changing the pacemaker primitive and the masters
can become slaves, i.e. when shrinking the cluster. In such case the
slaves never get promoted to masters because they are not monitored.
Adding the monitor operation for slaves solves this situation.
(cherry picked from commit 67fa21f8b086c862163ac044a788226ce159edcd)

[4.0] mysql: ha galera needs op monitor for slaves

---

chef/cookbooks/mysql/attributes/server.rb

Backport from: https://github.com/crowbar/crowbar-openstack/pull/1731
In a Galera HA environment the pacemaker primitive op monitor is only
set for master mode. This is not a problem because all galera resources
are in master mode.
The problem comes when changing the pacemaker primitive and the masters
can become slaves, i.e. when shrinking the cluster. In such case the
slaves never get promoted to masters because they are not monitored.
Adding the monitor operation for slaves solves this situation.
(cherry picked from commit 67fa21f8b086c862163ac044a788226ce159edcd)

[5.0] mysql: ha galera needs op monitor for slaves

---

chef/cookbooks/heat/attributes/default.rb
chef/cookbooks/heat/libraries/helpers.rb
chef/cookbooks/heat/recipes/ha.rb
chef/cookbooks/heat/recipes/monitor_monasca.rb
chef/cookbooks/heat/recipes/server.rb
chef/cookbooks/heat/templates/default/heat.conf.erb
chef/cookbooks/heat/templates/suse/loadbalancer.template.erb

The cloudwatch API has been removed upstream, so remove it and
its usage in the load balancer template from the barclamp as
well.

heat: Remove cloudwatch API

---

chef/cookbooks/ceilometer/recipes/server.rb

monasca-ceilometer was removed from rpm-packaging as it was not building
against master. As a result openstack-ceilometer-api is no longer
available.
This patch is here to help get ahead of that blocker until
monasca-ceilometer is available again.

do not install/configure ceilometer-api

---

chef/cookbooks/keystone/providers/register.rb

With commit 9ee935f86f we added a retry loop to _get_token() to avoid
issues with service restarts during chef-client runs. The retrys
currently happen on any non-success response code including the 4XX
ones. However the code for updating the password relies on the get_token
to return 401. The current retry behavior will trigger unnecessary
retrys. Which will often cause the HA syncmark on the admin password
update code in keystone/recipe/server.rb to run into a timeout.
This change update the retry loop to only retry on 5XX errors, which
caused the original problem that the retry loop was trying to address.
Everything else will be handled as a success (2XX) or hard
(non-retryable) error.

keystone: Fix retry behavior on password update

---

chef/cookbooks/keystone/providers/register.rb

With commit 9ee935f86f we added a retry loop to _get_token() to avoid
issues with service restarts during chef-client runs. The retrys
currently happen on any non-success response code including the 4XX
ones. However the code for updating the password relies on the get_token
to return 401. The current retry behavior will trigger unnecessary
retrys. Which will often cause the HA syncmark on the admin password
update code in keystone/recipe/server.rb to run into a timeout.
This change update the retry loop to only retry on 5XX errors, which
caused the original problem that the retry loop was trying to address.
Everything else will be handled as a success (2XX) or hard
(non-retryable) error.
(cherry picked from commit 5a6a79eb27d3fe752ddea2b1360f1cd331e50c4a)

[5.0] keystone: Fix retry behavior on password update

---

chef/cookbooks/keystone/providers/register.rb

With commit 9ee935f86f we added a retry loop to _get_token() to avoid
issues with service restarts during chef-client runs. The retrys
currently happen on any non-success response code including the 4XX
ones. However the code for updating the password relies on the get_token
to return 401. The current retry behavior will trigger unnecessary
retrys. Which will often cause the HA syncmark on the admin password
update code in keystone/recipe/server.rb to run into a timeout.
This change update the retry loop to only retry on 5XX errors, which
caused the original problem that the retry loop was trying to address.
Everything else will be handled as a success (2XX) or hard
(non-retryable) error.
(cherry picked from commit 5a6a79eb27d3fe752ddea2b1360f1cd331e50c4a)

[4.0] keystone: Fix retry behavior on password update

---

chef/cookbooks/keystone/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb

Backport of #1512 
Backported to make branches more consistent. Preparation for keystone::ha cleanup.

[4.0] Fernet keys sync polish

---

crowbar_framework/app/models/neutron_service.rb

This needs be assigned manually when the ACI/opflex drivers are enabled

neutron: Don't assign the aci role to any node by default

---

crowbar_framework/app/models/neutron_service.rb

This needs be assigned manually when the ACI/opflex drivers are enabled
(cherry picked from commit 2581217e072c0f415be410e80a266ba028637e1c)

[5.0] neutron: Don't assign the aci role to any node by default

---

crowbar_framework/app/models/neutron_service.rb

This needs be assigned manually when the ACI/opflex drivers are enabled
(cherry picked from commit 2581217e072c0f415be410e80a266ba028637e1c)

[4.0] neutron: Don't assign the aci role to any node by default

---

chef/cookbooks/nova/recipes/config.rb

nova-placement-api service is behing WGSI (apache2), and in order
to reload it when nova-placement.conf file change, we need to
create a proxy service.
This proxy will signal the WSGI apache modules for a reload,
without a full restart of apache service.
(cherry picked from commit db813e1ce3042eb17214532063ac8de9557fec98)

[5.0] nova: reload nova-placement-api (bsc#1103383)

---

chef/cookbooks/horizon/recipes/ha.rb

If HAProxy is serving :80 or :443 (because Horizon), we do not want
that Apache2 can also be listening on those ports.
HAProxy can be configured to resuse sockets, so that means that the
tuple IP:Port can be reused for different services, produncing bugs
like bsc#1105086, where the same IPv4 and the same port (:80) is
being listening connections from Apache and for HAProxy.
This patch remove the default :listen_ports from Apache if HAProxy
is deployed for Horizon, and reapply the Apache2 recipe from Crownar
Core.

Do not share ports Apache2 and HAProxy (bsc#1105086)

---

chef/cookbooks/monasca/recipes/master.rb
chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
chef/data_bags/crowbar/migrate/monasca/104_add_elasticsearch_tunables.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema

This commit adds various new elasticsearch tunables and passes them to
monasca-installer.
(cherry picked from commit a91f9c5d0fde868540b85ea14c7cf864a564f53a)

monasca: add elasticsearch tunables (bsc#1090343)

---

CODEOWNERS

This is an experiment which could supersede the mentionbot which was just removed in #1781.  It will cause the mentioned users to be automatically notified when pull requests are proposed which modify files matching the specified patterns, as described in
- https://help.github.com/articles/about-codeowners/
In our context, it does not mean anything about real ownership (yet), only notification.
Users and file patterns have been picked without any serious thought, and can of course easily be improved later.

kick off an experiment with CODEOWNERS

---

chef/cookbooks/nova/recipes/flavors.rb

The command getting the list of flavors is executed pretty close to
starting the nova ha resource, which can take bit more time (especially
on slow clusters). So give the flavor list command a few more tries
before erroring out.
Note: this is only an issue in setups where the stateless resources are still
managed by pacemaker (clone-stateless-service=true). In the alternative
setup (managed by systemd) the service are started a bit earlier during
the chef-client run.
(cherry picked from commit b2131f057a7b6c1b0839b1d48e1e3e148f273550)
Backport of: https://github.com/crowbar/crowbar-openstack/pull/1800

[5.0] nova: Increase retries for listing flavors

---

chef/cookbooks/nova/recipes/flavors.rb

The command getting the list of flavors is executed pretty close to
starting the nova ha resource, which can take bit more time (especially
on slow clusters). So give the flavor list command a few more tries
before erroring out.
Note: this is only an issue in setups where the stateless resources are still
managed by pacemaker (clone-stateless-service=true). In the alternative
setup (managed by systemd) the service are started a bit earlier during
the chef-client run.
(cherry picked from commit b2131f057a7b6c1b0839b1d48e1e3e148f273550)
Backport of: https://github.com/crowbar/crowbar-openstack/pull/1800

[4.0] nova: Increase retries for listing flavors

---

chef/cookbooks/keystone/providers/fernet.rb
chef/cookbooks/keystone/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/resources/fernet.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb
chef/cookbooks/nova/recipes/controller_ha.rb

Moved most of the fernet setup to ha.rb. Some redundancy was added but
it is now easier to work with the (more-complex) HA case.
The main goal was to reorder step so that fernet keys are configured and
distributed to cluster nodes before apache is (re)started. This way, there
is no time when apache would be configured to use fernet keys but no actual
keys would be present. The problem was detected in cluster extension scenario
where new node was added to an already existing cluster.

[4.0] keystone: Reorganize HA/fernet code

---

chef/cookbooks/neutron/recipes/common_config.rb

Without that change, the previous patch that tried to make this
parameter configurable and is expanded to the (raised) default of 50
did not work as it was never set.
(cherry picked from commit 3951bae99b7293ed50b42aad2dc358a6a5e6c6ca)

[4.0] neutron: define  sql_max_pool_size for config template expansion

---

chef/cookbooks/nova/recipes/flavors.rb

The command getting the list of flavors is executed pretty close to
starting the nova ha resource, which can take bit more time (especially
on slow clusters). So give the flavor list command a few more tries
before erroring out.
Note: this is only an issue in setups where the stateless resources are still
managed by pacemaker (clone-stateless-service=true). In the alternative
setup (managed by systemd) the service are started a bit earlier during
the chef-client run.

nova: Increase retries for listing flavors

---

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/neutron/212_add_default_log_levels.rb
chef/data_bags/crowbar/migrate/nova/210_add_default_log_levels.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

Allow overriding the default_log_leves from crowbar so we
can bump the log levels for several libraries like
oslo_messaging or amqp
This new setting accepts a list of "library=LEVEL" strings
as show in the docs[0][1]
[0] https://docs.openstack.org/mitaka/config-reference/compute/config-options.html#nova-logging
[1] https://docs.openstack.org/mitaka/config-reference/networking/networking_options_reference.html
(cherry picked from commit fe8cbc77e3604431a6b12551ad290463f1bc350d)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1725

[5.0] neutron/nova: allow overriding default_log_levels

---

chef/cookbooks/neutron/definitions/neutron_metadata.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb

In order to free some connections to rabbitmq the neutron
metadata agent is disabled in computer nodes if the
force_metadata flag is set to true. The pacemaker
primitive is removed as well if exists.

Neutron: disable metadata agent service if not necessary

---

chef/cookbooks/neutron/definitions/neutron_metadata.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb

In order to free some connections to rabbitmq the neutron
metadata agent is disabled in computer nodes if the
force_metadata flag is set to true. The pacemaker
primitive is removed as well if exists.
(cherry picked from commit 098b3a478bd9e78bb8c4bf112afd46f2f568846a)
backported from #1762

[5.0] Neutron: disable metadata agent service if not necessary

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb

passing domain info for neutron to send notifications back to nova
without this patch booting vms fails with error
```
ERROR neutron.notifiers.nova Traceback (most recent call last):
ERROR neutron.notifiers.nova   File "/usr/lib/python2.7/site-packages/neutron/notifiers/nova.py", line 245, in send_events
ERROR neutron.notifiers.nova     batched_events)
ERROR neutron.notifiers.nova   File "/usr/lib/python2.7/site-packages/novaclient/v2/server_external_events.py", line 39, in create
ERROR neutron.notifiers.nova     return_raw=True)
ERROR neutron.notifiers.nova   File "/usr/lib/python2.7/site-packages/novaclient/base.py", line 366, in _create
ERROR neutron.notifiers.nova     resp, body = self.api.client.post(url, body=body)
ERROR neutron.notifiers.nova   File …
```

Adding domain credential to the neutron.conf for nova

---

chef/cookbooks/nova/templates/default/nova.conf.erb

When all schedulers are picking the "best" host, in a 3 node
HA case they will all pick the same host, which is suboptimal.
Try to scale out a bit and increase retries in case of conflicts.
Even worse, a node that had still capacity when the scheduling
started might be out of memory at the time the VM is launched,
causing failed starts of VMs.

nova: avoid scheduling conflicts on HA CP

---

chef/cookbooks/neutron/definitions/neutron_metadata.rb

In commit 803e973e1b2db8df2f1eafef41340a5dc58d94d9 is introduced
an option to disable metadata agent in computer nodes.
In some cases, the condition to check if metadata is enabled
fails because these computers don't have the information of
node[:neutron][:metadata][:force]
This commit fixes this problem
(cherry picked from commit 06b538ac16ec5bf0edf475e9909eeacf519d8dcf)
Backport from #1822

Neutron force metadata disable metadata agent fix

---

chef/cookbooks/ceilometer/recipes/server_ha.rb

ceilometer api has been deprecated and is no longer available for
installation

do not create load balancer config for ceilometer api

---

chef/cookbooks/mysql/templates/default/galera.cnf.erb

For some reason the default configuration shipped with the
mariadb-galera package configures non-default limits for wsrep_max_ws_rows
and wsrep_max_ws_size. This commit changes the limits back to the
maximum supported values (which also happen to be the defaults used by
MariaDB if no configuration is present).
This is to reduce the likelyhood of failing DB transactions (with e.g.
"wsrep_max_ws_rows exceeded") when e.g.  ceilometer-expirer needs to
DELETE a large set of database rows.

database: Increase galera write set limits

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

changed authurl to v3 and added explicit auth_version otherwise it
defaults to 2.0

neutron: l3 ha service can talk to keystone v3

---

chef/cookbooks/neutron/definitions/neutron_metadata.rb

In commit 8e8f8e873ab9cb94ca1042529f289ca017ceff3d is introduced
an option to disable metadata agent in computer nodes.
In some cases, the condition to check if metadata is enabled
fails because these computers don't have the information of
node[:neutron][:metadata][:force]
This commit fixes this problem
(cherry picked from commit fa92cfd)
Backported from #1825

[5.0] Neutron force metadata disable metadata agent fix

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

"Database server found at" line had wrong reference to address variable.

[4.0] database: Fix log line

---

chef/cookbooks/mysql/templates/default/galera.cnf.erb

For some reason the default configuration shipped with the
mariadb-galera package configures non-default limits for wsrep_max_ws_rows
and wsrep_max_ws_size. This commit changes the limits back to the
maximum supported values (which also happen to be the defaults used by
MariaDB if no configuration is present).
This is to reduce the likelyhood of failing DB transactions (with e.g.
"wsrep_max_ws_rows exceeded") when e.g.  ceilometer-expirer needs to
DELETE a large set of database rows.
(cherry picked from commit 8a2877cd9c3084670c6dcc4230661cd31405dffb)
backport of https://github.com/crowbar/crowbar-openstack/pull/1830

[4.0]database: Increase galera write set limits

---

chef/cookbooks/mysql/templates/default/galera.cnf.erb

For some reason the default configuration shipped with the
mariadb-galera package configures non-default limits for wsrep_max_ws_rows
and wsrep_max_ws_size. This commit changes the limits back to the
maximum supported values (which also happen to be the defaults used by
MariaDB if no configuration is present).
This is to reduce the likelyhood of failing DB transactions (with e.g.
"wsrep_max_ws_rows exceeded") when e.g.  ceilometer-expirer needs to
DELETE a large set of database rows.
(cherry picked from commit 8a2877cd9c3084670c6dcc4230661cd31405dffb)

[5.0] database: Increase galera write set limits

---

chef/cookbooks/horizon/recipes/server.rb

This has been deprecated in Cloud8 and removed in cloud9

horizon: stop installing trove plugin

---

chef/data_bags/crowbar/migrate/neutron/212_add_default_log_levels.rb
chef/data_bags/crowbar/migrate/nova/210_add_default_log_levels.rb

The "*_add_default_log_levels.rb" were currenty failing with:
"undefined local variable or method `a' for SchemaMigration:Module"

nova/neutron: Fix copy'n paste error in schema migration

---

chef/data_bags/crowbar/template-neutron.json

https://docs.openstack.org/releasenotes/neutron-lbaas/rocky.html
is deprecated and not actually working with rocky anymore. so we
need to disable it and replace it with octavia. With it being
enabled the tempest tests are failing

neutron: disable lbaas integration for now

---

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/neutron/302_add_default_log_levels.rb
chef/data_bags/crowbar/migrate/nova/301_add_default_log_levels.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

Allow overriding the default_log_leves from crowbar so we
can bump the log levels for several libraries like
oslo_messaging or amqp
This new setting accepts a list of "library=LEVEL" strings
as show in the docs[0][1]
[0] https://docs.openstack.org/mitaka/config-reference/compute/config-options.html#nova-logging
[1] https://docs.openstack.org/mitaka/config-reference/networking/networking_options_reference.html

neutron/nova: allow overriding default_log_levels

---

chef/cookbooks/postgresql/attributes/default.rb

Because timestamps make the logs a lot more useful
Ref: https://www.postgresql.org/docs/9.5/static/runtime-config-logging.html#GUC-LOG-LINE-PREFIX

postgresql: Add timestamp prefix to logs

---

chef/cookbooks/postgresql/attributes/default.rb

Because timestamps make the logs a lot more useful
(cherry picked from commit 2da5b01b2706b9d955d6b66cdd7d16d2d56f50ec)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1845

[4.0] postgresql: Add timestamp prefix to logs

---

chef/cookbooks/postgresql/attributes/default.rb

Because timestamps make the logs a lot more useful
(cherry picked from commit 2da5b01b2706b9d955d6b66cdd7d16d2d56f50ec)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1845

[5.0] postgresql: Add timestamp prefix to logs

---

chef/data_bags/crowbar/template-neutron.json

VXLAN seems to be generally a more popular choice and
is the one actually tested in the CI environment, so
we should be defaulting to what we test.

neutron: default to vxlan type drivers (bsc#1112156)

---

chef/data_bags/crowbar/template-rabbitmq.json

The "nova" vhost is from the dark ages before openstack was
more than just nova. Lets use a more sensible default for new
installs. Intentionall no migration for existing installations.

rabbitmq: default to openstack/openstack for new installs

---

chef/cookbooks/nova/templates/default/nova.conf.erb

Skip instance state reporting when it has been disabled in rabbitmq.

nova: disable notification reporting when disabled

---

crowbar_framework/app/models/ceilometer_service.rb
crowbar_framework/config/locales/ceilometer/en.yml

Telemetry collection is based on clients configured to send
notifications. With the change to make the client notification sending
optional, we now should warn the user that the notifications have to
be enabled for Ceilometer/Telemetry to work.

[5.0] ceilometer: add validation that notifications are enabled client side

---

crowbar_framework/app/models/ceilometer_service.rb
crowbar_framework/config/locales/ceilometer/en.yml

Telemetry collection is based on clients configured to send
notifications. With the change to make the client notification sending
optional, we now should warn the user that the notifications have to
be enabled for Ceilometer/Telemetry to work.

ceilometer: add validation that notifications are enabled client side

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

Accidentally when forward porting the patch the setting was
only set for the native clustered mode.

rabbitmq: configure notification setting also in non-clustered mode

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

Accidentally when forward porting the patch the setting was
only set for the native clustered mode because the hash is
being assembled in two locations. Break out the common part
and merge it so that we follow DRY principles.
Backport of #1854 
(cherry picked from commit a06bbb3663f311ac47b85e0fea64d6973c221d12)

[5.0] rabbitmq: configure notification settings also in clustered mode

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

Remove enable_notifications line left in single_rabbit_settings by
previous commit.

[5.0] rabbitmq: Remove redundant code

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/crowbar-openstack/metadata.rb
chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/libraries/crowbar.rb
chef/cookbooks/rabbitmq/metadata.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

PR #1833 removed some attributes from rabbitmq nodes and replaced them with direct value lookups. This was a fix for race condition leading to empty addresses in rabbitmq connection strings. The change needs to be forward ported to later branches because otherwise the attributes (and the original problem) would be re-added in new systems and during the upgrade.
forward port of #1833

[5.0] rabbitmq: Fix address handling in rabbitmq (aka "glance timeout")

---

bin/prepare-mariadb

There is no need for this timeout since we simplified the script to do everything in
one ssh call. In addition, timeout command only kills the ssh client and leaves
chef-client running remotely. This gives the user false impression that prepare is
already done but also returns false-error result (exit status 124 from timeout reported
as chef-client exit code).

[4.0] upgrade: Remove chef-client timeout from prepare-mariadb 

---

chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

Allows to disable queue mirroring on rabbitmq as it should not be
linked to having a rabbitmq cluster
NOTICE: before someone complains, this does *not* require a migration file because we are building cloud9 and will backport this to cloud8/7 so either this gets in on a new install of cloud9 or anyone upgrading from cloud8 will already have it migrated due to the backport, so there is no need for a migration file here

rabbitmq: allow disabling queue mirroring

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/crowbar-openstack/metadata.rb
chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/libraries/crowbar.rb
chef/cookbooks/rabbitmq/metadata.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb

PR #1833 removed some attributes from rabbitmq nodes and replaced them with direct value lookups. This was a fix for race condition leading to empty addresses in rabbitmq connection strings. The change needs to be forward ported to later branches because otherwise the attributes (and the original problem) would be re-added in new systems and during the upgrade.
forward port of #1833

rabbitmq: Fix address handling in rabbitmq (aka "glance timeout")

---

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
chef/cookbooks/rabbitmq/templates/default/rabbitmq-alert-handler.erb
chef/cookbooks/rabbitmq/templates/default/rabbitmq-port-blocker.erb

This script blocks the connection to the rabbitmq cluster in case the number of nodes decay below the half
of the total. In this case the remaining rabbit nodes won't accept new connections until quorum is reached.
It takes advantage of the ClusterMon agent that notifies when a rabbitmq has failed or has restored.
All nodes rabbitmq ports will be blocked if the total number of alive nodes are below to the half of
nodes of the cluster, or unblock if its over this value.
The reasoning behind this patch is to allow waiting for more than one node in the cluster to be ready,
which is useful for two reasons:
- clients would connect to more than one node
- master for queues would be spread more evenly
Currently most of the connections and master queues are created on the master node, as its the …

[5.0] rabbitmq: block client port on startup

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

Accidentally when forward porting the patch the setting was
only set for the native clustered mode because the hash is
being assembled in two locations. Break out the common part
and merge it so that we follow DRY principles.
(cherry picked from commit a06bbb3663f311ac47b85e0fea64d6973c221d12)

[4.0] rabbitmq: configure notification settings also in clustered mode

---

chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/data_bags/crowbar/migrate/rabbitmq/206_add_enable_queue_mirroring.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

Allows to disable queue mirroring on rabbitmq as it should not be
linked to having a rabbitmq cluster
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1808

[5.0] rabbitmq: allow disabling queue mirroring

---

chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/data_bags/crowbar/migrate/rabbitmq/107_add_enable_queue_mirroring.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema

Allows to disable queue mirroring on rabbitmq as it should not be
linked to having a rabbitmq cluster
(cherry picked from commit fe7be665b25f0497d424bb87af8a201a784b35dc)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1808

[4.0] rabbitmq: allow disabling queue mirroring

---

.travis.yml
Gemfile

by leveraging the crowbar-validate-databags gem we can now test
the schemas, jsons and migrations for failures on each repo
This adds the appropiate trais entry so it runs the validation
on the proper dirs on each PR
crowbar-validate-databags comes from https://github.com/Itxaka/crowbar-validate-databags and its basically the extraction of `validate_data_bag.rb`[0] and `crowbar_validator.rb`[1]
As both of those utils are only available on crowbar-core, we cannot properly validate other repos that introduce new schemas and migrations. So instead of dulicating the code, it was easier to extract and make a simple gem only used for the testing part.
I also took the time to add some much needed migration duplication validation, and as you can see on the running tests for this PR it already …

travis: tests databags

---

Gemfile

We dont need an specific version and we control the gem release
versioning so we can manage it ourselves properly

Gemfile: Drop crowbar-validate-databags gem version

---

.travis.yml
Gemfile

by leveraging the crowbar-validate-databags gem we can now test
the schemas, jsons and migrations for failures on each repo
This adds the appropiate trais entry so it runs the validation
on the proper dirs on each PR
crowbar-validate-databags comes from Itxaka/crowbar-validate-databags and its basically the extraction of validate_data_bag.rb[0] and crowbar_validator.rb[1]
As both of those utils are only available on crowbar-core, we cannot properly validate other repos that introduce new schemas and migrations. So instead of dulicating the code, it was easier to extract and make a simple gem only used for the testing part.
I also took the time to add some much needed migration duplication validation, and as you can see on the running tests for this PR it already found duplicated …

[5.0] Travis: Validate databags

---

.travis.yml
Gemfile

by leveraging the crowbar-validate-databags gem we can now test
the schemas, jsons and migrations for failures on each repo
This adds the appropiate trais entry so it runs the validation
on the proper dirs on each PR
crowbar-validate-databags comes from Itxaka/crowbar-validate-databags and its basically the extraction of validate_data_bag.rb[0] and crowbar_validator.rb[1]
As both of those utils are only available on crowbar-core, we cannot properly validate other repos that introduce new schemas and migrations. So instead of dulicating the code, it was easier to extract and make a simple gem only used for the testing part.
I also took the time to add some much needed migration duplication validation, and as you can see on the running tests for this PR it already found duplicated …

[4.0] Travis: Validate databags

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/templates/default/linuxbridge_agent.ini.erb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb

This avoids a slighly misleading warning from stevedore
that the dotted path is not really an entrypoint.

neutron: use entrypoints for plugin drivers

---

chef/cookbooks/rabbitmq/recipes/rabbit.rb

otherwise the tags will be added like:
`Setting user tags for user 'yarb' to ['[administrator]']`

Add list of tags comma separated for extra users

---

chef/cookbooks/aodh/templates/default/aodh.conf.erb
chef/cookbooks/barbican/templates/default/barbican.conf.erb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/glance/templates/default/glance-registry.conf.erb
chef/cookbooks/glance/templates/default/glance-scrubber.conf.erb
chef/cookbooks/heat/templates/default/heat.conf.erb
chef/cookbooks/ironic/templates/default/ironic.conf.erb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/manila/templates/default/manila.conf.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/cookbooks/sahara/templates/default/sahara.conf.erb
chef/cookbooks/swift/templates/default/proxy-server.conf.erb

```
option                     from                    option                   to
idle_timeout                  database              connection_recycle_time    databas
auth_uri                      keystone_authtoken    www_authenticate_uri       keystone_authtoken
api_class                     key_manager           backend                    key_manager
vncserver_listen              vnc                   server_listen              vnc
vncserver_proxyclient_address vnc                   server_proxyclient_address vnc
rabbit_use_ssl                oslo_messaging_rabbit ssl                        oslo_messaging_rabbit
```
picked up from various log files

change  deprecated options from rocky

---

chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
chef/cookbooks/neutron/templates/default/l3_agent.ini.erb

If 'force_metadata' is configured as 'True' then disable the metadata
proxies in all nodes doe not have dhcp namespaces. They are not needed
in l3 agents.
And then 'enable_isolated_metadata' is neglected. So there is no need to
configure it, since 'force_metadata' is a superset and configured that
alone is sufficient to get the metadata from the dhcp server.

neutron: disable metadata proxy when metadata is forced

---

chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
chef/cookbooks/neutron/templates/default/l3_agent.ini.erb

If 'force_metadata' is configured as 'True' then disable the metadata
proxies in all nodes doe not have dhcp namespaces. They are not needed
in l3 agents.
And then 'enable_isolated_metadata' is neglected. So there is no need to
configure it, since 'force_metadata' is a superset and configured that
alone is sufficient to get the metadata from the dhcp server.
(cherry picked from commit e2b408e571e302cf2574a5b9517ca9ca0220becd)
Backport from #1826

[4.0] neutron: disable metadata proxy when metadata is forced

---

chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
chef/cookbooks/neutron/templates/default/l3_agent.ini.erb

If 'force_metadata' is configured as 'True' then disable the metadata
proxies in all nodes doe not have dhcp namespaces. They are not needed
in l3 agents.
And then 'enable_isolated_metadata' is neglected. So there is no need to
configure it, since 'force_metadata' is a superset and configured that
alone is sufficient to get the metadata from the dhcp server.
(cherry picked from commit e2b408e571e302cf2574a5b9517ca9ca0220becd)
Backport from #1826

[5.0] neutron: disable metadata proxy when metadata is forced

---

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/neutron/122_add_default_log_levels.rb
chef/data_bags/crowbar/migrate/nova/125_add_default_log_levels.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

Allow overriding the default_log_leves from crowbar so we
can bump the log levels for several libraries like
oslo_messaging or amqp
This new setting accepts a list of "library=LEVEL" strings
as show in the docs[0][1]
[0] https://docs.openstack.org/mitaka/config-reference/compute/config-options.html#nova-logging
[1] https://docs.openstack.org/mitaka/config-reference/networking/networking_options_reference.html
(cherry picked from commit fbb2121d79ed4257b3e44fdda1ce39d881b2393f
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1725

[4.0] neutron/nova: allow overriding default_log_levels

---

chef/cookbooks/rabbitmq/recipes/rabbit.rb

otherwise the tags will be added like:
`Setting user tags for user 'yarb' to ['[administrator]']`
(cherry picked from commit 3034446d7511ba23ea50060b6d68d9368d447621)

rabbitmq: Add list of tags comma separated for extra users

---

chef/cookbooks/cinder/templates/default/cinder-rootwrap.erb

This file got obsoleted by the removal of PFS in 2015.

cinder: Remove leftover rootwrap template

---

chef/cookbooks/nova/templates/default/nova-placement.conf.erb

nova-placement should use the service endpoint because
- thats what devstack does
- that url happens to be versioned and this allows version discovery
even in the case of insecure SSL being used

nova: Use service keystone endpoint

---

chef/data_bags/crowbar/migrate/keystone/301_convert_uuid_to_fernet.rb
chef/data_bags/crowbar/template-keystone.json
chef/data_bags/crowbar/template-keystone.schema
crowbar_framework/app/helpers/barclamp/keystone_helper.rb
crowbar_framework/app/views/barclamp/keystone/_edit_attributes.html.haml
crowbar_framework/config/locales/keystone/en.yml

In Rocky the UUID token format was removed[1][2]. This patch removes
uuid as a valid token format, leaving only fernet. The dropdown menu is
also removed, however the option is still left in the schema to allow
for the possibility that new token formats may be added in the future.
[1] https://docs.openstack.org/releasenotes/keystone/rocky.html
[2] https://review.openstack.org/543060

keystone: Remove UUID token format (SCRD-4086)

---

chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb

Pass keystone_region to monasca-installer: some roles use
api_region and some use keystone_region which caused us to end
up with the (wrong) default of "RegionOne" in some
configuration files.

monasca: pass keystone_region

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/l3_agent.ini.erb

With DVR the l3-agent needs to be configured on the compute nodes as
well. As the computes don't have the neutron proposal assigned we need
to read the [:metadata][:force] attribute from a neutron-node.

Fix "enable_metadata_proxy" setting for DVR setups

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/l3_agent.ini.erb

With DVR the l3-agent needs to be configured on the compute nodes as
well. As the computes don't have the neutron proposal assigned we need
to read the [:metadata][:force] attribute from a neutron-node.
(cherry picked from commit 67824043459426e033fd770d76070fc36cb3f70a)
Backport of: https://github.com/crowbar/crowbar-openstack/pull/1889

[4.0] neutron: Fix "enable_metadata_proxy" setting for DVR setups

---

chef/cookbooks/tempest/templates/default/tempest.conf.erb

It is required for creating secrets in Barbican. Otherwise
barbican_tempest_plugin will fail miserably.

add 'creator' role to dynamic credential (SCRD-5821)

---

chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb

Cuirrently we are enabling and running the metering agent at all
times in the network nodes for no reason.
Instead this patch makes it so its only deployed in the case of having
the ceilometer-agent role, which indicates that we are gathering
metrics and we want to run it. Otherwise its just wasted resources

neutron: disable metering agent if no ceilometer

---

chef/cookbooks/nova/templates/default/nova.conf.erb

nova: Remove deprecated attr from libvirt section(SCRD-5917)
Remove deprecated options:
- live_migration_progress_timeout=0
It's mentioned in Ocata release note.
https://docs.openstack.org/releasenotes/nova/ocata.html#deprecation-notes

nova: Remove deprecated attr from libvirt section(SCRD-5917)

---

chef/cookbooks/nova/templates/default/nova-placement.conf.erb

https://docs.openstack.org/releasenotes/nova/queens.html#deprecation-notes
Configuration options in the [placement] section are deprecated as follows: 
- os_region_name to region_name
- os_interface to valid_interfaces

nova: Rename deprecated placement configuration options (SCRD-5845).

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

Check whether the Barbican barclamp has been applied and only
assign the creator role to the tempest user if it has been.
This role is created by the Barbican barclamp and if the role
does not exist, this role assignment will fail, causing smoke
tests to fail across the board.

tempest: only assign creator role if needed

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb

Move nova configuration to [nova]
- os_region_name to region_name
- nova_api_insecure to insecure
- remove nova_catalog_info
- remove nova_catalog_admin_info
The os_privileged_xxx and nova_xxx in the [default] section are deprecated in
favor of the settings in the [nova] section.
https://docs.openstack.org/releasenotes/cinder/pike.html
Removed the deprecated options for the Nova connection: nova_catalog_info, nova_catalog_admin_info
https://docs.openstack.org/releasenotes/cinder/queens.html

cinder: move nova config options to [nova] section

---

chef/cookbooks/horizon/attributes/default.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb
chef/data_bags/crowbar/migrate/horizon/301_remove_token_hash_enanled_attribute.rb
chef/data_bags/crowbar/template-horizon.json
chef/data_bags/crowbar/template-horizon.schema

this settings was dropped in rocky
https://docs.openstack.org/releasenotes/horizon/rocky.html#upgrade-notes

 horizon: remove option OPENSTACK_TOKEN_HASH_ENABLED (SCRD-5906) 

---

chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/compute_register_cell.rb

We need to register compute nodes in nova cells. Otherwise the compute
node is not ready for scheduling VMs on it.
The current setup is racy because we rely on the
[scheduler]"discover_hosts_in_cells_interval" variable (which is set
to 600s currently). So if you add a new compute node, you have to wait
up to 600s until the node is usable.
This problem occured in the CI and also on local deployments. The
nova-conductor.log look like:
nova-conductor.log:2018-11-28 15:26:52.096 29009 ERROR
nova.conductor.manager No host-to-cell mapping found for selected
host d52-54-77-77-01-02. Setup is incomplete.: HostMappingNotFound:
Host 'd52-54-77-77-01-02' is not mapped to any cell
and a bit later the nova-scheduler.log indicates that the host got
discovered:
nova-scheduler.log:2018-11-28 15:27:30.816 …

nova: Register compute node in nova cell

---

chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/ironic/templates/default/ironic.conf.erb

Switched to using "ironic" network IP in api_url which is passed to
ironic-python-agent running on the node during deployment and/or cleanup.
This should fix problems when IPA can't access ironic API because ironic
network is the only one attached to the node and there is no routed
access to public network via ironic network.

ironic: Use ironic network for provisioning (bsc#1108398)

---

chef/cookbooks/tempest/templates/default/tempest.conf.erb

Some Tempest tests have microversion filters these days. For
these to work a minimum and maximum microversion needs to be
defined for services that do implement microversioning. This
commit adds these two values for all services that currently
implement microversioned testing.

tempest: configure microversions

---

chef/cookbooks/mysql/recipes/ha_galera.rb

Using the root user with empty password has the downside
that once the root user no longer has an empty password, it
can no longer observe the state. The monitoring user
is more useful for that as it is always available, even
when the cluster was already bootstrapped before. This
is important in case you want to add new nodes to an existing
cluster.

galera: Use monitoring user for observing wsrep state

---

chef/cookbooks/nova/attributes/default.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/303_update_vnc_keymap.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml
crowbar_framework/config/locales/nova/en.yml

nova: Remove deprecated vnc keymap configuration (SCRD-5787)

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/data_bags/crowbar/migrate/cinder/301_remove_use_syslog.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema

Removed use_syslog by deprecation since Pike
https://docs.openstack.org/cinder/pike/configuration/tables/conf-changes/cinder.html
Use syslog for logging. Existing syslog format is DEPRECATED and will be
changed later to honor RFC5424. This option is ignored if log_config_append
is set. (boolean value)
https://docs.openstack.org/cinder/rocky/configuration/block-storage/samples/cinder.conf.html

cinder: remove use_syslog setting by deprecation

---

chef/cookbooks/cinder/recipes/sql.rb

Due to a recent change in cinder, is considered a failure
if the command cinder-manage db online_data_migrations
exits code to 2
docs.openstack.org/releasenotes/cinder/rocky.html
The current tests include live migration and it generates
a failure (error code 2) in ci. So to avoid this problem in a fresh
installation all the migration code is removed. But it should
take in consideration when the cloud is upgraded.

cinder: removed live migrations code

---

chef/cookbooks/horizon/libraries/helper.rb
chef/cookbooks/horizon/recipes/monasca_ui.rb

The monasca databag config is accessing the monasca node attributes
unconditionally, which causes crashes when the monasca barclamp
is deactivated. Converting this to use the databag reduces
unnecessary nodesearches as well as avoiding those issues

horizon: load monasca from databag

---

chef/cookbooks/crowbar-openstack/libraries/provider_ssl_setup.rb

In 75fe195a a method was introduced to ensure certificates that are
installed by the operator were readable to OpenStack service users. This
method is never tested in CI because we only ever use self-signed,
crowbar-generated certs in CI. If an operator does generate their own
certs instead of having crowbar generate them, crowbar fails with this
message:
ArgumentError: ssl_setup[setting up ssl for keystone] (keystone::server line
78) had an error: ArgumentError: You must supply a name when declaring a
directory resource
This is because the method calls an operation on an object called
'directory' without defining it first, but 'directory' is already reserved
as the name of a Chef resource. Moreover, we can't directly call the
ruby File module from inside this module as ruby will assume …

ssl: Fix ACL setup in ssl_setup provider

---

chef/cookbooks/heat/templates/default/heat.conf.erb

also is not recommmended with keyston v3
https://review.openstack.org/#/q/Ib97fa5ef62f52e305cb406f423d261b80088d8a6

heat: deferred_auth_method is deprecated and

---

chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb

https://bugs.launchpad.net/horizon/+bug/1763204

horizon: django.wsgi has been deprecated, use wsgi.py (SCRD-4093)

---

chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/303_remove_rocky_deprecations.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

Removed deprecated settings from the configuration
- sql/min_pool_size
Minimum number of SQL connections to keep open in a pool.
https://github.com/openstack/oslo.db/blob/ab1c2b9076dc4fef9e3b7d880a69099172a5bf27/oslo_db/options.py#L70
- ovs/ovsdb_interface
The interface for interacting with the OVSDB
https://docs.openstack.org/releasenotes/neutron/queens.html

neutron: removed deprecation settings

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb

Some drivers has removed from cinder.conf because of deprecation
From https://docs.openstack.org/releasenotes/cinder/rocky.html
- HGST
- Disco 
From https://docs.openstack.org/releasenotes/cinder/pike.html
- Blockbridge
- Itachi Block Storage Driver (HBSD)
- Coho
- Infortrend
- Tegile

cinder: remove some deprecated drivers from cinder.conf

---

chef/cookbooks/mysql/templates/default/galera.cnf.erb

MariaDB 10.2.16 added a new option innodb_safe_truncate which requies a
the switch to mariabackup which can handle crash-safe rename operations.

mariadb: Set wsrep_sst_method to mariabackup (bsc#1116686)

---

chef/data_bags/crowbar/template-database.json

if you deploy the minimal of 10 services (each with the minimum
of 15 database threads) with the default 4 workers on a 3 node cluster,
you're at 1800 connections max already, so going with 1400 seems
to a reasonable default.

db: Raise default connection limit to 1400

---

crowbar_framework/app/models/database_service.rb
crowbar_framework/config/locales/database/en.yml

Monasca has its own MariaDB instance and we can't have it conflict
with the one deployed by database barclamp. See also bsc#1118759.

[4.0] database: Prevent deploying mysql-server role to monasca node

---

chef/cookbooks/keystone/recipes/server.rb
crowbar_framework/lib/openstack/upgrade.rb

This introduces the needed changes in the keystone cookbook for reducing its downtime during the upgrade. More details in: https://github.com/crowbar/crowbar-core/pull/1715
ToDo items:

[5.0] upgrade: reduce keystone downtime

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/mysql/templates/default/root-my.cnf.erb

Searching for the mysql database root password can be a major
pain, so just store it in ~/.my.cnf so that mysql defaults
to it and everything just works when you're root on the controller.
As you can change the password when you're root, this shouldn't
be an additional security hassle.

mysql: create .my.cnf in root home directory for mysql cmdline

---

chef/cookbooks/nova/recipes/compute.rb

This is just a wrapper package with no functionality, and
having two qemu binaries available seems to somewhat confuse
libvirt's capability caching.
(cherry picked from commit ac73ec54b215f08d79e59a021aa017183fbb1622)

nova-compute: stop installing qemu-kvm

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb

The current max of 4 is by far too low for Cloud8, we need to raise it.
In order to stay the same at 8 cores, try to use like 1/2 of the
available cores so that the rest remains available when nova or cinder
is colocated (which are the others using a lot of CPU)

neutron: scale up api workers on larger core envs

---

crowbar_framework/app/models/database_service.rb
crowbar_framework/config/locales/database/en.yml

Monasca has its own MariaDB instance and we can't have it conflict
with the one deployed by database barclamp. See also bsc#1118759.
(cherry picked from commit f552e748361703d515bd71c7fbec079066befa92)
port of https://github.com/crowbar/crowbar-openstack/pull/1923

database: Prevent deploying mysql-server role to monasca node

---

.travis.yml

Bundler has been updated and our travis configuration is no longer
working. There's a proposed fix at:
https://travis-ci.community/t/bundle-is-not-installed-for-ruby-2-3/1641

Update travis config to solve bundler dependency

---

.travis.yml

Bundler has been updated and our travis configuration is no longer
working. There's a proposed fix by limiting bunlder version to be less
than 2.0.0:
https://github.com/travis-ci/travis-ci/issues/5290
Our last working bundler version was 1.17.3
(cherry picked from commit ebc8927aada07e83cbee8ae75567df7f609618fe)

[5.0] Update travis config to solve bundler dependency

---

.travis.yml

Bundler has been updated and our travis configuration is no longer
working. There's a proposed fix by limiting bunlder version to be less
than 2.0.0:
https://github.com/travis-ci/travis-ci/issues/5290
Our last working bundler version was 1.17.3
(cherry picked from commit ebc8927aada07e83cbee8ae75567df7f609618fe)

[4.0] Update travis config to solve bundler dependency

---

crowbar_framework/app/models/database_service.rb
crowbar_framework/config/locales/database/en.yml

Monasca has its own MariaDB instance and we can't have it conflict
with the one deployed by database barclamp. See also bsc#1118759.
(cherry picked from commit f552e748361703d515bd71c7fbec079066befa92)
(cherry picked from commit fd0b95a8bb9b6f649edc95d459513771375ee0ca)

[5.0] database: Prevent deploying mysql-server role to monasca node

---

chef/cookbooks/keystone/libraries/helpers.rb
chef/cookbooks/keystone/providers/register.rb

The keystone_register LWRP currently does a clumsy, un-ruby-ish job of
creating an HTTP connection and performing REST operations with the
keystone server. This commit rewrites the keystone session management
interface as a class in the keystone helpers module so that the object
can be created once and used as needed in the provider, making the
interface cleaner and reducing LOC.

keystone: Make register requests object-oriented

---

chef/cookbooks/mysql/templates/default/galera.cnf.erb

MariaDB 10.2.16 added a new option innodb_safe_truncate which requies a
the switch to mariabackup which can handle crash-safe rename operations.
(cherry picked from commit cf6018758eca6af67f3f3c2c44c895608a0ae516)

[5.0] mariadb: Set wsrep_sst_method to mariabackup (bsc#1116686)

---

chef/cookbooks/nova/recipes/database.rb

Nova online data migrations should be run after the upgrade was
finished. They are not needed for regular deployments.
For the upgrade case, we can execute them directly using the upgrade
script (part of crowbar-core).
(cherry picked from commit 5cc5b312b3644fde1a500539a6bc5c77744beea4)
Port of https://github.com/crowbar/crowbar-openstack/pull/1938

upgrade: Do not run nova online-db-migrations from chef

---

chef/data_bags/crowbar/template-database.json

It seems the previous setting of 1400 is still not enough, with
https://github.com/crowbar/crowbar-openstack/pull/1952 we need
higher limits. 2048 should be safer.

db: Raise default connection limit to 2048

---

chef/cookbooks/manila/templates/default/manila.conf.erb

The `api_insecure` option in the [nova], [neutron], and [cinder] groups
was replaced by just `insecure`[1].
[1] https://docs.openstack.org/releasenotes/manila/rocky.html

manila: Fixup deprecated options (SCRD-6084)

---

chef/cookbooks/nova/templates/default/nova-placement.conf.erb

'auth_uri' is migrating to 'www_authenticate_uri' and there's nothing mentioned in doc about using this option under placement section on nova.conf
https://docs.openstack.org/nova/rocky/configuration/config.html#placement

nova: Remove auth_uri in placement section.

---

chef/cookbooks/swift/templates/default/object-server.conf.erb

Getting this from the object-server.log:
swift-o: Option object-replicator/run_pause is deprecated and will be removed
in a future version. Update your configuration to use option object-replica
tor/interval.

swift: Replace deprecated option.

---

chef/cookbooks/aodh/templates/default/aodh.conf.erb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
chef/cookbooks/ironic/templates/default/ironic.conf.erb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/manila/templates/default/manila.conf.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb

Fix up deprecated usage of ``[oslo_messaging_rabbit]/rabbit_use_ssl``
and ``[oslo_messaging_rabbit]/kombu_ssl_ca_certs`` in various services.
https://docs.openstack.org/oslo.messaging/latest/configuration/opts.html#oslo-messaging-rabbit

oslo.messaging: Fix deprecated options

---

chef/cookbooks/tempest/recipes/install.rb

In order to increase test coverate we want to install
the available tempest plugins for services that have splitted
them into a separate package.

tempest: install optional tempest plugins

---

chef/cookbooks/barbican/recipes/api.rb

This is already used by common, which is included here.

barbican: remove duplicate includes

---

CODEOWNERS

Triggering on the keystone keyword is not very fine-grained because
every service uses keystone_register to create users, projects,
endpoints, and services in keystone. Switch to just managing the
keystone cookbooks and databags.

Update cmurphy's code ownership

---

chef/cookbooks/horizon/attributes/default.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb
chef/data_bags/crowbar/migrate/horizon/302_remove_heat_policy_file.rb
chef/data_bags/crowbar/template-horizon.json
chef/data_bags/crowbar/template-horizon.schema

the policy file names are part of the settings files and the files are no longer there, so removing the config

Horizon policy fix (bsc#1111421)

---

chef/cookbooks/horizon/files/default/default-dashboards-provider.yaml
chef/cookbooks/horizon/files/default/grafana-monasca.json
chef/cookbooks/horizon/files/default/grafana-openstack.json
chef/cookbooks/horizon/recipes/monasca_ui.rb
chef/cookbooks/horizon/templates/default/_80_monasca_ui_settings.py.erb
chef/cookbooks/horizon/templates/default/grafana.ini.erb

Starting with Grafana 5.x [dashboards.json] configuration section has been
replaced with provisioning mechanism [1]. This requires following changes in the
set-up:
* Set dashboard uids
* Update default dashboard URLs
* Provide default paths.provisioning configuration value
[1] http://docs.grafana.org/administration/provisioning

horizon: Update configuration for Grafana 5.x

---

chef/data_bags/crowbar/migrate/database/200_add_slow_query.rb
chef/data_bags/crowbar/migrate/database/201_add_tuning_variables.rb
chef/data_bags/crowbar/migrate/database/202_add_ssl.rb
chef/data_bags/crowbar/migrate/database/203_add_expire_logs_days.rb

Schema revision 200 to 203 have been backported to older release
branches. In order to not loose some configurations values during the
upgrade those migration needed to have additional checks in the newer
branches.
(cherry picked from commit bd39c4890ee9cc6c539ec5e961c176b4e2a00e61)
backport of #1982

[5.0] database: Fix backport schema migrations actualy safe for backporting

---

chef/cookbooks/nova/recipes/vncproxy.rb

Opt out of installing nova-consoleauth to inline with astack cloud.
https://docs.openstack.org/releasenotes/nova/rocky.html#deprecation-notes

nova: nova-consoleauth is deprecated.

---

chef/cookbooks/monasca/recipes/master.rb

Currently, the monasca-installer run can fail but the Crowbar
deployment just continues. This might result in follow-up errors.
The reason is, that the return code of the run-monasca-installer
script is not evaluated. Instead the return code of awk is
evaluated (which is usually zero).
So set "pipefail" to also detect run-monasca-installer failures and
abort the chef-client run in that case.

monasca: Detect failure during monasca-installer run

---

chef/cookbooks/mysql/templates/default/galera.cnf.erb

MariaDB 10.2.16 added a new option innodb_safe_truncate which requies a
the switch to mariabackup which can handle crash-safe rename operations.
(cherry picked from commit cf6018758eca6af67f3f3c2c44c895608a0ae516)

[4.0] mariadb: Set wsrep_sst_method to mariabackup (bsc#1116686)

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb

The current max of 4 is by far too low for Cloud8, we need to raise it.
In order to stay the same at 8 cores, try to use like 1/2 of the
available cores so that the rest remains available when nova or cinder
is colocated (which are the others using a lot of CPU)
(cherry picked from commit 8d9cda292ac6e8e9507b1ec18bdd020f06ad9e48)

[5.0] neutron: scale up api workers on larger core envs

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb

Pike has been adding support for managing concurrently used pools, so
it spends more than half of its time on assessing the disk usage.
With https://review.openstack.org/#/c/625970/1 this should become better
but until then we can disable the cinder pool size calculation for
embedded ceph, which removes a perceived hang of multiple minutes
when the disk size calculation kicks in.
When using the RBD pool exclusively for Cinder we can now set
`rbd_exclusive_cinder_pool` to `true` and Cinder will use DB information
to calculate provisioned size instead of querying all volumes in the
backend, which will reduce the load on the Ceph cluster and the volume
service.

cinder: Set cinder pool to exclusive by default when using embedded ceph

---

chef/cookbooks/horizon/files/default/grafana-monasca.json
chef/cookbooks/horizon/files/default/grafana-openstack.json

monasca-agent creates the metric "mem.used_real_mb" now(see [1]). So
use that metric to list the used memory for the Monasca node and all
the OpenStack nodes.
[1] https://review.openstack.org/#/c/437159/

horizon: Fix mem.used_mb in Grafana

---

chef/cookbooks/nova/recipes/controller_ha.rb

because the service does not like empty ssl packets followed by RST.
The service restarts its internal server causing high CPU load, which is
bad itself but also causes other service disrutions during deploy.

novnc: disabled ssl based checks via haproxy

---

chef/cookbooks/monasca/templates/default/monasca-log-api.conf.erb

Instead of setting a custom value, drop "max_log_size" and use the
default (which is 1048576).
This fixes the following tempest tests:
- monasca_tempest_tests.tests.log_api.test_constraints.\
TestLogApiConstraints.test_should_reject_too_big_message
- monasca_tempest_tests.tests.log_api.test_constraints.\
TestLogApiConstraints.test_should_reject_too_big_message_multiline
Note: to fix this, it needs an change to the monasca-tempest-plugin so
the message size is configurable in tempest. Otherwise, the test will
fail if a user set a custom "max_log_size". But for now we just use
the default value.
Thanks Witek Bedyk for explaining the problem!

monasca: Drop [service]max_log_size config

---

chef/cookbooks/monasca/templates/default/monasca-persister.conf.erb

Upstream default value for `alarm_state_history_driver` in _monasca-persister_ configuration is wrong. It prevents storing alarms history and causes tempest tests failures.
This change sets the correct value.

monasca: Fix alarm_state_history repo module

---

chef/cookbooks/horizon/libraries/helper.rb
chef/cookbooks/horizon/recipes/server.rb

heat proposal is still not saved while it is being applied as a
result corresponding horizon plugin will not get installed
And thus requires another chef-client run.
This additional check will get the package installed even while heat
proposal is being applied

hoirzon: search for role while installing heat-plugin (SCRD-7430)

---

crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml

Reverts crowbar/crowbar-openstack#1984
as discussed in https://github.com/crowbar/crowbar-openstack/pull/1985 we were somehow confused about what Rick wanted so this should not have landed.

Revert "database: Hide SSL options from database UI"

---

chef/cookbooks/mysql/attributes/server.rb

We switched some time ago to mariabackup and therefore xtrabackup is not
needed anymore

mariadb: Remove installing the xtrabackup package

---

chef/cookbooks/keystone/libraries/helpers.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/data_bags/crowbar/migrate/keystone/302_add_osprofiler.rb
chef/data_bags/crowbar/template-keystone.json
chef/data_bags/crowbar/template-keystone.schema
crowbar_framework/app/models/keystone_service.rb

Adding osprofiler[1] support is useful for profiling OpenStack accross
different services. This can be used to find bottlenecks or slow code
inside the different OpenStack services.
osprofiler needs to be enabled in the different services and this
commit starts with keystone.
Once osprofiler is enabled (via the Crowbar attributes), it can be
used like this:
1) Call a command with the openstack client (which supports
osprofiler). Note: You have to know (and use) the HMAC key that is in the
Crowbar attribute stored. If you don't use that HMAC key, osprofiler
won't do anything.
$ openstack --os-profile 9tcwL56PlpAx endpoint list
...
Trace ID: e860c2b0-6945-4767-bbd9-c42c08e6417c
Beside the usual output (in this case the output of "endpoint list"),
there will be a Trace ID written to the …

keystone: Add basic osprofiler support

---

chef/cookbooks/monasca/templates/default/kafka-server.properties.erb

Monasca components still work with old message format version.

monasca: Set Kafka log message format version

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/mysql/templates/default/root-my.cnf.erb

#1701 
Searching for the mysql database root password can be a major
pain, so just store it in ~/.my.cnf so that mysql defaults
to it and everything just works when you're root on the controller.
As you can change the password when you're root, this shouldn't
be an additional security hassle.
(cherry picked from commit 95d2936fd5896a6942adcbb22cfa34c02f1fbec2)

[5.0] mysql: create .my.cnf in root home directory for mysql cmdline

---

chef/cookbooks/mysql/attributes/server.rb

We switched some time ago to mariabackup and therefore xtrabackup is not
needed anymore
(cherry picked from commit 10f65db2dd4fa19ba4ee99c551a8634513363a29)

[5.0] mariadb: Remove installing the xtrabackup package

---

chef/cookbooks/mysql/attributes/server.rb

We switched some time ago to mariabackup and therefore xtrabackup is not
needed anymore
(cherry picked from commit 10f65db2dd4fa19ba4ee99c551a8634513363a29)

[4.0] mariadb: Remove installing the xtrabackup package

---

chef/cookbooks/horizon/recipes/server.rb

this is a followup commit for 49ab94a82151941b2907420536f9698104db9728
it adapts the chef-package to install the plugin while applying the
corresponding proposal itself

horizon: use RoleHelper while deciding to install ui plugins (SCRD-7430)

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb

If in a neutron cluster are less than configured number of
nodes online, neutron will try to start squeeze the dhcp agents
on the remaining nodes, which does not seem to actually work
and does not actually improve availability. In larger deployments
the duplicated rules seem to cause the dhcp agents to trip over
and we have rolling outages.
By only starting dhcp agents for the "smallest" online cluster size
we can avoid that. In a 3 node cluster we can tolerate a single
node failure, starting two agents. in a 5 node we can tolerate 2
nodes failure so 3 agents should be started and so on.

neutron: Reduce number of dhcp agents to tolerate node failures

---

chef/cookbooks/sahara/templates/default/sahara.conf.erb

Use the new [trustee] section for trust configuration, as using the
credentials defined in [keystone_authtoken] is deprecated[1].
[1] https://docs.openstack.org/releasenotes/sahara/queens.html#deprecation-notes

sahara: Add [trustee] configuration (SCRD-6088)

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/templates/default/logging.cnf.erb

the mariadb package comes with a logrotate
script (/etc/logrotate.d/mariadb) that currently only rotates the
default /var/log/mysql/mysqld.log file.
So let's use that file instead of a custom path to fix log rotation.
Note: If "slow_query_logging" is enabled, this file is still not
rotated. This will hopefully be fixed in the package itself[1]
[1] https://build.opensuse.org/request/show/676156

mysql: Do not set a custom logfile for mysqld (bsc#1112767)

---

chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/glance/recipes/cache.rb
chef/cookbooks/glance/recipes/scrubber.rb
chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/glance/templates/default/glance-cache.conf.erb
chef/cookbooks/glance/templates/default/glance-scrubber.conf.erb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova-placement.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/keystone/303_add_osprofiler_connection_string.rb
chef/data_bags/crowbar/template-keystone.json
chef/data_bags/crowbar/template-keystone.schema

Adding osprofiler[1] support is useful for profiling OpenStack accross
different services. This can be used to find bottlenecks or slow code
inside the different OpenStack services.
See also commit 5ba4f0e1af92 for more information.
[1] https://docs.openstack.org/osprofiler/latest/

Add osprofiler support for more services

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/templates/default/logging.cnf.erb

the mariadb package comes with a logrotate
script (/etc/logrotate.d/mariadb) that currently only rotates the
default /var/log/mysql/mysqld.log file.
So let's use that file instead of a custom path to fix log rotation.
Note: If "slow_query_logging" is enabled, this file is still not
rotated. This will hopefully be fixed in the package itself[1]
[1] https://build.opensuse.org/request/show/676156
(cherry picked from commit aabd06b7a291a2e5a3465238957f32390c8fffdd)

[5.0] mysql: Do not set a custom logfile for mysqld (bsc#1112767)

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/mysql/templates/default/root-my.cnf.erb

Searching for the mysql database root password can be a major
pain, so just store it in ~/.my.cnf so that mysql defaults
to it and everything just works when you're root on the controller.
As you can change the password when you're root, this shouldn't
be an additional security hassle.
(cherry picked from commit 95d2936fd5896a6942adcbb22cfa34c02f1fbec2)

[4.0] mysql: create .my.cnf in root home directory for mysql cmdline

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/templates/default/logging.cnf.erb

the mariadb package comes with a logrotate
script (/etc/logrotate.d/mariadb) that currently only rotates the
default /var/log/mysql/mysqld.log file.
So let's use that file instead of a custom path to fix log rotation.
Note: If "slow_query_logging" is enabled, this file is still not
rotated. This will hopefully be fixed in the package itself[1]
[1] https://build.opensuse.org/request/show/676156
(cherry picked from commit aabd06b7a291a2e5a3465238957f32390c8fffdd)
(cherry picked from commit a0bb13aeddef74775ab15610d4b2def6cec8ba0c)

[4.0] mysql: Do not set a custom logfile for mysqld (bsc#1112767)

---

chef/cookbooks/ceilometer/attributes/default.rb
chef/cookbooks/ceilometer/recipes/server_ha.rb

With recent openstack-ceilometer packaging changes (Newton[1],
Pike[2]), the ceilometer-expirer cronjob is no longer installed on all
nodes where the openstack-ceilometer-collector package is
installed. Instead the cronjob is installed in
/usr/share/ceilometer//openstack-ceilometer-expirer.cron .
This is needed to avoid parallel runs of the cronjob from different
nodes which lead to database deadlocks.
Now use pacemaker to handle a symlink in /etc/cron.daily so the
cronjob is executed on a single node in the cluster.
[1] https://build.opensuse.org/request/show/676177
[2] https://build.opensuse.org/request/show/676174

[4.0] ceilometer: Use pacemaker to handle expirer cron link (bsc#1113107)

---

chef/cookbooks/ceilometer/attributes/default.rb
chef/cookbooks/ceilometer/recipes/server_ha.rb

With recent openstack-ceilometer packaging changes (Newton[1],
Pike[2]), the ceilometer-expirer cronjob is no longer installed on all
nodes where the openstack-ceilometer-collector package is
installed. Instead the cronjob is installed in
/usr/share/ceilometer//openstack-ceilometer-expirer.cron .
This is needed to avoid parallel runs of the cronjob from different
nodes which lead to database deadlocks.
Now use pacemaker to handle a symlink in /etc/cron.daily so the
cronjob is executed on a single node in the cluster.
[1] https://build.opensuse.org/request/show/676177
[2] https://build.opensuse.org/request/show/676174
(cherry picked from commit fc5971cbc019d1bf93723f401cd083647feae737)

[5.0] ceilometer: Use pacemaker to handle expirer cron link (bsc#1113107)

---

chef/cookbooks/mysql/templates/default/logging.cnf.erb

When "slow_query_logging_enabled" is used, enable also "explain" which
adds extra information[1] to the log file.
This is useful for debugging slow queries.
[1] https://mariadb.com/kb/en/library/explain-in-the-slow-query-log/

mysql: Enable "explain" in the slow query log file

---

crowbar_framework/app/models/monasca_service.rb

Pacemaker could fence a cluster node for some reason and having
monasca-server running there would mean monasca going down (bsc#1118759)

monasca: Prevent deploying monasca-server to the node in pacemaker cluster

---

chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

Fix the image file that the barbican tempest plugin uses for testing signed images, and fix glance's ability to use the castellan key manager.

Fix barbican tempest tests (SCRD-7084) (bsc#1123191)

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/glance/templates/default/glance-api.conf.erb

The keystone_settings keys use strings, not symbols, so fix the template for glance. Also add the required setting in the cinder config.

glance/cinder: Fix barbican auth endpoint

---

chef/data_bags/crowbar/migrate/keystone/302_add_osprofiler.rb

Commit 5ba4f0e1a added osprofiler support and added a migration to add
the relevant crowbar attributes. This migration needs to use a class
variable and the name of the class variable should be prefixed with
the barclamp name.

keystone: Fix migration which added osprofiler support

---

chef/cookbooks/rabbitmq/recipes/rabbit.rb

When the regex for mirroring queues was introduced on
341f6b059b33690e607e9a3da83cf250c97323d0 a typo was introduced
which skipped some of the default queues.
Restore it to the proper regex
(cherry picked from commit 97c1e7d1814fafbcfc92a1b133d4abea4eca427a)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/2047

[4.0] rabbit: fix mirroring regex

---

chef/data_bags/crowbar/migrate/ironic/301_drivers_to_hardware_types.rb

If enabled_drivers was empty, nothing was migrated and proposal was
failing validation.
This is a fix for migration introduced here: https://github.com/crowbar/crowbar-openstack/pull/2003

ironic: Fix drivers migration

---

chef/cookbooks/monasca/recipes/elasticsearch.rb
chef/cookbooks/monasca/templates/default/elasticsearch-systemd-override.conf.erb
chef/data_bags/crowbar/migrate/monasca/313_drop_elasticsearch_options.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema

The default installation of Elasticsearch is configured with a 1 GB
heap. For just about every deployment, this number is usually too small
[1]. This change allows setting `heap_size`.
elasticearch.tunables.max_open_files_soft_limit isn't used anymore. It
gets removed here, instead `limit_nofile` should be used.
elasticearch.tunables.memory_lock has is actually decoupled from
elasticsearch.bootstrap_memory_lock which it was supposed to control.
The latter has anyway a recommended default value. The setting is very
technical, so it makes sense to hide it from end user.
[1] https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html

monasca: Set heap size for Elasticsearch

---

chef/cookbooks/rabbitmq/recipes/rabbit.rb

When the regex for mirroring queues was introduced on
341f6b059b33690e607e9a3da83cf250c97323d0 a typo was introduced
which skipped some of the default queues.
Restore it to the proper regex

rabbit: fix mirroring regex

---

chef/cookbooks/rabbitmq/recipes/rabbit.rb

When the regex for mirroring queues was introduced on
341f6b059b33690e607e9a3da83cf250c97323d0 a typo was introduced
which skipped some of the default queues.
Restore it to the proper regex
(cherry picked from commit 97c1e7d1814fafbcfc92a1b133d4abea4eca427a)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/2047

[5.0] rabbit: fix mirroring regex

---

chef/cookbooks/mysql/recipes/ha_galera.rb

This patch applies the option "on-marked-down shutdown-sessions"
to our haproxy galera configuration to deal with the situation that
happens keeping connections open when a backend is declared down by
the health check but the mariadb server is still alive
Depends-On: https://github.com/crowbar/crowbar-ha/pull/347
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>

mysql: improve galera HA setup (bsc#1122875)

---

chef/cookbooks/nova/recipes/compute_register_cell.rb

When the nova-manage command is run, it tries to load configuration from
the default nova config directory even if --config-file is used. The
config files are owned by the root user but readable by the nova group.
If the nova group is not specified in the chef bash resource, the
nova-manage command fails. The failure is hidden and the chef run
continues because the exit code from the bash script comes from the `rm
-f` command the not the nova-manage command. The usual result is that
when the manila server is being booted in preparation for applying the
manila barclamp in CI, it fails. This patch adds the correct group to
the bash resource so that the nova-manage command can complete, and uses
'set -e' so that if it fails for some other reason, it will exit with a
proper failure code and …

nova: Fix discover_hosts group

---

chef/cookbooks/monasca/recipes/database.rb

Sometimes it takes a little longer to start the InfluxDB instance and
the request to create the database fails with:
Failed to connect to http://x.x.x.x:8086: connect: connection refused
Please check your connection settings and ensure 'influxd' is running.
This change retries the request to give InfluxDB some more time to spin
up.

monasca: Retry creating InfluxDB database

---

chef/cookbooks/tempest/recipes/install.rb

If a tempest plugin is installed then by default its tests will be run
unless explicitly turned off in tempest.conf. This breaks our
tempestfull CI because we do not install magnum by default. This change
ensures only plugins for barclamps we have applied will be installed.

tempest: Conditionally install nonrequired plugins

---

chef/cookbooks/swift/recipes/monitor_monasca.rb

Status of Swift service is not checked correctly. Swift offers
healhcheck middleware for monitoring. /healthcheck resource should be
used to monitor this service [1].
[1] https://docs.openstack.org/swift/latest/middleware.html#healthcheck

swift: Fix Monasca agent configuration (SCRD-7572)

---

chef/cookbooks/horizon/recipes/monasca_ui.rb

Monasca plugin should only be installed when all configuration options
are already available. Otherwise if Horizon barclamp is installed first
and Monasca afterwards the installation fails with the following error
message:
FATAL: NoMethodError: undefined method `[]' for nil:NilClass
Relevant File Content:
22>> grafana_password = monasca_cfg["db_grafana"]["password"]

horizon: Fix configuration loading for Monasca (SCRD-8179)

---

chef/cookbooks/tempest/recipes/config.rb

When a nova server is booted with the 'tempest-stuff' flavor and an
encrypted cinder volume is attached, it can never be detached. Instead,
it will hang in 'detaching' state for a while and then return to
'in-use' with no error messages in the logs. This causes the tempest
tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes
tests to fail since detaching times out. This change fixes the issue by
bumping up the size of the tempest-stuff flavor that is used for these
tempest tests.

tempest: Bump up size of tempest flavor

---

chef/cookbooks/nova/recipes/compute_register_cell.rb

In some cases there can be a race condition where a compute node is
being discovered by the controller at the same instant that the node is
trying to register itself with `nova-manage cell_v2 discover_hosts`,
which results in an error like this:
DBDuplicateEntry: (pymysql.err.IntegrityError) (1062, u"Duplicate entry 'd00-25-90-e5-0b-aa' for key 'uniq_host_mappings0host'")
In a case like this, it is safe to ignore because the host is already
discovered. This patch removes the `set -e` part of the script in order
to be more forgiving for errors like this, since we can't use crowbar
sync marks to orchestrate node discovery like this.

nova: Ignore errors for discover_hosts

---

chef/data_bags/crowbar/template-neutron.json

We want to have the option to use lbaasv2 in Crowbar enabled given
that Octavia is not yet ready.
This reverts commit 714f8f203c95055f38e3de3444ed9282ba9fc5cc.

Revert "neutron: disable lbaas integration for now"

---

chef/cookbooks/tempest/recipes/config.rb

This reverts commit a534ce224f6ba161000392c5844f35e9cdf81d54.
Increasing the test flavor size causes other tempest tests to fail with
a "no valid host" error since the instance size is now too big. We'll
need to find another solution to fix the problem with unmounting the
encrypted volume.

Revert "tempest: Bump up size of tempest flavor"

---

chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb

Avoiding plain text downgrade seems like a good thing. see
https://tools.ietf.org/html/rfc6797 for details.

horizon: Set HSTS for Horizon

---

chef/cookbooks/nova/recipes/compute_ha.rb

**[supersedes #2017]**
Without this patch, the three OCF RAs involved in providing compute HA use v2 of the keystone API.  This is a problem because [there is no longer a v2 API available](https://docs.openstack.org/releasenotes/keystone/queens.html#other-notes).
So for example the `fence_compute` agent tries to use keystone v2 and the following failures are seen in `/var/log/nova/fence_compute.log`:
DEBUG:
http://cluster-services.vc1.cloud.suse.de:5000 "GET /v2.0/ HTTP/1.1" 404
DEBUG: RESP: [404]....
and this in keystone logs:
GET/v2.0/HTTP/1.1 404 233 - python-keystoneclient
These get flagged as `crm_mon` failures, breaking the feature and causing the CI job to fail.
This patch solves the problem by switching to the standard `internal_auth_url` used elsewhere.  This is possible because …

nova: use correct url from keystone helper for fence-agent (SCRD-7603)

---

chef/cookbooks/keystone/libraries/helpers.rb
chef/cookbooks/keystone/providers/register.rb

This adds back the new object-oriented keystone session handling
introduced in ff7a6ec5. It fixes the issue that caused the original
revert by explicitly resetting the session object at the end of the
:update_one_endpoint action so that the old protocol is not still active
for the next keystone_register command.
This reverts commit 158755c15afd4baf97f34e7b52922c37ef311bcd.

Revert "Revert "keystone: Make register requests object-oriented""

---

chef/cookbooks/memcached/libraries/helpers.rb

When this code was refactored, a fallback of node[:memcache][:port] was
used, since the original code in the nova and horizon cookbooks used it.
However, node is not defined in this context, so the fallback causes a
NameError instead. Use the first array element as the fallback instead.

memcache: Use first array element as fallback (SCRD-8255)

---

chef/data_bags/crowbar/template-database.json

if you deploy the minimal of 10 services (each with the minimum
of 15 database threads) with the default 4 workers on a 3 node cluster,
you're at 1800 connections max already, so going with 1400 seems
to a reasonable default.
It seems the previous setting of 1400 is still not enough, with
#1952 we need
higher limits. 2048 should be safer

[5.0] db: Raise default connection limit to 2048

---

chef/cookbooks/memcached/libraries/helpers.rb

When this code was refactored, a fallback of node[:memcache][:port] was
used, since the original code in the nova and horizon cookbooks used it.
However, node is not defined in this context, so the fallback causes a
NameError instead. Use the first array element as the fallback instead.
(cherry picked from commit 6da784a4cb173d2023a1be34d4d8ebea12aa74f2)

[5.0] memcache: Use first array element as fallback (SCRD-8255)

---

chef/cookbooks/glance/recipes/api.rb

the currently used flag is not set anywhere as a result this migration is run
everytime the recipe is run.

glance: use the correct db_synced flag

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb
chef/data_bags/crowbar/migrate/tempest/301_remove_alt_users.rb
chef/data_bags/crowbar/template-tempest.json
chef/data_bags/crowbar/template-tempest.schema
crowbar_framework/app/models/tempest_service.rb
crowbar_framework/app/views/barclamp/tempest/_edit_attributes.html.haml
crowbar_framework/config/locales/tempest/en.yml

The tag extension is deprecated as of Queens, and has been
replaced by tagging.

tempest: update neutron extension list

---

chef/cookbooks/horizon/recipes/monasca_ui.rb
chef/cookbooks/manila/recipes/sql.rb

It has been observed that DB migrations for Grafana and Manila take
more time than the configured default 60 s timeout for sync_marks. This
change doubles the timeout in Horizon and Manila barclamps to 120 s.

Increase sync_mark timeouts (SCRD-8179)

---

chef/cookbooks/monasca/recipes/agent.rb

All agents should set FQDN as hostname to allow unambiguous
identification of the measurement source. Right now FQDN is set on
Monasca server and hostname on OpenStack nodes.
Release note should be provided as customers upgrading from existing
installation will observe new time series.

monasca: Set hostname for monasca-agent as FQDN (SCRD-8705)

---

designate.yml

This commit makes the Designate barclamp visible by removing
the `user_managed: false` barclamp attribute.

designate: show barclamp

---

chef/cookbooks/designate/recipes/mdns.rb

Fit typo in variable name and `dnsservs` array initialisation.

designate: Fix variables initialization in mdns

---

chef/cookbooks/monasca/recipes/agent.rb

All agents should set FQDN as hostname to allow unambiguous
identification of the measurement source. Right now FQDN is set on
Monasca server and hostname on OpenStack nodes.
Release note should be provided as customers upgrading from existing
installation will observe new time series.
backport of #2084
(cherry picked from commit f1d7809fe19f81f13999d334aeb9f160f7ca6353)

[5.0] monasca: Set hostname for monasca-agent as FQDN (SCRD-8705)

---

chef/cookbooks/ceilometer/recipes/server_ha.rb

Commit 2f441560b uses pacemaker to handle the cron symlink. But to
work correctly, the link
destination (/usr/share/ceilometer/openstack-ceilometer-expirer.cron)
needs to be there and this file is in the
openstack-ceilometer-collector package.
So install the package to solve this.

[5.0] ceilometer: Install package which contains cron file (bsc#1130414)

---

chef/cookbooks/tempest/templates/default/tempest.conf.erb

Following changes are included to make basic ironic testing possible:
1. Use fake-hardware driver
Current default in ironic_tempest_plugin config is still "fake"
with comment: "change to fake-hardware when Ocata is no longer supported".
2. Change endpoint type to public
Two tests in ironic suite check endpoint urls and they expect public ones.
3. Disable ironic inspector tests
Ironic barclamp doesn't support Inspector yet.
With above plus https://github.com/SUSE-Cloud/automation/pull/3295 I got following results:
```
======
Totals
======
Ran: 201 tests in 1949.0000 sec.
- Passed: 178
- Skipped: 21
- Expected Fail: 0
- Unexpected Success: 0
- Failed: 2
Sum of execute time for each test: 578.9197 sec.
```
Remaining two failed tests are for:
- BFV (Boot From Volume) - not implemented in …

tempest: Improve ironic test results (was: Use fake-hardware driver)

---

chef/cookbooks/ironic/libraries/helpers.rb
chef/cookbooks/ironic/templates/default/ironic.conf.erb

Swift endpoint in Glance section is used to build TempURLs. These
are then used by Ironic agent running from a ramdisk image. It is
better to use IP here as proper DNS configuration might not be
available in the image and Swift host would not be resolved.

ironic: Use IP instead of DNS name for Swift

---

chef/data_bags/crowbar/template-rabbitmq.json

With this configuration, the database Mnesia reduces the activity to the disk.
It is useful when a huge of queues/exchanges/bindings are created and destroyed.
With the default value (100), RabbitMQ could log {Mnesia is overloaded}. Moved to 300.
The range should be between 100 and 1000. Read [1] for more info. [1]
http://erlang.org/doc/man/mnesia.html#dump_log_write_threshold
main stream ref: https://review.openstack.org/#/c/648437/

Improve Mnesia IO performances

---

chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/cookbooks/ceilometer/templates/default/polling_pipeline.yaml.erb

* Add a [polling] section to ceilometer.conf with cfg_file property which
points to polling_pipeline.yaml
* removed default_domain_id and default_domain_name from  [service_credentials]
and added project_domain_name and user_domain name to [service_credentials]
in polling.conf to prevent ceilometer polling agent from failing with
"need user domain" and "need project domain" error.
* added a new pipeline yaml file for polling agent, called polling_pipeline.yml
* added swift meters which are polling meters to polling_pipeline.yml

ceilometer: add a polling section in ceilometer conf (SCRD-8720)

---

chef/cookbooks/designate/recipes/mdns.rb

there could be deployments with just single dns-server role in that
there will be no "dns-slaves". In such a case the array append fails as
dnsslaves is nil
So using `to_a` as fail-safe `(nil.to_a == [])` way to convert it to array
if not already.
`also_notifies` in such case will have to be empty list
yaml module take case of printing the right thing incase the array is
empty
```yaml
also_notifies: []
```

designate: rely on dns-master entirely (SCRD-8797)

---

crowbar_framework/app/views/barclamp/neutron/_edit_attributes.html.haml
crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml
crowbar_framework/config/locales/neutron/en.yml
crowbar_framework/config/locales/nova/en.yml

This is not supported, so keep the attributes for the raw view.

nova, neutron: Hide the ZVM attributes

---

chef/cookbooks/tempest/recipes/config.rb

ID 8 was already used in nova cookbook.
Taking 20 to leave some space for the future (and skip 13).

tempest: Fix Heat flavor id

---

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/data_bags/crowbar/migrate/neutron/306_fix_domains_names.rb
chef/data_bags/crowbar/template-neutron.json

the config enabled by this flag lets neutron create dns records when
floating ip are created and assigned.
The config was previously added but was not enabled as the barclamp was
still under development 
This config is not really needed for designate or neutron to work, but they help enable certain features
this is where the flag is used https://github.com/crowbar/crowbar-openstack/blob/a671c048ec071a13170d055b4dfc5a6906596cd0/chef/cookbooks/neutron/templates/default/neutron.conf.erb#L36-L48

neutron: enable designate integration

---

designate.yml

This reverts commit 64e7ad98f3ed075c3948ca542cfcd61ac9215a10.
We've are very close to the release and have multiple pull requests still open
for Designate:
* https://github.com/crowbar/crowbar-openstack/pull/2095
* https://github.com/crowbar/crowbar-openstack/pull/2104
* https://github.com/crowbar/crowbar-openstack/pull/2105
* https://github.com/SUSE-Cloud/doc-cloud/pull/931
There are way too many question marks on this so I am
switching the barclamp back to invisible mode. Lets get these
pull requests squared away carefully and without the rush of
imminent release.

Revert "designate: show barclamp"

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

This is currently the only "integration" test for Ironic. It requires
"real" Ironic node to be present and some adjustments in Tempest config
to pass.

tempest: Enable BaremetalBasicOps test

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

When we toggle ssl/non-ssl in keystone, neutron-ha-tool
gets a new config file but doesn't get restarted, so it just
repeatedly crashes all the way until it causes a pacemaker
failcount exceeded and then its dead. We should try better.

neutron: restart neutron-ha-tool when the config file changes

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

When we restart via systemd, it can happen that the service already
crashed and then 'service neutron-l3-ha-service status" will (correctly)
report that the service isn't running. And then the restart is not being
executed due to:
INFO: Ignoring restart action for neutron-l3-ha-service service since not running on this node (d52-54-77-77-01-01)
which will then later cause a pacemaker failcount. the pacemaker
resource restart hopefully does not have this problem.

neutron: use crm_resource restart for restarting neutron-l3-ha-service

---

chef/cookbooks/mysql/recipes/ha_galera.rb

This patch applies the option "on-marked-down shutdown-sessions"
to our haproxy galera configuration to deal with the situation that
happens keeping connections open when a backend is declared down by
the health check but the mariadb server is still alive
Depends-On: https://github.com/crowbar/crowbar-ha/pull/347
Backports: https://github.com/crowbar/crowbar-openstack/pull/2023
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>
(cherry picked from commit b1106b3ec54a6fc0f7dcfdf4fe9d37347e7ae344)

[5.0] mysql: improve galera HA setup (bsc#1122875)

---

chef/cookbooks/mysql/recipes/ha_galera.rb

This patch applies the option "on-marked-down shutdown-sessions"
to our haproxy galera configuration to deal with the situation that
happens keeping connections open when a backend is declared down by
the health check but the mariadb server is still alive
Depends-On: https://github.com/crowbar/crowbar-ha/pull/347
Backport: https://github.com/crowbar/crowbar-openstack/pull/2023
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>
(cherry picked from commit b1106b3ec54a6fc0f7dcfdf4fe9d37347e7ae344)

[4.0] mysql: improve galera HA setup (bsc#1122875)

---

chef/data_bags/crowbar/template-database.json

Looks like 5 minutes is too short in some cases
when a new node is joining. I have observed the 5 min timeout
in a small cloud of 100 nodes already that has been operated
for some time, so we might be better off being conservative.

database: Raise and align promote/demote timeouts (bsc#1131791)

---

chef/data_bags/crowbar/template-database.json

Looks like 5 minutes is too short in some cases
when a new node is joining. I have observed the 5 min timeout
in a small cloud of 100 nodes already that has been operated
for some time, so we might be better off being conservative.
(cherry picked from commit 2f84ad631c82bf75f84b395929a2bb5780c7da61)

[5.0] database: Raise and align promote/demote timeouts (bsc#1131791)

---

chef/cookbooks/monasca/providers/agent_plugin_ovs.rb
chef/cookbooks/monasca/recipes/role_monasca_server.rb
chef/cookbooks/monasca/resources/agent_plugin_ovs.rb
chef/cookbooks/monasca/templates/default/monasca-api.conf.erb
chef/cookbooks/monasca/templates/default/monasca-reconfigure-server.erb
chef/cookbooks/neutron/recipes/monitor_monasca_ovs.rb
chef/cookbooks/neutron/recipes/role_neutron_network.rb
chef/data_bags/crowbar/migrate/monasca/315_add_ovs_plugin_settings.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema
crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
crowbar_framework/config/locales/monasca/en.yml

Add Monasca OVS plugin configuration on all neutron-network nodes.
Plugin configuration is automatically enabled and can be disabled in
Crowbar UI.
Monasca OVS plugin autodetection is disabled on Monasca server node.
Add `monasca-agent` role to `delegate_authorized_roles` to enable
collecting tenant metrics.

monasca: Add openvswitch plugin (SCRD-7571)

---

chef/cookbooks/designate/recipes/common.rb
chef/cookbooks/designate/templates/default/designate.conf.erb

the desigante-worker does not need keystone auth token, it commnunicates
only with desginate-central over rpc.
the diagram gives a hint of this [1] or else one could look the code [2]
1 -
https://docs.openstack.org/designate/rocky/contributor/architecture.html
2-
https://opendev.org/openstack/designate/src/branch/master/designate/worker/service.py

designate: do not install the keystone_authtoken on worker nodes

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/templates/default/galera.cnf.erb
chef/data_bags/crowbar/migrate/database/301_make_wsrep_provider_options_configurable.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

It is sometimes useful to be able to add extra options (like
gcache.size, gcs.fc_debug, ...) to the galera wsrep_provider_options
configuration variable.
This can now be done via the Crowbar RAW view.

database: Make wsrep_provider_options configurable (fate#327745)

---

chef/cookbooks/horizon/recipes/monasca_ui.rb
chef/cookbooks/horizon/templates/default/grafana-openstack.json.erb

Grafana OpenStack dashboard should show Ceph panels if Ceph monitoring
is enabled.

horizon: Disable Ceph dashboard if not monitored (SOC-7573)

---

chef/data_bags/crowbar/template-database.json

Looks like 5 minutes is too short in some cases
when a new node is joining. I have observed the 5 min timeout
in a small cloud of 100 nodes already that has been operated
for some time, so we might be better off being conservative.
(cherry picked from commit 2f84ad631c82bf75f84b395929a2bb5780c7da61)

[4.0] database: Raise and align promote/demote timeouts (bsc#1131791)

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/templates/default/galera.cnf.erb
chef/data_bags/crowbar/migrate/database/210_make_wsrep_provider_options_configurable.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

It is sometimes useful to be able to add extra options (like
gcache.size, gcs.fc_debug, ...) to the galera wsrep_provider_options
configuration variable.
This can now be done via the Crowbar RAW view.
Also make (the currently hardcoded) "gcs.fc_limit" multiplier
configurable.
Also make (the currently hardcoded) "gcs.fc_factor"
configurable.
(cherry picked from commit 94eb55905b28e3407187f54d9ada4b7e27214704)

[5.0] database: Make wsrep_provider_options configurable (fate#327745)

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/templates/default/galera.cnf.erb
chef/data_bags/crowbar/migrate/database/111_make_wsrep_provider_options_configurable.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

It is sometimes useful to be able to add extra options (like
gcache.size, gcs.fc_debug, ...) to the galera wsrep_provider_options
configuration variable.
This can now be done via the Crowbar RAW view.
Also make (the currently hardcoded) "gcs.fc_limit" multiplier
configurable.
Also make (the currently hardcoded) "gcs.fc_factor"
configurable.
(cherry picked from commit 94eb55905b28e3407187f54d9ada4b7e27214704)

[4.0] database: Make wsrep_provider_options configurable (fate#327745)

---

chef/cookbooks/neutron/recipes/post_install_conf.rb

Legacy cli is still used in some places but didn't have proper
insecure args.

neutron: Add 'insecure' to old cli calls

---

chef/cookbooks/nova/recipes/flavors.rb

When running into the problem that the "openstack flavor list" command
fails, we want to know the error and not only see a comment that the
nova api might be down.
This is useful for debugging.

nova: Show stdout/stderr when "openstack flavor list" fails

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb

l3-ha service doesn't use .openrc so it doesn't need to be restarted
when that file is modified.
Second commit removes redundant generation of .openrc in neutron cookbook.
Third one increases grace period for l3-ha service from 10x10s to 10x30s. This is needed to improve reliability of CI running in ECP.

neutron: Don't restart l3-ha on .openrc change + timeout extension

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

Backport of #2112 and Backport of #2116

[4.0] Fix neutron-ha-tool restart on configuration changes

---

chef/cookbooks/ironic/templates/default/ironic.conf.erb

Swift settings in [glance] already use IP for endpoint URL. This
is used for deployment images.
If config drive is enabled and stored in Swift, this endpoint URL
is not used but instead standard keystone adapter is created based
on [swift] section of Ironic configuration. Added override makes
it possible to use deploy image which can't resolve Crowbar's
internal domain names.

ironic: Use IP also in [swift] section

---

chef/cookbooks/nova/recipes/flavors.rb

In some cases the flavor create call succeeds but client still returns
non-zero status. Retries of the create call fail with "Flavor already
exists" and the retry loop never succeeds. Added check is executed in
every loop turn and will stop reytring if the flavor already exists.
Example scenario where flavor might be correctly created but client
doesn't return zero is when one of HA nodes executes flavor create
commands while others perform delayed restart of nova API after config
files are modified. If the "create" request hits the API just before
restart it could be accepted but the client might not get the correct
response back.

nova: Don't retry creating existing flavors

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb

l3-ha service doesn't use .openrc so it doesn't need to be restarted
when that file is modified.
Second commit removes redundant generation of .openrc in neutron cookbook.
Third one increases grace period for l3-ha service from 10x10s to 10x30s. This is needed to improve reliability of CI running in ECP.
port of #2137

[5.0] neutron: Don't restart l3-ha on .openrc change + timeout extension

---

chef/cookbooks/nova/recipes/flavors.rb

In some cases the flavor create call succeeds but client still returns
non-zero status. Retries of the create call fail with "Flavor already
exists" and the retry loop never succeeds. Added check is executed in
every loop turn and will stop reytring if the flavor already exists.
Example scenario where flavor might be correctly created but client
doesn't return zero is when one of HA nodes executes flavor create
commands while others perform delayed restart of nova API after config
files are modified. If the "create" request hits the API just before
restart it could be accepted but the client might not get the correct
response back.
port of #2142

[5.0] nova: Don't retry creating existing flavors

---

chef/cookbooks/ironic/attributes/default.rb
chef/cookbooks/ironic/recipes/post_install.rb
chef/cookbooks/ironic/recipes/role_ironic_server.rb

The official SUSE deploy image package will be installed by default
together with ironic-server role. Kernel and ramdisk images will be
uploaded to glance.

ironic: Install deploy image with ironic

---

chef/cookbooks/tempest/templates/default/tempest.conf.erb

The change disables testing the signed image in Barbican. In the default
configuration of Nova, Glance signature verification is disabled and so
this test fails.
Depends On: https://build.opensuse.org/request/show/707799
Please also refer to: https://review.opendev.org/649670

tempest: Disable Barbican validation of signed image (SOC-8578)

---

chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/rabbitmq/recipes/ha.rb

In shared storage based HA setup, rabbitmq uses fixed uid/gid=91.
This user/group modification was done after (optional) SSL certificate
generation. The ACLs on the SSL key were incorrect making rabbitmq
unable to start because with EACCESS errors.
Second commit is taken from https://github.com/crowbar/crowbar-openstack/pull/2145 to avoid cross-PR dependencies in gating.
The sync failed when certs and/or keys were located in non-default paths.
**Note:** forward ports need to include only the rabbitmq part as the keystone change is not relevant for newer versions.

[4.0] rabbitmq: Fix ACL of SSL key after uid/gid change + keystone: Use correct paths when syncing certs

---

chef/cookbooks/rabbitmq/recipes/ha.rb

In shared storage based HA setup, rabbitmq uses fixed uid/gid=91.
This user/group modification was done after (optional) SSL certificate
generation. The ACLs on the SSL key were incorrect making rabbitmq
unable to start because with EACCESS errors.
(cherry picked from commit 086216018065b9855b27bfb73d556e70f7e336b2)
partial port of #2146

[5.0] rabbitmq: Fix ACL of SSL key after uid/gid change

---

chef/cookbooks/rabbitmq/recipes/ha.rb

In shared storage based HA setup, rabbitmq uses fixed uid/gid=91.
This user/group modification was done after (optional) SSL certificate
generation. The ACLs on the SSL key were incorrect making rabbitmq
unable to start because with EACCESS errors.
(cherry picked from commit 086216018065b9855b27bfb73d556e70f7e336b2)
partial port of #2146

rabbitmq: Fix ACL of SSL key after uid/gid change

---

chef/cookbooks/designate/definitions/designate_service.rb
crowbar_framework/app/models/designate_service.rb

[1] suggests that workers are there for designate-central to get work
done. So having more of them is a good idea.
A worker does not really have an idea of api so no vip or haproxy
config is required.
1 - https://docs.openstack.org/designate/rocky/contributor/architecture.html

designate: allow worker on cluster.

---

chef/cookbooks/nova/recipes/database.rb

These two commits get the nova part of the Cloud 8 to Cloud 9 upgrade working to the point where the chef run during the `crowbarctl upgrade nodes controllers` step finishes without crashing for a minimal cloud (only Keystone, Cinder, Glance, Neutron, Nova).

Upgrade nova

---

chef/data_bags/crowbar/migrate/monasca/302_add_mondb.rb
chef/data_bags/crowbar/migrate/monasca/303_add_grafanadb.rb
chef/data_bags/crowbar/migrate/monasca/304_rename_elastic_params.rb

Symbolic keys cause the migrations to fail during upgrade due
to these keys not being found. This commit fixes the problem.

monasca: use string keys for attrs in migrations

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/data_bags/crowbar/migrate/database/302_add_presync_timeout.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

We have a pacemaker sync-mark to wait for all nodes to have all galera
packages and configuration files installed. The default timeout is 60
seconds for these sync-marks.
While installing all cluster members at once, like in an initial
installation, all nodes take about the same time to install the packages
and reach the sync-mark about the same time as well. But when adding a
new node to the cluster, the already installed nodes reach the sync-mark
much faster and the default timeout proves insuficient.
Based on tests in developer environments, this takes roughly 70 seconds.
We will be setting this to 180 seconds to give enough margin.

Configurable timeout for Galera pre-sync

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/307_add_ovs_of_inactivity_probe.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This patch allows the user to change
the ovs inactivity_probe timeout from the neutron barclamp, in the 'raw'
view. Previously, this value was always set to the OVS default, 5.
It provides crowbar support for this upstream patch:
https://review.opendev.org/#/c/641681

Make ovs of_inactivity_probe configurable from neutron barclamp

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb

l3-ha service doesn't use .openrc so it doesn't need to be restarted
when that file is modified.
Second commit removes redundant generation of .openrc in neutron cookbook.
Third one increases grace period for l3-ha service from 10x10s to 10x30s. This is needed to improve reliability of CI running in ECP.
port of #2137

[4.0] neutron: Don't restart l3-ha on .openrc change + timeout extension

---

.travis.yml

This commit syncs the Travis confif with the one from crowbar-core:
- Switch from Travis dist from Trusty to Xenial
- Enable Gitlint
- Use proper names for the Travis Tests

Sync Travis with crowbar-core (SOC-9565)

---

chef/cookbooks/horizon/recipes/monasca_ui.rb
chef/cookbooks/monasca/recipes/database.rb

This commit moves Grafana DB creation to the Horizon barclamp
since this is where the Grafana service is being deployed.

monasca: move Grafana DB creation

---

chef/cookbooks/keystone/providers/register.rb

We should be using case-insensitive role name comparison
when doing a role lookup since we only support mysql backend
now. See
https://docs.openstack.org/keystone/rocky/admin/identity-case-insensitive.html#roles

case-insensitive role name lookup (SOC-9339)

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb

Pike has been adding support for managing concurrently used pools, so
it spends more than half of its time on assessing the disk usage.
With https://review.openstack.org/#/c/625970/1 this should become better
but until then we can disable the cinder pool size calculation for
embedded ceph, which removes a perceived hang of multiple minutes
when the disk size calculation kicks in.
When using the RBD pool exclusively for Cinder we can now set
`rbd_exclusive_cinder_pool` to `true` and Cinder will use DB information
to calculate provisioned size instead of querying all volumes in the
backend, which will reduce the load on the Ceph cluster and the volume
service.
Backport-of: #1949 
(cherry picked from commit c9da83110db4a126452327463483c999a25ee421)

[5.0] cinder: Set cinder pool to exclusive by default when using embedded ceph

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/124_add_ovs_of_inactivity_probe.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This patch allows the user to change
the ovs inactivity_probe timeout from the neutron barclamp, in the 'raw'
view. Previously, this value was always set to the OVS default, 5.
It provides crowbar support for this upstream patch:
https://review.opendev.org/#/c/663024/

[4.0] Make ovs of_inactivity_probe configurable from neutron barclamp

---

chef/cookbooks/swift/recipes/proxy.rb

In most barclamps using syncmarks existing syncmarks are reset when applying
proposal. In Swift barclamp, swift-proxy is the only "HA" role and it is not
executed as the first one (swift-storage and swift-ring-compute need to be
run first). Because of that, first chef-client run during proposal commit
might not include the founder node and syncmark mechanism would fail in all
cookbooks.
Because syncmarks are not reset when applying Swift proposal, nodes can be
out of sync beyond normal syncmark timeout. This 'sync' syncmark should
line them up and correct any time offsets.
port of #2161

[5.0] swift: Sync HA nodes (SOC-9683)

---

chef/cookbooks/swift/recipes/proxy.rb

In most barclamps using syncmarks existing syncmarks are reset when applying
proposal. In Swift barclamp, swift-proxy is the only "HA" role and it is not
executed as the first one (swift-storage and swift-ring-compute need to be
run first). Because of that, first chef-client run during proposal commit
might not include the founder node and syncmark mechanism would fail in all
cookbooks.
Because syncmarks are not reset when applying Swift proposal, nodes can be
out of sync beyond normal syncmark timeout. This 'sync' syncmark should
line them up and correct any time offsets.

swift: Sync HA nodes (SOC-9683)

---

crowbar_framework/app/models/designate_service.rb

[1] suggests that workers are there for designate-central to get work
done. So having more of them is a good idea.
A worker does not really have an idea of api so no vip or haproxy
config is required.
1 - https://docs.openstack.org/designate/rocky/contributor/architecture.html
(cherry picked from commit a0a087728dbd15559852bc58cb6400ed23a43a95)

[5.0] designate: allow worker on cluster (SOC-9632)

---

chef/cookbooks/tempest/templates/default/tempest.conf.erb

- Disable `extend_attached_volume`, for RBD this feature was implemented
only in Stein [1]
- Set the correct `manage_snapshot_ref` for ceph backend.
1. https://github.com/openstack/nova/commit/eab58069ea6afba875fb0a7d7ac68c7e83ebf14a

Fix tempest config for cinder using ceph as backend (SOC-9298)

---

chef/cookbooks/designate/recipes/common.rb

If designate is deployed across two clusters, one for the server and the
other for the workers, when the worker recipe applies, it will use the
current node to look up the VIP it should use to talk to the server,
which will fail, since it doesn't have one. Since we can guarantee a
server role exists, make use of the first server role node for those
look ups.

designate: Use server node for VIP look ups (SOC-9631)

---

chef/cookbooks/magnum/recipes/post_install.rb

Creating magnum flavors is done as a delayed action, alongside
all other delayed actions, such as restarting services.
If one of those restarted services is apache (e.g. because it
was triggered by another barclamp configuration change), then
keystone and other API services might not be available right
away, in which case the magnum flavor creation will fail.
Re-attempting magnum flavor creation fixes this issue.

[4.0] magnum: retry flavor creation (SOC-9991)

---

chef/cookbooks/barbican/recipes/ha.rb
chef/cookbooks/crowbar-openstack/libraries/helpers.rb

The check to identify if SSL is enabled on the barbican barclamp was
incorrect, there is no `ssl` entry on the barbican/api schema.
This change uses the `api.protocol` value (http/https) to check if SSL is
enabled or not, the same way other barclamps do (eg. keystone).

Fix barbican SSL support (SOC-9298)

---

crowbar_framework/app/models/neutron_service.rb

This is needed for designate. Designate will try to create zones
based on these names which get updated into the fixed and floating
network.

neutron: raise validation error if domain names dont end with a dot(.)

---

chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb
chef/data_bags/crowbar/template-tempest.json

Nova:
- disable `swap_volume` tests when cinder is using ceph backend as it is
not supported.
- replaced cirros uec used by tempest to qcow2 image
Fix for: `tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario`
Magnum:
- magnum barclamp: set `verify_ca = false`. The magnum barclamp does not
support setting `openstack_ca_file` which leaves magnum unusable when
deploying crowbar using self-signed certificates. Setting `verify_ca =
false` ensures that it will work for any case.
- tempest barclamp: for magnum set `dns_nameserver` with the crowbar DNS
server; and add `member` role to the list of roles given to users created by tempest.
Fix for: `magnum_tempest_plugin.tests.api.v1.test_cluster.ClusterTest.test_create_list_sign_delete_clusters`

Tempest fixes for nova and magnum (SOC-9298)

---

chef/cookbooks/magnum/recipes/post_install.rb

Creating the magnum image is done as a delayed action, alongside
all other delayed actions, such as restarting services.
If one of those restarted services is apache (e.g. because it
was triggered by another barclamp configuration change), then
keystone and other API services might not be available right
away, in which case the magnum image creation will fail.
Re-attempting magnum image creation fixes this issue.
NOTE: this is a follow-up to #2179

[4.0] magnum: retry magnum image creation (SOC-10015)

---

crowbar_framework/lib/openstack/upgrade.rb

Detection of HA scenario for keystone db_sync during upgrade used
incorrect logic relying on pacemaker attribute which is present also
in non-HA deployment.

upgrade: Fix HA detection for keystone db_sync (SOC-9981)

---

chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/templates/default/qemu.conf.erb
chef/data_bags/crowbar/migrate/nova/305_add_max_threads.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

In some cases, VMs my contain more threads than permissible by
the systemd set default of 16000. In this case, this tuneable
makes it possible to set a higher limit in qemu.conf through
the Nova barclamp.

add max_threads_per_process tuneable (SOC-10001)

---

chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/templates/default/qemu.conf.erb
chef/data_bags/crowbar/migrate/nova/211_add_max_threads.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

In some cases, VMs my contain more threads than permissible by
the systemd set default of 16000. In this case, this tuneable
makes it possible to set a higher limit in qemu.conf through
the Nova barclamp.
(cherry picked from commit 1ec1f30b6b594ad61b8e4b6940f259e8ddacb1e9)
Backport changes: migration renamed to 211_add_max_threads.rb and schema
revision adjusted accordingly.
Note: please hold off on merging this until https://github.com/crowbar/crowbar-openstack/pull/2184 lands. If that pull request undergoes any changes in the course of review, they need to be mirrored here.

[5.0] nova: add max_threads_per_process tuneable (SOC-10001)

---

chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/templates/default/qemu.conf.erb
chef/data_bags/crowbar/migrate/nova/126_add_max_threads.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

In some cases, VMs my contain more threads than permissible by
the systemd set default of 16000. In this case, this tuneable
makes it possible to set a higher limit in qemu.conf through
the Nova barclamp.
(cherry picked from commit 1ec1f30b6b594ad61b8e4b6940f259e8ddacb1e9)
Backport changes: migration renamed to 126_add_max_threads.rb and schema
revision adjusted accordingly.
Note: please hold off on merging this until https://github.com/crowbar/crowbar-openstack/pull/2185 lands. If that pull request undergoes any changes in the course of review, they need to be mirrored here.

SOC-10001: add max_threads_per_process tuneable

---

chef/cookbooks/designate/recipes/common.rb

If designate is deployed across two clusters, one for the server and the
other for the workers, when the worker recipe applies, it will use the
current node to look up the VIP it should use to talk to the server,
which will fail, since it doesn't have one. Since we can guarantee a
server role exists, make use of the first server role node for those
look ups.
(cherry picked from commit 6683938332f019053bea4d4eb9c4efde143f5a9e)

[5.0] designate: Use server node for VIP look ups (SOC-9631)

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

The `TestNetworkBasicOps.test_update_instance_port_admin_state` tempest
test is known to be failing when using neutron with linuxbridge ([SOC-10138](https://jira.suse.com/browse/SOC-10138)).
For now, skip that test for deployments using neutron with linuxbridge
until SOC-10138 is fixed.

tempest: Set port_admin_state_change to false when using linuxbridge (SOC-10029)

---

chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb

It was replaced with dns_domain in 9e96051,
but newton neutron dhcp needs dhcp_domain.

neutron: restore dhcp_domain in stable/4.0 (bsc#1145867)

---

chef/cookbooks/ceilometer/recipes/server.rb

When cloud8 is upgraded to cloud9, old ceilometer-api configs could
be left abandoned as Crowbar doesn't manage these anymore.
Explicit config removal should be enough to wipe remaining pieces of
ceilometer-api.

ceilometer: Remove old ceilometer-api vhosts (SOC-9483)

---

chef/cookbooks/designate/recipes/common.rb
chef/cookbooks/designate/templates/default/designate.conf.erb
chef/data_bags/crowbar/migrate/designate/201_add_resources.rb
chef/data_bags/crowbar/template-designate.json
chef/data_bags/crowbar/template-designate.schema
crowbar_framework/app/models/designate_service.rb
crowbar_framework/app/views/barclamp/designate/_edit_attributes.html.haml
crowbar_framework/config/locales/designate/en.yml

Designate requires a project and a responsible person contact for any
zones it creates, add them into the barclamp configuration with the
first migratation for designate.
(cherry picked from commit 852859e692f53c5d39772a89d6ee4a2684a4449d)

[5.0] designate: Configure resource settings (SOC-9633)

---

chef/cookbooks/barbican/recipes/common.rb
chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/designate/recipes/common.rb
chef/cookbooks/ec2-api/recipes/ec2api.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/heat/recipes/server.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/magnum/recipes/common.rb
chef/cookbooks/manila/recipes/common.rb
chef/cookbooks/memcached/libraries/helpers.rb
chef/cookbooks/monasca/recipes/monasca_api.rb
chef/cookbooks/monasca/recipes/monasca_log_api.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/sahara/recipes/common.rb
chef/cookbooks/swift/recipes/proxy.rb
chef/cookbooks/swift/recipes/storage.rb

With #2073 merged
we were looking up the port on the node with the lowest mac address,
which however in compilation phase might not yet have that attribute.
By passing in the local node and moving to execution phase we should
always have the default attributes for memcached port visible.

memcache: lookup memcached servers port only on local node (SOC-10173)

---

crowbar_framework/app/models/designate_service.rb

The implicit assumption of mkcloud(1) is that a create_proposal()
default proposal can be applied. the empty default of designate's
resource email broke that, so lets set it to a validating default.

designate: initialize email in default designate proposal

---

chef/cookbooks/rabbitmq/attributes/default.rb
chef/cookbooks/rabbitmq/recipes/default.rb

It interacts badly with the pacemaker health monitoring and
based on rumours does not work with IPv6.

rabbitmq: Turn off hipe compile

---

chef/cookbooks/mysql/recipes/client.rb
chef/cookbooks/postgresql/attributes/default.rb

Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-cstruct' not found in package
names`.

database: Hardcode ruby version for package installation (SOC-10010)

---

chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

(backport of #1915 )
tempest: only assign creator role if needed
Check whether the Barbican barclamp has been applied and only
assign the creator role to the tempest user if it has been.
This role is created by the Barbican barclamp and if the role
does not exist, this role assignment will fail, causing smoke
tests to fail across the board.
(cherry picked from commit c476337)
(backport of #2173  )
Fix magnum tempest tests (SOC-9298)
- magnum barclamp: set `verify_ca = false`. The magnum barclamp does not
support setting `openstack_ca_file` which leaves magnum unusable when
deploying crowbar using self-signed certificates. Setting `verify_ca =
false` ensures that it will work for any case.
- tempest barclamp: set the DNS nameserver for magnum to the crowbar DNS
server; and add `member` to …

Tempest backports

---

chef/cookbooks/mysql/recipes/client.rb
chef/cookbooks/postgresql/attributes/default.rb

Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-cstruct' not found in package
names`.
(cherry picked from commit 6c02091fc2ffbadfb8fa12f7537b91586e6e112b)

[5.0] database: Hardcode ruby version for package installation (SOC-10010)

---

chef/cookbooks/mysql/recipes/client.rb
chef/cookbooks/postgresql/attributes/default.rb

Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-cstruct' not found in package
names`.
(cherry picked from commit 6c02091fc2ffbadfb8fa12f7537b91586e6e112b)

[4.0] database: Hardcode ruby version for package installation (SOC-10010)

---

chef/cookbooks/barbican/recipes/ha.rb
chef/cookbooks/crowbar-openstack/libraries/helpers.rb

The check to identify if SSL is enabled on the barbican barclamp was
incorrect, there is no `ssl` entry on the barbican/api schema.
This change uses the api.protocol value (http/https) to check if SSL is
enabled or not, the same way other barclamps do (eg. keystone).
(cherry picked from commit ea5ba2576ae2ef43bd41ce35a34750cde2ee2539)

[5.0] Fix barbican SSL support (SOC-9799)

---

chef/cookbooks/designate/recipes/api.rb
chef/cookbooks/designate/recipes/ha.rb

Designate has another service 'producer', which is used to run
long-running periodic tasks. Install the package and start the service
on one of the server nodes, monitored by pacemaker.
(cherry picked from commit 0a0c48c998c0f5555af8a9bdaf523014400c3219)

[5.0] designate: Deploy producer on a server node (SOC-9766)

---

crowbar_framework/app/models/nova_service.rb

Mixing compute with "controller" roles is not supported during upgrade.
Placing Monasca on a dedicated node is a good idea anyway as it consumes
a lot of resources.

nova: Don't put nova-compute roles on monasca node (SOC-10373)

---

chef/cookbooks/designate/recipes/mdns.rb

The mdns recipe was written with the assumption that the dns-server role
would be applied to multiple servers, which means one of them would be
elected master with a master_ip property set. This does not exist if
dns-server is only applied to one role, so handle that case as well.
Also drive-by correcting the recipe name in the header comment.

designate: Handle one dns-server node for mdns (SOC-10456)

---

chef/cookbooks/nova/attributes/default.rb
chef/data_bags/crowbar/template-nova.json

The 30s is definitely too low for environments with many
thousand ports in active state. 300 is also the set value
in Ardana.

nova: raise neutron client timeout to 5 minutes

---

chef/cookbooks/designate/recipes/mdns.rb

The previous PR missed changing one use of the removed variables, switch
to the correct variable.
(cherry picked from commit 1e88db88ce8d00c1969a0e6f79e0938e1a95e8a3)

[5.0] designate: Correct missing variable (SOC-10549)

---

chef/cookbooks/horizon/libraries/helper.rb
chef/cookbooks/horizon/recipes/ha.rb
chef/cookbooks/horizon/recipes/monasca_ui.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
crowbar_framework/app/models/horizon_service.rb

This commit depends on crowbar/crowbar-core#1906  and  includes the followings:
1) Used NetworkHepler's wrap_ip to wrap any host, node or address that
can be used in a url form. Assume host or node in barclamp Horizon is
usually an ip address.
2) Upated "0.0.0.0" (any address) to use "::" which can be handled in both
IPV4 and IPV6 environment.
3) Added apache rewriterule in suse/openstack-dashboard.conf.erb to deal
with IPV6 when bind_host is in IPV6 form.

IPV6 - Horizon:barclamp make IPV6 compliant (SOC-6397)

---

octavia.yml

This patch sets `user_managed: false` so that the UI doesn't appear
in crowbar. This will be changed back to `true` once we've finished the
barclamp and it's been released.

Octavia: Hide UI until complete (SOC-10550)

---

designate.yml

The designate barclamp has been marked as not user manageable since it
had some issues. Since those have been corrected, mark it as user
manageable, so it appears in the web UI.

designate: Mark as user managed (SOC-10233)

---

designate.yml

The designate barclamp has been marked as not user manageable since it
had some issues. Since those have been corrected, mark it as user
manageable, so it appears in the web UI.
(cherry picked from commit 3b753ac93d36410c72ffc8a81e97e4320c603e97)

[5.0] designate: Mark as user managed (SOC-10233)

---

aodh.yml

This patch sets `user_managed: false` so that the UI doesn't appear
in crowbar. This will be changed back to `true` once we've finished the
barclamp and it's been released.
(cherry picked from commit 6b519401044aa3689bf1138fd612a19cf18eefb0)

[5.0] Octavia: Hide UI until complete (SOC-10550)

---

chef/cookbooks/nova/attributes/default.rb

Otherwise there will be a syntax error in the libvirt config
and the cloud is down afterwards.

nova: set default attribute for max_threads_per_process

---

designate.yml

Designate is not ready for customers.
This reverts commit 3b753ac93d36410c72ffc8a81e97e4320c603e97.

Revert "designate: Mark as user managed (SOC-10233)"

---

chef/cookbooks/monasca/attributes/default.rb
chef/cookbooks/monasca/recipes/elasticsearch.rb
chef/cookbooks/monasca/templates/default/elasticsearch.yml.erb

To create database backup the directory for storing snapshots must be
configured. Administrator should be able to specify target directories
for these snapshots and so the variable should be exposed in Crowbar
proposal.
Although [monasca][elasticsearch][repo_dir] variable has been present in
the data_bag, it hasn't been used in the template. This change allows
setting path.repo configuration setting in Crowbar proposal as
documented.

Allow setting ElasticSearch path.repo from Crowbar (SOC-10440)

---

chef/cookbooks/horizon/recipes/monasca_ui.rb
chef/cookbooks/monasca/recipes/monasca_api.rb
crowbar_framework/lib/openstack/upgrade.rb

This pull request will - once it's done - restore the Monasca and Grafana databases from the dump created by https://github.com/crowbar/crowbar-core/pull/1883 . This is necessary to move these databases from the MariaDB instance on the `monasca-server` node to the one on the controller node(s).

Upgrade: restore Monasca DB [SOC-9772]

---

chef/data_bags/crowbar/migrate/designate/301_add_resources.rb

To check the existence of a key in a ruby map is the `.key?` method not
`.keys?`.
This patch corrects the designate migrations to use the proper key method.

designate: Fix the keys syntax error on migrations (SOC-10660)

---

chef/cookbooks/glance/recipes/api.rb

Using the same sync mark name for two different sections can lead
to unexpected results. In this particular case, nodes running into
the second glance_database sync mark occurrence find that the sync mark
has already been set by the founder node and will proceed without
waiting for the founder node, which causes the non founder nodes to
start the openstack-glance-api service while the founder node
is running "glance-manage db sync", thus causing all sorts of conflicts.

glance: don't reuse sync mark names (SOC-10348)

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/216_add_ovs_of_inactivity_probe.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

*We should not be merging changes to attributes in 4.0 without fixing 5.0. *
This patch allows the user to change
the ovs inactivity_probe timeout from the neutron barclamp, in the 'raw'
view. Previously, this value was always set to the OVS default, 5.
It provides crowbar support for this upstream patch:
https://review.opendev.org/#/c/663024/
(cherry picked from commit c0a4d9e49d042c80b118404a3472727c41403145)

[5.0] Make ovs of_inactivity_probe configurable from neutron barclamp

---

chef/data_bags/crowbar/migrate/cinder/205_add_resource_limits.rb
chef/data_bags/crowbar/migrate/database/205_add_resource_limits.rb
chef/data_bags/crowbar/migrate/database/206_add_bootstrap_timeout.rb
chef/data_bags/crowbar/migrate/database/302_add_presync_timeout.rb
chef/data_bags/crowbar/migrate/horizon/203_add_resource_limits.rb
chef/data_bags/crowbar/migrate/nova/207_add_resource_limits.rb
chef/data_bags/crowbar/migrate/rabbitmq/200_add_resource_limits.rb
chef/data_bags/crowbar/migrate/rabbitmq/201_heartbeat_timeout.rb
chef/data_bags/crowbar/migrate/rabbitmq/202_add_mnesia_dump_log.rb
chef/data_bags/crowbar/migrate/rabbitmq/203_add_performance_config.rb
chef/data_bags/crowbar/migrate/rabbitmq/204_add_extra_users.rb

Two of the Cloud 8 migrations for RabbitMQ have a bug where
they never add the fields they are supposed to add to the
proposal. This commit fixes the issue.
See https://jira.suse.com/browse/SOC-10623 for details. This will need a backport to SOC8 as well since the missing migration breaks the Cloud 7 to Cloud 8 upgrade.
Setting "do not merge yet" since we are currently testing this on a QA cloud.

rabbitmq: fix migrations (SOC-10623)

---

crowbar_framework/app/models/nova_service.rb

nova: Don't autoselect nodes for Xen (continued) (bsc#1147144)

---

chef/cookbooks/keystone/attributes/default.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/keystone/templates/default/keystone.domain.conf.erb
chef/data_bags/crowbar/migrate/keystone/305_add_ldap_configs_and_insecure_debug.rb
chef/data_bags/crowbar/template-keystone.json
chef/data_bags/crowbar/template-keystone.schema

For Microsoft Active Directory deployments where users are not
visible/accessible via the global catalog, list users operation, as a
whole, will fail when one or more referrals are returned on an LDAP
lookup and the current (admin) user have no access to a given referral.
This patch exposes the chase_referrals option in Keystone to enable
customers who got stuck in the above situation to optionally turn
off referrals chasing.
By default, chase_referrals is set to an empty value to preserve
backward compatibility. This is a three state configuration.
Empty value means use the system default. This is all depended on the
underlying LDAP SDK and the system configuration (i.e. /etc/ldap.conf).
"0" means disable referrals chasing.
"1" means enable referrals chasing.
This patch is also exposes …

enable LDAP chase_referrals configuration (SOC-7364)

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/horizon/libraries/helper.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/tempest/recipes/install.rb

This is clean up ,as we need to use helper outside horizon barclamp
would be more convenient  to move it to crowbar-openstack.

helper: move config_for_role_exists from horizon to crowbar-openstack (SOC-10191)

---

chef/cookbooks/tempest/recipes/config.rb

The way that the tempest chef recipe figures out which OpenStack
services can be tested is by inspecting the openstack service
catalogue to retrieve a list of enabled services, instead of
using the barclamp configuration which is more accurate. Worse
even, it does so in the chef compilation phase, before the
running openstack configuration is updated to reflect changes
in the barclamp configuration.
Sometimes, this results in a tempest configuration that doesn't
reflect the list of services that are actuallly deployed. In some of
the more extreme cases, such as updating the admin password, the
OpenStack CLI command used to retrieve the service catalogue
fails completely and returns an empty list, which results in tempest
disabling all services in its configuration.
Inspecting the barclamp …

tempest: don't rely on service catalogue (SOC-10633)

---

chef/cookbooks/tempest/recipes/config.rb

(backport of #2255)
The way that the tempest chef recipe figures out which OpenStack
services can be tested is by inspecting the openstack service
catalogue to retrieve a list of enabled services, instead of
using the barclamp configuration which is more accurate. Worse
even, it does so in the chef compilation phase, before the
running openstack configuration is updated to reflect changes
in the barclamp configuration.
Sometimes, this results in a tempest configuration that doesn't
reflect the list of services that are actuallly deployed. In some of
the more extreme cases, such as updating the admin password, the
OpenStack CLI command used to retrieve the service catalogue
fails completely and returns an empty list, which results in tempest
disabling all services in its configuration. …

[5.0] tempest: don't rely on service catalogue (SOC-10633)

---

chef/cookbooks/glance/recipes/registry.rb

(backport of #2262)
Using the same sync mark name for two different sections can lead
to unexpected results. In this particular case, nodes running into
the second glance_database sync mark occurrence find that the sync mark
has already been set by the founder node and will proceed without
waiting for the founder node, which causes the non founder nodes to
start the openstack-glance-api service while the founder node
is running "glance-manage db sync", thus causing all sorts of conflicts.
(cherry picked from commit 7fd941e1e8b33714b9a9ee79a643086fa57146a6)

[5.0] glance: don't reuse sync mark names (SOC-10348)

---

chef/cookbooks/nova/attributes/default.rb

Otherwise there will be a syntax error in the libvirt config
and the cloud is down afterwards.
(cherry picked from commit da1798bbc0764d854821e86a1161bd36a7134f63)

[5.0] nova: set default attribute for max_threads_per_process

---

chef/cookbooks/nova/attributes/default.rb

Otherwise there will be a syntax error in the libvirt config
and the cloud is down afterwards.
(cherry picked from commit da1798bbc0764d854821e86a1161bd36a7134f63)

[4.0] nova: set default attribute for max_threads_per_process

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/horizon/recipes/server.rb

This is clean up, as we need to use helper outside horizon barclamp
would be more convenient to move it to crowbar-openstack.
(cherry picked from commit f7aa3ce)

[5.0] helper:move config_for_role_exists from horizon to crowbar-openstack(SOC-10191)

---

chef/cookbooks/neutron/recipes/server.rb

We need to replace 'dns' with 'dns_domain_ports' in ml2.conf extension_drivers.
This adds the capability to assign dns-domain to ports.

Designate: Add dns_domain_ports config (SOC-10740)

---

chef/cookbooks/designate/recipes/mdns.rb

The admin node shouldn't be listening on the public network. As such it
can't used as a designate server.
This patch filters it out of the pools list, as crowbar already has a
check to not use the admin node in barclamps that is all we need.

Designate: Filter out the admin node (SOC-10658)

---

chef/data_bags/crowbar/migrate/designate/201_add_resources.rb

To check the existence of a key in a ruby map is the `.key?` method not
`.keys?`.
This patch corrects the designate migrations to use the proper key method.

5.0: designate: Fix the keys syntax error on migrations (SOC-10660)

---

chef/cookbooks/designate/recipes/mdns.rb

The admin node shouldn't be listening on the public network. As such it
can't used as a designate server.
This patch filters it out of the pools list, as crowbar already has a
check to not use the admin node in barclamps that is all we need.
Co-Authored-By: Steve Kowalik
(cherry picked from commit 9a35e8b266e4280c858c8c004380d87c63fd14e5)

[5.0] Designate: Filter out the admin node (SOC-10658)

---

chef/data_bags/crowbar/migrate/database/302_add_presync_timeout.rb

I ended up on the wrong line in commit e9d4b69d033eac6c103a1cf8aedfc83a03e39238
thus accidently dropping a Boolean value in the database. This commit fixes
this error.
Note: the faulty commit is Cloud 9 only. Thus the other commit in pull request https://github.com/crowbar/crowbar-openstack/pull/2248/ (for the Cloud 8 migrations) remains as-is. I did double-check that one just to be sure, though and the Cloud 8 migrations all look good.

database: really fix migration 102 (SOC-10717)

---

chef/cookbooks/tempest/recipes/install.rb

Barbican tests curently not running on SOC8 because
python-barbican-tempest-plugin not installed.

Install barbican tempest plugin for SOC8 (SOC-10191)

---

chef/cookbooks/monasca/recipes/monasca_api.rb

The condition was written as a shell command but was to be executed
as ruby code. Added braces to mark code block.

monasca: Fix restore condition (SOC-9772)

---

chef/cookbooks/neutron/recipes/server.rb

We need replace 'dns' with 'dns_domain_ports' in ml2.conf extension_drivers.
This adds the capability to assign dns-domain to ports.

[5.0] Designate: Add dns_domain_ports config (SOC-10740)

---

chef/cookbooks/tempest/recipes/install.rb

python-designate-tempest-plugin need to be installed on SOC8

tempest:install designate tempest plugin for SOC8 (SOC-10288)

---

chef/cookbooks/designate/recipes/mdns.rb

In case where DNS server is only running on the admin node, which
is not publicly accessible, we are left with no DNS servers for
Designate integration. For such cases, we do not need to template
the rndc key file used for Bind9 rndc calls.
In this patch we check for such case, if true, we write a warning log
and only template the rndc key file if the case is not valid.

No rndc key if no public DNS server (SOC-10835)

---

chef/cookbooks/designate/recipes/mdns.rb

In case where DNS server is only running on the admin node, which
is not publicly accessible, we are left with no DNS servers for
Designate integration. For such cases, we do not need to template
the rndc key file used for Bind9 rndc calls.
In this patch we check for such case, if true, we write a warning log
and only template the rndc key file if the case is not valid.
(cherry picked from commit 5f34b2477a95e3b3c3ee2a9956c7912e35f5c53f)

[5.0] No rndc key if no public DNS server (SOC-10835)

---

chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/tempest/files/default/run_filters/barbican.txt
chef/cookbooks/tempest/recipes/config.rb
chef/data_bags/crowbar/template-tempest.json

- disable `swap_volume` tests when cinder is using ceph backend as it is
not supported.
- replace the uec image used in tempest for a qcow2 image
(cherry picked from commit 07864bdff573b4ad150530168f879e2e215c896b)

[5.0] Fix nova tempest tests (SOC-9298, SOC-10844)

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/cookbooks/neutron/templates/default/opflex-agent-ovs.conf.erb
chef/data_bags/crowbar/migrate/neutron/308_add_opflex_access_integration_bridge.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

This commit provides changes in plugin packages and config files
needed for integration of SOC with ACI 4.1 and higher versions.
ACI 4.1 uses a slightly different set of plugin packages and configs
for integration with OpenStack. This includes:
- python-gbpclient renamed to python-group-based-policy-client
- ovs-bridge-name in opflex-agent-ovs.conf removed
- addition of int-bridge-name and access-bridge-name in opflex-agent-ovs.conf
- Renaming of agent-ovs to opflex-agent
For uniformity, the template for opflex-agent-ovs.conf is now renamed
from 10-opflex-agent-ovs.conf.erb to opflex-agent-ovs.conf.erb
- The neutron template schema and json templates are updated to provide
integration_bridge and access_bridge details with default values. The
corresponding migration scripts are also …

Changes to integrate with ACI 4.1 and new packages (SOC-10403)

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/data_bags/crowbar/migrate/database/211_add_presync_timeout.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

Backport of #2150 
We have a pacemaker sync-mark to wait for all nodes to have all galera
packages and configuration files installed. The default timeout is 60
seconds for these sync-marks.
While installing all cluster members at once, like in an initial
installation, all nodes take about the same time to install the packages
and reach the sync-mark about the same time as well. But when adding a
new node to the cluster, the already installed nodes reach the sync-mark
much faster and the default timeout proves insuficient.
Based on tests in developer environments, this takes roughly 70 seconds.
We will be setting this to 180 seconds to give enough margin.
(cherry picked from commit 4f1d42ed8beb5e35b4428904adccde5cbd6ab570)

[5.0] Configurable timeout for Galera pre-sync

---

chef/cookbooks/neutron/templates/default/neutron_lbaas.conf.erb

This is not really configurable via CLI, and 10 is not a production
default. better have no limit.
(cherry picked from commit 45fc3dad4325d7e584cf37d84d76e19be99b961b)

[5.0] neutron-lbaas: remove loadbalancer/pool limit

---

chef/cookbooks/tempest/files/default/run_filters/cinder.txt

As this test is affecting the gating jobs for cloud 8 and LVM is not a
supported backend for Cinder, blacklist it until it is fixed or support
for a new Cinder backend is added on the CI.

[5.0] Tempest: blacklist test_volume_boot_pattern (SOC-10874)

---

chef/cookbooks/neutron/recipes/post_install_conf.rb

Correct option is --os-endpoint-type which by default uses
the value of OS_ENDPOINT_TYPE env var.

[4.0] Do not use obsoleted --endpoint-type option with CLI

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/data_bags/crowbar/migrate/database/112_add_presync_timeout.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

We have a pacemaker sync-mark to wait for all nodes to have all galera
packages and configuration files installed. The default timeout is 60
seconds for these sync-marks.
While installing all cluster members at once, like in an initial
installation, all nodes take about the same time to install the packages
and reach the sync-mark about the same time as well. But when adding a
new node to the cluster, the already installed nodes reach the sync-mark
much faster and the default timeout proves insuficient.
Based on tests in developer environments, this takes roughly 70 seconds.
We will be setting this to 180 seconds to give enough margin.
(cherry picked from commit 4f1d42ed8beb5e35b4428904adccde5cbd6ab570)
(cherry picked from commit 4c6f3f332d2fc8d7919da80004c4d1e74bccb9c9)
Originally …

[4.0] Configurable timeout for Galera pre-sync

---

chef/cookbooks/mysql/recipes/ha_galera.rb

The single node Galera cluster the barclamp uses for
bootstrapping may take a few seconds to report WSREP sync. If
the barclamp creates users before that point in time, user
creation will fail with
"WSREP replication failed. Check your wsrep connection state
and retry the query."
This commit makes the barclamp wait for the single-node
bootstrapping cluster to "sync" to prevent this race condition
from happening.

mysql: fix WSREP sync race (SOC-10717)

---

octavia.yml

The previous value of 101 conflicts with the Manila barclamp.

Change order of Octavia to 102 (SOC-10289)

---

chef/cookbooks/nova/recipes/compute.rb

https://github.com/crowbar/crowbar-openstack/pull/1379 brings a problem that  ssh-keygen reads the key from the file but the file might not yet exists (it is only created in convergence phase).
This is an attempt to fix it.
~(Not tested.)~

Make sure the input file with ssh key exists

---

chef/cookbooks/nova/recipes/compute.rb

Postpone the command into the convergence phase and make
sure it is executed when the input file is there.
Also, postpone the authorized_keys file creation with the use
of lazy evaluation of the variable that was adapted in convergence
phase.
(cherry picked from commit 921e931aea4ce758b3601e465f245a41408fdcf8)
Backport of https://github.com/crowbar/crowbar-openstack/pull/2293

[5.0] Make sure the input file with ssh key exists (SOC-10133)

---

chef/cookbooks/designate/templates/default/designate.conf.erb

Besides bringing the configuration closer to the ardana configuration,
those changes also gets all designate tempest tests to pass.
The configuration changes are:
- Increase the default quota for zones from 10 to 100
- Enable admin api
- Enable `quotas` and `zones` admin extensions
- Enable all extensions from v2 api

designate: change default configuration (SOC-10899)

---

chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/octavia/recipes/api.rb
chef/cookbooks/octavia/recipes/common.rb

The Octavia API service doesn't have intrinsic support for
terminating SSL traffic. The alternatives are to terminate
SSL traffic at haproxy level (which isn't done anywhere else
in Crowbar), or to deploy the API service as an Apacke WSGI
application. This PR implements the latter and it also solves
the problem described in the following paragraphs.
The octavia system group and user are created when the
openstack-octavia package is installed on the controller nodes.
This happens automatically when the octavia barclamp is
applied.
However, setting up the paths for the certificates required for
the two-way SSL amphorae communication needs to be done in advance,
before applying the octavia barclamp, and those paths need to have
their ownership set to the octavia system user/group, which …

octavia: add SSL support to octavia-api (SOC-10906)

---

chef/cookbooks/horizon/recipes/server.rb

Add the LBaaS dashboard to the UI if lbaas is enabled in the
neutron barclamp.

horizon: install lbaas horizon dashboard (SOC-10883)

---

chef/cookbooks/horizon/recipes/server.rb

(backport of #2307)
Add the LBaaS dashboard to the UI if lbaas is enabled in the
neutron barclamp.
(cherry picked from commit 2e0431c4cc8c8d8fd87b35d7d555c13e3b4faa0c)

[5.0] horizon: install lbaas horizon dashboard (SOC-10883)

---

chef/cookbooks/designate/recipes/mdns.rb

When creating zones the DNS server notify other servers about the new
zone, however the notification is only accepted when it comes from
masters.
Using the VIP as master causes the zone creation to fail as the
notification is refused because it does not come from the VIP, but from
the node IP address. This change fixes it by declaring all mdns server
as master on the default pool defined by crowbar.

designate: declare all mdns servers as master on pool config (SOC-10952)

---

chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb

The WebSSO code for local_settings.py attempted to retrieve
Keystone settings for WebSSO from the Horizon barclamp's node
object, which failed. This commit adds an explicit lookup of
the Keystone barclamp's node object which contains the data in
question.

horizon: fix keystone node lookup (SOC-10978)

---

chef/cookbooks/horizon/recipes/server.rb

(backports #2314)
Add the LBaaS dashboard to the UI if lbaas is enabled in the
neutron barclamp.
(cherry picked from commit 2e0431c4cc8c8d8fd87b35d7d555c13e3b4faa0c)

[4.0] horizon: install lbaas horizon dashboard (SOC-10883)

---

chef/cookbooks/designate/attributes/default.rb
chef/cookbooks/designate/recipes/api.rb
chef/cookbooks/designate/recipes/mdns.rb
chef/cookbooks/designate/templates/default/designate.conf.erb
chef/cookbooks/horizon/recipes/server.rb
chef/data_bags/crowbar/migrate/designate/202_add_ssl_attributes.rb
chef/data_bags/crowbar/template-designate.json
chef/data_bags/crowbar/template-designate.schema
crowbar_framework/app/helpers/barclamp/designate_helper.rb
crowbar_framework/app/views/barclamp/designate/_edit_attributes.html.haml
crowbar_framework/config/locales/designate/en.yml

Besides bringing the configuration closer to the ardana configuration,
those changes also gets all designate tempest tests to pass.
The configuration changes are:
- Increase the default quota for zones from 10 to 100
- Enable admin api
- Enable `quotas` and `zones` admin extensions
- Enable all extensions from v2 api
(cherry picked from commit 48dfc155dc4847979652e9e7ce869258e7416a42)
designate: add support for SSL (SOC-10877)
This change adds support for configuring designate with SSL.
(cherry picked from commit c1bf75c)
designate: declare all mdns servers as master on pool config (SOC-10952)
When creating zones the DNS server notify other servers about the new
zone, however the notification is only accepted when it comes from
masters
Using the VIP as master causes the zone creation to …

[5.0] designate backports

---

chef/cookbooks/octavia/templates/default/110-health-manager.conf.erb
chef/cookbooks/tempest/files/default/run_filters/lbaas-octavia.txt
chef/cookbooks/tempest/files/default/run_filters/smoke.txt
chef/cookbooks/tempest/templates/default/tempest.conf.erb

According to [1], if Octavia is deployed, the `lbaasv2-proxy` neutron service
plugin should replace the `lbaasv2` service plugin to allow users to continue
using the deprecated neutron API to manage Octavia load balancers.
However, some of the `neutron_lbaas.tests.tempest.v2.api` tempest test cases
no longer pass with the `lbaasv2-proxy` service plugin configured, mainly
because the regular neutron lbaas tempest test cases are not entirely
compatible with the Octavia API. Even if the Octavia API is backwards
compatible with the neutron LBaaS v2 API, there are runtime timing
considerations that these test cases don't cover, such as load balancer
state transitions.
To continue running these test cases, the lbaas tempest configuration needs
to be slightly changed to disable tracking the …

tempest: fix lbaasv2 tests with Octavia lbaasv2-proxy service plugin (SOC-10907)

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

For Monasca Tempest tests, the Kibana version in use must be
configured for that is the API version the Monasca Tempest
tests use to talk to Kibana (aka the logs-search endpoint). If
this is unconfigured, the tempest tests will use an out of
date version which causes the requests they issue to get
rejected by Kibana. This commit configures the Kibana version
to whatever is the most recent Kibana version available in
zypper, thus ensuring it matches what is installed or gets
installed on the monasca-server node.
Note: this does not need a forward port to stable/5.0 since Cloud 8 is not affected by this problem.

tempest: configure Kibana version (SOC-10131)

---

chef/cookbooks/octavia/definitions/octavia_conf.rb
chef/cookbooks/octavia/libraries/helpers.rb
chef/cookbooks/octavia/templates/default/100-octavia.conf.erb
chef/cookbooks/octavia/templates/default/110-api.conf.erb

This PR fixes some Octavia configuration options, either deprecated or missing.
Remaining Octavia deprecated configuration options:
- disables deprecated V1 API [1]
- use the service_token_roles_required and service_token_roles
parameters in the keystone auth config. Adding this will ensure that
token validation sent to keystone by Octavia service has the configured
service token role to pass otherwise keystone will reject that request [2]
Even though Octavia uses the service catalogue to auto-configure
the Barbican service endpoint, it helps if we use an endpoint
hard-coded in the configuration files because there is no other
way to restart Octavia services in case the Barbican endpoint
also changes (e.g. switch from HTTP to HTTPs or vice-versa).
This commit also sets the insecure option …

octavia: configuration fixes (SOC-10989,SOC-10990)

---

crowbar_framework/app/views/barclamp/octavia/_edit_attributes.html.haml
crowbar_framework/config/locales/octavia/en.yml

This change adds two configuration options for the Octavia barclamp in the Crowbar UI. The user can change the management network name and CIDR.

Add Crowbar UI options for mgmt net (SOC-10904)

---

chef/cookbooks/keystone/templates/default/openrc.erb

New openstack client(s) use OS_INTERFACE instead of OS_ENDPOINT_TYPE.
The default is 'public' so if we don't set it, clients will use mix of
internal and public calls depending on the implementation.

keystone: Add OS_INTERFACE env var to .openrc (SOC-11006)

---

chef/cookbooks/keystone/templates/default/openrc.erb

New openstack client(s) use OS_INTERFACE instead of OS_ENDPOINT_TYPE.
The default is 'public' so if we don't set it, clients will use mix of
internal and public calls depending on the implementation.
(cherry picked from commit 352e358e2c9e0f6dfefc034746f9bf13ffbce7a8)
port of #2323

[5.0] keystone: Add OS_INTERFACE env var to .openrc (SOC-11006)

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

This reverts commit 4dc961328fdde9b02071ce0f6881311066d5b330.
While the .openrc was not needed on network nodes during normal operation,
it was needed for proper upgrade of HA clouds with separate network cluster
(e.g. for router evacuation).
partial revert of #2140

neutron: Revert remove .openrc creation from neutron cookbooks (SOC-10378)

---

chef/data_bags/crowbar/migrate/tempest/302_update_tempest_image.rb
chef/data_bags/crowbar/template-tempest.json

This change adds a schema migrate function for updating the default
tempest image which has been changed in [1].
1. https://github.com/crowbar/crowbar-openstack/commit/07864bdff573b4ad150530168f879e2e215c896b

tempest: Update default image on schema (SOC-11023)

---

chef/data_bags/crowbar/migrate/tempest/201_update_tempest_image.rb
chef/data_bags/crowbar/template-tempest.json

This change adds a schema migrate function for updating the default
tempest image which has been changed in [1].
1. https://github.com/crowbar/crowbar-openstack/commit/53710208df7c77d7c069b9644306d41b864989ab

[5.0] tempest: Update default image on schema (SOC-11023)

---

chef/cookbooks/octavia/templates/default/110-health-manager.conf.erb
chef/cookbooks/octavia/templates/default/110-housekeeping.conf.erb
chef/cookbooks/octavia/templates/default/110-worker.conf.erb

The amphora ssh key needs to be known by the health manager so that it
can respawn dead amphora with the correct ssh key.
Co-Authored-By: Keith Berger <keith.berger@suse.com>

octavia: Add ssh key to health manager (SOC-11025)

---

aodh.yml

This reverts commit 75c75298a5330c9c76becf997feb2365d052c871.
NOTE: there is no Octavia in SOC8 and worse, the reverted commit was actually hiding the AODH barclamp.

[5.0] Revert "Octavia: Hide UI until complete (SOC-10550)"

---

chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/nova/libraries/availability_zone.rb
chef/cookbooks/nova/recipes/flavors.rb
chef/cookbooks/octavia/recipes/api.rb
chef/cookbooks/octavia/recipes/health_manager.rb
chef/cookbooks/octavia/recipes/housekeeping.rb
chef/cookbooks/octavia/recipes/nova.rb
chef/cookbooks/octavia/recipes/worker.rb

Recipe X should not access barclamp data looking for X in the same
run where this data should be saved for the first time.
This actually seems to have only one effect: not getting the "insecure"
value correctly if SSL was set up only for one component (neutron or nova)
but not for keystone.

Do not read data from barclamp that has not been saved yet.

---

chef/data_bags/crowbar/migrate/designate/302_add_ssl_attributes.rb

Make sure to use the template values only if attributes
do not exist yet, i.e. because we are upgrading.

designate: Fix the migrations of ssl values (SOC-11030)

---

chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/nova/libraries/availability_zone.rb
chef/cookbooks/nova/recipes/flavors.rb

Recipe X should not access barclamp data looking for X in the same
run where this data should be saved for the first time.
Barclamp data are saved to data bag after the chef call: see
save_config_to_databag in app/models/openstack_service_object.rb
This actually seems to have only one effect: not getting the "insecure"
value correctly if SSL was set up only for one component (e.g. neutron)
but not for keystone.
(cherry picked from commit fd093c2828566314194ae1bc04e68f4b5899847f)
(partial) backport of https://github.com/crowbar/crowbar-openstack/pull/2333

[5.0] Do not read data from barclamp that has not been saved (SOC-11028)

---

chef/cookbooks/octavia/attributes/default.rb
chef/cookbooks/octavia/templates/default/110-health-manager.conf.erb
chef/cookbooks/octavia/templates/default/110-housekeeping.conf.erb
chef/cookbooks/octavia/templates/default/110-worker.conf.erb
chef/data_bags/crowbar/migrate/octavia/302_add_anti_affinity.rb
chef/data_bags/crowbar/template-octavia.json
chef/data_bags/crowbar/template-octavia.schema

Add the anti-affinity setting to the relevant configuration files. The
affected services are the worker, the health-manager, and the
house-keeping service.

octavia: Add anti-affinity settings (SOC-11026)

---

chef/cookbooks/octavia/libraries/helpers.rb
chef/cookbooks/octavia/recipes/nova.rb

When the operator updates the amphora package, the Octavia barclamp
should also update the amphora image.

octavia: Install amphora image always (SOC-11024)

---

chef/cookbooks/octavia/attributes/default.rb
chef/cookbooks/octavia/templates/default/110-housekeeping.conf.erb
chef/cookbooks/octavia/templates/default/110-worker.conf.erb
chef/data_bags/crowbar/migrate/octavia/303_add_loadbalancer_topology.rb
chef/data_bags/crowbar/template-octavia.json
chef/data_bags/crowbar/template-octavia.schema
crowbar_framework/app/helpers/barclamp/octavia_helper.rb
crowbar_framework/app/models/octavia_service.rb
crowbar_framework/app/views/barclamp/octavia/_edit_attributes.html.haml
crowbar_framework/config/locales/octavia/en.yml

Currently a user can not deploy Octavia in active/standby topology
because Crowbar does not allow changes to the corresponding setting in
the Octavia configuration file. This change makes the setting
configurable.

octavia: Add topology setting (SOC-10876)

---

chef/cookbooks/neutron/recipes/post_install_conf.rb

This is only relevant when neutron nodes are in separate cluster
and openstack client is not installed by some other (most likely keystone)
dependency.

Install openstack client for neutron recipes

---

chef/cookbooks/neutron/recipes/post_install_conf.rb

This is only relevant when neutron nodes are in separate cluster
and openstack client is not installed by some other (most likely keystone)
dependency.
(cherry picked from commit f5249b2725c9bd2f5c1a8ff4ffe2fd029f3ab213)
Port of https://github.com/crowbar/crowbar-openstack/pull/2337

[5.0] Install openstack client for neutron recipes (SOC-11039)

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

just disable it for the backends that are known to not support it

tempest: enable multiattach for NetApp + LVM (SCPM-97)

---

chef/cookbooks/rabbitmq/libraries/crowbar.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb

Keep the policy configured in the generated definitions.json
file used during startup in sync with the policy configured
at runtime by the rabbitmq chef recipe, to avoid inconsistencies.
The policy configuration is kept in the CrowbarRabbitmqHelper
and invoked both to generate the definitions.json file and to
configure the rabbitmq policy.
Also see #1448 for more information on how we use definitions.json.

rabbitmq: sync startup definitions.json with recipe (SOC-11077)

---

chef/cookbooks/rabbitmq/libraries/crowbar.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb

(backports #2349)
Keep the policy configured in the generated definitions.json
file used during startup in sync with the policy configured
at runtime by the rabbitmq chef recipe, to avoid inconsistencies.
The policy configuration is kept in the CrowbarRabbitmqHelper
and invoked both to generate the definitions.json file and to
configure the rabbitmq policy.
(cherry picked from commit bc3d7de745ef2863b9b485bce6634951685d5293)

[4.0] rabbitmq: sync startup definitions.json with recipe (SOC-11077)

---

chef/cookbooks/ec2-api/recipes/ec2api.rb

The execution of the ec2-api cookbook includes restarting apache,
however, when apache is restarted while `keystone_register` is running on
the non-cluster founder nodes it fails as keystone (running under apache)
is also being restarted.
This change fixes that by including a condition for running the 
`keystone_register` operations only on the cluster founder node.

ec2-api: run keystone_register on cluster founder only (SOC-11079)

---

chef/cookbooks/ec2-api/recipes/ec2api.rb

(backports #2352)
The execution of the ec2-api cookbook includes restarting apache
however, when apache is restarted while `keystone_register` is running on
the non-cluster founder nodes it fails as keystone (running under apache)
is being restarted.

[5.0] ec2-api: run keystone_register on cluster founder only (SOC-11079)

---

chef/cookbooks/rabbitmq/libraries/crowbar.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb

Reverts crowbar/crowbar-openstack#2351
With this fix applied, we have problems rebooting controller nodes (see https://jira.suse.com/browse/SOC-11082). Reverting until a solution is found.

Revert "[4.0] rabbitmq: sync startup definitions.json with recipe (SOC-11077)"

---

chef/cookbooks/rabbitmq/libraries/crowbar.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb

With this fix applied, we have problems rebooting controller nodes.
Reverting until a more permanent solution is found for SOC-11082.

Revert "rabbitmq: sync startup definitions.json with recipe" (SOC-11082)

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb

Add required configuration to enable usage of SES/Ceph storage backend
for ephemeral storage in nova.
If multiple SES/Ceph backends are defined in cinder, first one is used
by nova for ephemeral strorage.

nova: Enable ephemeral volumes on SES (SOC-5269)

---

chef/cookbooks/keystone/libraries/helpers.rb

In a cloud where a controller was added after initial
deployment and MAC addresses are out of sequence, the
search_for_keystone() method may return the wrong controller
in the first upgraded controller's crowbar_join phase. This
commit ensures this does not happen by removing controllers in
still in the 'prepare-os-upgrade' stage from the list of
controllers.
Note: I'm not sure if we actually need this for Cloud 9 (currently testing whether it's affected). If we turn out not to need it, I'll abandon this pull request and create one for Cloud 8 only.

keystone: fix keystone node lookup (SOC-11333)

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/306_add_use_rbd_ephemeral.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/models/nova_service.rb
crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml
crowbar_framework/config/locales/nova/en.yml

New attribute was added to enable/disable ephemeral storage on CEPH/SES if
needed.
Added UI part:
bonus: remove redundant config line

nova: Add option to disable ephemeral on ceph (SOC-5269)

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/212_add_use_rbd_ephemeral.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/models/nova_service.rb
crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml
crowbar_framework/config/locales/nova/en.yml

Add required configuration to enable usage of SES/Ceph storage backend
for ephemeral storage in nova.
If multiple SES/Ceph backends are defined in cinder, first one is used
by nova for ephemeral strorage.
port of #2362 and #2373

[5.0] nova: Enable ephemeral volumes on SES (SOC-11119)

---

chef/cookbooks/magnum/attributes/default.rb
chef/cookbooks/magnum/recipes/common.rb
chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/data_bags/crowbar/migrate/magnum/301_add_ssl_attributes.rb
chef/data_bags/crowbar/template-magnum.json
chef/data_bags/crowbar/template-magnum.schema
crowbar_framework/app/helpers/barclamp/magnum_helper.rb
crowbar_framework/app/views/barclamp/magnum/_edit_attributes.html.haml
crowbar_framework/config/locales/magnum/en.yml

Added options to configure SSL settings in Magnum barclamp.
Taken over from https://github.com/crowbar/crowbar-openstack/pull/1608

magnum: Add SSL support (SOC-9849)

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/run_filters/nova.txt.erb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

This change fixes the tempest configuration and blacklists some tempest shelve tests that are known to fail when RBD is used for storing the Instance's ephemeral disk.

Fix tempest configuration when using RBD on nova (SOC-11176)

---

chef/cookbooks/tempest/templates/default/run_filters/lbaas.txt.erb
chef/cookbooks/tempest/templates/default/run_filters/neutron.txt.erb

Disabling failing tempest tests for SOC7 as they currently blocking
gating and mu jobs to pass. All filtered test has jira created and
planned to be enabled after fix.
neutron_lbaas.tests.tempest.v2.scenario.test_shared_pools.TestSharedPools.test_shared_pools
neutron_lbaas.tests.tempest.v2.ddt.test_health_monitor_admin_state_up.CreateHealthMonitorAdminStateTest.test_create_health_monitor_with_scenarios
tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps.test_in_tenant_traffic

Disabling failing tempest tests on SOC7

---

chef/cookbooks/ec2-api/recipes/ec2api.rb

(backports #2352)
The execution of the ec2-api cookbook includes restarting apache
however, when apache is restarted while `keystone_register` is running on
the non-cluster founder nodes it fails as keystone (running under apache)
is being restarted.

[4.0] ec2-api: run keystone_register on cluster founder only (SOC-11079)

---

chef/cookbooks/nova/recipes/config.rb

If nova_compute_kvm recipe is included in the runlist but nothing
populates cinder volumes before that, some values might be missing
in the generated configuration for ephemeral storage.
Added another "populate" call just before preparing the ephemeral
config just to be sure everything is ready for use.

nova: Populate cinder SES settings early (SOC-11179)

---

.travis.yml

For reverted commits, Travis CI uses
'git clone --depth=50 --branch=<reverted branch> <repo url> <dir>'
instead of 'git clone --depth=50 <repo url> <dir>' when cloning the repo
for testing.
With 'git clone --depth=50 --branch=<reverted branch> <repo url> <dir>',
there's no master branch. Therefore, we should always use the branch name
instead of master branch when invoking gitlint.

fix travis CI to handle reverted commits properly (SOC-11180)

---

chef/cookbooks/tempest/templates/default/run_filters/cinder.txt.erb
chef/cookbooks/tempest/templates/default/run_filters/neutron.txt.erb

Update the list of tempest test cases blacklisted in run filters:
* re-enable tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps
(fixed by https://review.opendev.org/#/c/570207/)
* blacklist tempest.api.volume.admin.test_volume_type_access.VolumeTypesAccessV2Test
(workaround for SOC-11187)
* TBD (magnum)

tempest: update blacklisted tempest test cases (SOC-9801,SOC-11174,SOC-11187)

---

chef/cookbooks/nova/recipes/config.rb

If nova_compute_kvm recipe is included in the runlist but nothing
populates cinder volumes before that, some values might be missing
in the generated configuration for ephemeral storage.
Added another "populate" call just before preparing the ephemeral
config just to be sure everything is ready for use.
(cherry picked from commit 73329ef4345815ce32c6ad71d99791103f37434d)
port of #2379

[5.0] nova: Populate cinder SES settings early (SOC-11179)

---

chef/cookbooks/horizon/templates/default/local_settings.py.erb

Identity v2 API doesn't exist in SOC 9 and the openrc file with URL to
it will not work.
Hide the download link from horizon using the provided for it option.

Disable "OpenStack RC File (identity API v2)" in horizon (bsc#1163444)

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/octavia/definitions/octavia_conf.rb
chef/cookbooks/octavia/libraries/helpers.rb
chef/cookbooks/octavia/recipes/api.rb
chef/cookbooks/octavia/recipes/health_manager.rb
chef/cookbooks/octavia/recipes/housekeeping.rb
chef/cookbooks/octavia/recipes/nova.rb
chef/cookbooks/octavia/recipes/worker.rb
chef/data_bags/crowbar/migrate/octavia/304_remove_cidr.rb
chef/data_bags/crowbar/template-octavia.json
chef/data_bags/crowbar/template-octavia.schema
crowbar_framework/app/models/neutron_service.rb
crowbar_framework/app/models/octavia_service.rb
crowbar_framework/app/views/barclamp/octavia/_edit_attributes.html.haml

TL;DR: Crowbar has a more powerful mechanism of setting up additional networks and connecting interfaces to them. We leverage that here to set up a network for Octavia that doesn't require external routing, meaning that customers don't need to configure any external services or additional routes. This is better than the CLM octavia management network implementation, where customers must provide an external router that is able to route between the octavia management network and the OpenStack management network. Furthermore, this implementation achieves a complete isolation of the octavia management network from all other networks, providing better security. Having it entirely managed by Crowbar reduces the risk of a misconfiguration on the customer's part.
Rework the implementation of the …

octavia: rework management network implementation (SOC-10904)

---

chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

- magnum barclamp: set `verify_ca = false`. The magnum barclamp does not
support setting `openstack_ca_file` which leaves magnum unusable when
deploying crowbar using self-signed certificates. Setting `verify_ca =
false` ensures that it will work for any case.
- tempest barclamp: set the DNS nameserver for magnum to the crowbar DNS
server; and add `member` to the list of roles used for tempest.
(cherry picked from commit abae955fdf8f3775e0b4d695fd9e9c803e667d4f)

Fix magnum tempest tests (SOC-9298)

---

chef/cookbooks/barbican/recipes/ha.rb
chef/cookbooks/crowbar-openstack/libraries/helpers.rb

(backports #2169)
The check to identify if SSL is enabled on the barbican barclamp was
incorrect, there is no `ssl` entry on the barbican/api schema.
This change uses the api.protocol value (http/https) to check if SSL is
enabled or not, the same way other barclamps do (eg. keystone).
(cherry picked from commit ea5ba2576ae2ef43bd41ce35a34750cde2ee2539)
(cherry picked from commit a05634b6b6ef703a14eff89f0a7277a4884ce996)

[4.0] Fix barbican ssl

---

crowbar_framework/app/views/barclamp/octavia/_edit_attributes.html.haml
crowbar_framework/config/locales/octavia/en.yml

The recommended way of configuring the Octavia management network
is by providing an `octavia` network in the network barclamp configuration,
while the Octavia barclamp takes care of the rest. This means it makes
no sense to keep the option of naming a different neutron provider network
as a main configuration option in the UI, because it may confuse customers
into thinking they still need to provide this network themselves.
The option will still be accessible through the raw barclamp view, if
necessary.

octavia: remove mgmt_net from UI (SOC-10904)

---

chef/cookbooks/tempest/templates/default/run_filters/magnum.txt.erb

Magnum test failing when ssl enabled
To unblock SOC7 gating jobs disabling tests till fix provided
Problem appear due to SOC7 missing https://review.opendev.org/#/c/529166
change.Heat failed to validate magnum certificates and cancel stack
creation.

Disable  magnum.tests.functional.api.v1.test_cluster (SOC-11224)

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

(backports 1/2 of #2377)
When using RBD for VM's ephemeral disks disable block migration for live
migration as it is not supported when using shared storage.
(cherry picked from commit abb9249679345557b1b856f835194282a8952758)

[5.0] tempest: disable block migration when using RBD (SOC-11176)

---

crowbar_framework/app/assets/javascripts/barclamps/nova/application.js
crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml
crowbar_framework/config/locales/nova/en.yml

This option is meant to be used only with Xen live migration.
Since Xen support has been removed, this option should not be presented
to the users anymore.
docs snippet

nova: Hide setup_shared_instance_storage (SOC-11225)

---

chef/cookbooks/tempest/recipes/config.rb

On a HA deployment, actions that requires reapplying barclamps for
openstack services (e.g. enabling SSL on keystone) causes the tempest
barclamp to occasionally fail.
It fails because while reapplying the tempest barclamp
(deployed in one of the controllers), on other nodes everything
was done and the post actions are called which triggers the restart
of openstack services, when the openstack commands from the tempest
barclamp are called at the same time as the service is restarting
those commands fails.
This change adds a retry on the ruby blocks executing openstack
commands. So if the command fails it tries again, giving time for the
service to restart.

tempest: retry openstack commands (SOC-11238)

---

chef/cookbooks/tempest/recipes/config.rb

On a HA deployment, actions that requires reapplying barclamps for
openstack services (e.g. enabling SSL on keystone) causes the tempest
barclamp to occasionally fail.
It fails because while reapplying the tempest barclamp
(deployed in one of the controllers), on other nodes everything
was done and the post actions are called which triggers the restart
of openstack services, when the openstack commands from the tempest
barclamp are called at the same time as the service is restarting
those calls fails.
This change adds a retry on the ruby blocks executing openstack
commands. So if the command fails it tries again, giving time for the
service to restart.
(cherry picked from commit 50d3409abba4b5e319e7d3f7626fda47f1ee848d)

[5.0] tempest: retry openstack commands (SOC-11238)

---

chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/placement_api.rb

The execution of the nova cookbook includes restarting apache,
however, when apache is restarted while keystone_register is running on
the non-cluster founder nodes it fails as keystone (running under apache)
is also being restarted.
This change fixes that by including a condition for running the
keystone_register operations only on the cluster founder node.

nova: run keystone_register on cluster founder only (SOC-11243)

---

chef/cookbooks/barbican/recipes/api.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/cinder/recipes/api.rb
chef/cookbooks/designate/recipes/api.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/glance/recipes/common.rb
chef/cookbooks/magnum/recipes/api.rb
chef/cookbooks/manila/recipes/api.rb
chef/cookbooks/neutron/recipes/api_register.rb
chef/cookbooks/octavia/recipes/keystone.rb
chef/cookbooks/sahara/recipes/api.rb
chef/cookbooks/swift/recipes/proxy.rb
chef/cookbooks/watcher/recipes/common.rb
chef/cookbooks/watcher/recipes/server.rb

Although it was fixed for some services (e.g. nova ) there are still
other services where keystone_register is called on all controllers with
a subsequent apache restart. From this, there is a risk of the
keystone_register call be executed while apache (and keystone) is
restarting and consequently failing the deployment.
This change make all calls for keystone_register to be made only on
one of the controllers for all services that supports HA.

run keystone_register on cluster founder only when HA (SOC-11248)

---

chef/cookbooks/barbican/recipes/api.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/cinder/recipes/api.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/glance/recipes/common.rb
chef/cookbooks/magnum/recipes/api.rb
chef/cookbooks/manila/recipes/api.rb
chef/cookbooks/neutron/recipes/api_register.rb
chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/placement_api.rb
chef/cookbooks/sahara/recipes/api.rb
chef/cookbooks/swift/recipes/proxy.rb

(backports #2399 and #2400)
There are still plenty of services where keystone_register is called on all controllers with
a subsequent apache restart. From this, there is a risk of the
keystone_register call be executed while apache (and keystone) is
restarting and consequently failing the deployment.
This change make all calls for keystone_register to be made only on
one of the controllers for all services that supports HA.

[4.0] run keystone_register on cluster founder only when HA (SOC-11248,SOC-11243)

---

chef/cookbooks/barbican/recipes/api.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/cinder/recipes/api.rb
chef/cookbooks/designate/recipes/api.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/glance/recipes/common.rb
chef/cookbooks/magnum/recipes/api.rb
chef/cookbooks/manila/recipes/api.rb
chef/cookbooks/neutron/recipes/api_register.rb
chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/placement_api.rb
chef/cookbooks/sahara/recipes/api.rb
chef/cookbooks/swift/recipes/proxy.rb

(backports #2399 and #2400)
There are still plenty of services where keystone_register is called on all controllers with
a subsequent apache restart. From this, there is a risk of the
keystone_register call be executed while apache (and keystone) is
restarting and consequently failing the deployment.
This change make all calls for keystone_register to be made only on
one of the controllers for all services that supports HA.

[5.0] run keystone_register on cluster founder only when HA (SOC-11248,SOC-11243)

---

chef/data_bags/crowbar/template-monasca.json

This patch is one of the pieces needs to fix the monasca
libvirt ping checks. The other patch is an rpm-packaging patch
to correct the sudoers file used by the monasca-agent.

Fix monasca libvirt ping checks (bsc#1107190)

---

chef/data_bags/crowbar/template-monasca.json

This patch is one of the pieces needed to fix the monasca
libvirt ping checks. The other patch is an rpm-packaging patch
to correct the sudoers file used by the monasca-agent.
https://review.opendev.org/724689
(cherry picked from commit b0b10d61f248ea5c2dc26ccdf951dee89a2c5623)

[5.0]  Fix monasca libvirt ping checks (bsc#1107190)

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

(reverts #2189)
Changing the admin state of a port was broken due to a bug on
vhost net and tun/tap. This bug has been fixed on SLES12SP4, so
we can again run tempest test cases targeting this feature.

tempest: remove port_admin_state_change workaround (SOC-10029)

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

This patch fixes the rabbitmq connection url by ensuring that the vhost
is properly added only at the end of the generated url.

trove: fix rabbitmq connection URL (SOC-11286)

---

chef/cookbooks/rabbitmq/libraries/crowbar.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb

In an HA setup, every time a rabbitmq broker is restarted, whatever the
reason may be (an RA monitor failure, a controller node reboot etc.), the
rabbitmq queue policy is changed from this:
```
openstack	ha-queues	queues	^(?!(amq.)|(.*_fanout_)|(reply_)).*	{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}	0
```
to this:
```
openstack	ha-queues	queues	^(?!amq.).*	{"ha-mode":"exactly","ha-params":2}	0
```
This behavior isn't intentional, it's just a byproduct of neglect (the
startup rabbitmq configuration has over time fallen behind the runtime
configuration enforced by the chef recipes). It has a negative impact
on performance and reliability, because it abruptly makes fanout and
reply queues fully mirrored, making matters worse in the middle of a
restart operation that …

rabbitmq: sync startup definitions.json with recipe (SOC-11077,SOC-11274)

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

(backports #2412)
This patch fixes the rabbitmq generated url by ensuring that the vhost
is properly added only at the end of the url.
(cherry picked from commit cd19cab6de21007c82e8bebba48b4591dd6b214d)

[5.0] trove: fix rabbitmq connection URL (SOC-11286)

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

(backports #2412)
This patch fixes the rabbitmq generated url by ensuring that the vhost
is properly added only at the end of the url.
(cherry picked from commit cd19cab6de21007c82e8bebba48b4591dd6b214d)
(cherry picked from commit 6a4a82f07ceedec3b854e48b491a4dd929f6402b)

[4.0] trove: fix rabbitmq connection URL (SOC-11286)

---

chef/cookbooks/rabbitmq/libraries/crowbar.rb
chef/cookbooks/rabbitmq/recipes/default.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/rabbitmq/templates/default/definitions.json.erb

(backports #2413)
In an HA setup, every time a rabbitmq broker is restarted, whatever the
reason may be (an RA monitor failure, a controller node reboot etc.), the
rabbitmq queue policy is changed from this:
```
openstack       ha-queues       queues  ^(?!(amq.)|(.*_fanout_)|(reply_)).*     {"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}  0
```
to this:
```
openstack       ha-queues       queues  ^(?!amq.).*     {"ha-mode":"exactly","ha-params":2}     0
```
This behavior isn't intentional, it's just a byproduct of neglect (the
startup rabbitmq configuration has over time fallen behind the runtime
configuration enforced by the chef recipes). It has a negative impact
on performance and reliability, because it abruptly makes fanout and
reply queues fully mirrored, making …

[5.0] rabbitmq: sync startup definitions.json with recipe (SOC-11077,SOC-11274)

---

chef/cookbooks/mysql/recipes/ha_galera.rb

Monitoring user that is used for clusterchecks is set up without
the password. Galera pacemaker setup needs to be adjusted so it is
using the empty password instead falling back to default ~/.my.cnf.
We have to wait and publish this only after the fix in resource agents is released:
https://github.com/ClusterLabs/resource-agents/pull/1473

galera: Make sure checks are executed without password (bsc#1136928)

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/run_filters/cinder.txt.erb

This reverts commit db7d6b3f4158874eff1e47e1146374d9c11c65e9.
As CI is now using Ceph for SOC 8, enable the `test_volume_boot_pattern`
tempest test.

[5.0] Tempest: enable test_volume_boot_pattern test (SOC-10874)

---

chef/cookbooks/nova/recipes/database.rb

`nova-manage cell_v2 create_cell --name cell1` will fail if
cell1 exists already, so check for its existence before
attempting to create it blindly.
(cherry picked from commit fe218f4eee1e44af4a55923a6ffb491f323869c6)

[5.0] nova: only create nonexistent cell1

---

chef/cookbooks/nova/files/default/crowbar-nova-set-availability-zone

This script was failing with an auth error because
the project_name was not being passed correctly.

[5.0] Fix availability zone script (bsc#1171661)

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb

This option was removed [1] in crowbar because it was deprecated in nova.
But it is required by the metadata service so the deprecated status was removed [2].
[1] https://github.com/crowbar/crowbar-openstack/commit/fff5958b50d29b3c99a0874eebfcec93aeeee840
[2] https://opendev.org/openstack/nova/commit/886b0a5d748ae1deda3a039734f831d7c0cf0476

Restore undeprecated nova dhcp_domain option (bsc#1171594)

---

chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb

This option was removed [1] in crowbar because it was deprecated in nova.
But it is required by the metadata service so the deprecated status was removed [2].
[1] https://github.com/crowbar/crowbar-openstack/commit/fff5958b50d29b3c99a0874eebfcec93aeeee840
[2] https://opendev.org/openstack/nova/commit/886b0a5d748ae1deda3a039734f831d7c0cf0476
(cherry picked from commit b41f6ee05de6962de41ebe0afc36df70e0456927)

[5.0] Restore undeprecated nova dhcp_domain option (bsc#1171594)

---

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

The "running" commands expected different exit codes depending on the
status for checked resources.
Later tests showed that `crm resource show` returns 0 for both: running
and NOT running cases. Non-zero exit code is returned when e.g. the
checked resource doesn't exist.
Parsing the console output of check commands seems to be more reliable.

rabbitmq: Fix crm running check (SOC-11240)

---

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

The "running" commands expected different exit codes depending on the
status for checked resources.
Later tests showed that `crm resource show` returns 0 for both: running
and NOT running cases. Non-zero exit code is returned when e.g. the
checked resource doesn't exist.
Parsing the console output of check commands seems to be more reliable.
(cherry picked from commit c59d41707e590a60cb496486c92b18c82725f61d)
port of #2429

[5.0] rabbitmq: Fix crm running check (SOC-11240)

---

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb

The "running" commands expected different exit codes depending on the
status for checked resources.
Later tests showed that `crm resource show` returns 0 for both: running
and NOT running cases. Non-zero exit code is returned when e.g. the
checked resource doesn't exist.
Parsing the console output of check commands seems to be more reliable.
(cherry picked from commit c59d41707e590a60cb496486c92b18c82725f61d)
port of #2429

[4.0] rabbitmq: Fix crm running check (SOC-11240)

---

chef/cookbooks/keystone/libraries/helpers.rb

In a cloud where a controller was added after initial
deployment and MAC addresses are out of sequence, the
search_for_keystone() method may return the wrong controller
in the first upgraded controller's crowbar_join phase. This
commit ensures this does not happen by restricting the search for
nodes that are not in state `crowbar_upgrade`.
(cherry picked from commit e12c448d8eca2b5a71990e8dd208c2301ac2b360)
This is the Cloud 8 backport of https://github.com/crowbar/crowbar-openstack/pull/2369 . It's already tested, I used Cloud 8 (with the same commit) for most of my testing anyway.

keystone: fix keystone node lookup (SOC-11333, bsc#1164838)

---

chef/cookbooks/cinder/attributes/default.rb
chef/cookbooks/cinder/recipes/controller_ha.rb
chef/cookbooks/nova/attributes/default.rb
chef/cookbooks/nova/recipes/controller_ha.rb
chef/data_bags/crowbar/migrate/cinder/304_add_haproxy_mode_http.rb
chef/data_bags/crowbar/migrate/nova/307_add_haproxy_mode_http.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

If ssl is passed-thru on haproxy, the source ip gets replaced with
the one of the node where haproxy lives, and there is no way to get the
original ip on the services side.
Add ssl termination on haproxy. Two new hidden options are added:
loadbalancer_terminate_ssl (boolean) and pemfile (path to the
certificate to use in haproxy-recognized format).
Depends on https://github.com/crowbar/crowbar-ha/pull/373

Terminate ssl on haproxy (bsc#1149535)

---

chef/cookbooks/neutron/recipes/post_install_conf.rb

Chef uses default LC_ALL=C locale for all internal ShellOut calls.
These fails if command output contains non-ASCII characters.
The problem is bigger but it was really fixed only in Chef 12.
We could patch ShellOut to use different default be it could cause
some unwanted side effects in many places.
In this case the problem is with network names so it's easier to
limit the output to include only expected entries and not print all
names.

neutron: Fix handling of networks with non-ascii names (SOC-11429)

---

chef/cookbooks/neutron/recipes/post_install_conf.rb

Chef uses default LC_ALL=C locale for all internal ShellOut calls.
These fails if command output contains non-ASCII characters.
The problem is bigger but it was really fixed only in Chef 12.
We could patch ShellOut to use different default be it could cause
some unwanted side effects in many places.
In this case the problem is with network names so it's easier to
limit the output to include only expected entries and not print all
names.
(cherry picked from commit 70356d630962b27cfd53eb569bfe10e3f7a562e5)
port of #2433

[5.0] neutron: Fix handling of networks with non-ascii names (SOC-11429)

---

chef/cookbooks/monasca/recipes/master.rb

In the course of fixing bsc#1148158, an overzealous check for
the monasca-server node's state was introduced. This check
causes monasca-installer to not run when the monasca-server
node isn't in state `ready`. This commit changes the check to
only trip when the node is in state `reinstall`.
Note: I'm only targeting stable/pike with this because it does not apply to Cloud 9 where we did away with monasca-installer entirely.

monasca: fix monasca-server reinstall state check (SOC-11471)

---

chef/cookbooks/monasca/recipes/agent.rb
chef/cookbooks/monasca/recipes/server.rb

In the course of the Kibana update from 4.6.3 to 4.6.6,
automatic service restart will not work. Hence, Crowbar needs
to ensure Kibana is restarted.

monasca: restart Kibana on update (bsc#1044849)

---

chef/cookbooks/keystone/providers/register.rb
chef/cookbooks/keystone/recipes/server.rb

Before f0f3e481 the keystone wakeup action would always get a
new token, but now it tries to reuse the session object. The
sessions's token might be expired, and the retry loop only tries
to get a new session if the password changes. This patch chnages
that so it gets a new session on any error.

keystone wakeup: get new session on any error (bsc#1189052)
