crowbar/crowbar-openstack

chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/data_bags/crowbar/bc-template-cinder.json, chef/data_bags/crowbar/bc-template-cinder.schema, chef/data_bags/crowbar/migrate/cinder/043_add_rpc_response_timeout.rb
When using i.e. a Hitachi storage backend, the timeout needs to be
increased.
=> cinder: make rpc_response_timeout configurable

chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/templates/default/keystone.conf.erb, chef/data_bags/crowbar/bc-template-keystone.json, chef/data_bags/crowbar/bc-template-keystone.schema, chef/data_bags/crowbar/migrate/keystone/033_add_token_timeout.rb
Horizon session timeout is dependant also on the keystone
token timeout, which is "only" 1h by default. Raise this to
four hours and make it configurable via the hidden crowbar proposal.
=> Make token expiration configurable (bsc#941537)

chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/bc-template-nova.json, chef/data_bags/crowbar/bc-template-nova.schema, chef/data_bags/crowbar/migrate/nova/033_add_configdrive.rb
This is useful in environments where the dhcp-agent is
disabled, which means there is no neutron/nova metadata proxy
available.
=> Add option to enforce use of config drive (bsc#943166)

chef/cookbooks/nova/recipes/docker.rb
so that tempest could run tests with docker based image.
The image is packaged in tempest barclamp. We can't do this from
tempest recipe because tempest might be deployed on another node
which does not have access to the docker comput node.
Tex version is here https://github.com/crowbar/barclamp-nova/pull/481
This should work together with https://github.com/crowbar/crowbar-openstack/pull/18
=> If tempest is deployed, load docker image at docker compute node

chef/data_bags/crowbar/migrate/keystone/031_add_version.rb
Do not overwrite the api version if it was already set.
=> Fix up migration after tex backport

crowbar_framework/examples/HA-cloud.yaml, crowbar_framework/examples/simple-cloud.yaml
This should allow people to "kick the tyres" even quicker.  They originate from https://github.com/SUSE-Cloud/suse-cloud-vagrant/tree/master/vagrant/provisioning/admin and @dirkmueller suggested that some of the tweaks in the appliances / Vagrant boxes should be ported into the product.  So this is the first step towards that.
=> add sample input files for `crowbar batch build`

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
test that is not supported by docker instances.
Requires https://review.openstack.org/#/c/221874/
=> Set dhcp_client to empty value will skip test_subnet_details

chef/cookbooks/postgresql/attributes/default.rb
It's 9.4, not 9.3 like in SLE12.
=> postgresql: Fix version of postgresql for SLE12 SP1

chef/cookbooks/neutron/recipes/post_install_conf.rb
It needs to be on "floating" not "physnet1". It seems this didn't matter much as
long as we still had the "external_network_bridge" setting in the config. But
that needed to go for mulitple external network support.
=> Set the right physical_network for the floating network

chef/cookbooks/manila/recipes/share.rb, chef/cookbooks/manila/templates/default/manila.conf.erb, chef/data_bags/crowbar/bc-template-manila.json, chef/data_bags/crowbar/bc-template-manila.schema, chef/data_bags/crowbar/migrate/manila/010_add_manual_backend.rb, crowbar_framework/app/helpers/manila_barclamp_helper.rb, crowbar_framework/app/views/barclamp/manila/_edit_attributes.html.haml, crowbar_framework/config/locales/manila.en.yml
A manual backend can be used when the crowbar ui and raw view
don't support a driver or a specific feature of a driver.
Something similar in Cinder already exists and was used as blueprint.
=> manila: Allow manual backend setup

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/recipes/post_install_conf.rb, chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb
This should work regardless of the mechanism driver that is used  (openvswitch
or neutron) as we have the ml2 type driver "flat" enabled unconditionally. This
is also in line with the behaviour of devstack.
For linuxbridge setups this commit also adjust the interface mappings for
external networks to use the VLAN interface instead for the underlying physical
interface. That's required for "flat" networks.
=> Create external networks as "flat" provider networks (bsc#946882)

chef/cookbooks/nova/attributes/default.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/nova/034_configure_block_device_allocation.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema
Make block_device_allocate_retries and block_device_allocate_retries_interval
configurable from the crowbar web ui in the raw view.
See also https://bugzilla.suse.com/show_bug.cgi?id=937800
(cherry picked from commit 50c65af8878cf9e749557e194b86d1c0cef33144)
Conflicts:
chef/data_bags/crowbar/bc-template-nova.json
=> Make block device allocation settings configurable

chef/cookbooks/glance/templates/default/glance-api.conf.erb
It now needs to be in the glance_store group. For some reason, the
deprecated location doesn't work.
=> glance: Fix default_store option

chef/data_bags/crowbar/migrate/keystone/032_add_domain_specific_drivers.rb, crowbar_framework/app/models/keystone_service.rb
Support of Keystone domain specific drivers is being backported to tex. Fix
migrartion to be prepared for that. Also try clarify proposal validation
message a bit.
=> Fixup migration for tex backport

chef/cookbooks/cinder/recipes/ceph.rb
According to Ceph documentation cinder caps for glance pool should be like follows
http://docs.ceph.com/docs/master/rbd/rbd-openstack/
```
ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'
ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
ceph auth get-or-create client.cinder-backup mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=backups'
```
=> Update cinder caps for glance pool, (bnc#944810)

crowbar_framework/app/models/nova_service.rb
This was already enforced during validation, but we can add an explicit
constraint for it.
=> nova: Only accept suse nodes for xen compute role

chef/cookbooks/nova/templates/default/nova.conf.erb
It turns out Nova does not handle running out of RPC connections
gracefully, but rather misbehaving badly and failing VMs. Since
you're quickly running out of RPC threads when talking to neutron
while launching a massive number of VMs in parallel, we should
raise the upper limit to a saner value.
=> Raise Nova defaults to avoid hangs on mass-deployment (bsc#944489)

chef/cookbooks/cinder/recipes/scheduler.rb, chef/cookbooks/glance/recipes/api.rb
qemu-img is used by some bits of both cinder and glance.
=> cinder, glance: Install qemu-img only when needed

chef/cookbooks/heat/recipes/ha.rb
Heat HA resources can take over 1 minute to be set up, as
seen by mkcloud failures in ci.suse.de Jenkins.
=> increase timeout for synchronization of HA resources (bsc#935462)

chef/cookbooks/horizon/recipes/ha.rb
Horizon HA resources can take over 1 minute to be set up, as seen by [mkcloud failures in ci.suse.de Jenkins](https://trello.com/c/Z1L5phHx).
See also #54 for equivalent tweak to heat.
=> increase timeout for synchronization of horizon HA resources (bsc#935462)

chef/data_bags/crowbar/migrate/keystone/032_add_domain_specific_drivers.rb
Check for the correct attribute. "multi_domain_support" never was an attribute
of the keystone proposal.
=> Fixup migration for tex backport (again)

chef/data_bags/crowbar/template-horizon.json, crowbar_framework/app/models/horizon_service.rb, crowbar_framework/app/models/keystone_service.rb
Horizon timeout is impacted by keystone token timeout since when the
token gets outdated, then the user is automatically unable to use
horizon. This patch includes a check for the timeout of horizon and
keystone barclamps.
Increased default keystone token expiration timeout to 24 hours up
from 4 hours.
=> Add warning for horizon/keystone timeouts

chef/cookbooks/nova/recipes/compute.rb
VNC ports are accessible from the management network. This patch will
allow us to restrict the VNC console from unwanted access to VNC
console. Using iptables u32 and string module to filter out VNC packets.
Forwardport from https://github.com/crowbar/barclamp-nova/pull/483
Signed-off-by: Pranav Salunke <dguitarbite@gmail.com>
=> Add iptables rules to deny unwanted VNC access (bsc#938200)

chef/cookbooks/nova/recipes/api.rb
Make the v2.1 the new default "nova" endpoint. Provide v2.0 via the
"nova_legacy" service. (As e.g. done in devstack)
=> Fix nova endpoints for liberty

chef/cookbooks/cinder/attributes/default.rb, chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/cookbooks/nova/attributes/default.rb
Without the settings on Nova and Cinder-volume in sync, there are
interesting side effects in several drivers since they pass through
inconsistent information between Cinder and Nova, that causes undesired
artefacts.
=> Enable multipath for image xfer also on cinder-volume

chef/cookbooks/neutron/recipes/common_agent.rb
The non-network nodes also need to have access to the external networks
when using DVR.
=> neutron: Fix multiple external networks with DVR

chef/cookbooks/crowbar-openstack/libraries/helpers.rb, chef/cookbooks/swift/templates/default/proxy-server.conf.erb
The rabbitmq settings in Liberty are expected as an url instead.
=> Fix ceilometer middleware configuration

chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb
We already send the right MTU value to instances via an option in DHCP,
but this mechanism may not work in all Docker instances because some of
them won't even run a DHCP client. Having the right MTU setting on
instance creation is needed. There's an option (network_device_mtu)
that can be configured in nova.conf to achieve that.
The 1500-byte MTU is too big when a tunneling underlay is used. The
overhead caused by the tunneling is usually 20-byte for IPv4 header,
8-byte for either GRE or VxLAN and 14-byte for Ethernet, totalling
42 bytes. In this situation the right MTU should be 1458 bytes. In
this patch we use 1450 in case two additional VLAN headers are added
in the overlay. This should also be revisited when the underlay or
overlay are using IPv6.
This is only needed when the compute …
=> Help Docker instances get proper MTU value

chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
On a slow system, the first request can take a long time due
to online compression. Apache is then running into a:
Timeout when reading response headers from daemon process 'horizon'
error.
=> horizon: increase timeout in apache config

chef/cookbooks/nova/recipes/compute.rb
python-nova already depends on python-oslo.vmware which depends
on python-suds-jirko which is the successor of python-suds.
=> nova: don't install python-suds for vmware

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/recipes/server.rb, chef/data_bags/crowbar/migrate/neutron/044_drop_use_l2pop.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema, crowbar_framework/app/assets/javascripts/barclamps/neutron/application.js, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/config/locales/neutron/en.yml
The only reason we had an attribute for it is that it was not possible
to automatically set this up during a maintenance upgrade as it was
possibly creating some downtime. Since we're moving to a new version,
there will be downtime anyway, so let's use this as an opportunity to
enable l2pop.
There should be no big downside to just always enable l2pop when it's
possible to use it.
=> neutron: Always automatically enable l2pop whenever possible

chef/cookbooks/neutron/templates/default/metadata_agent.ini.erb
The metadata agent (neutron-metadata-agent) is receiving requests from
metadata proxies in namespaces (neutron-ns-metadata-proxy) through a
UNIX socket. The requests there are always plain HTTP and since it's not
going through the network, it's fine.
However, if [DEFAULT] use_ssl in neutron.conf is set to true, then
neutron-metadata-agent inherits this and expects HTTPS on this UNIX
socket too. So always override this setting.
=> neutron: Fix metadata agent when neutron is using SSL

chef/cookbooks/cinder/templates/default/cinder.conf.erb
We set [keymgr] encryption_auth_url in cinder.conf to the keystone v3
auth URI. This is terrible because that's unrelated to this setting and
this hardcodes a need for the v3 API, but that's really upstream bugs.
See upstream bugs:
https://bugs.launchpad.net/cinder/+bug/1517043
https://bugs.launchpad.net/cinder/+bug/1516085
https://bugs.launchpad.net/cinder/+bug/1511960
https://bugs.launchpad.net/cinder/+bug/1509308
On top of this, the quotas are broken when using insecure SSL with
keystone, but it's not something we can fix here.
=> cinder: Ugly hack to make cinder quotas work again

chef/cookbooks/horizon/recipes/server.rb
If there is a manila-server role, install the UI plugin package
on the dashboard node to be able to handle shares via the UI.
=> horizon: Install Manila UI plugin when needed

chef/cookbooks/ceilometer/attributes/default.rb, chef/cookbooks/ceilometer/recipes/polling.rb, chef/cookbooks/ceilometer/recipes/polling_ha.rb, chef/data_bags/crowbar/migrate/ceilometer/023_rename_ceilometer_cagent_role.rb, chef/data_bags/crowbar/template-ceilometer.json, chef/roles/ceilometer-cagent.rb, chef/roles/ceilometer-polling.rb, crowbar_framework/app/models/ceilometer_service.rb
Services agent-central, agent-ipmi have been deprecated upstream from Kilo release onwards. These are now replaced by ceilometer-polling. The current ceilometer barclamp does not address this deprecation. Neither ceilometer-agent-central nor ceilometer-polling services run on the control node failing some ceilometer functionalities (like metering for control node services). This change updates the barclamp to install and start ceilometer-polling service instead of the deprecated services.
=> Add ceilometer-polling service as required for Liberty installation

chef/cookbooks/keystone/attributes/default.rb, chef/data_bags/crowbar/template-keystone.json
While investigating performance issues we recognized that
using PKI tokens is a lot slower.
I.e. running "cinder list" needs 3s instead of 1s with uuid tokens.
=> keystone: switch default token format to uuid

chef/data_bags/crowbar/migrate/keystone/034_update_default_attributes.rb
We don't need to migrate the attribute just for sql, but for all the
other backends too.
=> keystone: Fix migration of driver attributes

chef/cookbooks/nova/recipes/controller_ha.rb
This reverts commit f04bd35ef94822f8e229e6cfb5219a16f1d92cb9.
When we merge this PR https://github.com/crowbar/crowbar-ha/pull/45,
the sync_mark timeout will increase to 180 second by default.
=> Revert "increase timeout for synchronization of HA resources (bsc#935462)"

chef/cookbooks/nova/recipes/compute.rb
We explicitly start the iscsid daemon to help nova-compute, but we
didn't make sure it was installed, and it's not a dependency of nova.
It's generally okay because it's a dependency of libvirt, but on docker
nodes, the package is actually not installed by default (at least on
Leap).
=> nova: Install open-iscsi before starting its daemon

chef/cookbooks/heat/templates/opensuse/loadbalancer.template.erb, chef/cookbooks/horizon/templates/opensuse/openstack-dashboard.conf.erb, chef/cookbooks/neutron/templates/opensuse/sysconfig.neutron.erb
We want the same set of templates for both SUSE and openSUSE.
=> heat, horizon, neutron: Symlink the suse templates as opensuse

chef/cookbooks/postgresql/attributes/default.rb
This is the latest version of postgresql in Leap.
=> postgresql: Use 9.4 for openSUSE

crowbar_framework/app/models/swift_service.rb
It is documented that the proposal status is not something that should
be used to detect if a proposal is deactivated or not. So we need to
check if the role exists for this.
=> swift: Fix crash when applying proposal with a deactivated ceph proposal

chef/cookbooks/cinder/recipes/monitor.rb, chef/cookbooks/glance/recipes/monitor.rb, chef/cookbooks/heat/recipes/monitor.rb, chef/cookbooks/horizon/recipes/monitor.rb, chef/cookbooks/keystone/recipes/monitor.rb, chef/cookbooks/manila/recipes/monitor.rb, chef/cookbooks/neutron/recipes/monitor.rb, chef/cookbooks/nova/recipes/monitor.rb, chef/cookbooks/rabbitmq/recipes/monitor.rb, chef/cookbooks/swift/recipes/monitor.rb
We return directly if the node is not nagios-client.
=> cookbooks: Simplify monitor recipes

chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/data_bags/crowbar/migrate/glance/025_remove_vsphere_api_insecure.rb, chef/data_bags/crowbar/template-glance.json, chef/data_bags/crowbar/template-glance.schema, crowbar_framework/app/views/barclamp/glance/_edit_attributes.html.haml, crowbar_framework/config/locales/glance/en.yml
Because of discussion in https://github.com/crowbar/crowbar-openstack/pull/131#discussion-diff-46124162, we decided to drop it
=> Dropping VMware API insecure option from Glance

chef/cookbooks/rabbitmq/attributes/default.rb, chef/cookbooks/rabbitmq/templates/default/rabbitmq-env.conf.erb
It was missing the rabbit@ part, which is wrong as this could mean a
conflict with other erlang apps.
Note that this change breaks existing deployment of rabbitmq, as
rabbitmq can't get restarted (due to the nodename change). So it's only
okay to get in if we know that the upgrade process will stop rabbitmq.
(+ a cleanup commit)
=> rabbitmq: Fix nodename used for rabbitmq

chef/cookbooks/keystone/templates/default/openrc.erb
In case the public network is down, debugging is rather painful.
I think if you're on the node that has the .openrc then the
internalURL should always work, so use that instead.
=> Use internalURL for communication with OpenStack

chef/cookbooks/nova/recipes/database.rb
The default sync timeout is now 180 seconds, so we definitely don't want to decrease it here; if anything it should be longer since nova is towards the end of a full run list, so the nodes are more likely to have drifted by this point.
https://bugzilla.suse.com/show_bug.cgi?id=935462
See also #138 which does something similar for `nova_ha_resources`.
=> increase nova_database sync timeout to 240 (bsc#935462)

chef/cookbooks/ceilometer/recipes/server_ha.rb
crowbar/crowbar-ha@d2c1a01c7 from crowbar/crowbar-ha#45 increased the default timeout from 60 to 180, so it no longer makes sense to set this to 120 which is now lower than the default.
This reverts commit 7b7cd2b571b2e7b0416bf22a9e6fdd5b04129fe4.
See also #138 and #159.
=> Revert increase timeout for sync of ceilometer HA resources (bsc#935462)

chef/cookbooks/neutron/templates/default/linuxbridge_agent.ini.erb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb, chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb
For Linux Brigde should be
`firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver`
For OpenvSwitch  should be
`firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver`
=> Configure proper firewall_driver for ML2 specific agents

chef/cookbooks/tempest/templates/default/tempest.conf.erb
Instead of having 
```
2015-12-17 09:19:56,629 18418 INFO     [tempest_lib.common.rest_client] Request (TestNetworkBasicOps:test_update_router_admin_state): 200 GET http://d52-54-77-77-77-01.vc3.cloud.suse.de:8774/v2.1/6d4c3dcb7cbf47459f535ec1cf01a28e/servers/bfbe2f04-a8d5-4f5c-b8b4-3a9783c248c9 0.251s
2015-12-17 09:19:58,251 18418 INFO     [tempest_lib.common.rest_client] Request (TestNetworkBasicOps:test_update_router_admin_state): 200 GET http://d52-54-77-77-77-01.vc3.cloud.suse.de:8774/v2.1/6d4c3dcb7cbf47459f535ec1cf01a28e/servers/bfbe2f04-a8d5-4f5c-b8b4-3a9783c248c9 0.592s
2015-12-17 09:19:58,303 18418 INFO     [tempest.common.waiters] State transition "BUILD/scheduling" ==> "BUILD/block_device_mapping" after 2 second wait
2015-12-17 09:19:59,666 18418 INFO …
```
=> Switch off verbose option for better transparency

chef/cookbooks/neutron/recipes/common_agent.rb
There's no need to drop DVR support for linuxbridge in the cookbook:
what matters is that crowbar makes it impossible; having the cookbook
support this will be helpful when upstream adds support for DVR with
linuxbridge.
=> neutron: Revert one piece from a98aa50da5471ea58657d4abf6cbf186fd1096a5

chef/cookbooks/heat/recipes/ha.rb, chef/cookbooks/horizon/recipes/ha.rb, chef/cookbooks/neutron/recipes/network_agents_ha.rb, chef/cookbooks/nova/recipes/database.rb, crowbar_framework/app/models/ceilometer_service.rb, crowbar_framework/app/models/cinder_service.rb, crowbar_framework/app/models/database_service.rb, crowbar_framework/app/models/glance_service.rb, crowbar_framework/app/models/heat_service.rb, crowbar_framework/app/models/horizon_service.rb, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/app/models/manila_service.rb, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/app/models/nova_service.rb, crowbar_framework/app/models/rabbitmq_service.rb
This depends on https://github.com/crowbar/crowbar-ha/pull/60
=> Use reset_sync_marks_on_clusters_founders to avoid drift (bsc#935462)

chef/cookbooks/nova/recipes/compute.rb, chef/data_bags/crowbar/migrate/nova/039_add_zvm_xcat_ssh_key.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml, crowbar_framework/config/locales/nova/en.yml
The user needs to enter the xCAT public key to the nova
user in order to scp the images from the node.
=> Make xCAT ssh key configurable

chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/cookbooks/glance/templates/default/glance-registry.conf.erb
See https://bugs.launchpad.net/nova/+bug/1361360 for the full
story.
=> glance: Avoid greenthreads hanging endlessly on "slowloris" attack

chef/data_bags/crowbar/template-keystone.json
New deployments should be using v3 as it provides more
features onwards, and starting with Liberty v3-only should
be possible (however this change still enables both versions).
=> Switch to OpenStack Identity API version 3 by default

chef/cookbooks/neutron/recipes/network_agents.rb, chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb, chef/cookbooks/neutron/templates/default/dnsmasq-neutron.conf.erb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb, chef/cookbooks/neutron/templates/default/neutron.conf.erb
Removes custom dnsmasq-neutron.conf.erb and sets mtu options via.
neutron ml2_conf.ini.erb.
=> Updates mtu configuration to use neutron config options.

chef/cookbooks/cinder/templates/default/cinder.conf.erb
This is no longer needed, the problem was fixed upstream:
https://review.openstack.org/#/c/262162/
This reverts commit a3070412e9cda71b1e64717f9f246e105f8f1b7f.
=> Revert "cinder: Ugly hack to make cinder quotas work again"

chef/cookbooks/horizon/recipes/server.rb
We need to verify the certificate is non-empty, and we need
to check for it before we reconfigure services to use it.
=> Run SSL certificate checks more thoroughly (bsc#960006)

chef/cookbooks/neutron/recipes/network_agents_ha.rb
Right now, the order explicitly requires haproxy to be started before
neutron-server, which results in neutron-server being stopped and
started when migration haproxy.
Instead, do not require an order in the dependencies of neutron-ha-tool.
Also depends on postgresql and rabbitmq since without them, this won't
work.
Depends on crowbar/crowbar-ha#29
=> neutron: Fix order constraint for neutron-ha-tool

chef/cookbooks/nova/templates/default/nova.conf.erb
See https://bugs.launchpad.net/nova/+bug/1361360 for the full
story.
=> nova: Avoid greenthreads hanging endlessly on "slowloris" attack

chef/cookbooks/tempest/recipes/config.rb
This will be useful to disable some tests that are failing for Xen, and
that are caused by known unfixed upstream bugs.
The check is not really thorough as we only check that there's no KVM
node, but for all practical matters, it's good enough.
=> tempest: Add a file to flag when a deployment is Xen-only

chef/cookbooks/nova/libraries/boot_kernel.rb, chef/cookbooks/nova/recipes/compute.rb
The code to change the grub config is parsing the list of available
kernels, but since it was running in the compilation phase, it had to
reboot twice to actually work as intended. So run this in the
convergence phase with a ruby_block.
=> nova: Change grub config after xen kernel is installed

tempest.yml
The tempest dashboard is non-functional right now, so at least hide it.
This can be reverted once https://github.com/crowbar/crowbar-openstack/pull/191 is completed.
=> tempest: Hide menu item that leads to tempest dashboard

chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb
This was set to flat, but this results in a config that is invalid for
tempest tests related to external networks
(tempest.api.network.admin.test_external_network_extension.ExternalNetworksTestJSON):
it's simply not possible to create an external network because there's
no way to allocate a segment for the flat type.
Note that this was introduced following https://github.com/crowbar/crowbar-openstack/pull/97#issuecomment-160137507
cc @rhafer
=> neutron: Do not set external_network_type in ml2_conf.ini

chef/cookbooks/swift/templates/default/proxy-server.conf.erb
Driver must be messaging, not rabbit.
=> swift: Fix ceilometer integration

chef/cookbooks/swift/recipes/common_config.rb, chef/cookbooks/swift/recipes/proxy.rb, chef/cookbooks/swift/recipes/storage.rb
The file is needed not just on container/storage nodes, but also on the
proxy node.
=> swift: Create container-sync-realms.conf on proxy nodes too

chef/cookbooks/manila/templates/default/manila.conf.erb
For the generic driver, Manila uses internally cinder, neutron and nova
to setup a service instance.
While i.e. creating a cinder volume, the cinderclient uses the auth_url
configured in manila.conf . This url must be set to v2. Otherwise
authentication fails. See lp#1535700 .
=> manila: Use keystone v2 for cinder,neutron and nova

chef/cookbooks/swift/recipes/default.rb
Swift wants to restart the rsyslog service which is defined in
the logging recipe. This fixes:
FATAL: Chef::Exceptions::ResourceNotFound: resource
template[/etc/rsyslog.d/11-swift.conf] is configured to notify resource
service[rsyslog] with action restart, but service[rsyslog] cannot be
found in the resource collection. template[/etc/rsyslog.d/11-swift.conf]
is defined in /var/chef/cache/cookbooks/swift/recipes/default.rb:39:in
`from_file'
=> swift: Include logging recipe

chef/cookbooks/nova/recipes/config.rb
Nova now tries to use the certificates also when creating a client for
glance: https://review.openstack.org/#/c/72974/
Since we really only have this setting to control whether the controller
uses SSL, always put empty paths for ssl certificates on compute-only
nodes.
=> nova: Don't specify ssl certificates in nova.conf for compute-only nodes

chef/cookbooks/cinder/recipes/common.rb, chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/data_bags/crowbar/migrate/glance/026_add_store_location.rb, chef/data_bags/crowbar/template-glance.json, chef/data_bags/crowbar/template-glance.schema, crowbar_framework/app/views/barclamp/glance/_edit_attributes.html.haml, crowbar_framework/config/locales/glance/en.yml
By storing images in cinder backend, an efficient COW initialisation of volumes can be used, which saves both time and disk usage.
=> Allow enablement of glance image backend optimizations (bsc#945043)

chef/cookbooks/tempest/recipes/config.rb
Currently we have the tests disabled in our package but we want
to enable it without breaking the gate. So disable the tests for
now, enable the tests in the package then as see gating results
when reverting this patch.
=> tempest: Temporary disable manila tests

chef/cookbooks/neutron/recipes/server.rb, chef/data_bags/crowbar/migrate/neutron/045_create_default_networks.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
This is a common request we receive; ideally, we would simply move the
definitions of the networks to the barclamp, and add a way to disable
them there, but in the meantime, this should be good enough.
http://bugzilla.suse.com/show_bug.cgi?id=963007
=> neutron: Add attribute to disable creation of fixed/floating networks

chef/cookbooks/tempest/templates/default/tempest.conf.erb
There is no "internal_URL". It's "internalURL".
This fixes:
ConfigFileValueError: Value for option endpoint_type is not valid
=> tempest: Use correct endpoint type for manila

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/recipes/server.rb
We see quite some failures in the HA gating that seem to be related to
the use of l2pop. Until this is fixed, let's just not use l2pop for now,
unless we need it for DVR.
cc @rossella  @abel-navarro
=> neutron: Disable l2pop mechanism unless DVR is enabled

chef/cookbooks/cinder/templates/default/cinder_eternus_dx_config.xml.erb
For Liberty, the driver (which is now out-of-tree) changed the
attribute names of the configuration file.
=> cinder: Adjust Fujitsu Eternus config

chef/cookbooks/tempest/templates/default/tempest.conf.erb
A couple of weeks ago we updated the tempest version to 7.0.0 .
The configuration changed so update the current tempest.conf.erb
template.
=> tempest: Sync tempest.conf again with sample config

chef/cookbooks/openstack-database/recipes/api.rb, chef/cookbooks/openstack-database/recipes/taskmanager.rb, chef/cookbooks/openstack-database/templates/default/trove-taskmanager.conf.erb, chef/cookbooks/openstack-database/templates/default/trove.conf.erb, chef/cookbooks/trove/recipes/default.rb
This depends on upstream trove patch that we need to backport:
https://review.openstack.org/#/c/272686/
=> trove: Add insecure options for openstack services in trove.conf

chef/cookbooks/nova/templates/default/nova.conf.erb
Without specifying a memcache server, the indivual nova-consoleauth
instances can not synchronise their state between each other in
the cluster.
=> Fix novnc for HA deployments

crowbar_framework/lib/openstack/upgrade.rb
The node[barclamp] attribute might not be there. E.g. if a specific components is not
deployed.
=> Upgrade: Fix db_synced reset

chef/data_bags/crowbar/migrate/ceilometer/023_rename_ceilometer_cagent_role.rb
There's only one element that is central-agent/polling, and we were
assuming that find would return this element and only this one, but find
returns an array.
=> ceilometer: Fix broken migration

ceilometer.yml, heat.yml, manila.yml
OpenStack barclamp description follow the format:
"OpenStack projectname: description".
=> Use consistent naming schema for OpenStack barclamps

chef/cookbooks/nova/recipes/compute.rb
Illegal connections to VNC server on compute nodes which were blocked
left an open process on compute node leaving possibilities for
potential DDOS.
=> Update VNCBLOCK to close rejected connections.

chef/data_bags/crowbar/migrate/nova/036_rename_nova_roles.rb
Only add the new role to the "elements" if the old role was already listed
there before. Otherwise the value will be initialized to "nil" and cause
proposal validation failures.
=> Fix nova role rename migration

chef/cookbooks/postgresql/recipes/server_redhat.rb
When upgrading a node from SLES11-SP3 to SLES12-SP1 some pieces of the
update-alternatives get not cleaned up correctly. Remove those before
installing the new postgresql packages.
(See: https://bugzilla.suse.com/show_bug.cgi?id=964254)
=> Remove update-alternatives leftover pieces (bnc#964254)

chef/cookbooks/tempest/recipes/config.rb
This reverts commit 2d27de339d69f5a6ea938d38632563e0e3994d76.
=> Revert "tempest: Temporary disable manila tests"

chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/templates/default/keystone.conf.erb
Removing the public endpoint fixes the issue of mismatched endpoints.
=> Removes public endpoint from keystone conf (bsc#954957)

chef/data_bags/crowbar/migrate/nova/036_rename_nova_roles.rb
When upgrading from tex the nodes do not have the nova element roles assigned.
Because they are in the "crowbar_upgarde" state.  Use the run_list_map
attribute as a search criteria for the nodes instead.
=> Additional fix for rename_nova_roles migration

chef/cookbooks/nova/recipes/compute_ha.rb
This just makes it more readable, and will be better for avoiding random
changes if we move to a LWRP later on.
=> nova: Sort fencing_topology used for compute HA

chef/cookbooks/mysql/attributes/server.rb
ipddress fails, needs to be node['ipaddress']
=> mysql: Fix undefined attribute 'ipaddress' (bsc#921015)

crowbar_framework/app/models/nova_service.rb
We want to reset sync marks of all clusters, not just the one that might
be in the controller role. Otherwise, we might still get a drift.
=> nova: Reset sync marks of clusters that are in compute roles

chef/cookbooks/postgresql/recipes/db_restore.rb, chef/cookbooks/postgresql/recipes/server.rb
Does not remove database dump even after restore and creates file to indicate successful restore.
=> Keeps postgresql dump even after restore

chef/data_bags/crowbar/migrate/ceilometer/023_rename_ceilometer_cagent_role.rb
When upgrading from tex the nodes do not have the ceilometer element roles assigned,
because they are in the "crowbar_upgarde" state.
Use the run_list_map attribute as a search criteria for the nodes instead.
Based on https://github.com/crowbar/crowbar-openstack/pull/259. I didn't test it...
=> Additional fix for renaming ceilometer roles during upgrade

chef/cookbooks/nova/templates/default/nova.conf.erb
Another regession from the big nova.conf update :-(
=> Fix nova not using a glance SSL regression

chef/cookbooks/nova/recipes/compute_ha.rb
All services are indeed required because nova-evacuate will trigger nova
instances to be spawned. And that indeed requires a lot of services.
And we're actually missing swift-proxy...
=> nova: Remove wrong TODO about nova-evacuate order constraint

chef/cookbooks/neutron/attributes/default.rb
Package was renamed and the correct name is now python-networking-hyperv.
=> neutron: Use correct hyperv package name on SUSE

chef/cookbooks/nova/recipes/compute_ha.rb
If the cluster is used for both controller and compute roles, then it
can happen that the nodes don't have the compute roles yet when
chef-client runs on the controller.
Here we don't do a search but really look at the roles attribute, and
this means that we need more than the role being set to the node through
the "crowbar-$node" role, which generally requires chef-client to run.
And that chef-client run would be in the second batch of apply_role
(compute roles), while the exception will be raised from the first batch
(controller role).
=> nova: Move from exception to log message when compute HA can't be setup

chef/cookbooks/horizon/recipes/server.rb
"syncdb" has been deprecated in favor of "migrate" with recent Django releases.
Also "syncdb" didn't work correctly when run on a database migrated from an
older release. See https://docs.djangoproject.com/en/1.8/ref/django-admin/ for
details.
=> Switch from syncdb to migrate for Django database

chef/cookbooks/neutron/recipes/common_config.rb, chef/cookbooks/neutron/templates/default/neutron.conf.erb
All others were / are still using tenant_name, and there seems
to be a caching bug in the chef server with the tenant_id that
we're still investigating. This is a workaround until that bug
is fixed.
=> Switch to using the tenant_name for now in the neutron cookbook

chef/cookbooks/manila/templates/default/manila.conf.erb, chef/data_bags/crowbar/migrate/manila/014_generic_required_keys.rb, chef/data_bags/crowbar/template-manila.json, chef/data_bags/crowbar/template-manila.schema, crowbar_framework/app/models/manila_service.rb
The default proposal has a generic backend with no password nor key;
however, the UI makes you believe that a password is set (it actually
displays "undefined").
To have this work, we need to change the validation to not check that
there's one attribute between password and key, but also to check that
there's one non-empty attribute.
cc @toabctl
=> manila: Fix default proposal for generic backend

chef/cookbooks/nova/recipes/database.rb
When upgrading from juno to kilo, after running the db migrations the flavor
information for instance had be migrated using the "nova-manage db
migrate_flavor_data" tool. As we're upgrading directly from juno to liberty we
need execute this step else. Because of this the actually db migration step is
now split into three steps:
1. Run db migrations up to kilo
2. run flavor migration tool
3. Run the rest of the db migrations
To have this working a patched nova is needed (migrate_flavor_data forward
ported from kilo to juno).
=> Run flavor migration tool when upgrading from juno

chef/cookbooks/openstack-database/recipes/api.rb, chef/cookbooks/openstack-database/templates/default/api-paste.ini.erb, chef/cookbooks/trove/recipes/default.rb
The keystone configuration in api-paste.ini was missing the insecure
bit.
=> trove: Fix to work with insecure ssl

chef/data_bags/crowbar/migrate/ceilometer/023_rename_ceilometer_cagent_role.rb
There can be multiple nodes with the ceilometer-cagent role. Update all of them
not only the first.
=> Fix ceilometer role renaming for HA

chef/cookbooks/crowbar-openstack/libraries/helpers.rb, chef/cookbooks/keystone/libraries/helpers.rb
We use a cache to avoid querying the same data again and again over the
network. However that cache is surviving chef-client runs inside the
chef-client daemon (since they're all in the same process).
So it needs to be invalidated for each chef-client run at some point. We
use the ohai time as a marker that lets us know if the cache is for the
current run or from a previous run (since ohai time is updated at the
beginning of each run, in the deployer cookbook).
https://bugzilla.suse.com/show_bug.cgi?id=966214
cc @dirkmueller
=> keystone, openstack: Invalidate caches for each chef run (bsc#966214)

chef/cookbooks/nova/recipes/neutron.rb
https://bugzilla.suse.com/show_bug.cgi?id=966690
=> nova: Skip neutron configuration on VMware compute nodes (bsc#966690)

chef/cookbooks/cinder/templates/default/cinder.conf.erb
See https://bugs.launchpad.net/nova/+bug/1361360 for the full
story.
=> Avoid greenthreads hanging endlessly on "slowloris" attack

chef/cookbooks/postgresql/recipes/db_restore.rb, chef/cookbooks/postgresql/recipes/server.rb
The file check in the condition for including the restore recipe happened in
the compile phase of chef-client and because of that it failed on the first
iteration in an HA setup (fs-postgresql isn't running at that time).
So we turn those checks into an only_if condition on the resource that actually
does the restore.
Also the ".restored-ok" file is now created only on explicit notification of
the restore resource, as now the recipe might be include also when the restore
step is not being executed.
https://bugzilla.suse.com/show_bug.cgi?id=966575
=> Fix postgresql restore only occuring on 2nd chef-client run (bsc#966575)

chef/cookbooks/ceilometer/recipes/common.rb, chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
Ceilometer in Liberty is hardcoded to request a v2 authentication
token with "tenantName", which does not exist anymore in v3 (it is now
projectName). Pass in a v2 url to workaround the problem.
=> Query polling meters only via Keystone v2

crowbar_framework/app/models/nova_service.rb
This revert partially commit 6b20c0b
=> nova: Revert vmware compute nodes don't need direct access to networking

chef/cookbooks/nova/recipes/neutron.rb
This reverts commit 5ff33ee4f720c7e9deed45bfe4be7ee2d2c76194.
=> Revert "nova: Skip neutron configuration on VMware compute nodes (bsc#966690)

chef/cookbooks/horizon/templates/default/local_settings.py.erb
Adding this allows to use non-ASCII characters
in config file for openstack-dashboard.
=> Adds encoding (bsc#953786)

chef/cookbooks/glance/templates/default/glance-scrubber.conf.erb
It's not compatible with the v3 API.
Also use the internal IP, not the public one.
https://bugzilla.suse.com/show_bug.cgi?id=966924
=> glance: Use v2.0 auth url for glance scrubber (bsc#966924)

chef/cookbooks/nova/templates/default/libvirtd.conf.erb
When debugging nova problems and setting the debug attribute to true,
also enable libvirtd debugging which can be very useful.
=> nova: Also enable libvirtd debug logs when debug is true

chef/cookbooks/glance/recipes/scrubber.rb
We have /etc/cron.hourly/openstack-glance in the package already.
=> glance: Do not create /etc/cron.d/glance-scrubber on SUSE platforms

chef/cookbooks/neutron/files/default/crowbar-fix-tunnel-networks-mtu, chef/cookbooks/neutron/recipes/network_agents.rb
When upgrading from Juno, we move the MTU advertisement from
/etc/neutron/dnsmasq-neutron.conf (custom dnsmasq config file) to new
settings in configuration files.
However, the MTU for each network is saved in the database and the
database migration from Juno to Liberty just set this to NULL, resulting
in broken MTU.
This is only an issue for networks with a tunnel type. In tex/Juno, we
only had two such possibilities: gre and vxlan (and with ovs only).
We fix this by tweaking the MTU in the database directly and restarting
the DHCP agents, which results in restarting dnsmasq for each network
with the correct settings.
https://bugzilla.suse.com/show_bug.cgi?id=968426
=> neutron: Fix broken MTU for tunnel networks after upgrade (bsc#968426)

chef/cookbooks/ceilometer/attributes/default.rb
The LSB init script is only on SLE11; move to systemd for anything else.
https://bugzilla.suse.com/show_bug.cgi?id=968969
=> ceilometer: Fix RA for mongodb when using HA (bsc#968969)

chef/cookbooks/nova/attributes/default.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/nova/042_disk_allocation_ratio.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml, crowbar_framework/config/locales/nova/en.yml
We allow setting the disk_allocation_ratio option, like we do for the
cpu and ram options.
=> nova: Allow overcommitting disk when spawning instances

chef/cookbooks/horizon/recipes/ha.rb
We include another recipe, and that recipe might need to do additional
setup that needs to happen on all nodes. So avoid the sync mark here,
and rely on sync marks there.
We keep our "sync" sync mark because it doesn't hurt.
**Goes with https://github.com/crowbar/crowbar-ha/pull/95**
=> horizon: Do not protect apache HA setup with wait/create sync marks

chef/cookbooks/ceilometer/attributes/default.rb
The LSB init script is only on SLE11; move to systemd for anything else.
https://bugzilla.suse.com/show_bug.cgi?id=968969
(cherry picked from commit 05b4f21a0cc469cf21e0291d59d63cf376ed8ca4)
Backport of https://github.com/crowbar/crowbar-openstack/pull/315
=> [3.0] ceilometer: Fix RA for mongodb when using HA (bsc#968969)

crowbar_framework/config/locales/nova/en.yml
Regex to match the name of a datastore.
This was reported to documentation too
https://github.com/SUSE-Cloud/doc-cloud/pull/15
=> nova proposal UI: Change Datastore Name

crowbar_framework/config/locales/nova/en.yml
Regex to match the name of a datastore.
(cherry picked from commit b7fa3b2c4e11af6867e19fee7e343ccb806a4e74)
=> [3.0] nova proposal UI: Change Datastore Name

Gemfile
This change is needed due to the incompatibility with rake 11.0.0.
=> Set rake to version to 10.3.2

chef/cookbooks/neutron/libraries/helpers.rb
The neutron cookbook created an inconsistent physnet configuration for
ml2_conf.ini and openvswitch_agent.ini for setups that didn't need the
"nova_fixed" interface enabled (i.e. no "vlan" type driver) and where
"use_vlan" was disabled for the "nova_floating" network.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=969877
=> Fix physnet mapping for non-vlan setups (bsc#969877)

chef/cookbooks/nova/templates/default/nova.conf.erb
So yes, booting docker instance works. Thanks to @vuntz for spotting this.
=> Do not set virt_type for docker (bnc#968656)

chef/cookbooks/nova/templates/default/nova.conf.erb
(cherry picked from commit bf1d96dae20c579c45aef24357223e9dc3cb6181)
=> [3.0] Do not set unsupported virt_type values (bnc#968656)

chef/cookbooks/nova/attributes/default.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/nova/042_disk_allocation_ratio.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml, crowbar_framework/config/locales/nova/en.yml
We allow setting the disk_allocation_ratio option, like we do for the
cpu and ram options.
(cherry picked from commit 0613c81dcef4b5c04f6622536ce2914d24de8868)
Backport of https://github.com/crowbar/crowbar-openstack/pull/311
=> [3.0] nova: Allow overcommitting disk when spawning instances

chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb
Neutron already substracts the overhead caused by tunnels (length of
tunnel headers), so no need to put a lower value.
cc @abel-navarro @rossella
=> neutron: Set path_mtu to 1500 and not 1400 for tunnel types

chef/cookbooks/horizon/recipes/ha.rb
We include another recipe, and that recipe might need to do additional
setup that needs to happen on all nodes. So avoid the sync mark here,
and rely on sync marks there.
We keep our "sync" sync mark because it doesn't hurt.
(cherry picked from commit 99ebd719147db0b1da7ded054ca2bb3eb9e83d06)
Backport of https://github.com/crowbar/crowbar-openstack/pull/316
**Goes with https://github.com/crowbar/crowbar-ha/pull/96**
=> [3.0] horizon: Do not protect apache HA setup with wait/create sync marks

chef/cookbooks/glance/recipes/cache.rb, chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/cookbooks/glance/templates/default/glance-cache.conf.erb, chef/cookbooks/glance/templates/default/glance-scrubber.conf.erb
Backport of https://github.com/crowbar/crowbar-openstack/pull/306
=> [3.0] glance: Fix glance-scrubber to work with insecure SSL for keystone

chef/cookbooks/neutron/libraries/helpers.rb
The neutron cookbook created an inconsistent physnet configuration for
ml2_conf.ini and openvswitch_agent.ini for setups that didn't need the
"nova_fixed" interface enabled (i.e. no "vlan" type driver) and where
"use_vlan" was disabled for the "nova_floating" network.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=969877
(cherry picked from commit 4dfb6729816dfe2ce5bd26088947d6732f5b2cea)
=> [3.0] Fix physnet mapping for non-vlan setups (bsc#969877)

chef/cookbooks/neutron/attributes/default.rb
https://github.com/SUSE-Cloud/cookbook-openstack-network/pull/1 adds retry logic to `neutron-ha-tool` so that it will not fail immediately if there are problems talking to the `neutron-server` API.  Therefore we need to give neutron-ha-tool enough time to have a decent chance of succeeding if the `neutron-server` still needs a while to recover after some kind of failover.
https://bugzilla.suse.com/show_bug.cgi?id=965886
=> increase neutron-ha-tool start timeout to 120s (bsc#965886)

chef/cookbooks/crowbar-openstack/libraries/helpers.rb, chef/cookbooks/keystone/libraries/helpers.rb
This makes it more obvious why cache invalidation is being triggered...
and AFAICS, `ohai_time` gets updated more than once per run, so the cache gets invalidating too often, although this is obviously not a huge issue.  I even saw `ohai_time` go backwards within the run!?
Continuation of #281.
=> Log which barclamp we're invalidating the caches on behalf of

chef/cookbooks/neutron/attributes/default.rb
https://github.com/SUSE-Cloud/cookbook-openstack-network/pull/1
adds retry logic to neutron-ha-tool so that it will not fail
immediately if there are problems talking to the neutron-server
API.  Therefore we need to give neutron-ha-tool enough time
to have a decent chance of succeeding if the neutron-server
still needs a while to recover after some kind of failover.
https://bugzilla.suse.com/show_bug.cgi?id=965886
(cherry picked from commit 55504e2e8ccfb23abb8a6b5b31e4ff7ef99e911b)
backport of https://github.com/crowbar/crowbar-openstack/pull/344
=> [3.0] increase neutron-ha-tool start timeout to 120s (bsc#965886)

chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/heat/templates/default/heat.conf.erb, chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb, chef/data_bags/crowbar/migrate/heat/100_add_trusts_delegated_roles.rb, chef/data_bags/crowbar/template-heat.json, chef/data_bags/crowbar/template-heat.schema
This commit exposes the previously hardwired trusts_delegated_roles
setting in the Heat barclamp. This allows setting
trusts_delegated_roles to `Member` which is more useful than the
previous hardwired setting of `heat_stack_owner` (the latter will have
to be assigned to each user manually, while most users already have
the former).
trusts_delegated_roles will default to:
* `Member` for new installations
* `heat_stack_owner` for existing installations, so as not to break
SUSE Cloud installations that have assigned heat_stack_owner to all
users manually.
In addition to exposing this setting it also uses its value for
assigning the roles required for using Heat to
* the admin user
* the unprivileged account created for Tempest's use
and sets the Tempest setting `stack_owner_role`. …
=> Expose trusts_delegated_roles in Heat barclamp

chef/cookbooks/cinder/templates/default/cinder.conf.erb
They were not using the right service name for nova.
=> cinder: Fix nova catalog info settings

chef/cookbooks/ceilometer/recipes/mongodb.rb, chef/cookbooks/ceilometer/recipes/server_ha.rb, chef/cookbooks/cinder/recipes/controller_ha.rb, chef/cookbooks/glance/recipes/ha.rb, chef/cookbooks/heat/recipes/ha.rb, chef/cookbooks/keystone/recipes/ha.rb, chef/cookbooks/manila/recipes/controller_ha.rb, chef/cookbooks/neutron/recipes/network_agents_ha.rb, chef/cookbooks/neutron/recipes/server_ha.rb, chef/cookbooks/nova/recipes/compute_ha.rb, chef/cookbooks/nova/recipes/controller_ha.rb, chef/cookbooks/swift/recipes/proxy_ha.rb
By default, Pacemaker clones aren't interleaved.  This means that if
Pacemaker wants to restart a dead clone instance, and there is an order
constraint on that clone, it will do the same restart on all other
nodes, even if all the others are healthy.
More details on interleaving are here:
https://www.hastexo.com/resources/hints-and-kinks/interleaving-pacemaker-clones/
This behaviour is far more disruptive than we want.  For example, in
https://bugzilla.suse.com/show_bug.cgi?id=965886
we saw that when a network node dies and Pacemaker wants to stop the
instance of cl-g-neutron-agents on that node, it also stops and restarts
the same clone instances on the healthy nodes.  This means there is a
small window in which there are no neutron agents running anywhere.  If
neutron-ha-tool attempts a …
=> [3.0] interleave Pacemaker clones to minimise disruption (bsc#965886)

chef/cookbooks/neutron/files/default/crowbar-fix-tunnel-networks-mtu, chef/cookbooks/neutron/recipes/network_agents.rb
pass database connection uri instead of calculating it
avoids a bug when a node is neutron-network but not neutron-server
https://github.com/crowbar/crowbar-openstack/pull/354
=> [stable/3.0] backport #354

chef/cookbooks/neutron/recipes/network_agents.rb
only in #355 (which is a backport) the issue has been detected
here is the comment https://github.com/crowbar/crowbar-openstack/pull/355#discussion_r58825854
=> fix hound style issue which was not detected previously

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
Defcore guidelines 2016.1 or newer require run_validation to
be enabled for tests that are getting submitted.
=> Enable validation runs for defcore compliance

chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/default/neutron_zvm_plugin.ini.erb, chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
Defcore guidelines 2016.1 or newer require run_validation to
be enabled for tests that are getting submitted.
=> Various Cloud 6.x backports

chef/data_bags/crowbar/migrate/cinder/041_add_rbd_secret_uuid.rb
(cherry picked from commit 4c71ed5827cc214f856badb9ab894ede604dccd0)
Backport of https://github.com/crowbar/crowbar-openstack/pull/369
=> [3.0] cinder: Do not regenerate secret_uuid due to wrong check in migration

chef/cookbooks/ceilometer/recipes/server.rb, chef/cookbooks/cinder/recipes/api.rb, chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/glance/recipes/common.rb, chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/keystone/providers/register.rb, chef/cookbooks/manila/recipes/api.rb, chef/cookbooks/neutron/recipes/api_register.rb, chef/cookbooks/nova/recipes/api.rb, chef/cookbooks/swift/recipes/dispersion.rb, chef/cookbooks/swift/recipes/proxy.rb, chef/cookbooks/swift/templates/default/proxy-server.conf.erb, chef/cookbooks/tempest/recipes/config.rb
Keystone register is modified to generate token from user name and password and all the cookbooks (except Trove and Keystone) use this logic instead of directly using the admin_token. There is a follow-up card to handle bootstrapping for Trove and Keystone cookbooks here https://trello.com/c/ipXUuRQl/1052-adapt-usage-of-keystone-manage-bootstrap-for-bootstrapping-keystone-service.
co-authored with @rhafer
=> Avoid usage of admin_token in cookbooks

chef/cookbooks/ceilometer/attributes/default.rb, chef/cookbooks/ceilometer/recipes/central.rb, chef/cookbooks/ceilometer/recipes/central_ha.rb, chef/data_bags/crowbar/migrate/ceilometer/101_bring-central-role-back.rb, chef/data_bags/crowbar/template-ceilometer.json, chef/roles/ceilometer-agent.rb, chef/roles/ceilometer-central.rb, chef/roles/ceilometer-polling.rb, chef/roles/ceilometer-server.rb, crowbar_framework/app/models/ceilometer_service.rb
ceilometer-polling service will be used as the one being executed by central/compute/ipmi services with different arguments.
This needs to go together with https://build.opensuse.org/request/show/397382
Relevant documentation: 
- http://specs.openstack.org/openstack/ceilometer-specs/specs/kilo/merge-compute-and-central-agents.html
- http://docs.openstack.org/developer/ceilometer/architecture.html
- http://docs.openstack.org/admin-guide/telemetry-data-collection.html
=> Do not use polling as a role, bring central role back.

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
* config_drive is disable for the blkid test
* run_validation is disable for the hard reset test
(cherry picked from commit 6fd6e480427ca24db50310a3e3aa03f5c74714dc)
=> Docker: disable config_drive and run_validation

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
Tempest fails randomly is some tests when reset the VMs and try
to connect to it via SSH. `remote_client.RemoteClient` use
`CONF.validation.ssh_timeout` and `CONF.validation.connect_timeout`
to configure the timeouts for ssh connections.
=> tempest: increase validation TO for XEN

chef/cookbooks/nova/attributes/default.rb, chef/cookbooks/nova/templates/default/nova.conf.erb
Since mitaka, nova has a second DB for the API. We already setup the DB
but the chef attributes were not there yet.
This is similar to what we already do for the other nova db.
=> Add missing nova Api DB attributes

chef/cookbooks/heat/templates/default/heat.conf.erb
When using the WaitCondition resource in Heat the
{ get_attr: ['wait_handle', 'curl_cli'] }
call will return a internal URL as endpoint not a public one.
Since those handles are used to trigger handles from inside the instance,
the internal IP in such cases is usually not usable.
https://bugs.launchpad.net/openstack-ansible/+bug/1459414
=> Fix Heat WaitCondition URL points to internalURL Endpoint (bug#1459414)

chef/cookbooks/swift/recipes/dispersion.rb
The execute statement calling "swift-dispersion-populate" hangs
so add a timeout as workaround for now.
=> swift: Add timeout when running swift-dispersion-populate

.mention-bot
This is just a test setup for https://github.com/facebook/mention-bot but it's hopefully close to what we would want as a final configuration, although obviously we would probably want to add many more entries for all the OpenStack components and the team members working on them.
See https://github.com/facebook/mention-bot#configuration for more detail on the meaning of the configuration options.
Extended glob syntax is used; see https://github.com/facebook/mention-bot/issues/140
=> first attempt at setting up mention-bot

chef/cookbooks/heat/recipes/server.rb
It's a fix for current ugly code, which would rather require rewrite... but still we might want to have this as a quick fix.
UPDATE: Cloud6 is fine, it's using `--os-token` with `--os-url`
=> Fixed os-auth-url argument to openstack command

.mention-bot
A PR could be updated via a git push, in which case github will send a PR event of type `synchronize` to the webhook.  We want the mention-bot to react to this, because the push probably introduces new changes which might require additional reviewers.
This also makes testing the bot easier :-)
There appears to be little documentation covering exactly when `synchronize` is invoked, but there is this, at least:
https://developer.github.com/v3/activity/events/types/#pullrequestevent
=> trigger mention-bot on PR "synchronize" events

Gemfile, Rakefile
Since we switched to SLE12 we can use the faster uglifier which uses NodeJS.
=> Switch from closure-compiler to uglifier

chef/cookbooks/nova/recipes/compute.rb
The package only exists in SLE12 SP2 or later.
=> nova: Fix regression on SLE12 SP1 due to qemu-ovmf-x86_64

chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/cookbooks/glance/templates/default/glance-swift.conf.erb
This seems to be required now with keystone v3, as glance is unable to
authenticate with swift without specifying the domain.
=> glance: Put swift config in /etc/glance/glance-swift.conf

chef/cookbooks/nova/recipes/compute.rb
openSUSE and SLES12SP2 use the module shipped with upstream kernel.
See https://github.com/crowbar/crowbar-core/pull/517
=> nova: Only install openvswitch-kmp-xen on SLE 12 <= SP1

bin/crowbar_magnum
Adding crowbar_magnum back to avoid dirty hacking in automation script to do crowbarctl actions only for magnum. Its easier to remove a file in bin/ folder than cleaning up hacks in automation scripts. We should remove all bin/ files in one go when we update automation to completely use crowbarctl based comands for deployment. Until then IMO its better to have these redundant files even for new barclamps to ensure automation and CI can be run for the new features. 
Here is a trello card to keep track of crowbarctl changes.
https://trello.com/c/lZouEfeR/1108-use-crowbarctl-in-automation-setup-and-remove-all-obseleted-bin-crowbar-files
=> Re-add crowbar_magnum until crowbarctl is fixed

crowbar_framework/app/models/database_service.rb, crowbar_framework/app/models/rabbitmq_service.rb
ChefObject.cloud_domain got moved to Crowbar::Settings.domain.
Needed because https://github.com/crowbar/crowbar-core/pull/519 was merged.
=> crowbar: Update for Crowbar::Settings.domain new API

chef/cookbooks/magnum/recipes/common.rb, chef/cookbooks/magnum/templates/default/magnum.conf.erb
Magnum API should listen on "0.0.0.0" and port "9511" otherwise we will get following stacktrace:
/var/log/magnum/magnum-api.log
```
2016-07-05 11:44:28.621 6512 CRITICAL magnum [-] ConfigFileValueError: Value for option host is not valid: public.d52-54-77-77-77-01.virtual.cloud.suse.de is not IPv4 or IPv6 address
2016-07-05 11:44:28.621 6512 ERROR magnum Traceback (most recent call last):
2016-07-05 11:44:28.621 6512 ERROR magnum   File "/usr/bin/magnum-api", line 10, in <module>
2016-07-05 11:44:28.621 6512 ERROR magnum     sys.exit(main())
2016-07-05 11:44:28.621 6512 ERROR magnum   File "/usr/lib/python2.7/site-packages/magnum/cmd/api.py", line 46, in main
2016-07-05 11:44:28.621 6512 ERROR magnum     host, port = cfg.CONF.api.host, cfg.CONF.api.port
2016-07-05 11:44:28.621 6512 ERROR …
```
=> [magnum] Fix Magnum API host and port options

crowbar_framework/app/models/magnum_service.rb
This fixes:
Failed to apply the proposal: exception before calling chef (undefined
method `role_expand_elements' for #)
=> magnum: Use PacemakerServiceObject class

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
This needs to be fixed when the tempest tests pass. But
for now we want to add the tests to the packages but don't run them.
=> tempest: Disable aodh and magnum tempest tests for now

chef/cookbooks/tempest/recipes/config.rb
Run the tempest tests from the Alarming plugin when Aodh is deployed.
=> tempest: Enable aodh tests

chef/cookbooks/nova/attributes/default.rb, chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/cookbooks/nova/templates/default/suse-vendor-data.json.erb, chef/data_bags/crowbar/migrate/nova/102_nova_add_metadata_vendordata.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/models/nova_service.rb, crowbar_framework/config/locales/nova/en.yml
Create a vendordata.json file which will be served through the metadata
server to the guest VM.
This vedordata.json contains some information about a possible SMT server.
The provided information is then used by the SUSE guest images to automatically
configure the repositories for the guest.
This is based on a solution the public cloud team is already using.
=> nova: Allow some SUSE specific vendordata

.mention-bot
as we don't have any contributors outside the SUSE org it does not
make sense to mention people that haven't contributed for a long
time.
This prevents spamming for now, and if crowbar grows to form an
infrastructure for a wider community we can adapt the list again.
Main reason for this change is to stop spamming non-active
contributors.
=> [mention-bot] only mention SUSE employees for now

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb, chef/data_bags/crowbar/migrate/tempest/100_add_magnum_options.rb, chef/data_bags/crowbar/template-tempest.json, chef/data_bags/crowbar/template-tempest.schema
The tempest tests for magnum need a couple of configuration options.
Add theses options and use sane defaults.
=> tempest: Configure and enable magnum tests

chef/data_bags/crowbar/migrate/ceilometer/023_rename_ceilometer_cagent_role.rb, chef/data_bags/crowbar/migrate/ceilometer/024_bring-central-role-back.rb
When we are reinstalling packages from cloud5 to cloud6, ceilometer-polling role is not even installed, thus the migration fails.
I did not test it, and it might be completely wrong...
=> Check carefully if the role we are renaming is actually present

chef/cookbooks/keystone/libraries/helpers.rb, chef/cookbooks/keystone/recipes/server.rb, chef/data_bags/crowbar/migrate/keystone/100_non_admin_user_create_flag.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema, crowbar_framework/app/models/tempest_service.rb, crowbar_framework/app/views/barclamp/keystone/_edit_attributes.html.haml, crowbar_framework/config/locales/keystone/en.yml, crowbar_framework/config/locales/tempest/en.yml
This adds the option "Create Regular User" to the barclamp UI and respective handling in the keystone cookbook. See: https://trello.com/c/lF2pdHYl/21-3-make-creation-of-non-admin-user-in-keystone-barclamp-optional
=> added toggle to disable creation of non-admin user

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb, chef/data_bags/crowbar/migrate/neutron/100_add_tunnel_csum.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
As per http://openvswitch.org/pipermail/dev/2015-August/059335.html enabling tunnel_csum on the openvswitch agents may boost the network performance by a huge margin.
=> Add tunnel_csum attribute to neutron barclamp

chef/cookbooks/tempest/recipes/config.rb
Currently the tests are disabled in the package but we want to enable
the tests in the package and disable them there to have gating when we
reenable the tests (with a revert PR for this PR).
=> manila: Disable tempest tests for now

chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb
For Layer 2 traffic, neutron needs to know the segment_mtu to correctly
calculate the the MTU of networks. The `mtu_value` has to match the MTU values
of the physical interfaces.
=> Add segment_mtu setting for neutron

chef/cookbooks/neutron/recipes/common_config.rb, chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb, chef/cookbooks/neutron/templates/default/neutron.conf.erb
Neutron correctly subtracts the GRE or VXLAN overheads and the MTU for Neutron
routers can be set to the MTU of the underlying NIC.
Forward port of https://github.com/crowbar/crowbar-openstack/pull/411.
=> bsc# 984128: Match MTU values of VLAN and Neutron ml2

chef/cookbooks/tempest/recipes/config.rb
Tests are now enabled in the package so let's enable the tests here, too.
This reverts commit 0ceb7e2e4ce0a0207608e737516d707884471517.
=> Revert "manila: Disable tempest tests for now"

chef/cookbooks/swift/libraries/rack_awareness.rb
It looks like some network interfaces might miss addresses key on SP2.
=> Check addresses only when they exist

chef/cookbooks/magnum/templates/default/magnum.conf.erb, chef/data_bags/crowbar/migrate/magnum/100_add_cert_manager_attribute.rb, chef/data_bags/crowbar/template-magnum.json, chef/data_bags/crowbar/template-magnum.schema, crowbar_framework/app/helpers/barclamp/magnum_helper.rb, crowbar_framework/app/models/magnum_service.rb, crowbar_framework/app/views/barclamp/magnum/_edit_attributes.html.haml, crowbar_framework/config/locales/magnum/en.yml
* Adds dropdown to select cert_manager_type in magnum.
* Makes barbican the default cert_manager_type if barbican
is present else defaults to local.
=> Adds cert_manager option to magnum

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/recipes/server.rb
This was a workaround for a HA issue, but the HA issue was actually
broken ordering of HA resources (see
f5e6477147533a4f6aeddcfcdbb6e6d0cf5d1f0c)
So we should be able to enable l2pop by default.
This reverts commit 92a316a639acc1004e930a371fe53b76c3fc95af.
=> Revert "neutron: Disable l2pop mechanism unless DVR is enabled"

chef/cookbooks/horizon/templates/default/local_settings.py.erb
When launching windows instances, there is no ssh and no public key can be
injected via cloud-init. But cloud-init for windows can generate a password
and expose that. The nova CLI already can get th password via
"nova get-password" and the same option is now enabled via the web UI.
Note: The password is sill encrypted with the public ssh key so when getting the
password you need to provide the private ssh key to decrypt the password.
=> horizon: Enable password retrieve option

chef/cookbooks/nova/recipes/compute.rb
We recently added newer libvirt packages to our CI and we still use
SLES12SP1 so we need to start virtlogd now also for suse-12.1.
This commit should be reverted once we did the switch to SLE12SP2.
=> nova: Start virtlogd also for SLES 12.1 platform

chef/cookbooks/magnum/recipes/api.rb
When creating a bay, magnum expects a endpoint without a trailing
slash. Otherwise you get a 404 response when trying to get a
certificate and the error in the instance is:
File "/var/lib/cloud/instance/scripts/part-004", line 138, in
write_server_cert
fp.write(csr_resp.json()['pem'])
KeyError: 'pem'
=> magnum: Remove trailing slashes from endpoints

crowbar_framework/app/models/ceilometer_service.rb, crowbar_framework/app/models/cinder_service.rb, crowbar_framework/app/models/database_service.rb, crowbar_framework/app/models/glance_service.rb, crowbar_framework/app/models/heat_service.rb, crowbar_framework/app/models/horizon_service.rb, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/app/models/magnum_service.rb, crowbar_framework/app/models/manila_service.rb, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/app/models/nova_service.rb, crowbar_framework/app/models/rabbitmq_service.rb, crowbar_framework/app/models/swift_service.rb, crowbar_framework/app/models/tempest_service.rb, crowbar_framework/app/models/trove_service.rb
This will be needed once we switch to SP2 as default architecture for nodes
=> Enable role deployment for SLES12SP2 only

chef/cookbooks/keystone/libraries/helpers.rb
For now (as we still use v2 to create users) this will always be "Default". But
by defining it here we can avoid having the hardcoded value spread out through
all the other cookbooks.
=> Added user and admin domain to keystone settings

chef/cookbooks/nova/recipes/compute.rb, chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/nova/103_add_migration_network.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/models/nova_service.rb, crowbar_framework/config/locales/nova/en.yml
Right now, live migration is being done only on the admin network.
However, the admin network might be on a 1G interface, while some other
network might be defined with 10G interface. It'd be better to use such
a network for live migration, to speed up things.
We add a new attribute to specify which network to use.
It's important to keep in mind that the public network is not
appropriate here, as it would make the compute nodes publicly reachable,
and libvirt listen on the public IP. So it's better to define a new
private network, or use an existing one like the storage network.
=> nova: Allow defining on which network live migration happens

chef/data_bags/crowbar/migrate/keystone/101_update_default_attributes.rb
https://github.com/crowbar/crowbar-openstack/pull/482 contains some errors, this should fix them.
While some are just typos, I was really confused by `user_enabled_emulaton_use_group_config`. Is it something that was originally part of PR 482, and deleted before merging?
=> Fix errors introduced by last migration

chef/cookbooks/keystone/recipes/server.rb
Adding missing --os-project-name option to get a scoped token. Use
--os-auth-url instead of --os-url. --os-url is only relevant when
authenticating with an already existing token). This broke when we switched
away from using the admin token for authentication.
=> keystone: Fix openstack command line options

chef/cookbooks/cinder/attributes/default.rb, chef/cookbooks/cinder/recipes/volume.rb, chef/cookbooks/cinder/recipes/volume_ha.rb, chef/cookbooks/cinder/templates/default/cinder-volume.conf.erb, crowbar_framework/app/models/cinder_service.rb, crowbar_framework/config/locales/cinder/en.yml
We cannot do active/active at the moment because there needs to be some
synchonization between the various volume services in that case.
But it turns out that active/passive is relatively easy to achieve: it's
only a matter of making sure that the cinder-volume service on the
various cluster members register with the same host. We use the
vhostname of the cluster for this.
Of course, it doesn't work with the LVM backend, so we have validation
checks for this in Crowbar.
Another restriction is that we cannot use the same cluster for
cinder-controller and cinder-volume: due to the use of the same host in
the config, if we were to allow cinder-controller there too, only one
cinder-scheduler service would be register (with the vhostname of the
cluster), which is wrong in this case.
=> cinder: Allow to use a HA cluster for cinder-volume in active/passive

chef/cookbooks/nova/recipes/compute.rb
This only exists on platforms for which ceph exists, which is
aarch64 and x86_64 right now.
=> Skip installation of qemu-block-rbd on s390x

crowbar_framework/app/models/trove_service.rb
Allocate a public IP in the Trove barclamp so it will also work if it is
deployed on a standalone machine without other barclamps. Without this code it
won't work if it is deployed to a machine that doesn't have at least one other
barclamp assigning a public IP.
Note: since this commit adds a apply_role_pre_chef_call() function to the Trove
barclamp's model it also contains commented HA code to make enabling HA for
Trove easier later on.
=> Add public IP allocation

.hound.ruby.yml
Same as https://github.com/crowbar/crowbar/pull/2267 but for crowbar-openstack
=> Fix rubocop ruby version

chef/cookbooks/heat/templates/default/heat.conf.erb
We would like to change endpoints on publicURL for Heat
and Magnum clients. This will be used by OS::Heat::WaitCondition
resource and wc_notify.
=> Heat: Change clients endpoints on publicURL

chef/cookbooks/nova/recipes/availability_zones.rb
On s390x this can easily take 30s due to the slowness of the test
environment (constantly swapping).
=> Raise timeout value for setting availability zone

chef/cookbooks/barbican/recipes/keystone-listener.rb
Otherwise starting aborts and the barclamp apply fails
=> Only start barbican-keystone-listener when enabled

chef/cookbooks/swift/recipes/dispersion.rb, chef/cookbooks/swift/recipes/proxy.rb
switf-proxy can be configured with keystone auth. Paste will try
to load the authtoken filter_factory, that resides in the package
python-keystonemiddleware.
Without this package, the service proxy-swift will fail to load
with an error:
ImportError: No module named keystonemiddleware.auth_token
=> swift: install keystonemiddleware package in case of keystone auth

bin/crowbar_sahara, chef/cookbooks/sahara/README.md, chef/cookbooks/sahara/attributes/default.rb, chef/cookbooks/sahara/definitions/sahara_service.rb, chef/cookbooks/sahara/libraries/helpers.rb, chef/cookbooks/sahara/metadata.rb, chef/cookbooks/sahara/recipes/api.rb, chef/cookbooks/sahara/recipes/common.rb, chef/cookbooks/sahara/recipes/engine.rb, chef/cookbooks/sahara/recipes/ha.rb, chef/cookbooks/sahara/recipes/role_sahara_server.rb, chef/cookbooks/sahara/recipes/sql.rb, chef/cookbooks/sahara/templates/default/sahara-rootwrap.erb, chef/cookbooks/sahara/templates/default/sahara.conf.erb, chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/recipes/install.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb, chef/data_bags/crowbar/template-sahara.json, chef/data_bags/crowbar/template-sahara.schema, chef/roles/sahara-server.rb, crowbar_framework/app/controllers/sahara_controller.rb, crowbar_framework/app/models/sahara_service.rb, crowbar_framework/app/views/barclamp/sahara/_edit_attributes.html.haml, crowbar_framework/config/locales/sahara/en.yml, sahara.yml
This is basically https://github.com/crowbar/crowbar-openstack/pull/365 fixed and improved upon.
=> Add Sahara barclamp

crowbar_framework/app/models/nova_service.rb
KVM support was implemented in s370 Second Edition, so anything
s390 or newer supports it.
aarch64 also has no feature flag to disable KVM
=> aarch64/s390x always support KVM

chef/cookbooks/sahara/recipes/common.rb, chef/cookbooks/sahara/templates/default/sahara-rootwrap.erb
There's no need to override the sudoers file from the package. We
also use the package provided file for the other services.
=> sahara: Use sudoers file from package

chef/cookbooks/neutron/libraries/helpers.rb
We're using the Barclamp::Inventory.Network class now.
Note: Barclamp::Inventory.Network.interface() returns the interface name
including the vlan tag if use_vlan is true for the network while
Barclamp::Inventory.Network.lookup_interface_info didn't include it.
This is not a real problem for "nova_fixed". As "use_vlan" is always set to
"false" when the "nova_fixed" network is enabled on any node (see
NeutronService.rb).
=> neutron: Simplify code to get nova_fixed interface

chef/cookbooks/nova/templates/default/nova.conf.erb
EC2 support has been moved to another project, out of nova.
=> nova: Remove ec2 from enabled_ssl_apis in nova.conf

chef/cookbooks/nova/recipes/config.rb, chef/data_bags/crowbar/migrate/nova/045_add_zvm_xcat_network.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/models/nova_service.rb, crowbar_framework/config/locales/nova/en.yml
This is a backport of: https://github.com/crowbar/crowbar-openstack/pull/530
=> [stable/3.0] nova: Allow to define a custom network for xCAT access (bsc#976778)

chef/cookbooks/swift/recipes/dispersion.rb
extreme workaround to bsc#1003366. Python 2.7.9 and greenlet 0.4.5
produce GIL deadlock in this service. A restart usually resolves the
issue in local testing. This needs to be removed once the bug is
fixed.
=> dispersion: restart swift-proxy service to avoid bsc#1003366

crowbar_framework/config/locales/swift/en.yml
When deploying swift and not enough storage nodes are available, the error
message was:
Need at least as many swift-storage nodes as zones; only %{swift-storage}
swift-storage node was set for 2 zones.
=> swift: Fix variable replacement in error message

chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
Ceilometer 7.0 change the section service_credentials.  If auth_type
is not set, some queries to keytone will use the legacy v2.0 API,
and this cause problems (POST can be blocked in SSL connections).
If we set this value to `password` V3 will be used.
Update `username` parameter to `user-name`, to avoid deprecation
warning.
=> ceilometer: Use auth_type to password (bsc#1001273)

chef/cookbooks/nova/recipes/availability_zones.rb, chef/cookbooks/nova/recipes/compute.rb
There were two places that set availability zones. Set both to the same,
higher timeout to accomodate slowness on s390x
=> Raise availability-zone timeout consistently

chef/cookbooks/neutron/templates/default/10-opflex-agent-ovs.conf.erb
@mfriesenegger identified a fatal error in reading opflex config file. This commit is to fix that and correct few other values.
=> Fix for Fatal error in reading opflex config file

crowbar_framework/app/models/magnum_service.rb
This logic will return nodes for allocation and is not checking if barbican_server exist:
```
if select_nodes_for_role(nodes, "barbican-server", "controller").empty?
base["attributes"][@bc_name][:cert][:cert_manager_type] = "local"
else
base["attributes"][@bc_name][:cert][:cert_manager_type] = "barbican"
end
```
=> Magnum: Partially revert commit 326bd034d81135f40f5b7dfa887d73e973af52ab

chef/cookbooks/manila/templates/default/manila.conf.erb
The settings for the different clients (nova, cinder, neutron) must be
set. Otherwise the manila-share service complains with:
Expecting to find domain in project - the server could not comply with the \
request since it is either malformed or otherwise incorrect. The \
client is assumed to be in error. (HTTP 400)
=> manila: Fix keystone default domain settings

chef/cookbooks/tempest/templates/default/tempest.conf.erb
The tests are currently failing when running a full tempest run.
The tests for personality can not pass because they need an enabled
"inject_partition" in nova.conf .
=> tempest: Disable personality tests

chef/cookbooks/sahara/templates/default/sahara.conf.erb
The keystone helper variable names were wrongly used.
=> sahara: Fill admin_user_domain_name and admin_project_domain_name

crowbar_framework/app/models/nova_service.rb
When deploying Xen and the target platform is not supported, the
warning message used the wrong class.
=> nova: Fix  "undefined method `pretty_target_platform'"

chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/neutron/recipes/server.rb, chef/data_bags/crowbar/migrate/keystone/102_switch_default_frontend.rb, chef/data_bags/crowbar/template-keystone.json
The native frontend (eventlet based) is no longer available and upstream
recommends to use a "real" webserver so use Apache.
=> keystone: Use apache frontend

chef/cookbooks/cinder/attributes/default.rb, chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/cookbooks/nova/attributes/default.rb, chef/cookbooks/nova/recipes/compute.rb, chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/cinder/102_use_multipath.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema
Currently, mulitpath support is set by default in the cinder and
nova cookbooks, and both cookbooks force it to be true, but the
built package overrides nova's setting to false.
Remove that default support, and add a new option to cinder which allows
operators to enable or disable multipath support for both cinder
and nova.
=> Add configuration option for multipath (bsc#997607)

chef/cookbooks/horizon/recipes/server.rb, chef/cookbooks/horizon/templates/default/local_settings.py.erb, chef/data_bags/crowbar/migrate/horizon/100_remove_use_launch_instance_ng.rb, chef/data_bags/crowbar/template-horizon.json, chef/data_bags/crowbar/template-horizon.schema
Made the Angular Launch Instance workflow the default in Horizon.
=> Remove `use_launch_instance_ng` attribute in Horizon

chef/cookbooks/magnum/recipes/api.rb
This commit sets the port used for Magnum's service catalog entries to
`node[:magnum][:bind_port]`, as opposed to the port retrieved from `MagnumHelper`
that was used before this commit. The port retrieved from `MagnumHelper` is the
service's actual listening port, which is incorrect in an HA setting. There,
the endpoint catalog entries must use the port where the haproxy instance
forwarding to the actual service port listens.
=> magnum: Use correct port for endpoint

chef/cookbooks/cinder/attributes/default.rb, chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/cookbooks/nova/attributes/default.rb, chef/cookbooks/nova/recipes/compute.rb, chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/cinder/49_use_multipath.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema
Currently, mulitpath support is set by default in the cinder and
nova cookbooks, and both cookbooks force it to be true, but the
built package overrides nova's setting to false.
Remove that default support, and add a new option to cinder which allows
operators to enable or disable multipath support for both cinder
and nova.
Cherry picked from ab5df7ef6df1d84a33bd41f4473dd58fdd504542.
=> cinder: Add configuration option for multipath (bsc#997607)

chef/cookbooks/crowbar-openstack/libraries/ha_helpers.rb
Make sure that the services supposed to run on controller nodes
do not get started when the node is in pre-upgrade state.
See also https://bugzilla.suse.com/show_bug.cgi?id=1005346
=> Add another constraint to the controller only locati

chef/cookbooks/crowbar-openstack/libraries/ha_helpers.rb
https://github.com/crowbar/crowbar-openstack/pull/562 totally broke HA cluster setup, because when the pre-upgrade node attribute is not present, the location constraints generated by this helper prevent anything useful from running.
So instead we reverse the
pre-upgrade eq false
logic to
pre-upgrade ne true
so that the constraints will *only* prevent resources from running when pre-upgrade is set to true, and not when it isn't set at all.
=> don't break whole cluster when not upgrading

crowbar_framework/app/views/barclamp/sahara/_edit_attributes.html.haml, crowbar_framework/config/locales/sahara/en.yml
To be consistent with the rest of the barclamps, let's not expose debug
and use_syslog on the UI
=> sahara: remove UI widgets

chef/cookbooks/nova/recipes/vncproxy.rb
The service is always started some lines later for suse/rhel
so install the packages before using the service.
=> nova: Install openstack-nova-consoleauth for suse/rhel

chef/data_bags/crowbar/migrate/neutron/100_add_tunnel_csum.rb
Don't touch the tunnel_csum attribute if it already exists before
migration
=> Adjust 100_add_tunnel_csum migration to allow backport

chef/cookbooks/crowbar-openstack/definitions/openstack_pacemaker_controller_location_ignoring_upgrade_for.rb, chef/cookbooks/crowbar-openstack/libraries/ha_helpers.rb, chef/cookbooks/postgresql/recipes/ha_storage.rb, chef/cookbooks/rabbitmq/recipes/ha.rb
DRBD resources need to be running on both (upgraded AND not upgraded) nodes during the upgrade, so DRBD data can be synchronized correctly.
=> keep DRBD running during upgrade

chef/cookbooks/nova/recipes/compute.rb
For the libvirt driver, by default hardware properties will be retrieved from the Glance image and if such haven’t been provided, it will use a libosinfo database to get those values.
=> nova: install libosinfo to provide hardware properties when driver is libvirt

chef/cookbooks/neutron/recipes/network_agents.rb
This reverts commit 208ec23e473ac64a6603f50192254aa327c55c80.
It does not work with Newton. The error (neutron-lbaas.log) on Newton is:
Could not load neutron_lbaas.services.loadbalancer.drivers.haproxy.\
namespace_driver.HaproxyNSDriver
=> Revert "neutron: Fix device_driver for Neutron Lbaas agent"

chef/cookbooks/glance/attributes/default.rb, chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/data_bags/crowbar/migrate/glance/101_remove_conversion_task_api.rb, chef/data_bags/crowbar/template-glance.json, chef/data_bags/crowbar/template-glance.schema
The conversion task API for glance is being deprecated. The PR removes the attributes and tasks related to this service, effectively reverting this PR https://github.com/crowbar/crowbar-openstack/commit/2123499b53c7820c8cb8850a99dfe9d171dfc3a1 as well as migrates the schema
=> glance: remove conversion task api support from glance

chef/cookbooks/cinder/recipes/api.rb, chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/manila/recipes/api.rb, chef/cookbooks/nova/recipes/api.rb, chef/cookbooks/swift/recipes/proxy.rb, chef/cookbooks/trove/recipes/api.rb
Keystone supports $(project_id)s in the catalog. It works the same as $(tenant_id)s. Use of $(tenant_id)s is deprecated and catalog endpoints should be updated to use $(project_id)s.
=> api: replace (tenant_id) with (project_id) in service endpoint registration urls

crowbar_framework/app/models/glance_service.rb, crowbar_framework/app/models/nova_service.rb, crowbar_framework/config/locales/glance/en.yml, crowbar_framework/config/locales/nova/en.yml
crowbar-ceph got recently CephFS support. With that, the instances
running on compute nodes need access to the Ceph cluster to be able
to mount shares.
For that, the default network for ceph client traffic changed to
the public network (set via the "ceph_client" attribute).
See https://github.com/crowbar/crowbar-ceph/commit/4f893f6bbf6c3 for
details about the new ceph_client attribute.
=> nova: Allocate IPs on compute nodes from the ceph_client network

chef/cookbooks/aodh/metadata.rb, chef/cookbooks/barbican/metadata.rb, chef/cookbooks/ceilometer/metadata.rb, chef/cookbooks/cinder/metadata.rb, chef/cookbooks/heat/metadata.rb, chef/cookbooks/horizon/metadata.rb, chef/cookbooks/manila/metadata.rb
Commit 4c24cb3d010e8ec392cfba57ac3c2bd7f087462a was missing updates in
the metadata of the affect cookbooks.
=> Complete renaming of READMEs

chef/cookbooks/cinder/recipes/api.rb
To aid support for API microversions, the Cinder team has decided to up the endpoint of cinder from v2 to v3. The v3 endpoint is similar in functionality to v2, the difference being mainly the introduction of API microversioning support.
=> cinder: register cinder v3 service and endpoint

chef/cookbooks/nova/templates/default/nova.conf.erb
It's deprecated, but actually still required in Mitaka. Without it, when
we do HA for nova, then the console doesn't work.
=> nova: Add back memcached_servers option

chef/data_bags/crowbar/migrate/neutron/102_infoblox_update.rb
when running the bin/rake crowbar:schema_migrate_prod
=> fix undefined method `key?' for nil:NilClass

chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
This fixes:
ERROR ceilometer BadRequest: Expecting to find domain in project - the server \
could not comply with the request since it is either malformed or \
otherwise incorrect. The client is assumed to be in error. (HTTP 400)
from the ceilometer-upgrade.log
=> ceilometer: Set default_domain_{id,name}

chef/data_bags/crowbar/migrate/swift/100_dispersion_states.rb, chef/data_bags/crowbar/template-swift.json
Restart of swift-proxy from dispersion recipe during readying
(introduced by commit 77ec11da5b7db42bedfdd3829234957af1c28011)
could break pacemaker cluster setup.
=> Do not execute dispersion recipe in readying state.

chef/cookbooks/nova/attributes/default.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/nova/108_add_host_mb_reserve.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml, crowbar_framework/config/locales/nova/en.yml
This updated commit should add the Nova Compute RAM/MB reservation. The specified reserved memory will be substracted from the total available memory in ompute hosts by the nova scheduler.
=> Adding reserved_host_memory_mb Parameter for nova

chef/cookbooks/manila/libraries/helpers.rb, chef/cookbooks/manila/recipes/cephfs.rb, chef/cookbooks/manila/recipes/common.rb, chef/cookbooks/manila/recipes/share.rb, chef/cookbooks/manila/templates/default/manila.conf.erb, chef/data_bags/crowbar/migrate/manila/101_add_cephfs_config.rb, chef/data_bags/crowbar/template-manila.json, chef/data_bags/crowbar/template-manila.schema, crowbar_framework/app/helpers/manila_barclamp_helper.rb, crowbar_framework/app/models/manila_service.rb, crowbar_framework/app/views/barclamp/manila/_edit_attributes.html.haml, crowbar_framework/config/locales/manila/en.yml
Manila has a CephFS driver since Mitaka. Allow the usage from Crowbar.
=> manila: Add CephFS driver support

chef/cookbooks/tempest/templates/default/tempest.conf.erb, chef/data_bags/crowbar/migrate/tempest/102_add_more_manila_options.rb, chef/data_bags/crowbar/template-tempest.json, chef/data_bags/crowbar/template-tempest.schema
This is needed to be able to run Manila tempest tests when a
CephFS backend is used.
=> tempest: Allow more settings for Manila tests

chef/cookbooks/nova/templates/default/nova.conf.erb
Option memcached_servers is deprecated in Mitaka. Operators should use oslo.cache configuration instead. Specifically enabled option under [cache] section should be set to True and the url(s) for the memcached servers should be in [cache]/memcache_servers option.
memcached was already enabled. This PR sets the cache to enabled
=> nova: set cache.enabled in nova.conf

chef/cookbooks/magnum/recipes/api.rb
OpenStack Magnum changed service_type name from "container" to "container-infra".
It was done in upstream bug https://bugs.launchpad.net/magnum/+bug/1584251
=> magnum: Rename service_type from "container" to "container-infra" bsc#1010673

chef/cookbooks/aodh/attributes/default.rb, chef/cookbooks/aodh/metadata.rb, chef/cookbooks/aodh/recipes/aodh.rb, chef/cookbooks/aodh/templates/default/apache_aodh.conf.erb, chef/cookbooks/ceilometer/attributes/default.rb, chef/cookbooks/ceilometer/recipes/server.rb, chef/cookbooks/ceilometer/recipes/server_ha.rb, chef/cookbooks/ceilometer/templates/default/apache_ceilometer.conf.erb
The builtin wsgi server in Newton does not read the port setting
from the config file anymore, so any attempt at setting that (which
is needed to be customized for HA) is failing.
=> aodh/ceilometer: put behind apache2

chef/cookbooks/keystone/attributes/default.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/templates/default/apache_keystone.conf.erb, chef/cookbooks/keystone/templates/default/keystone.conf.erb, chef/data_bags/crowbar/migrate/keystone/103_remove_cert_required.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema, crowbar_framework/app/views/barclamp/keystone/_edit_attributes.html.haml, crowbar_framework/config/locales/keystone/en.yml
When using the wsgi apache module we need to enable SSL for it not in
the `keystone.conf` but in apache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crowbar/crowbar-openstack/576)
=> Deploy keystone wsgi mod with SSL

chef/cookbooks/nova/templates/default/nova.conf.erb
Using the daemon mode fails for Xen (see lp#1643457).
This is a workarround until the bug in oslo.rootwrap is fixed.
https://bugzilla.suse.com/show_bug.cgi?id=1010553
=> nova: Use rootwrap daemon mode only for kvm (bsc#1010553)

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb, chef/data_bags/crowbar/migrate/tempest/103_add_heat_options.rb, chef/data_bags/crowbar/template-tempest.json, chef/data_bags/crowbar/template-tempest.schema
The heat tempest plugin does not use the [orchestration] section.
Instead it uses its own config section called [heat_plugin].
So add that section with the needed parameters to the tempest config
template.
=> tempest: Add missing heat_plugin config section

chef/cookbooks/neutron/recipes/network_agents_ha.rb
During the initial post-upgrade chef-client run, network routers
are still present on another node.
We do not want neutron-ha-tool to create new ones automatically, so
we prevent the creation of neutron-ha-tool primitive and hope to handle the situation
manually later.
=> upgrade: Do not start neutron-ha-tool for node in the upgrade state

crowbar_framework/app/helpers/barclamp/magnum_helper.rb
Introduce a new certificate store called x509keypair to magnum.
=> magnum: add x509keycert store option

crowbar_framework/lib/openstack/ha.rb
Fix this error:
Failed to apply the proposal: exception before calling chef
(undefined method `[]' for nil:NilClass)
which was seen when a customer added two new nodes to a network cluster (only running neutron agents and nothing else) and then re-applied the Pacemaker proposal.
https://bugzilla.suse.com/show_bug.cgi?id=1013549
=> fix undefined method [] for nil:NilClass (bsc#1013549)

crowbar_framework/lib/openstack/ha.rb
Backport of #626.
Fix this error:
Failed to apply the proposal: exception before calling chef
(undefined method `[]' for nil:NilClass)
which was seen when a customer added two new nodes to a network cluster (only running neutron agents and nothing else) and then re-applied the Pacemaker proposal.
(cherry picked from commit eea2ba58018fbfeb3bb4beebf22caf2c76987af2)
https://bugzilla.suse.com/show_bug.cgi?id=1013549
=> [3.0] fix undefined method [] for nil:NilClass (bsc#1013549)

chef/cookbooks/horizon/templates/default/local_settings.py.erb, chef/cookbooks/keystone/libraries/helpers.rb
It is no longer necessary to include the version suffix into OPENSTACK_KEYSTONE_URL setting. Thanks to a recent update of django-openstack-auth library as of 2.3.0 release, Horizon will append the proper version suffix to the URL based on the value stored inside OPENSTACK_API_VERSIONS[‘identity’] setting.
=> horizon:  add unversioned keystone endpoint url

chef/cookbooks/swift/attributes/default.rb
With the move of swift from init scripts to systemd units, change
to the systemd: resource.
=> Transition swift to systemd

chef/cookbooks/horizon/recipes/server.rb, chef/data_bags/crowbar/migrate/horizon/101_remove_nova_instance.rb, chef/data_bags/crowbar/template-horizon.json, chef/data_bags/crowbar/template-horizon.schema, crowbar_framework/app/models/horizon_service.rb, horizon.yml
Horizon no longer requires Nova (or Glance) to function; it will run as long as keystone is present (for instance, swift-only deployments).
=> horizon: Do not require other openstack proposals for deployment

chef/cookbooks/nova/recipes/controller_ha.rb
Instead of using the service resource class, use directly systemd.
There may be some problems with the service resource class.
=> nova: Use systemd resource class

chef/cookbooks/barbican/recipes/api.rb
This breaks HA deployment in the CI.
=> barbican: Add missing sync marks when creating service & user

chef/cookbooks/horizon/templates/default/local_settings.py.erb
The horizon dialogs were switched to the Angular based ones
but the corresponding REST api wasn't enabled, which caused
them to fail completely. Resurrect functionality.
=> horizon: Enable REST API for Images

chef/cookbooks/tempest/recipes/config.rb
They eat > 6 hours and fail since most of the functionality
that they depend on isn't there. disable it for now until
it is properly fixed
=> tempest: temporarily disable heat tests

chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/cinder/103_add_keymgr_fixed_key.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema, crowbar_framework/app/models/cinder_service.rb
With this key set in the cinder proposal, volumes casn be encrypted.
Be careful: For *all* volumes the *same* key is used!
=> cinder/nova: Allow setting a fixed-key for encrypted volumes

chef/cookbooks/keystone/metadata.rb, chef/cookbooks/keystone/recipes/memcached.rb, chef/cookbooks/keystone/recipes/role_keystone_server.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/templates/default/keystone.conf.erb
With the move to Apache2 the performance suffered greatly without
a cross-process caching layer. use memcached for this
=> keystone: Enable caching

chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/opensuse/sysconfig.neutron.erb, chef/cookbooks/neutron/templates/suse/sysconfig.neutron.erb
/etc/sysconfig/neutron is no longer supported. Instead use symlinks
to enable/disable specific configs for the neutron-server.
=> neutron: Replace /etc/sysconfig/neutron usage with links

Gemfile
Rake 12.0.0 got released on Dec 6 but our rspec version still uses
removed code.
(cherry picked from commit bf64e908c6d5f4baab001a597bd30de8349185c4)
=> [3.0] travis: Use rake < 12.0.0

chef/cookbooks/sahara/attributes/default.rb
Instead of using the service resource class, use directly systemd.
There may be some problems with the service resource class.
=> sahara: Use systemd resource class

chef/cookbooks/keystone/libraries/helpers.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/trove/templates/default/trove-conductor.conf.erb, chef/cookbooks/trove/templates/default/trove-taskmanager.conf.erb
per barclamp is actually unnecessarily conservative, per keystone
instance is enough. even in the dumb nova-compute node case this
reduces cache misses by factor two.
=> Cache keystone settings per instance not per barclamp

chef/cookbooks/neutron/recipes/common_config.rb
Other nodes (neutron-network, compute) don't need that.
=> neutron: Only put sql credentials in neutron.conf on neutron-server node

chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/templates/default/keystone.conf.erb, chef/data_bags/crowbar/migrate/keystone/104_remove_use_syslog.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema
http://docs.openstack.org/newton/config-reference/tables/conf-changes/keystone.html
=> keystone: drop the use of 'use_syslog' as its deprecated in newton

chef/cookbooks/cinder/templates/default/cinder-looplvm.erb
to simplify code and reduce sources of errors
=> cinder: looplvm: avoid one level of indirection

chef/cookbooks/keystone/libraries/helpers.rb, chef/cookbooks/keystone/recipes/ha.rb, chef/cookbooks/keystone/recipes/server.rb
Since the attribute was never set, it fell back to the non-HA case
and pointed to the non-VIP endpoint, which tentantivel might not work.
=> Fix unversioned internal auth url for the HA case

chef/cookbooks/tempest/templates/default/tempest.conf.erb
Heat has currently 2 test sources. The tests from Tempest itself
and the tests from the Heat Tempest plugin. When running Tempest and
Heat is not deployed, also the tests from the Heat Tempest plugin must
be disabled.
=> tempest: Use "use_heat" also for the heat plugin tests

chef/cookbooks/barbican/recipes/api.rb
The missing/wrong vars were causing to make barbican bind to `localhost:80` so it barbican was working but not listening
=> barbican: Set missing port and proper var for host in case of non-HA

chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb
as per
http://specs.openstack.org/openstack/neutron-specs/specs/kilo/ml2-ovs-portsecurity.html
https://wiki.openstack.org/wiki/Neutron/ML2PortSecurityExtensionDriver
this should allow us to run our own routers and DHCP-servers within the cloud
that would allow us to test SOC within OpenStack
using
neutron net-update ournet --port-security-enabled=False
or neutron port-update
to override the defaults (default is to filter as before)
=> neutron: add port_security to ml2 extension_drivers

chef/cookbooks/swift/recipes/dispersion.rb
This is an ultra brutal workaround of restarting proxy on every
chef run and completely destabilizes HA (as the restarts happen
on all nodes at the same time and pacemaker collapses as the services
disappear everywhere). If there is a problem this needs to be fixed
elsewhere.
This reverts commit 77ec11da5b7db42bedfdd3829234957af1c28011.
This reverts https://github.com/crowbar/crowbar-openstack/pull/544
=> Revert "dispersion: restart swift-proxy service to avoid bsc#1003366"

chef/cookbooks/trove/libraries/helpers.rb
The mechanical code changes just for the sake of satisfying a
stupid robot are actually done by humans, and humans tend to
make mistakes.
=> trove: Handle radosgw being on a different node properly

chef/data_bags/crowbar/migrate/keystone/106_pki_uuid_switch.rb, chef/data_bags/crowbar/template-keystone.json
As part of https://github.com/crowbar/crowbar-openstack/pull/702 while the behavior of 702 is correct, it leaves the value for the token_format incorrect in the attribute list, which is a bug. This PR migrates the value of the attribute since in the new release the PKI is not supported.
=> keystone: migrate value of token_format

barbican.yml, manila.yml
for barbican, manila and ceilometer so that aodh can be listed in the right order
=> crowbar: remove barclamp order overlap

chef/cookbooks/keystone/templates/default/keystone.conf.erb
We are not using '.*dumb_member' in the template anymore so remove it
from the conf file. Also sorted the ldap keys in the template and schema
files to make comparisons between the two easier.
=> keystone: Remove unused options

chef/cookbooks/neutron/recipes/server.rb
The default timeout of 60s seems to be not enough. The error msg is:
FATAL: Cluster founder didn't set neutron_db_sync to 5!
There are multiple reasons for that:
- neutron-server is started/stopped inside of the sync mark. We recently
switched to systemd and use now Type=notify for the service. That means
that starting the service blocks until the service is ready
- there are multiple db-syncs between the sync-mark. There is a sync
for the main DB, but also for fwaas, lbaas and possibly for Cisco
APIC.
=> neutron: Increase sync-mark timeout for DB sync

chef/cookbooks/tempest/templates/default/tempest.conf.erb
boto testing was dropped in tempest 10.0, so there is no point
in trying to set it. Also ec2api is now handled via a tempest
plugin
=> tempest: Remove boto related options

chef/cookbooks/ec2-api/recipes/ec2api.rb
Commit a7cc09d4156fcea8e changed the attribute with the
config_file name. This fixes:
undefined method `[]' for nil:NilClass
=> ec2api: Fix restart on config file change

chef/cookbooks/aodh/recipes/aodh_ha.rb, chef/cookbooks/barbican/recipes/ha.rb, chef/cookbooks/ceilometer/recipes/server_ha.rb, chef/cookbooks/cinder/recipes/controller_ha.rb, chef/cookbooks/crowbar-openstack/definitions/openstack_pacemaker_controller_only_location_for.rb, chef/cookbooks/glance/recipes/ha.rb, chef/cookbooks/heat/recipes/ha.rb, chef/cookbooks/horizon/recipes/ha.rb, chef/cookbooks/keystone/recipes/ha.rb, chef/cookbooks/magnum/recipes/ha.rb, chef/cookbooks/manila/recipes/controller_ha.rb, chef/cookbooks/neutron/recipes/server_ha.rb, chef/cookbooks/nova/recipes/compute_ha.rb, chef/cookbooks/nova/recipes/controller_ha.rb, chef/cookbooks/postgresql/recipes/ha_storage.rb, chef/cookbooks/rabbitmq/recipes/ha.rb, chef/cookbooks/sahara/recipes/ha.rb, chef/cookbooks/swift/recipes/proxy_ha.rb
We make it possible to not run the crowbar-pacemaker cookbook when we run some OpenStack cookbook that use HA and require some specific setup (for drbd or haproxy, for instance).
This depends on and needs to be merged at the same time as: https://github.com/crowbar/crowbar-ha/pull/164
=> Do not require crowbar-pacemaker cookbook to run when we configure HA in openstack

chef/cookbooks/trove/recipes/api.rb
action :nothing is a leftover of a more complicated setup to be triggered that I experimented on while doing https://github.com/crowbar/crowbar-openstack/commit/dfb322935fca75f6e2b6887fad77c27f90d9c380 and blocks the database for trove to be created+synced, breaking the tempest run for all jobs in the CI
=> trove: Fix wrong db_sync resource action

chef/cookbooks/keystone/libraries/helpers.rb
We need the VIP of the cluster for the URL. get_host_for_public_url()
needs to know if this is a HA setup to return the correct name/IP.
=> keystone_helpers: Fix public keystone public url for ha setups

chef/cookbooks/aodh/metadata.rb, chef/cookbooks/ec2-api/metadata.rb, chef/cookbooks/trove/metadata.rb
This matters if these services are installed on nodes where nothing else
is installed.
=> cookbooks: Add missing dependencies to cookbooks

chef/cookbooks/tempest/templates/default/tempest.conf.erb
Reverts crowbar/crowbar-openstack#736
Wait until bsc#1018614 is fixed and package is available *and* tested
=> Revert "tempest: disable trove until bsc1018614 is fixed so we dont block all…"

chef/data_bags/crowbar/migrate/neutron/103_add_lbaasv2_driver.rb, chef/data_bags/crowbar/migrate/neutron/103_remove_use_lbaasv2.rb, chef/data_bags/crowbar/migrate/neutron/104_add_f5_attributes.rb
The migrations related to lbaasv2 & F5 were assuming that the code would not hit 3.0.
=> Fix neutron migrations for upgrade when F5 backport lands

chef/cookbooks/keystone/recipes/server.rb
Due to the fact that Ceph depends on Keystone signing certificates for communication with Keystone we need to have the right code to set up the attributes and related content.
relates to this https://github.com/crowbar/crowbar-ceph/pull/83
=> keystone: revert back certificate attributes setup

chef/cookbooks/glance/templates/default/glance-registry.conf.erb
seems like the existance of the whitespace was
causing issue when parsing the config
=> glance: fix registry config whitespace

chef/cookbooks/neutron/recipes/network_agents_ha.rb
It was requested to have f5-agent in its own clone so that it's not
impacted by anything happening in g-neutron-agents.
=> neutron: Move f5-agent resource out of cl-g-neutron-agents

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/recipes/server.rb, chef/data_bags/crowbar/migrate/neutron/105_add_back_use_l2pop.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema, crowbar_framework/app/assets/javascripts/barclamps/neutron/application.js, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/app/views/barclamp/neutron/_edit_attributes.html.haml, crowbar_framework/config/locales/neutron/en.yml
Quoting @dirkmueller:
> l2pop with HA/vxlan just doesn't seem to work at all. Only enable what upstream does in devstack: when DVR is used.
This should replace https://github.com/crowbar/crowbar-openstack/pull/684
=> Re-add use_l2pop attribute

chef/cookbooks/rabbitmq/recipes/default.rb, chef/cookbooks/rabbitmq/recipes/ha.rb
We reset the UID/GID of rabbitmq to `91` to make it consistent across
the cluster. This change has to happen before we create the fs-rabbitmq
pacemaker resource, otherwise rabbitmq can not be started due to
potentially wrong ownership values on its home directory. This patch
moves the `bash` resource further up.
=> ha: Re-order rabbitmq UID/GID and pacemaker resource creation

chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
the default is number of cpus which is just eating too much memory for no real gain
=> ec2-api: Limit ec2 metadata workers

chef/cookbooks/cinder/recipes/volume.rb
The generated systemd file had a dependency "Before=" pointing to
itself, causing systemd warnings every chef run
=> cinder: Avoid self-dependency

crowbar_framework/app/models/swift_service.rb
This change was not wanted by upstream in 2013, since then this patch is in our package but a lot changed since then so let's try it again.
=> swift: Fail to create swift proposal if there is no keystone

chef/cookbooks/neutron/recipes/network_agents_ha.rb
So we can execute neutron-ha-tool or nova commands if they
are in the different cluster than keystone.
OK, I'm not sure if this is correct, so it's rather initial proposal...
=> [stable/3.0] Provide .openrc for nodes with neutron-network role

chef/cookbooks/neutron/recipes/network_agents_ha.rb
(cherry picked from commit 80fe40dd56a5fe2e92ec01d9081799825f0f1c6d)
backport of https://github.com/crowbar/crowbar-openstack/pull/758
=> Create .openrc at nodes with neutron-network role.

chef/data_bags/crowbar/migrate/neutron/049_infoblox_update.rb
We hit "undefined method `key?' for nil:NilClass", because it's a hash,
and using symbols don't work here.
Note that the fix is already in master...
=> neutron: Additional fix for infoblox migration (bsc#1020121)

crowbar_framework/app/helpers/barclamp/keystone_helper.rb, crowbar_framework/app/helpers/barclamp/swift_helper.rb, crowbar_framework/app/views/barclamp/keystone/_edit_attributes.html.haml, crowbar_framework/app/views/barclamp/swift/_edit_attributes.html.haml, crowbar_framework/config/locales/keystone/en.yml, crowbar_framework/config/locales/swift/en.yml
This patch has been in our packages since more or less forever.
As it causes conflicts in the PR testing, upstreaming that patch
is easier.
=> keystone/swift: Hide unneeded options from proposal screen

chef/data_bags/crowbar/migrate/swift/101_drop_slog.rb
This was broken in https://github.com/crowbar/crowbar-openstack/pull/777
=> swift: Use correct slog_passwd key to drop during migration

chef/cookbooks/neutron/recipes/server.rb
Setting extension_drivers causes *only* those drivers to be loaded,
instead of a builtin default, so suddenly a lot of extensions
got disabled.
=> neutron: Reenable qos and dns extensions

chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb, chef/cookbooks/neutron/attributes/default.rb
This depends on Neutron VPNaaS which we have not implemented
=> ec2-api: Disable VPC support

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb, chef/data_bags/crowbar/migrate/neutron/107_add_ovs_interface_attributes.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
Neutron uses "native" by default now. Allow to switch back to the old
vsctl/ovs_ofctl based implementations.
Workaround for: https://bugzilla.suse.com/show_bug.cgi?id=1022074
=> neutron: Add attribute of choosing ovsdb/of interface (bsc#1022074)

chef/data_bags/crowbar/migrate/ceilometer/103_remove_hyperv.rb, chef/data_bags/crowbar/migrate/nova/113_remove_hyperv.rb, chef/data_bags/crowbar/template-ceilometer.json, chef/data_bags/crowbar/template-nova.json, crowbar_framework/app/models/ceilometer_service.rb, crowbar_framework/app/models/nova_service.rb
This only removes the minimal things needed, in case Hyper-V support
gets staffed with ressources again.
=> ceilometer/nova: Hide references to Hyper-V

chef/cookbooks/neutron/templates/default/neutron.conf.erb
This is a new setting that got introduced in
https://review.openstack.org/#/c/291810/
Note that master already uses this setting.
=> neutron: Use internal endpoint for nova notifications

chef/cookbooks/cinder/recipes/common.rb, chef/cookbooks/crowbar-openstack/files/default/crowbar-openstack.tmpfiles, chef/cookbooks/crowbar-openstack/recipes/common.rb, chef/cookbooks/nova/recipes/config.rb
Without this, we rely on chef-client for this directory to be created on
boot, which is undesired.
https://bugzilla.suse.com/show_bug.cgi?id=1021753
=> cinder, nova: Use a tmpfiles.d config file for /var/run/openstack

chef/cookbooks/aodh/recipes/aodh_ha.rb, chef/cookbooks/barbican/recipes/ha.rb, chef/cookbooks/ceilometer/recipes/central_ha.rb, chef/cookbooks/ceilometer/recipes/mongodb.rb, chef/cookbooks/ceilometer/recipes/server_ha.rb, chef/cookbooks/cinder/recipes/controller_ha.rb, chef/cookbooks/crowbar-openstack/definitions/openstack_pacemaker_controller_clone_for_transaction.rb, chef/cookbooks/ec2-api/recipes/ec2api_ha.rb, chef/cookbooks/glance/recipes/ha.rb, chef/cookbooks/heat/recipes/ha.rb, chef/cookbooks/magnum/recipes/ha.rb, chef/cookbooks/manila/recipes/controller_ha.rb, chef/cookbooks/neutron/recipes/network_agents_ha.rb, chef/cookbooks/neutron/recipes/server_ha.rb, chef/cookbooks/nova/recipes/compute_ha.rb, chef/cookbooks/nova/recipes/controller_ha.rb, chef/cookbooks/sahara/recipes/ha.rb, chef/cookbooks/swift/recipes/proxy_ha.rb
The downside of groups is that this creates ordering constraints within
a group, and in nearly all cases, these ordering constraints are not
reflecting real dependencies.
This is then causing issues when restarting an individual resource,
because all later resources in the group are also restarted, possibly
leading to temporary failures that were not wanted.
On top of that, a helper was created to significantly reduce code duplication.
This depends on https://github.com/crowbar/crowbar-ha/pull/178 and contains https://github.com/crowbar/crowbar-openstack/pull/330.
=> Do not use pacemaker groups unless needed

chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb
Incase when using network other than admin, the said variable should
have the fqdn/ip of the migration interface.
`live_migration_uri` is no longer used for migration.
=> nova: use `live_migration_inbound_addr`

chef/cookbooks/neutron/recipes/server.rb
QoS and dns extensions were not enabled. The actual bug in Tempest tests was a wrong check for existing extensions. See https://review.openstack.org/#/c/422040 .
Reverts crowbar/crowbar-openstack#802
=> Revert "neutron: Reenable qos and dns extensions"

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb, chef/data_bags/crowbar/migrate/neutron/055_add_tunnel_csum.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
(cherry picked from commit eca6eb435189d1c63c431e7df4ae2af97d527d57)
=> [stable/3.0] Add tunnel_csum attribute to neutron barclamp

chef/cookbooks/ec2-api/attributes/default.rb, chef/cookbooks/ec2-api/recipes/ec2api.rb, chef/cookbooks/ec2-api/recipes/ec2api_ha.rb, chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb, chef/cookbooks/nova/recipes/role_ec2_api.rb, crowbar_framework/app/models/nova_service.rb
Since nothing was changing the listening ports for the ec2-api service,
when deploying in a HA environment, either haproxy would grab the port,
and then the service wouldn't start; or the service would, and then
haproxy would be sad. Change the listening ports if HA is enabled.
=> ec2-api: Change listen ports if using HA

chef/cookbooks/nova/recipes/compute_ha.rb
This gives
Constraint 'o-nova-evacuate': Invalid reference to 'neutron-l3-agent'
otherwise
=> Fix ordering constraint for ha-compute

chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
While in concept, the commit that landed yesterday should have fixed
ec2-api's HA support, it doesn't actually start the services because
the values are not written to the config file. Add in the missing equal
signs.
=> ec2-api: Actually write host/port values

chef/cookbooks/ec2-api/recipes/ec2api.rb, chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
The "verbose" option for ec2-api is deprecated, remove it. I don't think
it requires a migration since it was making use of the nova barclamp
setting directly.
=> ec2-api: Remove deprecated "verbose" option

chef/cookbooks/keystone/recipes/server.rb
Otherwise there is no symlink to execute the cronjob and
the tokens are not rotated.
=> keystone: Start fernet-rotate HA resource

chef/cookbooks/tempest/templates/default/tempest.conf.erb, chef/data_bags/crowbar/migrate/tempest/105_manila_add_storage_protocol.rb, chef/data_bags/crowbar/template-tempest.json, chef/data_bags/crowbar/template-tempest.schema
storage_protocol needs to be set to "CEPHFS" when only cephfs is available
as manila backend.
Otherwise tests like "test_get_share_with_share_type" fail with:
Failed to schedule create_share: No valid host was found.
=> tempest: Add storage_protocol option for Manila

chef/cookbooks/cinder/templates/default/cinder-volume.conf.erb
Unfortunately as part of the Hyper Agile Super config rediffing effort the feature was accidentally disabled. Revert the incorrect change and switch to a more robust implementation that does not suffer from deprecation warnings .
=> Make cinder volume HA work again

chef/cookbooks/aodh/recipes/aodh_ha.rb, chef/cookbooks/manila/recipes/controller_ha.rb
ssl was always marked as disabled.
=> manila: Fix haproxy config when ssl is enabled

chef/data_bags/crowbar/template-magnum.json
the issue with "local" is that it stores on the local filesystem,
which is 100% not working for a HA deployment because there is no shared
filesystem. Also "local" is explictely marked as non-production ready
so it doesn't make a good default.
Storing in the database seems to be a saner default.
=> magnum: switch default cert store to x509keypair

chef/cookbooks/barbican/templates/default/barbican.conf.erb
Seems that it was wrongly removed during the minify of the templates.
=> barbican: restore missing keystone config (bsc#1024554)

chef/cookbooks/crowbar-openstack/providers/wsgi.rb
Instead of restarting the apache service when a new vhost is
created, try to reload the configuration.
This can resolve issues in HA when apache is restarted, but a
barclamp in a different node is making queries to a service that
is behing apache (like keystone)
=> crowbar_openstack_wsgi: reload apache configuration

crowbar_framework/app/models/magnum_service.rb, crowbar_framework/config/locales/magnum/en.yml
In case the cert_manager in magnum is set to barbican we must check
if the barbican proposal is active.
=> Validate barbican barclamp in magnum (bsc#1025040)

chef/data_bags/crowbar/migrate/database/100_add_log_min_duration_statement.rb, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema
This is useful to understand why some OpenStack API calls may be slow,
if this turns out to be caused by the database.
The setting is in ms; -1 means that it's disabled.
Closes https://github.com/sap-oc/crowbar-openstack/issues/8
=> database: Add ability to log slow queries in postgresql

chef/cookbooks/nova/templates/default/nova.conf.erb
It's wrong to not set live_migration_flag when no shared storage is
used because it's actually still the flag used when volume-backed
instances are migrated.
This becomes visible since we now set live_migration_uri, and we get
this error:
Live Migration failure: argument unsupported: migration URI is not supported by tunnelled migration
That's because the default value of live_migration_flag contains
VIR_MIGRATE_TUNNELLED.
(cherry picked from commit 096cb6f3c8df50857fe39b5f75745399dbe13e01)
Backport of https://github.com/crowbar/crowbar-openstack/pull/856
=> nova: Always set live_migration_flag/block_migration_flag for kvm

chef/cookbooks/barbican/attributes/default.rb, chef/cookbooks/barbican/recipes/api.rb, chef/cookbooks/barbican/recipes/common.rb, chef/data_bags/crowbar/migrate/barbican/101_add_ssl_attributes.rb, chef/data_bags/crowbar/template-barbican.json, chef/data_bags/crowbar/template-barbican.schema, crowbar_framework/app/helpers/barclamp/barbican_helper.rb, crowbar_framework/app/views/barclamp/barbican/_edit_attributes.html.haml, crowbar_framework/config/locales/barbican/en.yml
Add a "protocol" setting and "ssl" configuration options to the barbican
barclamp.
This patch also removes the "api" "ssl" config flag in favor of the "protocol"
string setting, as this was the only barclamp to use such a setting. This
brings it into conformance with other barclamps and makes it possible to test
the SSL scenario without any special treatment[1].
[1] https://github.com/SUSE-Cloud/automation/blob/93fac15bdaa15751362f5856fa348ba3c632e8dd/scripts/qa_crowbarsetup.sh#L2242
=> barbican: Add SSL support

chef/cookbooks/magnum/templates/default/magnum.conf.erb, chef/data_bags/crowbar/migrate/magnum/101_add_cluster_user_trust.rb, chef/data_bags/crowbar/template-magnum.json, chef/data_bags/crowbar/template-magnum.schema, crowbar_framework/app/views/barclamp/magnum/_edit_attributes.html.haml, crowbar_framework/config/locales/magnum/en.yml
[This upstream commit](https://github.com/openstack/magnum/commit/2d4e617a529ea12ab5330f12631f44172a623a14) in Magnum introduced the setting `cluster_user_trust` which defaults to `False` (the secure choice) but must be set to `True` for some clusters that run their own registry and/or the `rexray` volume drivers. In order to allow users (and functional tests that test the problematic cluster types) to make that choice we need to expose this setting in Crowbar.
=> magnum: expose trust/cluster_user_trust.

chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/nova/115_add_cache_manager_interval.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema
Disabling this option as a precaution to avoid the race wherin
the cache_manager removes the images which are actually in use.
This can be enabled by setting to a value greater than -1.
=> Disable image_cache_manager_interval(bsc#1015324)

chef/cookbooks/keystone/providers/register.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/resources/register.rb, chef/cookbooks/keystone/templates/default/keystone.domain.conf.erb, chef/data_bags/crowbar/migrate/keystone/109_add_domain_specific_configs.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema
In SOC6 we had the "hybrid" keystone identity and assignment backend
which allowed LDAP users to authenticate with keystone. Recent versions
of keystone allow domain-specific identity backends to be configured,
essentially providing the same functionality. This patch adds support
for domain specific configuration by adding the parameter
"domain_specific_config", which provides a mapping from domain names to
their [identity] and [ldap] settings, as well as adding a new add_domain
action to keystone_register. Instead of setting the identity and
assignment drivers to "hybrid" and setting LDAP parameters in the main
LDAP section, users should now leave the default drivers as "sql",
enable "domain_specific_drivers", and set the LDAP parameters under
"domain_specific_config" for a domain of …
=> keystone: Enable domain specific configuration

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
As of now (newton) the nfs backend in cinder does not support snapshots.
=> Disable cinder snapshots in tempest when using the nfs backend

chef/cookbooks/ceilometer/attributes/default.rb, chef/cookbooks/ceilometer/recipes/server.rb, chef/cookbooks/horizon/recipes/server.rb, chef/data_bags/crowbar/migrate/ceilometer/104_add_ssl_attributes.rb, chef/data_bags/crowbar/template-ceilometer.json, chef/data_bags/crowbar/template-ceilometer.schema, crowbar_framework/app/helpers/barclamp/ceilometer_helper.rb, crowbar_framework/app/views/barclamp/ceilometer/_edit_attributes.html.haml, crowbar_framework/config/locales/ceilometer/en.yml
Add ability to configure SSL to the ceilometer barclamp
- SSL parameters can be accessed through the UI 'protocol' attribute (aligned to other barclamps)
- chef cookbook support to generate and configure certificates for the ceilometer-api service
- modified horizon chef deployment to take note of the insecure ceilometer certificates
Side notes:
- the ceilometer global REST API will be [deprecated in Ocata](https://docs.openstack.org/releasenotes/ceilometer/ocata.html#deprecation-notes) and replaced with the individual REST APIs of its components (Aodh, Gnocci and Panko), which are already available in Newton
=> Ceilometer: add ssl support

chef/cookbooks/cinder/recipes/ceph.rb, chef/cookbooks/glance/recipes/ceph.rb, chef/cookbooks/nova/recipes/ceph.rb
When ceph node is prepared for the upgrade, it cannot be find by
the search for roles, but search for run_list_map still works.
This is actually consistent with the (upgrade unrelated) search method
that is already used in ceph recipes.
=> upgrade: Check for run_list_map when searching for ceph nodes.

chef/cookbooks/ec2-api/attributes/default.rb, chef/cookbooks/ec2-api/recipes/ec2api.rb, chef/cookbooks/ec2-api/recipes/ec2api_ha.rb, chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb, chef/data_bags/crowbar/migrate/nova/116_add_ec2_ssl.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml, crowbar_framework/config/locales/nova/en.yml
Add support to deploy ec2-api with SSL enabled endpoints, optionally
generating self-signed certificates.
Co-Authored-By: Steve Kowalik <steven@wedontsleep.org>
This replaces https://github.com/crowbar/crowbar-openstack/pull/773 .
=> ec2-api: Add SSL support

bin/crowbar_monasca, chef/cookbooks/monasca/README.md, chef/cookbooks/monasca/attributes/default.rb, chef/cookbooks/monasca/metadata.rb, chef/cookbooks/monasca/recipes/agent.rb, chef/cookbooks/monasca/recipes/api.rb, chef/cookbooks/monasca/recipes/role_monasca_agent.rb, chef/cookbooks/monasca/recipes/role_monasca_server.rb, chef/cookbooks/monasca/recipes/server.rb, chef/cookbooks/monasca/templates/default/agent.yaml.erb, chef/cookbooks/monasca/templates/default/api-config.conf.erb, chef/data_bags/crowbar/template-monasca.json, chef/data_bags/crowbar/template-monasca.schema, chef/roles/monasca-agent.rb, chef/roles/monasca-server.rb, crowbar_framework/app/controllers/monasca_controller.rb, crowbar_framework/app/models/monasca_service.rb, crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml, crowbar_framework/config/locales/monasca/en.yml, monasca.yml
This commit contains skeleton code for deploying OpenStack Monasca. It is meant
as a scaffold to add the actual code for deploying Monasca to. It is divided
into three roles:
* monasca-agent: for deploying a Monasca logging/monitoring agent to arbitrary
nodes
* monasca-api: for deploying the Monasca API service to the OpenStack
controller nodes.
* monasca-server: for deploying the Monasca backend services for receiving and
storing logs and monitoring events to dedicated Monasca nodes.
There are some TODO and FIXME comments in the places where things still need to
be changed.
=> monasca: Added skeleton for Monsasca barclamp

chef/cookbooks/nova/recipes/compute_ha.rb
Do not create virtlogd primitive for remote resource if all nodes are not yet upgraded to SLES12SP2.
=> upgrade: Check for remote nodes platform version before creating virtlogd primitive

chef/cookbooks/magnum/recipes/post_install.rb
The curl command to download the image uses one long string with inner
line continuations, which also includes the spaces used to keep Hound
happy. Split the image url string to the outer block so it can be
constructed without spaces while keeping Hound silent.
=> magnum: Stop encoding spaces into image URL

chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/data_bags/crowbar/migrate/glance/104_add_vsphere_insecure.rb, chef/data_bags/crowbar/template-glance.json, chef/data_bags/crowbar/template-glance.schema, crowbar_framework/app/views/barclamp/glance/_edit_attributes.html.haml, crowbar_framework/config/locales/glance/en.yml
This is the switch for vmware_api_insecture.
It reverts a23290463630d89df893cac2ee81193ffb5ca47c, but using "insecure"
in the barclamp to match cinder and nova barclamp options.
=> glance: reintroduce vSphere insecure API option (bsc#1027791)

chef/cookbooks/horizon/recipes/server.rb, chef/cookbooks/horizon/templates/default/openstack-dashboard.conf.erb, chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
horizon: create a dummy service for reload (bsc#1029442)
Apache reload (graceful) will signal the apache process, that will
restart the child process (WSGI).  This can cause a race, were an
OpenStack client try to contact to one of the WSGI services, and
the old WSGI process can answer.  This process will fail because
the WSGI socket is not anymore in the file system.
The aproach here is to create a dummy service for 'horizon', what
will SIGUSR1 the wsgi:horizon childs from apache, signaling the
reload of the configuration file.
=> Fix BSC#1029442

chef/cookbooks/cinder/templates/default/cinder.conf.erb
Operators that do not have Cinder backup service deployed in their cloud should set this option to False.
=> cinder: set backups_enabled to false

chef/cookbooks/neutron/attributes/default.rb, chef/cookbooks/neutron/recipes/common_config.rb, chef/cookbooks/neutron/templates/default/neutron.conf.erb, chef/data_bags/crowbar/migrate/neutron/108_add_rpc_workers.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
The rpc_workers neutron.conf configurable parameter was introduced in OpenStack Icehouse. It controls the number of RabbitMQ/ZeroMQ RPC listener processes spawned by neutron-server (one by default).
More info:
* OS blueprint: https://blueprints.launchpad.net/neutron/+spec/multiple-rpc-workers
* subsequent change in default value (from 0 to 1): https://bugs.launchpad.net/neutron/+bug/1463129
* official Mitaka documentation: https://docs.openstack.org/mitaka/config-reference/networking/networking_options_reference.html#configure-messaging
=> neutron: make rpc_workers attribute configurable

chef/cookbooks/aodh/templates/default/aodh.conf.erb, chef/cookbooks/barbican/templates/default/barbican.conf.erb, chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb, chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/cookbooks/crowbar-openstack/libraries/helpers.rb, chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb, chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/heat/templates/default/heat.conf.erb, chef/cookbooks/keystone/templates/default/keystone.conf.erb, chef/cookbooks/magnum/templates/default/magnum.conf.erb, chef/cookbooks/manila/templates/default/manila.conf.erb, chef/cookbooks/neutron/templates/default/neutron.conf.erb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/cookbooks/rabbitmq/recipes/rabbit.rb, chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb, chef/cookbooks/sahara/templates/default/sahara.conf.erb, chef/cookbooks/swift/recipes/proxy.rb, chef/cookbooks/trove/recipes/conductor.rb, chef/cookbooks/trove/recipes/taskmanager.rb, chef/cookbooks/trove/templates/default/trove-conductor.conf.erb, chef/cookbooks/trove/templates/default/trove-taskmanager.conf.erb, chef/cookbooks/trove/templates/default/trove.conf.erb, chef/data_bags/crowbar/migrate/rabbitmq/012_ssl.rb, chef/data_bags/crowbar/template-rabbitmq.json, chef/data_bags/crowbar/template-rabbitmq.schema, crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml, crowbar_framework/config/locales/rabbitmq/en.yml
Add SSL support to rabbitmq barclamp
This patch adds the option to configure some of the SSL settings for
rabbitmq and ensure all OpenStack services are using the SSL-secured
port. There are some important notes regarding how this differs from
enabling SSL for the REST APIs:
- The SSL port is configurable, since typically rabbitmq has different
ports designated for regular and SSL traffic and it would be confusing
to only allow one port.
- The ceilometer pipeline for swift does not have the ability to read
the oslo.messaging SSL-specific options from oslo.config[1]. Rather
than send ceilometer traffic over an unsecured channel, we disable
this pipeline when rabbitmq is enabled.
- Disabling the "insecure" option requires the client services to
configure a CA to validate the rabbitmq server …
=> rabbitmq: Add SSL support

chef/cookbooks/horizon/templates/centos/openstack-dashboard.conf.erb, chef/cookbooks/horizon/templates/default/openstack-dashboard.conf.erb, chef/cookbooks/horizon/templates/redhat/openstack-dashboard.conf.erb, chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
The current SSLCipherSuite default is not anymore contemporary. The new
default is based on the latest recommendation from the Mozilla Foundation.
see: https://wiki.mozilla.org/Security/Server_Side_TLS
=> horizon: Increase Apache SSLCipherSuite forward secrecy

chef/cookbooks/keystone/recipes/server.rb
To ensure that all cluster nodes have the `rsync` package installed,
insert a sync mark after the `package` call.
Co-Authored-By: Roman Arcea <rarcea@suse.com>
Co-Authored-By: Nicolas Bock <nicolas.bock@suse.com>
=> bsc_1023522: Synchronize on rsync install

chef/cookbooks/horizon/templates/centos/openstack-dashboard.conf.erb, chef/cookbooks/horizon/templates/default/openstack-dashboard.conf.erb, chef/cookbooks/horizon/templates/redhat/openstack-dashboard.conf.erb, chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
The current SSLCipherSuite default is not anymore contemporary. The new
default is based on the latest recommendation from the Mozilla Foundation.
see: https://wiki.mozilla.org/Security/Server_Side_TLS
(cherry picked from commit 13bb6f2a844ac7d91f4765ed2d47739f418a30db)
Backport of https://github.com/crowbar/crowbar-openstack/pull/866
=> [3.0] horizon: Increase Apache SSLCipherSuite forward secrecy

chef/cookbooks/neutron/attributes/default.rb, chef/cookbooks/neutron/recipes/common_config.rb, chef/cookbooks/neutron/templates/default/neutron.conf.erb, chef/data_bags/crowbar/migrate/neutron/056_add_rpc_workers.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
Backport for #863:
> The rpc_workers neutron.conf configurable parameter was introduced in OpenStack Icehouse. It controls the number of RabbitMQ/ZeroMQ RPC listener processes spawned by neutron-server (one by default).
> 
> More info:
> 
> OS blueprint: https://blueprints.launchpad.net/neutron/+spec/multiple-rpc-workers
> subsequent change in default value (from 0 to 1): https://bugs.launchpad.net/neutron/+bug/1463129
> official Mitaka documentation: https://docs.openstack.org/mitaka/config-reference/networking/networking_options_reference.html#configure-messaging
=> [3.0] neutron: make rpc_workers attribute configurable

chef/cookbooks/swift/recipes/proxy.rb
We have to look inside the output of fetch_rabbitmq_settings output
for rabbitmq configuration.
Originally introduced with https://github.com/crowbar/crowbar-openstack/pull/873
=> Do not assume swift-proxy node is also rabbitmq node

chef/cookbooks/nova/libraries/boot_kernel.rb
During node upgrade, we're executing chef-client from crowbar_join.
If node reboots in this stage, upgrade script that executed this
crowbar_join will be interrupted and cannot finish.
The reboot is indeed needed, but it could be delayed to the next regular chef-client run, I hope.
=> upgrade: Do not reboot XEN node from the first chef-client run

chef/cookbooks/aodh/recipes/aodh.rb, chef/cookbooks/barbican/recipes/api.rb, chef/cookbooks/barbican/recipes/common.rb, chef/cookbooks/ceilometer/recipes/server.rb, chef/cookbooks/cinder/recipes/sql.rb, chef/cookbooks/ec2-api/recipes/ec2api.rb, chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/glance/recipes/common.rb, chef/cookbooks/glance/recipes/registry.rb, chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/horizon/recipes/server.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/magnum/recipes/api.rb, chef/cookbooks/magnum/recipes/setup.rb, chef/cookbooks/magnum/recipes/sql.rb, chef/cookbooks/manila/recipes/sql.rb, chef/cookbooks/neutron/recipes/api_register.rb, chef/cookbooks/neutron/recipes/database.rb, chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/nova/recipes/api.rb, chef/cookbooks/nova/recipes/database.rb, chef/cookbooks/sahara/recipes/api.rb, chef/cookbooks/sahara/recipes/sql.rb, chef/cookbooks/swift/recipes/proxy.rb, chef/cookbooks/trove/recipes/api.rb
CrowbarPacemakerSynchronization (that implements crowbar_pacemaker_sync_mark)
has a generic check for node being part of a cluster.
However, if a node is part of a cluster, but certain component is not
deployed as Higly Available, sync marks should not be used at all.
It's possible that such setup is not supported, however failing with missing sync mark is probably not the right way of pointing that out.
=> Call crowbar_pacemaker_sync_mark only when HA is enabled for component

chef/cookbooks/magnum/templates/default/magnum.conf.erb
This removes the deprecation warning
WARNING keystonemiddleware.auth_token [-] Use of the auth_admin_prefix, \
auth_host, auth_port, auth_protocol, identity_uri, admin_token, \
admin_user, admin_password, and admin_tenant_name configuration \
options was deprecated in the Mitaka release in favor of an \
auth_plugin and its related options. This class may be removed in \
a future release.
when starting the magnum-api service.
=> magnum: Use correct values for keystone authentication

chef/cookbooks/horizon/recipes/monasca_ui.rb
This file should not be installed by the package, as we don't want
package installation to activate new services. so the attempt
at deleting it is obsolete and this needs to be fixed in packaging
instead.
=> horizon: stop deleting grafana.conf

chef/cookbooks/rabbitmq/recipes/rabbit.rb
The ha recipe of the rabbitmq cookbook forcibly changes the IDs of the
rabbitmq user and group after rabbitmq is installed. If we try to change
group ownership of a file after rabbitmq is installed but before the
rabbitmq group's gid is changed, the file will be left with just an
apparently-random gid as its group. This was happening to the rabbitmq
crowbar-generated private SSL key, which caused rabbitmq to be unable to
read its own key.  Subsequently, the memcached package was installed
which scooped up the gid and the SSL key then became apparently owned by
the memcached group.
This patch simply delays generation of the SSL key pair until after the
ha recipe has been able to muck with the rabbitmq user and group.
=> rabbitmq: Fix ordering of ssl setup

chef/cookbooks/horizon/files/default/grafana-monasca.json
This patch updates the grafana monasca dashboard to
reflect the changes on the Metrics Api replacement
from java to python
=> Monasca: Default grafana-monasca dashboard

chef/cookbooks/monasca/attributes/default.rb, chef/cookbooks/monasca/recipes/agent.rb, chef/cookbooks/monasca/recipes/role_monasca_agent.rb, chef/cookbooks/monasca/recipes/server.rb, chef/data_bags/crowbar/template-monasca.json, chef/data_bags/crowbar/template-monasca.schema, chef/roles/monasca-agent.rb, chef/roles/monasca-metric-agent.rb, crowbar_framework/app/helpers/barclamp/monasca_helper.rb, crowbar_framework/app/models/monasca_service.rb, crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml, crowbar_framework/config/locales/monasca/en.yml
monasca-agent is the upstream project name. It is confusing to have
- monasca-agent
- monasca-log-agent
- monasca-metric-agent
In fact there are only 2 (the 2 first ones).
=> monasca: Rename metric-agent to agent

chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/data_bags/crowbar/migrate/cinder/106_add_max_over_subscription_ratio.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema, crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml, crowbar_framework/config/locales/cinder/en.yml
Enable users to specify the max_over_subscription_ratio when using
netapp driver. If other drivers needed this configuration value they
would add max_over_subscription_ratio to their configuration and the
template will render the value to the configuration file. So if for a
specific volume
volume[volume['backend_driver']]['max_over_subscription_ratio']
exists, then it's value will be included.
Please note that an integer is used for this number whereas OpenStack
will interpret this as a float.
=> cinder: netapp: add max_over_subscription_ratio

chef/cookbooks/horizon/templates/default/_80_monasca_ui_settings.py.erb
The monasca plugin expects a URL in this field so we need to prefix
the IP address we are currently putting in there with an 'http://'.
See also: https://gitlab.com/monasca-installer/ansible-monasca-ui/blob/master/templates/local_settings.py.j2#L55 - the monasca-installer puts a URL in there as well.
=> horizon: fix KIBANA_HOST setting

chef/cookbooks/keystone/recipes/server.rb, chef/data_bags/crowbar/migrate/keystone/110_add_updated_password.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/app/views/barclamp/keystone/_edit_attributes.html.haml, crowbar_framework/config/locales/keystone/en.yml
Before this, we could not update the password of the admin user in keystone
due using the same var for auth and the new password.
=> keystone: Allow updating the admin pass after barclamp deployment

monasca.yml
It only depends on keystone, so we could deploy it sooner.
=> monasca: put monasca proposal in order after keystone

chef/cookbooks/horizon/recipes/server.rb
Without this patch, the horizon service reload produces strange
non-fatal errors in the chef logs:
```
ERROR: service[horizon] (horizon::server line 33) had an error: Expected process to exit with [0], but received ''
```
This happens because while pkill is smart enough not to include its own
PID in its matching processes, it is not smart enough not to include its
parent process. When chef executes a command, it shells out using 'sh
-c', then because the command includes a '&&' it must fork and exec the
pkill command rather than simply execing, so the command "sh -c pkill
--signal SIGUSR1 '(wsgi:horizon)' && sleep 1" is in the process table
and gets caught by pkill. You can see this in action by comparing these
commands:
```
$ sh -c "pgrep -alf foobar && true"
586 sh -c pgrep -alf foobar …
```
=> horizon: Fix pkill process search (bsc#1035270)

chef/cookbooks/keystone/templates/default/openrc.erb
The previously set OS_TENANT_NAME is deprecated with the switch
to Keystone v3, so it is time to switch to the new setting..
=> keystone: Set OS_PROJECT_NAME in openrc

chef/cookbooks/monasca/recipes/agent.rb, chef/cookbooks/monasca/templates/default/monasca-reconfigure.erb, chef/data_bags/crowbar/template-monasca.json, chef/data_bags/crowbar/template-monasca.schema, crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml, crowbar_framework/config/locales/monasca/en.yml
There were some options in the monasca-agent config which where in fact
only used by the monasca-reconfigure template (which triggers a
monasca-setup call).
Given that we do not use (and do not recommend) the monasca-reconfigure
script, delete these options and add a generic "extra_params" option
which can be used to customize the monasca-reconfigure script.
=> monasca: Cleanup monasca-setup script generator

crowbar_framework/app/models/aodh_service.rb, crowbar_framework/app/models/barbican_service.rb, crowbar_framework/app/models/ceilometer_service.rb, crowbar_framework/app/models/cinder_service.rb, crowbar_framework/app/models/database_service.rb, crowbar_framework/app/models/glance_service.rb, crowbar_framework/app/models/heat_service.rb, crowbar_framework/app/models/horizon_service.rb, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/app/models/magnum_service.rb, crowbar_framework/app/models/manila_service.rb, crowbar_framework/app/models/monasca_service.rb, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/app/models/nova_service.rb, crowbar_framework/app/models/rabbitmq_service.rb, crowbar_framework/app/models/sahara_service.rb, crowbar_framework/app/models/swift_service.rb, crowbar_framework/app/models/tempest_service.rb, crowbar_framework/app/models/trove_service.rb
Since the logger parameter became optional for ServiceObjects[1],
deactivating a proposal has been broken, producing a cryptic error in
the UI:
wrong number of arguments (0 for 1)
This is because deactivating a proposal causes a lookup of proposal
dependencies which are no longer initialized with an argument[2], but
all of the OpenStack barclamps still require this parameter. This patch
makes the OpenStack barclamps compatible with the new interface, though
more work will need to be done to clean up use of the logger parameter.
[1] https://github.com/crowbar/crowbar-core/pull/1025
[2] https://github.com/crowbar/crowbar-core/pull/1025/files#diff-494b2794304fa30be60cafd3d2c7f161
=> Make logger parameter optional

crowbar_framework/app/helpers/barclamp/monasca_helper.rb
Instead of showing "ERROR", show "Error" and do the same for the other
log levels.
=> monasca: Make UI log levels pretty

chef/cookbooks/monasca/recipes/server.rb, chef/data_bags/crowbar/template-monasca.json
This pull request adds the roles we need to use the Kibana/Grafana dashboards in Monasca.
=> Add missing keystone roles for Monasca

chef/cookbooks/nova/templates/default/nova.conf.erb
The trailing -% caused erb to leave out the newline, which causes
this to be concatened and consequently non-working.
=> nova: fix cpu model overwrites

chef/cookbooks/monasca/recipes/master.rb
This pull request should fix our current issues with the Monasca Kibana dashboard. I haven't fully tested this yet and I'm still unsure why we do not see logs when the dashboard _is_ working (even though curling the elasticsearch index does show some), so marking this WIP for now.
=> monasca: fix Kibana dashboard

chef/cookbooks/monasca/recipes/master.rb
This will use `cluster-data.c0.cloud.suse.de` with Keystone cluster
=> monasca: Fix keystone host to use FQDN instead of fixed IP

chef/cookbooks/keystone/recipes/server.rb, chef/data_bags/crowbar/migrate/keystone/111_add_wsgi_params.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema
It seems our default was way too low, especially for the UUID
backend. In experiments a chef-client on the controller node
was speed up almost by factor two by raising numbers accordingly.
=> keystone: Raise and expose number of wsgi workers

chef/data_bags/crowbar/migrate/magnum/101_add_cluster_user_trust.rb
The key is called trustee not trust. See
https://github.com/crowbar/crowbar-openstack/blob/master/chef/data_bags/crowbar/template-magnum.json#L17
=> magnum: Fix add_cluster_user_trust migration (bsc#1038122)

chef/cookbooks/monasca/recipes/master.rb, chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
Save MD5 of variables for Ansible to lock file and compare it on every
Chef run.
=> monasca: Re-execute installer on variables change

chef/cookbooks/horizon/recipes/server.rb
In commit a64765b1 we removed the ignore_failure setting for the
horizon wsgi worker reload resource, intending to treat command failures
as fatal. This became a problem because there are still cases where the
refresh might fail, such as when apache is starting and there are no
wsgi processes yet, and we don't want that to cause the chef run to
abort. While we search for these corner cases, this patch adds back the
ignore_failure parameter so that chef can continue to run even if the
refresh fails.
=> Re-add ignore_failure param for horizon service

chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb, chef/data_bags/crowbar/migrate/neutron/109_add_agent_boot_time.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
With L2pop, when the first port on a node gets active, or when the agent
is still starting (uptime of agent  < agent_boot_time), then a full sync
of the L2pop for that network is done.
The sync therefore does not happen if there are more than one port on
the node (like dhcp + router) and if the agent gets the port
notification after start+agent_boot_time.
The first condition can occur fairly easily, and the second definitely
happens when the cloud is large and/or on boot (because the l3 agent
and the dhcp agent are start after the ovs agent, and sometimes the
addition of the ports can hence happen long after ovs agent has
started).
Closes https://github.com/sap-oc/crowbar-openstack/issues/36
=> neutron: Add ability to specify agent_boot_time

chef/cookbooks/monasca/providers/agent_plugin_kafka.rb, chef/cookbooks/monasca/providers/agent_plugin_zookeeper.rb, chef/cookbooks/monasca/recipes/monitor_monasca.rb, chef/cookbooks/monasca/resources/agent_plugin_kafka.rb, chef/cookbooks/monasca/resources/agent_plugin_zookeeper.rb
The monasca-agent has a plugin system to configure monitoring in
different scenarios. One plugin is the 'kafka' plugin which can
collect data from kafka.
This commit adds a LWRP and also uses it to collect kafka data.
=> monasca: more agent checks

chef/cookbooks/heat/templates/default/heat.conf.erb, chef/cookbooks/manila/templates/default/manila.conf.erb, chef/cookbooks/trove/templates/default/trove.conf.erb
Building on an earlier commit that fixed Magnum, fix Heat, Manila
and Trove configuration templates to use the New World Order of
Keystone settings. As a drive-by, remove the lots of lines checking
the insecure setting in the heat template.
Builds on the work started in https://github.com/crowbar/crowbar-openstack/pull/867, but doesn't require it.
=> heat,manila,trove: Switch to new keystone settings

chef/cookbooks/horizon/recipes/server.rb
Horizon plugin for Ironic baremetal service will be installed when ironic services are detected when configuring Horizon.
=> Ironic horizon ui

chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/ironic/attributes/default.rb, chef/cookbooks/ironic/recipes/server.rb, chef/cookbooks/ironic/templates/default/ironic.conf.erb, chef/data_bags/crowbar/migrate/ironic/101_add_enabled_drivers.rb, chef/data_bags/crowbar/template-ironic.json, chef/data_bags/crowbar/template-ironic.schema, crowbar_framework/app/models/ironic_service.rb, crowbar_framework/config/locales/ironic/en.yml
Ironic agent_* drivers require proper Swift configuration for downloading
images. Additional validations were added to Ironic barclamp to make sure
all requirements are in place when using agent_* drivers.
Ironic uses TempURL feature of Swift for providing images to deployment
agent. Random TempURL key is set for glance user if it was not defined
before.
Ironic barclamp was modified to expose enabled_drivers as an attribute.
=> Ironic agent with swift

chef/cookbooks/keystone/providers/register.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/resources/register.rb
We were missing giving out the admin role for the default admin
to the admin user, thus horizon would not display the domains
panel.
In order to do this a new action is created on the keystone helpers
add_domain_role that would take a user, a role and a domain and grant
that user the given role in that domain.
Unfortunately, the calls to the domain role modify will return
"204 - No content" on create/update so the "_update_item" method on
the keystone provider needed an update to also accept a http 204 as
"success". As to not affect any other calls that may receive a 204
but turning that response into a success is not wanted, a new parameter
was introduced into the function to activate this behaviour. This
safely allows the introduction of the new response as valid only for
those calls …
=> keystone: grant admin role for default domain to admin (bsc#1040822)

chef/cookbooks/ironic/recipes/server.rb, chef/cookbooks/ironic/templates/default/ironic.conf.erb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/ironic/102_add_autoclean.rb, chef/data_bags/crowbar/template-ironic.json, chef/data_bags/crowbar/template-ironic.schema, crowbar_framework/app/views/barclamp/ironic/_edit_attributes.html.haml, crowbar_framework/config/locales/ironic/en.yml
A new attribute was added to disable automatic cleaning of baremetal nodes. This is especially useful during testing and development as the cleaning procedure can take a lot of time. For production it is not recommended but there are also some cases where it can be useful (e.g. when one tenant wants to quickly re-cycle hardware).
Second commit is update of nova conf to remove some deprecation warnings.
=> Ironic: add option to disable autoclean + conf update

chef/cookbooks/monasca/files/default/monasca-installer.logrotate, chef/cookbooks/monasca/recipes/master.rb
By popular demand: log full debug output from monasca-installer to `/var/log/monasca-installer.log`.
=> monasca: log monasca-installer output

chef/cookbooks/monasca/recipes/master.rb
The dual execute resources in master.rb caused monasca-installer to be run twice upon initial deployment. This commit replaces them by a single execute resource. It performed well for initial deployment, but please do not merge just yet, since I'd like to test all the corner cases we originally added the dual execute resources for.
=> monasca: fix double monasca-installer run

chef/cookbooks/tempest/recipes/config.rb
For some reason the keystone resources used on the
tempest cookbook are forced to run on the compile phase.
Not only there seems to be no reasoning behind this written
anywhere, but also causes issues in case we modify the keystone
protocol or endpoints, as the resources will run before anything
in the keystone cookbook.
This change makes the resources run at the proper execution phase
so this respects the cookbook ordering, making keystone resources
run always first.
=> tempest: run resources on the execute phase

chef/cookbooks/monasca/providers/agent_plugin_postfix.rb, chef/cookbooks/monasca/providers/agent_plugin_process.rb, chef/cookbooks/monasca/recipes/monitor_monasca.rb, chef/cookbooks/monasca/resources/agent_plugin_postfix.rb, chef/cookbooks/monasca/resources/agent_plugin_process.rb
The monasca-agent has a plugin system to configure monitoring in
different scenarios. One plugin is the 'postfix' plugin which can
collect data from postfix.
This commit adds a LWRP and also uses it to collect postfix data.
=> monasca: More LWRP and checks

chef/cookbooks/keystone/recipes/server.rb
Due to not enough guards, the update_endpoint resource in the
keystone cookbook was executing on every run, causing several
extra calls to the keystone endpoints, including updating
the endpoint on every chef run.
This adds an extra guard to avoid executing it in case
the protocol nor the insecure or port have changed, thus
only updating the endpoints when they need to be updated.
As a side effect it also removes a log line that was not needed.
=> keystone: Avoid executing update_endpoint for no reason

chef/cookbooks/ironic/attributes/default.rb
Paramiko is needed for all SSH based drivers.
=> ironic: Added missing dependency for agent_ssh

chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/data_bags/crowbar/migrate/cinder/107_remote_nfs_mount_options.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema, crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml, crowbar_framework/config/locales/cinder/en.yml
Hint for nfs_shares value encourages user to put the options there
already, so we do not need extra field for specifying Mount Options.
An alternative approach to https://github.com/crowbar/crowbar-openstack/pull/939
UPDATE: not only that it is redundant, nfs_mount_options actually does not work
=> cinder: Remove nfs_mount_options key as redundant (bsc#1036369)

chef/cookbooks/neutron/files/default/sysctl-neighbour-table-overflow.conf, chef/cookbooks/neutron/recipes/common_agent.rb
When having too many routers on a network node, we have seen messages in
the kernel log, like:
net_ratelimit: 26 callbacks suppressed
And experiencing ping returning:
ping: sendmsg: Invalid argument
This change adds some settings to increase the garbage collector's
thresholds. For more information, see also:
* https://bugs.launchpad.net/fuel/+bug/1488938
* man 7 arp
this is the forward port from: https://github.com/sap-oc/crowbar-openstack/pull/44
=> Adjust neighbour table thresholds (bsc#1035923)

chef/cookbooks/neutron/attributes/default.rb, chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/neutron/recipes/vmware_dvs_agents.rb, chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb, chef/cookbooks/neutron/templates/default/vmware_dvs_agent.ini.erb, chef/cookbooks/nova/attributes/default.rb, chef/data_bags/crowbar/migrate/neutron/110_add_vmware_dvs_attributes.rb, chef/data_bags/crowbar/migrate/nova/118_add_vmware_dvs_attrs.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/assets/javascripts/barclamps/neutron/application.js, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/config/locales/neutron/en.yml
The PR extends the neutron barclamp to add support for the vmware_dvs ML2 mechanism driver available from the [openstack/networking-vsphere](https://github.com/openstack/networking-vsphere) GitHub project.
The plugin allows VMware/ESXi VMs to be attached to the VLAN-based neutron networks that are already implemented through the linuxbridge or openvswitch ML2 mech driver. It also provides the following features:
- connecting KVM VMs and VMware VMs to the same provider or tenant network
- for VMware VMs:
- security groups support 
- DHCP & metadata support
- L3 services (routers, floating IPs, LBaaS, FWaaS etc)
Some architectural highlights:
- new s/w components are shipped with the openstack-networking-vsphere package
- the openvswitch or linuxbridge ML2 mech driver and the VLAN ML2 type …
=> neutron: add VMware DVS ML2 networking support

chef/cookbooks/heat/templates/default/heat.conf.erb
we can revert this if https://review.openstack.org/#/c/473543/ is
merged. The review backports the original fix to newton branch.
=> heat: heat-engine uses a old keys from keystone_authtoken

chef/cookbooks/tempest/recipes/install.rb
[].empty gives the expected result
=> tempest: search of roles:monasca_server effectively

chef/cookbooks/tempest/recipes/config.rb, chef/data_bags/crowbar/template-monasca.json
This pull request creates two roles required by the Monasca tempest tests:
* Create monasca-read-only-user (allows read-only access to monasca-api) in
Monasca barclamp
* Create role `anotherrole` as part of tempest setup (used by Monasca tempest
tests)
I split them across these two barclamps because it makes sense to generally create  `monasca-read-only-user` in the Monasca barclamp.
=> monasca, tempest: create missing Monasca roles

chef/cookbooks/tempest/recipes/install.rb
When searching, the role is called 'monasca-server' and not
'monasca_server'.
=> tempest: Fix spelling of the monasca-server role

chef/cookbooks/heat/templates/default/heat.conf.erb
Tempest seems to pass with this change.
partial revert: https://github.com/crowbar/crowbar-openstack/commit/eef7a80fe8835cd9e8ea2401039bd9d532799268
(cherry picked from commit d0e707c)
=> heat: revert to using older config options

crowbar_framework/app/models/aodh_service.rb, crowbar_framework/app/models/barbican_service.rb, crowbar_framework/app/models/ceilometer_service.rb, crowbar_framework/app/models/cinder_service.rb, crowbar_framework/app/models/database_service.rb, crowbar_framework/app/models/glance_service.rb, crowbar_framework/app/models/heat_service.rb, crowbar_framework/app/models/horizon_service.rb, crowbar_framework/app/models/ironic_service.rb, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/app/models/magnum_service.rb, crowbar_framework/app/models/manila_service.rb, crowbar_framework/app/models/monasca_service.rb, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/app/models/nova_service.rb, crowbar_framework/app/models/rabbitmq_service.rb, crowbar_framework/app/models/sahara_service.rb, crowbar_framework/app/models/swift_service.rb, crowbar_framework/app/models/tempest_service.rb, crowbar_framework/app/models/trove_service.rb
Since we allow deployments of 2 different SP versions, make sure only SP3 are used for openStack.
(SP2 nodes are for ceph)
=> Allow deployment of OpenStack roles to SP3 nodes only.

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
Until volume encryption is supported for RBD in Nova
(i.e. through qemu native RBD encryption), the tempest
tests that cover this scenario will have to be skipped
in Ceph environments.
This disables the following tempest test cases now failing 
in the cloud-mkcloud7-job-4nodes-linuxbridge-tempestfull-x86_64
CI job:
tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_cryptsetup
tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_luks
=> Tempest: disable encryption for RBD volumes

chef/cookbooks/tempest/recipes/config.rb, chef/cookbooks/tempest/templates/default/tempest.conf.erb
Cloud7 backport from #1015 
Until volume encryption is supported for RBD in Nova
(i.e. through qemu native RBD encryption), the tempest
tests that cover this scenario will have to be skipped
in Ceph environments.
This disables the following tempest test cases now failing
in the cloud-mkcloud7-job-4nodes-linuxbridge-tempestfull-x86_64
CI job:
tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_cryptsetup
tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_luks
=> [4.0] Tempest: skip volume encryption test cases for RBD

chef/cookbooks/horizon/files/default/grafana-openstack.json
In HA clouds a given service may be up on one controller and down on another.
In this case, the behaviour of the Grafana dashboard is undefined since it may
use the value from either http_status metric for displaying the service's
status. By computing the maximum over all status checks we get a more accurate
reading, i.e. the status transitions to DOWN if any backend is down in the time
period under scrutiny and remains UP otherwise.
=> horizon: fix Openstack Grafana for HA clouds

chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
This change move the double quotes into the brackets.
=> monasca: Fix the host configuration of curator

chef/cookbooks/monasca/attributes/default.rb, chef/cookbooks/monasca/libraries/helper.rb, chef/cookbooks/monasca/recipes/server.rb
This PR needs back porting to stable/4.0, unfortunately I don't have permissions (?) to add the appropriate label :(
=> monasca: Register logs endpoints in keystone

chef/cookbooks/horizon/templates/default/_80_monasca_ui_settings.py.erb
Configuration file for monasca-ui was missing
KIBANA_POLICY_SCOPE and KIBANA_POLICY_RULE
variables that are used when taking a decison
wheter or not given user should see buttont that
opens up Kibana.
Depends-On: https://review.openstack.org/#/c/472575/
=> monasca: Specify policy values for kibana button

crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
Requires backporting to stable/4.0
=> monasca: Hide password in SMTP configuration

chef/cookbooks/monasca/recipes/agent.rb
I forgot actually passing the correct log API into the template in https://github.com/crowbar/crowbar-openstack/pull/1007. This commit fixes that omission.
=> monasca: monitor correct monasca-log-api URL.

chef/cookbooks/mysql/attributes/server.rb, chef/cookbooks/mysql/recipes/client.rb, chef/cookbooks/mysql/recipes/server.rb, chef/cookbooks/mysql/templates/default/my.cnf.erb
Some simple fixes to make mysql/mariadb work again on SLES 12.
This is currently not really required an just the result of a small experiment with mariadb on Cloud 7. It might be interesting for our way to Cloud 8 though.
(There is no HA support)
=> Fix mysql cookbook for SLES12

chef/cookbooks/horizon/files/default/grafana-monasca.json, chef/cookbooks/horizon/files/default/grafana-openstack.json
If the browser time zone differs from the time zone of
the monasca-server node we may get 'no results found'
until local time in the browser catches up with the
monasca-server node's time zone for the first time.
(cherry picked from commit 585de206aa49a09b424bbf9873e1a8484970b62c)
=> monasca: Hardwire grafana timezone to UTC

chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
This should make monasca-log-api and monasca-api work with SSL enabled Keystone. Please do not merge yet, for it only configures monasca-log-api correctly so far. It still fails to configure monasca-api correctly.
=> Configure Monasca for Keystone enabled SSL

chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
This commit passes additional parameters to monasca-installer
in order to configure the [keystone_authtoken] correctly for
monasca-api and monasca-log-api.
(cherry picked from commit 5349119d36320dc20dafb274a81b0ecbe0dd1e8a)
=> monasca: make monasca-installer aware of SSL enabled Keystone

chef/cookbooks/monasca/libraries/helper.rb, chef/cookbooks/monasca/recipes/agent.rb
The monasca-log-api health check had an extra "v3.0" in its URL which
caused it to always fail. This commit generates a proper URL.
=> monasca: fix health check URL for monasca-log-api.

chef/cookbooks/horizon/files/default/grafana-monasca.json
this is consistent with what we did for the OpenStack dashboard
and makes the graph slightly more bearable.
=> monasca: Disable load_avg 5 and 15 min graphs on monasca dashboard

chef/cookbooks/postgresql/recipes/server_redhat.rb, chef/cookbooks/rabbitmq/recipes/default.rb
=> ha: Fix postgresql and rabbitmq crm services

chef/cookbooks/horizon/files/default/grafana-monasca.json
Monasca Health Grafana dashbouard should only include monitoring nodes.
Use filtering by service=monitoring to achieve that.
Also fix disk usage graph.
=> monasca: Filter out non-monitoring nodes on monasca dashboard

chef/cookbooks/sahara/templates/default/sahara.conf.erb, chef/data_bags/crowbar/migrate/sahara/102_add_use_barbican_key_manager.rb, chef/data_bags/crowbar/template-sahara.json, chef/data_bags/crowbar/template-sahara.schema, crowbar_framework/app/models/sahara_service.rb, crowbar_framework/app/views/barclamp/sahara/_edit_attributes.html.haml, crowbar_framework/config/locales/sahara/en.yml
People can configure on the barclamp's UI if they want to use Barbican's
key manager.
=> sahara: use barbican key manager made configurable

chef/cookbooks/sahara/templates/default/sahara.conf.erb, chef/data_bags/crowbar/migrate/sahara/102_add_use_barbican_key_manager.rb, chef/data_bags/crowbar/template-sahara.json, chef/data_bags/crowbar/template-sahara.schema, crowbar_framework/app/models/sahara_service.rb, crowbar_framework/app/views/barclamp/sahara/_edit_attributes.html.haml, crowbar_framework/config/locales/sahara/en.yml
People can configure on the barclamp's UI if they want to use Barbican's
key manager.
(cherry picked from commit 7f3fc4f45a65c719c660fbe4b3ab3e5769fab4aa)
=> [4.0] sahara: use barbican key manager made configurable

chef/cookbooks/ceilometer/recipes/server.rb
Since Ocata, 'ceilometer-dbsync' is no longer
available. 'ceilometer-upgrade' is the new command.
=> ceilometer: Use ceilometer-upgrade command

chef/cookbooks/monasca/templates/default/log-agent.conf.erb
This commit adds the keystone_api_insecure setting to
agent.yaml. This setting defaults to false, so we set
it to the value of keystone_settings['insecure'] for
monasca-log-agent to work in clouds with unsigned
Keystone API certificates.
=> monasca: fix SSL for monasca-log-agent

chef/cookbooks/nova/recipes/compute_ha.rb
A potential issue was identified in ACI integration for compute HA. The primitive was appended even if the pacemaker resource was not created when ACI plugins were enabled. Also the variable was wrongly named as `compute_primitives` instead of `compute_primitives_to_clone`. The PR corrects these minor issues.
=> nova: correct handling of neutron_agent for cisco_apic

chef/cookbooks/postgresql/recipes/server_redhat.rb, chef/cookbooks/rabbitmq/recipes/default.rb
Backport of: #1029
Without these patches, the postgresql and rabbitmq OCF resource agents cannot be
restarted by crowbar. When running in HA mode, if the service is
notified to restart, both controller nodes will claim that the service
is not running. Since it is managed as a special OCF resource agent
instead of as a systemd resource, it is necessary to use crm to check
whether it is running and to restart it. This pull request sets the
restart_crm_resource field in the 'supports' parameter for the
postgresql and rabbitmq services so that they can be properly restarted if necessary.
This was not noticed previously because the configuration options for
these services are rarely changed and so they rarely requires a
restart. However, the resource limits management feature added in pr#974 …
=> [4.0] ha: Fix postgresql and rabbitmq crm services

chef/cookbooks/postgresql/recipes/server_redhat.rb, chef/cookbooks/rabbitmq/recipes/default.rb
Without these patches, the postgresql and rabbitmq OCF resource agents cannot be
restarted by crowbar. When running in HA mode, if the service is
notified to restart, both controller nodes will claim that the service
is not running. Since it is managed as a special OCF resource agent
instead of as a systemd resource, it is necessary to use crm to check
whether it is running and to restart it. This pull request sets the 
restart_crm_resource field in the 'supports' parameter for the 
postgresql and rabbitmq services so that they can be properly restarted if necessary.
This was not noticed previously because the configuration options for 
these services are rarely changed and so they rarely requires a
restart. However, the resource limits management feature added in pr#974
requires …
=> [3.0] Fix postgresql and rabbitmq crm services

chef/cookbooks/horizon/files/default/grafana-monasca.json
This commit aligns the Monasca dashboard with the OpenStack one ("SUSE OpenStack Cloud Monitoring" title and dark theme). I tested this against a fresh cloud (built this afternoon) and it works.
=> horizon: fixed title/style for Monasca dashboard.

.travis.yml
We seem to be running into Travis-CI issues lately. Travis-CI has
switched their default VM to the trusty release which might be reason
for the issues we are seeing. This patch is only a test to verify that
this is the case (or not).
=> Insist on precise for Travis-CI

.travis.yml
backport from: https://github.com/crowbar/crowbar-openstack/pull/1073
Travis-CI has switched their default VM to the trusty release which also
upgraded the Ruby environment available.
This change updates our Travis-CI setting to a new Ruby environment
version, following [1].
[1] https://github.com/crowbar/crowbar-core/commit/cb037a689155c94cbef709d8bcb50dd4b1390e76
=> Update Ruby environment for trusty Travis-CI image

chef/cookbooks/keystone/attributes/default.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/templates/default/keystone.conf.erb, chef/data_bags/crowbar/migrate/keystone/200_remove_deprecated_opts.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema
This patch removes settings that were deprecated in Ocata and earlier.
These changes are all compatible with the Newton release incorporated in
Cloud 7.
* Remove use of the "verbose" setting. This was deprecated in oslo.log
in favor of always logging at the INFO level[1].
* Remove settings for [eventlet_server]. The eventlet server has been
deprecated since kilo[2], though the config options remain in tree in
Ocata and were not removed in Mitaka as planned. We are not making use
of the eventlet server, we only support apache and uwsgi as frontends,
and only test on apache. The bind port and host settings that are
exposed to the user are still valid for these alternate frontends so
we do not remove them from the databag, only from the
[eventlet_server] section in the config file.
* Remove …
=> keystone: Remove deprecated options (SCRD-46)

Rakefile
Looks like travis installs all gems to the vendor dir,
that means that the syntaxcheck will check all the ruby files
under that directory, slowing down the travis work for no reason.
This removes any rb files coming from under the vendor directory
=> rakefile: avoid doing the syntaxcheck on vendor dir

chef/cookbooks/nova/recipes/controller_ha.rb
haproxy needs to be setup in front of the placement API services. Otherwise
no service is listening on the correct port and the placement API is not
responsive.
=> nova: Fix placement API setup in HA

crowbar_framework/app/models/aodh_service.rb, crowbar_framework/app/models/barbican_service.rb, crowbar_framework/app/models/ceilometer_service.rb, crowbar_framework/app/models/cinder_service.rb, crowbar_framework/app/models/glance_service.rb, crowbar_framework/app/models/heat_service.rb, crowbar_framework/app/models/horizon_service.rb, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/app/models/magnum_service.rb, crowbar_framework/app/models/manila_service.rb, crowbar_framework/app/models/monasca_service.rb, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/app/models/nova_service.rb, crowbar_framework/app/models/openstack_service_object.rb, crowbar_framework/app/models/rabbitmq_service.rb, crowbar_framework/app/models/sahara_service.rb, crowbar_framework/app/models/swift_service.rb, crowbar_framework/app/models/trove_service.rb, crowbar_framework/lib/openstack.rb, crowbar_framework/lib/openstack/data_bag_config.rb
As we commonly search for the insecure value of a service in
all cookbooks, we provide a helper to quickly gather that value.
This is only the first building block, next one will save those insecure
values into the databag.
=> crowbar: Use databags to store config

chef/cookbooks/glance/attributes/default.rb, chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/cookbooks/glance/templates/default/glance-cache.conf.erb, chef/cookbooks/glance/templates/default/glance-manage.conf.erb, chef/cookbooks/glance/templates/default/glance-registry.conf.erb, chef/cookbooks/glance/templates/default/glance-scrubber.conf.erb, chef/data_bags/crowbar/migrate/glance/200_remove_deprecated_opts.rb, chef/data_bags/crowbar/template-glance.json, chef/data_bags/crowbar/template-glance.schema
The following deprecated glance & related config options
are removed in this PR:
* [default]/verbose deprecated option
* [glance_store]/vmware_api_insecure - renamed to vmware_insecure
* [keystone_authtoken]/service_token_roles_required is set
to True to enable fetching expired tokens based on valid
service tokens
The following deprecated glance config options are NOT
removed in this commit:
* [default]/show_multiple_locations - this option is still required
to enable cinder internal image transfer and there is no alternative
in place (see bsc#945043). When this option is removed, it is expected
that the underlying feature will be enabled by default, in which case
the policy.json file is already updated in the glance package
to protect against unauthorized access (see …
=> glance: remove options deprecated in ocata

chef/cookbooks/glance/metadata.rb, chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/glance/recipes/registry.rb, chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/cookbooks/glance/templates/default/glance-registry.conf.erb, chef/cookbooks/neutron/metadata.rb, chef/cookbooks/neutron/recipes/common_config.rb, chef/cookbooks/neutron/templates/default/neutron.conf.erb, chef/cookbooks/nova/templates/default/nova.conf.erb
The deprecated keystonemiddleware.auth_token in-process token
cache used by various services (glance-api, glance-registry, neutron-server, nova-api, nova-scheduler, etc) is replaced with a memcached server. When HA is used, several memcached servers are configured and used, one for each controller node.
References:
* Mitaka release notes for keystonemiddleware: https://docs.openstack.org/releasenotes/keystonemiddleware/mitaka
=> replace auth_token in process cache with memcached

chef/data_bags/crowbar/migrate/cinder/102_use_multipath.rb
(cherry picked from commit 88a1778c45b1e649ab5d187007fb8a68b42175d8)
=> cinder: Fix broken downgrade in schema migration

crowbar_framework/app/models/aodh_service.rb, crowbar_framework/app/models/barbican_service.rb, crowbar_framework/app/models/ceilometer_service.rb, crowbar_framework/app/models/cinder_service.rb, crowbar_framework/app/models/glance_service.rb, crowbar_framework/app/models/heat_service.rb, crowbar_framework/app/models/horizon_service.rb, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/app/models/magnum_service.rb, crowbar_framework/app/models/manila_service.rb, crowbar_framework/app/models/monasca_service.rb, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/app/models/nova_service.rb, crowbar_framework/app/models/openstack_service_object.rb, crowbar_framework/app/models/rabbitmq_service.rb, crowbar_framework/app/models/sahara_service.rb, crowbar_framework/app/models/swift_service.rb, crowbar_framework/app/models/trove_service.rb, crowbar_framework/lib/openstack.rb, crowbar_framework/lib/openstack/data_bag_config.rb
Makes all barclamps inherit from OpenstackServiceObject which automatically calls
the save_to_databag method in order to save config values after the chef run into a databag.
In this commit, only the insecure values and the rabbitmq host values are being saved into the
databags
(cherry picked from commit 1a869e073eb63d397bba12844705c4dab1e36cbf)
=> [4.0] crowbar: Use databags to store config values for services

chef/data_bags/crowbar/template-tempest.json
It's that time of the year again. It is only a security fix rebase
of 0.3.4, so it should go in pretty smoothly.
=> tempest: Update to use cirros 0.3.5

chef/cookbooks/horizon/templates/centos/local_settings.py.erb, chef/cookbooks/horizon/templates/redhat/local_settings.py.erb
This patch removes usage of the TEMPLATE_DEBUG parameter from the
RHEL-based horizon config templates. Django template debugging is now
tied to the regular DEBUG parameter[1]. We were already not using this
parameter in the regular SUSE config templates, so this patch is just a
minor cleanup.
[1] https://docs.openstack.org/releasenotes/horizon/ocata.html
=> horizon: Update for Ocata

chef/cookbooks/heat/templates/default/heat.conf.erb
Using keystoneauth credentials for trustee user was deprecated, and
removed since ocata release. Trustee credentials must be defined in
a separate conf section now. We already have this section populated,
but it needs a few adjustments: need to provide auth_type, user and
project domain ids. Also, project_name needs to be removed, because
trustee token is scoped to a trust.
=> heat: justify trustee credentials

crowbar_framework/app/models/manila_service.rb
When adding extra sections to the ceph config, the node hash might
not be initialized which leads to:
undefined method `[]' for nil:NilClass
=> manila: Init node hash for ceph config (bsc#1051229)

chef/cookbooks/manila/recipes/common.rb, chef/cookbooks/manila/templates/default/manila.conf.erb, chef/data_bags/crowbar/migrate/manila/200_add_memcache_secret_key.rb, chef/data_bags/crowbar/template-manila.json, chef/data_bags/crowbar/template-manila.schema, crowbar_framework/app/models/manila_service.rb
Use the service_token_roles and service_token_roles_required parameters
to ensure properly authenticated interservice communication and to avoid
deprecation warnings[1].
Add a memcached instance for the manila controller and configure manila
to use it for token caching, since the in-process token cache is
deprecated and produces warnings[2]. This includes adding a parameter to
generate a secret key to use for cache encryption.
[1] https://docs.openstack.org/releasenotes/keystonemiddleware/ocata.html
[2] https://docs.openstack.org/releasenotes/keystonemiddleware/mitaka.html
manila: Add memcached servers
=> manila: Update keystone_authtoken parameters

chef/cookbooks/neutron/recipes/post_install_conf.rb, chef/cookbooks/tempest/recipes/config.rb
Replaces deprecated usage of neutronclient CLI occurrences
with openstackclient CLI equivalent commands.
References:
* Ocata release notes for python-neutronclient: https://docs.openstack.org/releasenotes/python-neutronclient/ocata.html
* neutronclient to openstackclient CLI mapping guide: https://docs.openstack.org/python-openstackclient/latest/cli/decoder.html
Important: these modifications are not backwards-compatible with
Newton because the 'openstack router set --external-gateway'
command support is not available in Newton (introduced in
python-openstackclient 3.6.0).
=> neutron: migrate from neutronclient to openstackclient CLI

chef/cookbooks/mysql/recipes/server.rb, chef/cookbooks/mysql/templates/default/grants.sql.erb
We don't really care about debian, so let's clean up the
root password setting mechanism and stop using the grants.sql file.
=> mysql: Cleanup root password setting

crowbar_framework/app/models/openstack_service_object.rb
It seems that during the rake task of update_config_db the @logger
is not passed properly, which can cause @logger to be nil.
So instead of that, use the Rails.logger directly
fixes: SCRD-739
=> framework: Fix the OpenstackServiceObject logger to use Rails.logger directly

chef/cookbooks/swift/templates/default/proxy-server.conf.erb
Use the service_token_roles and service_token_roles_required parameters
that were introduced in Ocata and will soon become required[1] to ensure
properly authenticated interservice communication.
This wasn't producing deprecation warnings in the logs, but that is
likely due to a logging bug in swift[2]. Swift still uses
keystonemiddleware and we still need to keep its config up to date even
though swift wasn't kind enough to warn us about it.
[1] https://docs.openstack.org/releasenotes/keystonemiddleware/ocata.html
[2] https://bugs.launchpad.net/swift/+bug/1380815
=> swift: Update keystonemiddleware authtoken config

chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/data_bags/crowbar/migrate/glance/201_fill_databag_with_insecure.rb, chef/data_bags/crowbar/template-glance.json
the databag
Provides a migration that would look for the actual values
of the insecure attribute and create/update the databag with
them, so the cookbooks will always find the real value in there
instead of defaulting to false
=> Glance: get insecure values from databag

chef/cookbooks/neutron/recipes/common_config.rb, chef/cookbooks/neutron/recipes/post_install_conf.rb, chef/data_bags/crowbar/migrate/neutron/203_fill_databag_with_insecure.rb, chef/data_bags/crowbar/template-neutron.json
the databag
Provides a migration that would look for the actual values
of the insecure attribute and create/update the databag with
them, so the cookbooks will always find the real value in there
instead of defaulting to false
=> Neutron: get insecure values from databag

chef/cookbooks/nova/libraries/availability_zone.rb, chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/recipes/flavors.rb, chef/data_bags/crowbar/migrate/nova/202_fill_databag_with_insecure.rb, chef/data_bags/crowbar/template-nova.json
the databag
Provides a migration that would look for the actual values
of the insecure attribute and create/update the databag with
them, so the cookbooks will always find the real value in there
instead of defaulting to false
=> Nova: get insecure values from databag

chef/cookbooks/heat/recipes/server.rb, chef/data_bags/crowbar/migrate/heat/200_fill_databag_with_insecure.rb, chef/data_bags/crowbar/template-heat.json
Instead of doing a node search which is expensive, check
for the existance of the magnum databag which will mean that
magnum is deployed
=> Heat: use the databags to find if magnum is deployed

chef/data_bags/crowbar/migrate/glance/201_fill_databag_with_insecure.rb, chef/data_bags/crowbar/migrate/heat/200_fill_databag_with_insecure.rb, chef/data_bags/crowbar/migrate/neutron/203_fill_databag_with_insecure.rb, chef/data_bags/crowbar/migrate/nova/203_fill_databag_with_insecure.rb, chef/data_bags/crowbar/template-nova.json
Looks like during the upgrade, the templates being passed
to the upgrade method contains all values in strings and we
were trying to access them by symbol instead.
Also fixes a nova migration numbering issue.
=> migrations: fix databag migrations

crowbar_framework/app/views/barclamp/glance/_edit_attributes.html.haml, crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml, crowbar_framework/config/locales/glance/en.yml, crowbar_framework/config/locales/nova/en.yml
Removes the deprecated 'verbose' attribute from the custom view, left over from two previous PRs that removed the 'verbose' attribute from the glance (#1069) and nova (#1091) cookbooks.
=> glance,nova: remove leftover 'verbose' custom view attr

chef/cookbooks/crowbar-openstack/libraries/helpers.rb, chef/data_bags/crowbar/migrate/rabbitmq/200_fill_databag_with_settings.rb, chef/data_bags/crowbar/template-rabbitmq.json, crowbar_framework/app/models/rabbitmq_service.rb
Use the databag to provide the rabbitmq settings to other cookbooks.
Includes a rabbitmq migration to fill the rabbitmq databag in
case rabbitmq is already deployed when applying this commit.
=> crowbar-openstack: Use databag to search for rabbitmq settings

chef/cookbooks/heat/attributes/default.rb, chef/cookbooks/heat/metadata.rb, chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/heat/templates/default/heat.conf.erb, chef/data_bags/crowbar/migrate/heat/201_remove_deprecated_options.rb, chef/data_bags/crowbar/migrate/heat/202_add_memcache_secret_key.rb, chef/data_bags/crowbar/template-heat.json, chef/data_bags/crowbar/template-heat.schema, crowbar_framework/app/models/heat_service.rb, crowbar_framework/app/views/barclamp/heat/_edit_attributes.html.haml, crowbar_framework/config/locales/heat/en.yml
The following heat configuration options deprecated in Ocata (or earlier) are removed or replaced in this PR:
- [default]/verbose deprecated option removed
- [keystone_authtoken]/service_token_roles_required is set to True to enable fetching expired tokens based on valid service tokens and [keystone_authtoken]/service_token_roles is set to the admin role
- the following deprecated keystone_authtoken configuration options: _identity_uri_, _admin_user_,
_admin_password_, and _admin_tenant_name_ are replaced with _auth_url_, _project_name_, _project_domain_name_ and _user_domain_name_
The deprecated keystonemiddleware.auth_token in-process token cache used by heat services is replaced with a memcached server. When HA is used, several memcached servers are configured and used, one for each …
=> heat: ocata cookbook update

chef/cookbooks/sahara/recipes/common.rb, chef/data_bags/crowbar/migrate/sahara/201_fill_databag_with_insecure.rb, chef/data_bags/crowbar/template-sahara.json
the databag
Provides a migration that would look for the actual values
of the insecure attribute and create/update the databag with
them, so the cookbooks will always find the real value in there
instead of defaulting to false
=> Sahara: get insecure values from databag

chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/cookbooks/glance/templates/default/glance-registry.conf.erb, chef/cookbooks/neutron/templates/default/neutron.conf.erb, chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/migrate/glance/202_add_memcache_secret_key.rb, chef/data_bags/crowbar/migrate/neutron/204_add_memcache_secret_key.rb, chef/data_bags/crowbar/migrate/nova/204_add_memcache_secret_key.rb, chef/data_bags/crowbar/template-glance.json, chef/data_bags/crowbar/template-glance.schema, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/models/glance_service.rb, crowbar_framework/app/models/neutron_service.rb, crowbar_framework/app/models/nova_service.rb
This PR continues the work done in #1090 by configuring the auth_token keystone middleware for all services currently using memcached caching (neutron, glance, nova) to authenticate and encrypt the token data stored in memcached using a generated secret key.
More information: 
- https://docs.openstack.org/keystonemiddleware/latest/middlewarearchitecture.html#memcache-protection
=> nova,neutron,glance: keystone auth_token memcached protection

crowbar_framework/app/models/nova_service.rb
Fix the previous behaviour of allowing more than
one node or cluster to have the 'ec2-api' role
in the nova barclamp.
=> ec2-api: allow a single ec2-api node or cluster

chef/cookbooks/database/libraries/crowbar.rb, chef/cookbooks/mysql/recipes/ha_galera.rb, chef/cookbooks/mysql/recipes/server.rb, chef/cookbooks/mysql/templates/default/my.cnf.erb, crowbar_framework/app/models/database_service.rb, crowbar_framework/config/locales/database/en.yml
Add a ha_galera recipe that will install Galera on a cluster. It will
create Pacemaker resources for bootstrapping and monitoring the cluster,
with other support sprinkled into the mysql::server recipe.
A current limitation of the configuration it creates is, that it relies
on the passwordless user "''@'localhost'" for monitoring the local
cluster node.
Remove limitation that only PostgreSQL can be deployed in a HA fashion.
Co-Authored-By: Ralf Haferkamp <rhafer@suse.de>
Co-Authored-By: Jiří Suchomel <jiri.suchomel@suse.com>
=> mysql: Add support for HA provisioning with Galera

chef/cookbooks/keystone/recipes/server.rb
During the deployment of the keystone barclamp on an
HA cluster, it was observed that the apache service was
being restarted on a controller node (due to a delayed
reload action) while on another controller node the
default users/tenants/domains/etc. were being created.
This caused the second node to fail deploying the barclamp,
because there was a small time window during which the
keystone WSGI entry points on one of the controller nodes
could not be accessed.
This commit fixes this problem by ensuring two things:
- the default users/roles/domains/etc. are only created
by the cluster founder node
- an additional synchronization marker is used at the
beginning of the section that creates the keystone
objects to ensure that keystone services are properly
configured and running on all …
=> [4.0] keystone: fix ha race condition during default objects creation

chef/cookbooks/database/libraries/crowbar.rb, chef/cookbooks/mysql/recipes/ha_galera.rb, chef/cookbooks/mysql/recipes/server.rb, chef/cookbooks/mysql/templates/default/my.cnf.erb, crowbar_framework/app/models/database_service.rb, crowbar_framework/config/locales/database/en.yml
This is a backport of https://github.com/crowbar/crowbar-openstack/pull/1134
Add a ha_galera recipe that will install Galera on a cluster. It will
create Pacemaker resources for bootstrapping and monitoring the cluster,
with other support sprinkled into the mysql::server recipe.
A current limitation of the configuration it creates is, that it relies
on the passwordless user "''@'localhost'" for monitoring the local
cluster node.
Remove limitation that only PostgreSQL can be deployed in a HA fashion.
Co-Authored-By: Ralf Haferkamp <rhafer@suse.de>
Co-Authored-By: Jiří Suchomel <jiri.suchomel@suse.com>
(cherry picked from commit 2cd79d39e755712d6b26ad58be5834f80c70eaed)
=> [stable/4.0] mysql: Add support for HA provisioning with Galera

crowbar_framework/app/models/nova_service.rb
Fix the previous behaviour of allowing more than
one node or cluster to have the 'ec2-api' role
in the nova barclamp.
(backport of #1138)
=> [4.0] ec2-api: allow a single ec2-api node or cluster

chef/cookbooks/nova/recipes/database.rb
In commit b46e5ac8ac7f7d04ff6388879bea56d1462c0a72 we introduced the
cell0 database creation but unfortunately we give the rights to the
nova_api user which is wrong.
See
https://docs.openstack.org/ocata/install-guide-obs/nova-controller-install.html
=> nova: Fix cell0 database privileges (bsc#1053412)

chef/cookbooks/horizon/recipes/server.rb, chef/cookbooks/horizon/templates/default/local_settings.py.erb, chef/data_bags/crowbar/migrate/horizon/200_add_dashboard_secret_key.rb, chef/data_bags/crowbar/template-horizon.json, chef/data_bags/crowbar/template-horizon.schema, crowbar_framework/app/models/horizon_service.rb
In a HA environment the secret key used in Horizon to store the
session data is not shared, producing form with different CFSR
tokens. This invalidate the session after a HA failover.
This patch also reload the apache service when the local_settings
file is updated, removing the race condition from bsc#1051439
=> Horizon: add SECRET_KEY as an attribute (bsc#1051439)

chef/cookbooks/sahara/attributes/default.rb, chef/cookbooks/sahara/metadata.rb, chef/cookbooks/sahara/recipes/common.rb, chef/cookbooks/sahara/templates/default/sahara.conf.erb, chef/data_bags/crowbar/migrate/sahara/202_remove_deprecated_opts.rb, chef/data_bags/crowbar/migrate/sahara/203_add_memcache_secret_key.rb, chef/data_bags/crowbar/template-sahara.json, chef/data_bags/crowbar/template-sahara.schema, crowbar_framework/app/models/sahara_service.rb, crowbar_framework/app/views/barclamp/sahara/_edit_attributes.html.haml, crowbar_framework/config/locales/sahara/en.yml
The following sahara parameters are deprecated:
- DEFAULT.verbose
In addition, new parameters to the neutron.conf template:
- keystone_authtoken.service_token_roles_required
- keystone_authtoken.service_token_roles
- keystone_authtoken.memcached_server
- keystone_authtoken.memcache_security_strategy
- keystone_authtoken.memcache_secret_key
=> Sahara: remove deprecated parameters

chef/cookbooks/mysql/recipes/ha_galera.rb, chef/cookbooks/mysql/recipes/server.rb
The role might not be saved yet. It should be safe to use the
default search (pacemaker-cluster-member) because cluster_members
helper will take care that result is in the same cluster as current
node (by checking pacemaker_config_environment).
This should fix [bsc#1053703](https://bugzilla.suse.com/show_bug.cgi?id=1053703)
=> Do not search for nodes with database-server role

chef/cookbooks/ironic/attributes/default.rb, chef/cookbooks/ironic/libraries/helpers.rb, chef/cookbooks/ironic/recipes/server.rb, chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/recipes/post_install_conf.rb, chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/templates/default/nova.conf.erb, crowbar_framework/app/models/neutron_service.rb
This set of changes will enable deployment of ironic on non-neutron nodes. Also some old bugs with ironic deployment in HA clouds were fixed.
NOTE: these changes might possibly fix flapping status of CI jobs for ironic (looks like a race condition).
~~NOTE2: unfortunately the bug is still there after this change :o(~~
~~NOTE3: last commit is another attempt to fix this bug... looks promising~~
=> Ironic neutron decouple + HA fixes

chef/cookbooks/aodh/recipes/aodh.rb, chef/cookbooks/barbican/recipes/common.rb, chef/cookbooks/ceilometer/recipes/common.rb, chef/cookbooks/cinder/recipes/common.rb, chef/cookbooks/crowbar-openstack/libraries/helpers.rb, chef/cookbooks/ec2-api/recipes/ec2api.rb, chef/cookbooks/glance/recipes/common.rb, chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/ironic/recipes/server.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/magnum/recipes/common.rb, chef/cookbooks/manila/recipes/common.rb, chef/cookbooks/neutron/recipes/database.rb, chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/sahara/recipes/common.rb, chef/cookbooks/trove/libraries/helpers.rb, chef/cookbooks/trove/recipes/api.rb, chef/cookbooks/trove/recipes/conductor.rb, chef/cookbooks/trove/recipes/taskmanager.rb
This commit moves the creation of all OpenStack database connection
strings to a helper. This is required to change the string in one place
to use the correct driver everywhere. Additional we use now the correct
mysql driver and charset everywhere.
(cherry picked from commit 9fd40e760f4a3f8f7e2e56e0ba25780f724f87f1)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1157
=> [4.0] database: Move connection string creation to a helper (bsc#1053827)

chef/cookbooks/tempest/templates/default/tempest.conf.erb, chef/data_bags/crowbar/migrate/tempest/200_rename_manila_params.rb, chef/data_bags/crowbar/template-tempest.json, chef/data_bags/crowbar/template-tempest.schema
This patch updates the following config options noted as deprecated in
the ongoing release notes[1]:
- remove [image-feature-enabled]/deactivate_image which has not been
needed since kilo
- remove the entire [input-scenario] section which are nonfunctional
It also updates the following config options which are not mentioned in
the release notes but produce deprecation warnings tempest.log:
- switch [auth]/admin_tenant_name to [auth]/admin_project_name
- remove [scenario]/img_dir and the different image container formats
leaving only one raw disk image file
- update manila config option names
[1] https://docs.openstack.org/releasenotes/tempest/unreleased.html
=> tempest: Update for ocata

chef/cookbooks/mysql/recipes/ha_galera.rb, chef/cookbooks/mysql/recipes/server.rb
Backport of https://github.com/crowbar/crowbar-openstack/pull/1155
The role might not be saved yet in which case no cluster node would be found.
It should be safe to use the default search without specifying the role:
CrowbarPacemakerHelper.cluster_members helper will use pacemaker-cluster-member
role and by searching for pacemaker_config_environment from current node
it ensures that the nodes are not from any different cluster.
(cherry picked from commit 2fbfe4cf6f4d878e3ddb5868540bf27a18a3c47d)
=> Do not search for nodes with database-server role (bsc#1053703).

chef/cookbooks/neutron/recipes/server.rb
This is a prerequisite for DNS as a Service integration,
but also allows assigning a dns_name attribute to ports,
see
https://docs.openstack.org/newton/networking-guide/config-dns-int.html
=> neutron: enable dns extension

chef/cookbooks/ceilometer/attributes/default.rb, chef/cookbooks/ceilometer/recipes/common.rb, chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb, chef/data_bags/crowbar/migrate/ceilometer/200_remove_deprecated_opts.rb, chef/data_bags/crowbar/template-ceilometer.json, chef/data_bags/crowbar/template-ceilometer.schema, crowbar_framework/app/views/barclamp/ceilometer/_edit_attributes.html.haml, crowbar_framework/config/locales/ceilometer/en.yml
The following Ceilometer configuration options deprecated in Ocata (or earlier) are removed or replaced in this PR:
- [default]/verbose  deprecated option removed
References:
- Ocata release notes for Ceilometer: https://docs.openstack.org/releasenotes/ceilometer/ocata.html
=> SCRD-39 removed deprecated verbose option for ceilometer

chef/cookbooks/mysql/recipes/ha_galera.rb, chef/cookbooks/mysql/recipes/server.rb
(cherry picked from commit aa6a9815ec3249693856c8cf594bb468cf22d37c)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1161
=> [4.0] Use the same user for haproxy and RA monitoring.

chef/cookbooks/sahara/recipes/ha.rb
Name has spaces on it, while the rest of the other sync marks dont have
any spaces. This also causes problems with the existing task of trying
to move the sync marks into the pacemaker attributes, as the attributes
do not accept spaces, and we are using the name in the sync mark to set
it as the attribute.
(cherry picked from commit 4a38ace1c8cfef45eac296c3b36fd65d07df33e5)
=> [4.0] sahara: fix sahara sync mark name

chef/cookbooks/mysql/recipes/server.rb
The mysql_secure_install script drops all anonymous database users to
prevent unauthorized logins. Let's do the same in our cookbooks.
(cherry picked from commit 7c4e10f2430021cbe708001f3b906e20c8e74e74)
Backport from https://github.com/crowbar/crowbar-openstack/pull/1145
=> [4.0] mariadb: Drop anonymous database user

chef/cookbooks/ec2-api/recipes/ec2api.rb, chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb, chef/cookbooks/neutron/definitions/neutron_metadata.rb, chef/cookbooks/neutron/templates/default/metadata_agent.ini.erb
When ec2-api is enabled, the ec2-api-metadata service
must be used instead of nova-metadata-agent when configuring
neutron.
The EC2 metadata service needs to act as a proxy between neutron
and the original nova metadata agent, adapting the metadata
information according to the EC2 API specifications.
This PR also re-enables VPC, for two main reasons:
- without VPC enabled, ec2-api-metadata assumes it is running in a nova-network environment, which leads to failures (e.g. see [this upstream bug report](https://bugs.launchpad.net/ec2-api/+bug/1660888))
- this was initially part of #1151, which aims to enable and pass as many applicable ec2-api tempest test cases as possible
Given the fact that VPC support was previously disabled precisely to correct some tempest test failures, a full …
=> neutron,ec2-api: use ec2-api-metadata in neutron-metadata-agent

chef/cookbooks/nova/templates/default/nova.conf.erb
Currently, the nova.conf that is rendered by chef contains a lot of
empty newlines. This is cosmetically displeasing but also hinders
debugging because of the need to scroll further to see all declared
configuration options. Moreover, the markup in this template was
inconsistent with itself, so new additions had no good example to copy
from.
Chef uses Erubnis, which is not actually the same as ERB. One of the
main differences is that in Erubnis, `<% %>`, `<%- %>`, `<% -%>`, and
`<%- -%>` are all equivalent, i.e. the `-` is completely unnecessary.
Where the `-` makes a difference is when closing a `<%=` tag, especially
if the expression within the tags is conditional. There is not really
any documentation about this, so this evaluation is based on trial and
error and stackoverflow[1].
This …
=> nova: Clean up config template

chef/cookbooks/mysql/recipes/ha_galera.rb
1. lower the number of unsuccessful checks needed for declaring server DOWN (default is 5)
2. lower the interval checking after first failure is found (default is 2 seconds)
Requires https://github.com/crowbar/crowbar-ha/pull/220
=> Finetune haproxy settings for galera.

chef/cookbooks/crowbar-openstack/libraries/helpers.rb
db_auth may be passed as Chef::Node::Attribute, so let's make
sure we have Hash so we can correctly access its insides.
(cherry picked from commit 2ca4be4bdc6784cca5f783d62ad4f50804cf70f2)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1182
=> [4.0] Make sure the argument with auth settings is a Hash

chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
Fix according to deprecation warning in log:
**Option "nova_http_log_debug" from group "DEFAULT" is deprecated for removal. Its value may be silently ignored in the future.**
=> ceilometer: remove deprecated nova_http_log_debug option

chef/cookbooks/ceilometer/metadata.rb, chef/cookbooks/ceilometer/recipes/common.rb, chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb, chef/data_bags/crowbar/migrate/ceilometer/201_add_memcache_secret_key.rb, chef/data_bags/crowbar/template-ceilometer.json, chef/data_bags/crowbar/template-ceilometer.schema, crowbar_framework/app/models/ceilometer_service.rb
The following Ceilometer configuration options deprecated in Ocata (or earlier) are removed or replaced in this PR:
- [keystone_authtoken]/service_token_roles_required  is set to True to enable fetching expired tokens based on valid service tokens and [keystone_authtoken]/service_token_roles is set to the admin role
The deprecated keystonemiddleware.auth_token in-process token cache used by ceilometer services is replaced with a memcached server. When HA is used, several memcached servers are configured and used, one for each ceilometer-server node. The keystone token data stored in memcached is authenticated and encrypted using a generated secret key.
References:
- Ocata release notes for Ceilometer: https://docs.openstack.org/releasenotes/ceilometer/ocata.html
- Ocata release notes for …
=> ceilometer: replaced auth_token in process cache with memcached in ocata cookbook

chef/data_bags/crowbar/migrate/nova/204_add_placement_password.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/models/nova_service.rb
Without this change, the nova placement user has a default password of
"placement", set in attributes.rb, and it is impossible to change it.
This is a massive security flaw for obvious reasons. This change adds
the ability to change the placement service password via the raw view of
the nova barclamp and also ensures it defaults to a random one.
=> nova: Randomize placement password

chef/cookbooks/mysql/recipes/ha_galera.rb
The galera-3 got splited into a base package and a wsrep-provider
package.
(cherry picked from commit c1ff439e8399f745e51dd2a79f22c1710c0d7c2b)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1192
=> [4.0] mariadb: Install the galera-3-wsrep-provider package

chef/cookbooks/mysql/recipes/ha_galera.rb
1. lower the number of unsuccessful checks needed for declaring server DOWN (default is 5)
2. lower the interval checking after first failure is found (default is 2 seconds)
(cherry picked from commit c2fc247391c3d62d526fff9d7b7295224799af02)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1168
=> [4.0] Finetune haproxy settings for galera.

chef/cookbooks/mysql/recipes/server.rb, chef/cookbooks/mysql/templates/default/logging.cnf.erb, chef/data_bags/crowbar/migrate/database/200_add_slow_query.rb, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema
Before the config cleanup some archs had slow_query_logging enabled.
Let's reenable it for all archs.
=> mariadb: Enable slow query logging

chef/cookbooks/magnum/metadata.rb, chef/cookbooks/magnum/recipes/common.rb, chef/cookbooks/magnum/templates/default/magnum.conf.erb, chef/data_bags/crowbar/migrate/magnum/200_add_memcache_secret_key.rb, chef/data_bags/crowbar/migrate/magnum/201_add_trustee_keystone_interface.rb, chef/data_bags/crowbar/template-magnum.json, chef/data_bags/crowbar/template-magnum.schema, crowbar_framework/app/models/magnum_service.rb
Added following new feature config option:
* Add trustee: keystone_interface
Makes Keystone URL, used by Cluster Template instances, configurable
Replace keystone middleware, as in-process token cache, with memcache:
* Add [keystone_authtoken]/service_token_roles_required = ture
Allows fetching expired token based on valid service token
* Add [keystone_authtoken]/service_token_roles = admin
Service will request for token playing admin role
* Add memcached_servers cluster for magnum service
* Add memcache_security_strategy = ENCRYPT
* Add memcache_secret_key
References:
* Ocata release notes for magnum: https://docs.openstack.org/releasenotes/magnum/ocata.html
* Ocata release notes for keystonemiddleware: https://docs.openstack.org/releasenotes/keystonemiddleware/ocata.html
* Mitaka …
=> magnum: update config to Ocata release

chef/cookbooks/nova/definitions/nova_package.rb
Without this change, changing the placement configuration after the
initial deployment will have no effect on any of the nova services. This
is a problem if we want to change the way the compute service connects
to the placement API after the initial deployment. This patch ensures
that nova services subscribe to both configuration files. The placement
config file is really just an extension of the main config file, so it
makes sense for the services to subscribe to both.
=> nova: Subscribe to placement config (bsc#1055188)

.rspec, .travis.yml
Until now, we are just running the default rake tasks which would do a
syntaxcheck and also run any tests that rspec found. Instead of that,
lets separate those into different travis jobs to have more visibility
in case of failure.
Also it enhances the rspec tests by setting the output format to a nicer
way for easy checking and tags the travis builds by using the
environment variables to give the jobs a easy visual distiction ont he
travis page.
=> [4.0] travis: separate the different checks

chef/cookbooks/mysql/recipes/server.rb, chef/data_bags/crowbar/migrate/database/200_add_slow_query.rb, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema
I just realized that slow query is not specific enough and does not
provide any context. This commit renames slow_query too
slow_query_logging and changes the migrations.
=> mariadb: Rename slow_query to slow_query_logging

chef/cookbooks/mysql/recipes/ha_galera.rb
"mariadb-tools" and "xtrabackup" contain the tooling for "xtrabackup"
and "rsync" based SST (State Snapshot Transfer) to work.
=> mariadb: Pull in additional packages required for SST

.rspec, .travis.yml
Until now, we are just running the default rake tasks which would do a
syntaxcheck and also run any tests that rspec found. Instead of that,
lets separate those into different travis jobs to have more visibility
in case of failure.
Also it enhances the rspec tests by setting the output format to a nicer
way for easy checking and tags the travis builds by using the
environment variables to give the jobs a easy visual distiction ont he
travis page.
(cherry picked from commit 269c32deaef8744fda35beea8fba7c338e5b78b1)
=> travis: separate the different checks

chef/cookbooks/mysql/attributes/server.rb, chef/cookbooks/mysql/recipes/server.rb, chef/cookbooks/mysql/templates/default/my.cnf.erb, chef/cookbooks/mysql/templates/default/tuning.cnf.erb, chef/data_bags/crowbar/migrate/database/201_add_tuning_variables.rb, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema
This PR splits the tuning related config options in a extra config and makes them available via crowbar (for tuning purposes).
This settings expect at least 1GB of total memory and are optimized for this.
=> MariaDB config tuning

chef/cookbooks/mysql/recipes/ha_galera.rb
"mariadb-tools" and "xtrabackup" contain the tooling for "xtrabackup"
and "rsync" based SST (State Snapshot Transfer) to work.
(cherry picked from commit 51637d5c45b351e622158399714e184bef51d72e)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1201
=> [4.0] mariadb: Pull in additional packages required for SST

chef/cookbooks/horizon/attributes/default.rb, chef/cookbooks/horizon/templates/default/local_settings.py.erb, chef/data_bags/crowbar/migrate/horizon/201_remove_telemetry_policy_file.rb, chef/data_bags/crowbar/template-horizon.json, chef/data_bags/crowbar/template-horizon.schema
ceilometer_policy.json is not anymore in the OpenStack Horizon
package, producing an exception during the login process.
=> horizon: remove telemetry policy file (bsc#1055293)

chef/cookbooks/nova/templates/default/nova-placement.conf.erb
By default, the nova compute service tries to access the public endpoint
of the placement API. The "public" network defined in network.json isn't
accessible to the compute nodes. Without this patch, the nova-compute
service is unable to connect to the placement API and so is unable to be
scheduled. This patch forces the service to request the internal
placement endpoint, which it can reach.
=> nova: Use internal placement url (bsc#1055188)

crowbar_framework/app/models/neutron_service.rb
The variable `netext` is not defined, but `net_ext`. This error
disable the option of adding new external networks.
=> neutron: Fix undefined variable (bsc#1040335)

chef/cookbooks/mysql/recipes/ha_galera.rb
We allow users to change the default value of mysql data directory,
so we have to make sure galera resource agent knows about it.
=> mysql: Provide datadir value to the pacemaker resource

chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/ironic/libraries/helpers.rb, chef/cookbooks/ironic/recipes/server.rb, chef/cookbooks/ironic/templates/default/ironic.conf.erb, chef/data_bags/crowbar/migrate/ironic/200_add_memcache_secret_key.rb, chef/data_bags/crowbar/migrate/ironic/201_remove_deprecated_opts.rb, chef/data_bags/crowbar/template-ironic.json, chef/data_bags/crowbar/template-ironic.schema, crowbar_framework/app/models/ironic_service.rb
This patch makes several updates for the ironic barclamp:
* Add service user credentials for the [glance], [neutron], [swift],
[service_catalog], and [inspector] sections so that ironic can use 
appropriate service users for each related service rather than getting
credentials for all operations from [keystone_authtoken]. We still use 
the ironic service user's credentials for the [inspector] and 
[service_catalog] sections rather than creating new users for the 
inspector service and API discovery. We must also include these auth
options for the [swift] section even when swift is not being used in
order to avoid a deprecation warning, but they of course do not have
to work in that case. See the newton upgrade notes for more
information about access credentials for services[1].
* Use the …
=> ironic: Update for ocata

chef/cookbooks/keystone/recipes/server.rb
This looks like a leftover from changes in https://github.com/crowbar/crowbar-openstack/commit/e4bc9e55cc1203607239cabefc8262360ca9a272#diff-28b6adf7bd1f81183dace3201a2720a5L91
There are no other references to `internal_URL_host` attribute (note: capital "URL").
The original introduction of these attributes and comment: https://github.com/crowbar/crowbar-openstack/commit/8f7bc6eae7cad61ba49734f302e3cc501270a7ee#diff-28b6adf7bd1f81183dace3201a2720a5R112
=> keystone: Removed unused attribute

chef/cookbooks/horizon/templates/centos/local_settings.py.erb, chef/cookbooks/horizon/templates/default/local_settings.py.erb, chef/cookbooks/horizon/templates/redhat/local_settings.py.erb
The Django update from 1.8. to 1.11 that was
done as a result of switching to Pike packages
has deprecated and removed the 'django.utils.log.NullHandler'
option in favor of 'logging.NullHandler' option.
This change fixes the horizon barclamp deployment errors
in pikecloud8:
`ValueError: Unable to configure handler 'null': Cannot resolve 'django.utils.log.NullHandler': No module named NullHandler
`
=> horizon: replace NullHandler option deprecated in Pike

chef/cookbooks/mysql/recipes/ha_galera.rb
We allow users to change the default value of mysql data directory,
so we have to make sure galera resource agent knows about it.
(cherry picked from commit fc58131d7a5059f9a9ca7bb51fa06e97bacde87c)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1209
=> [4.0] mysql: Provide datadir value to the pacemaker resource

chef/cookbooks/tempest/templates/default/tempest.conf.erb
The option "domain_specific_drivers" must be enabled when testing an environment
that is configured to use domain-specific identity drivers.
Otherwise the tempest test
tempest.api.identity.admin.v3.test_groups.GroupsV3TestJSON.test_list_groups
fails.
=> tempest: Set domain specifc drivers identitiy feature flag

chef/cookbooks/mysql/recipes/ha_galera.rb, chef/cookbooks/mysql/recipes/server.rb, chef/cookbooks/mysql/templates/default/galera.cnf.erb, chef/data_bags/crowbar/template-database.schema, crowbar_framework/app/models/database_service.rb
Use xtrabackup-v2 for transferring the state to new nodes joining the cluster.
This requires access to a root mysql user to do the transfer. Set up a new one
called "sstuser".
=> Set State Snapshot Transfer Settings

chef/cookbooks/ceilometer/recipes/common.rb, chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
Instead of using libvirt to get metadata about a domain, use nova in
case of xen as it does not support call to DomainGetMetadata
[relevant ceilometer change](https://review.openstack.org/#/c/397654/)
=> Ceilometer: use nova-api for discovery hyp=xen, (bsc#1056142)

chef/data_bags/crowbar/template-database.json
In Cloud 8 we will use maridb as the default and only supported database
for OpenStack. This change sets the database to mysql (mariadb).
=> mariadb: Set mariadb as the default database

chef/cookbooks/horizon/templates/default/local_settings.py.erb
When configuring a cache in Django, the KEY_PREFIX is a key of the
configured cache itself, not of the OPTIONS dict[1].
This was not a problem until Django 1.11 but since commit
65ec8fa8ca5[2] in Django itself, the OPTIONS are passed to the client
__init__() call which leads to:
File
"/usr/lib/python2.7/site-packages/django/core/cache/backends/memcached.py",
line 173, in _cache
self._client = self._lib.Client(self._servers, **client_kwargs)
TypeError: __init__() got an unexpected keyword argument 'KEY_PREFIX'
[1] https://docs.djangoproject.com/en/1.11/ref/settings/#caches
[2] https://github.com/django/django/commit/65ec8fa8ca56a53783453
=> horizon: Fix cache backend KEY_PREFIX

chef/cookbooks/horizon/recipes/server.rb
Apache reload (graceful) will signal the apache process, that will
restart the child process (WSGI).  This can cause a race, were an
OpenStack client try to contact to one of the WSGI services, and
the old WSGI process can answer.  This process will fail because
the WSGI socket is not anymore in the file system.
The aproach here is to use a dummy service for 'horizon', what
will SIGUSR1 the wsgi:horizon childs from apache, signaling the
reload of the configuration file which was introduced on commit 02120688d5d3bf35ba12d29ec68be3eba19253f9
=> horizon: Reload horizon after migration instead of restart

crowbar_framework/app/helpers/barclamp/database_helper.rb, crowbar_framework/config/locales/database/en.yml
We're not using MySQL, but MariaDB as an option for OpenStack
database.
Instead of replacing all relevant mysql strings (including variable
and cookbook names), we go the easy way and only change the part
that is visible to user in crowbar UI.
=> database: Replace MySQL UI string with MariaDB

crowbar_framework/app/helpers/barclamp/database_helper.rb, crowbar_framework/config/locales/database/en.yml
We're not using MySQL, but MariaDB as an option for OpenStack
database.
Instead of replacing all relevant mysql strings (including variable
and cookbook names), we go the easy way and only change the part
that is visible to user in crowbar UI.
(cherry picked from commit 49c0782483b8ff81eaf2b689068a4426c7e79c7e)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1225
=> [4.0] database: Replace MySQL UI string with MariaDB

chef/cookbooks/manila/recipes/api.rb
The endpoint is still needed for some tempest tests.
This reverts commit fd14030cc3319b775addab5c52edb75c8615a67d.
=> Revert "manila: Remove v1 endpoint"

chef/cookbooks/neutron/recipes/common_agent.rb, chef/cookbooks/neutron/templates/default/metadata_agent.ini.erb, chef/cookbooks/neutron/templates/default/neutron.conf.erb, chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb, chef/data_bags/crowbar/migrate/neutron/204_remove_of_interface.rb, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
The following neutron configuration options deprecated in Pike
are removed or renamed:
- the of_interface Open vSwitch agent configuration option.
The current default (native) will be the only supported
of_interface driver in Queens. [1]
- the nova_metadata_ip option is deprecated in favor of the
new nova_metadata_host option because it reflects better
that the option accepts an IP address and also a DNS name. [1]
- the [oslo_messaging_rabbit]/rabbit_use_ssl option is deprecated
in favor of the ssl option under the same group [2]
More information:
- [1] https://docs.openstack.org/releasenotes/neutron/pike.html#deprecation-notes
- [2] https://review.openstack.org/#/c/438455/
=> neutron: remove options deprecated in Pike

chef/cookbooks/mysql/recipes/ha_galera.rb
Configure the pacemaker resource to use the same log file as set in the
config file to avoid confusion.
=> mariadb: Fix log file location of pacemaker resource

chef/cookbooks/mysql/recipes/ha_galera.rb
Configure the pacemaker resource to use the same log file as set in the
config file to avoid confusion.
(cherry picked from commit 2247b50948902ad26e726c8242054def6de1d7e8)
=> [4.0] mariadb: Fix log file location of pacemaker resource

chef/cookbooks/cinder/recipes/common.rb, chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/data_bags/crowbar/migrate/cinder/203_remove_multi_backend.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema, crowbar_framework/app/assets/javascripts/barclamps/cinder/application.js, crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml
Remove the attribute "use_multi_backend". All configured backends
should be in its own config section. The single-backend case is
deprecated since Ocata[1].
[1]
https://docs.openstack.org/releasenotes/cinder/ocata.html#upgrade-notes
=> cinder: Remove non-multibackend support

chef/cookbooks/mysql/recipes/ha_galera.rb
If bootstrapping fails, we have to raise some error, not wait in the endless loop.
=> mysql: Add a timeout to galera bootstrapping

chef/cookbooks/neutron/templates/default/metadata_agent.ini.erb
The recent PR #1229 introduced config options that don't work
in Ocata. Revert to an Ocata compatible code.
=> neutron: Fix metadata server for ocata again

chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
Option "rabbit_use_ssl" from group "oslo_messaging_rabbit" is deprecated.
=> ceilometer: update deprecated option rabbit_use_ssl

chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/glance/recipes/setup.rb, chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/ironic/libraries/helpers.rb, chef/cookbooks/magnum/recipes/post_install.rb, chef/cookbooks/magnum/recipes/setup.rb, chef/cookbooks/neutron/recipes/post_install_conf.rb, chef/cookbooks/nova/libraries/availability_zone.rb, chef/cookbooks/nova/recipes/availability_zones.rb, chef/cookbooks/nova/recipes/compute.rb, chef/cookbooks/nova/recipes/flavors.rb, chef/cookbooks/swift/recipes/dispersion.rb, chef/cookbooks/tempest/recipes/config.rb
Using --os-password in command line calls exposes the password in the
process table and may therefor potentially expose it to unprivileged
users. This patch converts all shell-outs to use the environment
variable version of their credential settings, which is not leaked to
the process table.
We can omit passing '--os-auth-type password' since it is always implied
by the use of '--os-password' or OS_PASSWORD.
For openstackclient commands, if we want to specify a particular
endpoint type, we should use --os-interface/OS_INTERFACE, not
--os-endpoint/OS_ENDPOINT.
Using OS_PROJECT_NAME instead of OS_TENANT_NAME is acceptable in all
cases except for the nova availability zone setter, which is a custom
script.
=> Stop exposing passwords in the process table

chef/cookbooks/keystone/attributes/default.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/keystone/templates/default/keystone.conf.erb, chef/data_bags/crowbar/migrate/keystone/202_remove_signing.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema, crowbar_framework/app/views/barclamp/keystone/_edit_attributes.html.haml, crowbar_framework/config/locales/keystone/en.yml
Remove the [signing] section which is only applicable to the now-defunct PKI token format, and remove the [resource]/driver setting.
=> keystone: Update for pike (SCRD-781)

chef/cookbooks/keystone/recipes/server.rb
In various tests, actions happening inside keystone_register syncmark
block tend to take more than 40 secods. Depending on the setup,
it could be even little bit over 1 minute which is the default value
when the waiting nodes time out.
=> keystone: Increase timeout for keystone_register actions

chef/cookbooks/keystone/providers/register.rb
The 'private' declaration is not needed for every method, in ruby it is
sufficient to declare it once, then it applies to everything below it.
We've already cleaned up most of the unnecessary ones in an unrelated
refactor, this patch cleans up the last one.
=> keystone: Cleanup private declarations in register

chef/cookbooks/mysql/attributes/server.rb, chef/cookbooks/mysql/recipes/ha_galera.rb
Promoting the galera resource to master might require a full State
Transfer (SST) which can be time consuming. Increase the default timeout
for that to 300 seconds.
Partial-Bug: #1057806
=> mariadb: Increase timeout for the promote operation

chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/recipes/database.rb, chef/cookbooks/nova/templates/default/nova.conf.erb
The following nova configuration options deprecated in Pike
are removed or renamed:
- [DEFAULT]/default_floating_pool has been deprecated for neutron
users in favor of [neutron]/default_floating_pool [1]
- the following [ssl] options are moved to the [glance] group:
ca_file, cert_file and key_file and renamed to cafile, certfile
and keyfile respectively (these options were only used by the
Nova code that interacts with the Glance client) [1]
- api_insecure option from [glance] group is renamed to insecure [1]
- the [DEFAULT]/firewall_driver is deprecated as its default
value has been changed to nova.virt.firewall.NoopFirewallDriver
to coincide with the default value of [DEFAULT]/use_neutron=True [1]
- the --version optional parameter accepted by the
'nova-manage api_db sync' and …
=> nova: remove/rename config options deprecated in Pike

chef/cookbooks/glance/recipes/api.rb, chef/cookbooks/glance/recipes/setup.rb, chef/cookbooks/heat/recipes/server.rb, chef/cookbooks/ironic/libraries/helpers.rb, chef/cookbooks/magnum/recipes/post_install.rb, chef/cookbooks/magnum/recipes/setup.rb, chef/cookbooks/neutron/recipes/post_install_conf.rb, chef/cookbooks/nova/libraries/availability_zone.rb, chef/cookbooks/nova/recipes/availability_zones.rb, chef/cookbooks/nova/recipes/compute.rb, chef/cookbooks/nova/recipes/flavors.rb, chef/cookbooks/swift/recipes/dispersion.rb, chef/cookbooks/tempest/recipes/config.rb
Using --os-password in command line calls exposes the password in the
process table and may therefor potentially expose it to unprivileged
users. This patch converts all shell-outs to use the environment
variable version of their credential settings, which is not leaked to
the process table.
We can omit passing '--os-auth-type password' since it is always implied
by the use of '--os-password' or OS_PASSWORD.
For openstackclient commands, if we want to specify a particular
endpoint type, we should use --os-interface/OS_INTERFACE, not
--os-endpoint/OS_ENDPOINT.
Using OS_PROJECT_NAME instead of OS_TENANT_NAME is acceptable in all
cases except for the nova availability zone setter, which is a custom
script.
(cherry picked from commit a1accbafb6f46e6ab08862ce8b03ceea3f235423)
=> [4.0] Stop exposing passwords in the process table

chef/cookbooks/keystone/recipes/server.rb
When we do a apache2 restart action, as the apache2 service is declared
on the apache2 cookbook, we have no idea of what triggered the restart
for it.
This makes it a problem to differentiate between the different cookbooks
calling the restart for the service, if we want to introduce a feature
to avoid restarts based on origin/barclamps.
This PR introduces a ruby_block that sets a temporal key on the node
when apache2 is restarted, to flag where the restart was triggered from.
The run_state values are ephemeral so we dont modify the node attributes
at all.
Only affected cookbook is keystone for the moment, as the other cookbooks do a reload instead of a restart.
Unblocks: This unblocks https://github.com/crowbar/crowbar-core/pull/1307
Required-By: …
=> keystone: Set an origin flag on apache2 restart

chef/cookbooks/ceilometer/recipes/server_ha.rb
(cherry picked from commit 154f85d4af558df839ce2103f13b73b1a553ac55)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1072
=> [4.0] ceilometer: Allow enabling SSL with HA (bsc#1049153)

chef/cookbooks/keystone/templates/default/keystone.conf.erb, chef/data_bags/crowbar/migrate/keystone/203_add_password_hash_algorithm.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/config/locales/keystone/en.yml
Since Pike, the new default password hash algorithm is
"bcrypt"[1]. This is more secure but also significantly slower (factor 10
in my tests) when eg. trying to get a new token via the v3 API.
To be able to increase performance (if wanted), make the hashing
algorithm and the hashing rounds for the selected algorithm
configurable. Reducing the value for "password_hash_rounds" increases
the performance.
[1]
https://docs.openstack.org/releasenotes/keystone/pike.html#new-features
=> keystone: Make password hash algorithm configurable

chef/cookbooks/manila/libraries/helpers.rb
The bind_host IP address value reflected in the
osapi_share_listen configuration option (the listening
address for manila-api) was previously set to an empty
value in the HA case, which defaulted to the 0.0.0.0 value
being used by the manila-api service.
However, since Pike, the configured value is checked
against an IP address syntax and having an empty
value causes all manila services to fail.
This PR is meant to fix the [Pike HA gate job](https://ci.suse.de/view/Cloud/view/Cloud8/job/cloud-mkcloud8-job-ha-pike/).
=> manila, ha: fix listen address in HA case

chef/cookbooks/manila/libraries/helpers.rb
The bind_host IP address value reflected in the
osapi_share_listen configuration option (the listening
address for manila-api) was previously set to an empty
value in the HA case, which defaulted to the 0.0.0.0 value
being used by the manila-api service.
However, since Pike, the configured value is checked
against an IP address syntax and having an empty
value causes all manila services to fail.
(cherry picked from commit 1bb133bd0cf1f890e0f3e30149f7a2f3fc6525f0)
=> [4.0] manila, ha: fix bind_host in HA case

chef/cookbooks/neutron/attributes/default.rb, chef/cookbooks/neutron/files/default/neutron-l3-ha-service.rb, chef/cookbooks/neutron/libraries/helpers.rb, chef/cookbooks/neutron/recipes/network_agents_ha.rb, chef/cookbooks/neutron/templates/default/neutron-l3-ha-service.service.erb, spec/neutron_helpers_spec.rb, spec/neutron_l3_ha_service_spec.rb
Turn neutron-ha-tool into a service
As an operator I want to see that neutron-ha-tool is a service monitored by pacemaker.
Currently NHT (Neutron HA-TOOL) is a one-shot script that's "managed" by pacemaker. This is a problem, because the model for a daemon and a one-time script differ. We want to modify NHT so that it is a service rather than a one-shot script.
https://suse-jira.dyndns.org/browse/SCRD-117
https://trello.com/c/qeBCsC0d/9-turn-neutron-ha-tool-into-a-service
=> Forwardport neutron-ha-tool service

chef/cookbooks/ec2-api/recipes/ec2api.rb, chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
Update the ec2-api cookbook to configure a memcached
instance running on every ec2-api node that will serve
as a cache backend for the ec2-api-metadata service.
This has been added in Pike as a recommended feature
without which the metadata service complains during
startup.
More info: https://review.openstack.org/#/c/469075/
=> ec2-api: add memcached cache backend for ec2-api-metadata

chef/cookbooks/keystone/templates/default/keystone.conf.erb
Per the oslo.cache documentation it's recommended to use the pooling
backend for eventlet based and threaded services. As our setup for the
keystone vhost in apache uses threads by default, let's use the pooling
backend. This seems to significantly reduce the number of open
connections to memcached.
Partial-Bug: bsc#1057822
Note: An alternative fix might be to disable threads for the WSGIDaemonProcess. (I don't really have an idea how much good that does anyway, give pythons GIL)
=> keystone: Switch memcache backend to oslo_cache.memcache_pool

chef/cookbooks/glance/templates/default/glance-api.conf.erb, chef/cookbooks/glance/templates/default/glance-registry.conf.erb
rabblt_use_ssl and kombu_ssl_ca_certs oslo messaging
config options were deprecated in Ocata.
They were replaced by ssl and ssl_ca_file instead.
Reference: https://review.openstack.org/#/c/438455/
=> glance: update cookbook for pike

chef/cookbooks/mysql/recipes/ha_galera.rb
Adding the location constraint should ensure that the service
is not running at remote cluster nodes.
=> mysql: Make sure galera resources are started on controller nodes only

chef/cookbooks/neutron/files/default/sysctl-inotify-max-instances.conf, chef/cookbooks/neutron/recipes/network_agents.rb
It has been found that during heavy network creation by Neutron (>1K
networks) dnsmasq is unable to complete due to lack of inotify user
instances.
Each neutron network spawns one dnsmasq process. Each dnsmasq process
consumes one inotify instance. Existing processes in network nodes consume
less than 10 inotify instances so this number would virtually be the
maximum number of networks supported.
For now we are setting this number to 8192 which will support over 8k
networks.
=> neutron: Increase inotify max user instances

chef/cookbooks/barbican/templates/default/barbican.conf.erb
The following deprecated options have been updated:
- the [oslo_messaging_rabbit]/rabbit_use_ssl option was
renamed to [oslo_messaging_rabbit]/ssl [1]
- the oslo_messaging_rabbit]/kombu_ssl_ca_certs option was
renamed to [oslo_messaging_rabbit]/ssl_ca_file [1]
[1] https://review.openstack.org/#/c/438455/
=> barbican: remove options deprecated in Pike

chef/cookbooks/heat/templates/default/heat.conf.erb
rabblt_use_ssl and kombu_ssl_ca_certs oslo messaging
config options were deprecated in Ocata.
They were replaced by ssl and ssl_ca_file instead.
Reference: https://review.openstack.org/#/c/438455/
=> heat: update cookbook for pike

chef/cookbooks/nova/recipes/controller_ha.rb, chef/data_bags/crowbar/migrate/nova/205_add_rate_limit.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema
Adds rate limiting options to the raw template for the different
services that depend from nova. Defaults to 0 as the values, which means
no rate limiting
Depends-on: https://github.com/crowbar/crowbar-ha/pull/228
=> nova: add rate limiting options to raw template

chef/cookbooks/keystone/templates/default/keystone.conf.erb
Per the oslo.cache documentation it's recommended to use the pooling
backend for eventlet based and threaded services. As our setup for the
keystone vhost in apache uses threads by default, let's use the pooling
backend. This seems to significantly reduce the number of open
connections to memcached.
Partial-Bug: bsc#1057822
(cherry picked from commit 2f512cf110cebea278285d0dd8ac846d75e8de57)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1266
=> [4.0] keystone: Switch memcache backend to oslo_cache.memcache_pool

chef/cookbooks/nova/recipes/controller_ha.rb, chef/data_bags/crowbar/migrate/nova/119_add_rate_limit.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema
Adds HA rate limiting options to the raw template for the different
services that depend from nova. Defaults to 0 as the values, which means
no rate limiting
(cherry picked from commit ffcc557fcc85888b95d058de7e72d315ba0008f6)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1233
=> [4.0] nova: add HA rate limiting options to raw template

chef/cookbooks/ironic/templates/default/ironic.conf.erb
The glance_host, glance_port, and glance_protocol options of the
[glance] section were deprecated in favor of the glance_api_servers
option[1], which we were already using anyway. This patch just removes
those unnecessary settings.
[1] https://docs.openstack.org/releasenotes/ironic/pike.html#deprecation-notes
=> ironic: Remove deprecated glance params (SCRD-768)

chef/data_bags/crowbar/migrate/nova/205_add_rate_limit.rb
As we have backported the migration onto 4.0 branch but on 4.0 the
placement api does not exists, we could end up with a situation in which
the ha_rate_limit key exists in an environment but the
nova-placement-api inside that attribute is missing, so lets make sure
that we check for that case and update it if its missing.
Do-Not-Merge-Until: https://github.com/crowbar/crowbar-openstack/pull/1281
=> nova: fix ratelimit migration

chef/cookbooks/ceilometer/recipes/common.rb, chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
mkcloud deployed with cloudsource=pikecloud8 has below error in controller:
/var/log/ceilometer/ceilometer-collector.log (cotyledon._service_manager [-] ServiceManager raised exception during new_worker hooks: **ConfigFileValueError: Value for option libvirt_type is not valid: Valid values are [kvm, lxc, qemu, uml, xen], but found ''**)
/var/log/ceilometer/ceilometer-polling-central.log (cotyledon._service_manager [-] ServiceManager raised exception during new_worker hooks: **ConfigFileValueError: Value for option libvirt_type is not valid: Valid values are [kvm, lxc, qemu, uml, xen], but found ''**)
/var/log/ceilometer/ceilometer-polling-central.log (cotyledon._service_manager **ConfigFileValueError: Value for option host_ip is not valid:  is not a valid host address**)
Local tested the …
=> ceilometer: fix libvirt_type & host_ip null error

chef/cookbooks/sahara/templates/default/sahara.conf.erb
deprecation message below is seen in sahara-api.log and sahara-server.log:
WARNING oslo_config.cfg [-] Option "rabbit_use_ssl" from group "oslo_messaging_rabbit" is deprecated. Use option "ssl" from group "oslo_messaging_rabbit".
=> sahara: update deprecated option rabbit_use_ssl, use_neutron, and kombu_ssl_ca_certs

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
By setting this to the number of "real" cluster nodes (non-remote) we
avoid having the resource listed as "Stopped" on remote nodes
(compute-ha) in the crm status output.
(cherry picked from commit 638a7322ff71f1cf74ac86d84f8e53239e670737)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1293
=> [4.0] rabbitmq: Set "clone-max" for the ms-rabbitmq resource

chef/cookbooks/mysql/recipes/ha_galera.rb
This way, when haproxy is running on a node, it primarily directs
mariadb database traffic to the same node.
(cherry picked from commit 87ee4986fb2739d52f29cbd9ac8c9d2923441d06)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1288
=> [4.0] mysql: Set the current node as non-backup server in haproxy config

chef/cookbooks/nova/templates/default/nova.conf.erb
We were leaving the default hardcoded values for serialproxy which could
collide with haproxy if deployed on HA as both will try to use the same
ports.
=> nova: use the proper vars for serialproxy

chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
By setting this to the number of "real" cluster nodes (non-remote) we
avoid having the resource listed as "Stopped" on remote nodes
(compute-ha) in the crm status output.
See https://github.com/crowbar/crowbar-openstack/pull/1265
=> rabbitmq: Set "clone-max" for the ms-rabbitmq resource

chef/cookbooks/rabbitmq/attributes/default.rb, chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
When starting rabbitmq, especially if we are recovering from fencing,
the start could take a while as it needs to check for the tables
to be correct and/or reset the mnesia dir depending on the outcome, of
that check so the whole process could take much longer than the
default 60 seconds.
We also increase the promote timeout as it also needs to do some
internal checking for the master score and it could easily go over the
default timeout.
=> rabbitmq: Increase timeouts for start/promote actions (bsc#1059532)

chef/cookbooks/magnum/recipes/setup.rb
In a1accbaf we switched out the credentials in the command flags for
environment variables, but we forgot to use the environment in one of
the magnum commands. This was causing the magnum domain admin to not
have a role in its own domain and causing our tests to fail when trying
to create a cluster template. This patch adds the environment setting to
the last mixlib call so that it works the same as the other shellouts.
=> magnum: Use credential env to setup domain role

chef/cookbooks/nova/templates/default/nova.conf.erb
We were leaving the default hardcoded values for serialproxy which could
collide with haproxy if deployed on HA as both will try to use the same
ports.
(cherry picked from commit 2f8b1d3b8f5ef0774cf7acddc58b5e36a4a3aab3)
=> [4.0] nova: use the proper vars for serialproxy

chef/cookbooks/database/libraries/crowbar.rb
Certificates are usually issued for the FQDN not just the hostname.
=> mysql: Use fqdn for database hostname when using SSL

chef/cookbooks/rabbitmq/attributes/default.rb, chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
When starting rabbitmq, especially if we are recovering from fencing,
the start could take a while as it needs to check for the tables
to be correct and/or reset the mnesia dir depending on the outcome, of
that check so the whole process could take much longer than the
default 60 seconds.
We also increase the promote timeout as it also needs to do some
internal checking for the master score and it could easily go over the
default timeout.
(cherry picked from commit 594853623315ba9be4c7563cda6e5a39dcf1293e)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1290
=> [4.0] rabbitmq: Increase timeouts for start/promote actions (bsc#1059532)

chef/cookbooks/glance/recipes/registry.rb
Glance metadata definitions are missing from the database,
which causes the following fulltempest test cases to fail:
tempest.api.image.v2.test_images_metadefs_namespace_properties.MetadataNamespacePropertiesTest.test_basic_meta_def_namespace_property
tempest.api.image.v2.test_images_metadefs_resource_types.MetadataResourceTypesTest.test_basic_meta_def_resource_type_association
The metadef can be loaded into the database right after the
db sync step.
More info:
- official openstack docs: https://docs.openstack.org/image-guide/image-metadata.html
=> glance: load glance metadefs into the database

chef/cookbooks/horizon/attributes/default.rb, chef/cookbooks/horizon/recipes/server.rb, chef/cookbooks/horizon/templates/default/local_settings.py.erb, chef/data_bags/crowbar/migrate/horizon/202_add_neutron_fwaas_policy_file.rb, chef/data_bags/crowbar/template-horizon.json, chef/data_bags/crowbar/template-horizon.schema
The following dashboard configuration options are deprecated in Pike [1]:
- the profile_support setting has been removed from the OPENSTACK_NEUTRON_NETWORK dict
- the enable_firewall, enable_vpn and enable_lb settings deprecated since Juno are dropped in Pike. Since Horizon has the ability to enable/disable dashboard panels automatically by checking the availability of FWaaS v1, LBaaS and VPNaaS services, no additional configuration steps are required to enable/disable these panels.
Starting with Pike, the VPNaaS horizon dashboard is maintained as a separate project neutron-vpnaas-dashboard that needs to be installed and configured separately [2]. The VPNaaS dashboard package [has been submitted upstream](https://review.openstack.org/#/c/501791/).
Starting with Pike, the FWaaS horizon …
=> horizon: Pike updates

chef/cookbooks/neutron/templates/default/metadata_agent.ini.erb
The nova_metadata_ip option is deprecated in favor of the
new nova_metadata_host option because it reflects better
that the option accepts an IP address and also a DNS name. [1]
This change was originally included in #1229, but then later was
reverted in #1245 because it was braking the (then Ocata based)
Devel:Cloud:8.
This PR reverts commit 416c1bb99f9b289e7a4a2c920eeafa5fb6da8ec5 
(#1245) in effect bringing back these suppressed changes.
More information:
[1] https://docs.openstack.org/releasenotes/neutron/pike.html#deprecation-notes
=> neutron: Fix deprecated nova_metadata_ip option

crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml, crowbar_framework/config/locales/database/en.yml
This commit makes max_connections and slow_query_logging configurable
via the UI.
=> database: Expose max_connections and slow_query_logging in UI

chef/cookbooks/tempest/templates/default/tempest.conf.erb
The img_dir, ami_img_file, ari_img_file and aki_img_file
options from the scenario group are still being used by
some test cases:
scenario.test_minimum_basic.TestMinimumBasicScenario.*
scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.*
, which fail unless these configuration options are supplied.
These options were removed during the Ocata update in #1167.
More info:
- tempest configuration doc: https://github.com/openstack/tempest/blob/17.0.0/doc/source/configuration.rst#images
=> tempest: readd img_dir and ami/ari/aki_img_file options

chef/cookbooks/ceilometer/recipes/common.rb, chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
Corrects the hypervisor_inspector value for 'vmware' to be 'vsphere' instead of 'vmware'. Without this, the ceilometer compute polling agent running on vmware role compute nodes is not working.
More info: https://github.com/openstack/ceilometer/blob/stable/newton/setup.cfg#L234
(cherry picked from commit a870a5d80fc8cdf39f877df7a730a3f3e65802cb)
=> [4.0] ceilometer: fix hypervisor_inspector value for 'vmware' to be 'vsphere'

chef/cookbooks/cinder/templates/default/cinder.conf.erb, chef/cookbooks/nova/templates/default/nova.conf.erb
Starting with Ocata, as part of the migration to castellan as
an external key manager interface lib, the default key manager
was changed from ConfKeyManager - the nova internal fixed-key,
insecure key manager - to Barbican [1]. This change isn't explicitly
documented in the release notes and creates a default dependency
between nova/cinder and Barbican. As currently nova/cinder have
not yet been fully integrated with Barbican, the encrypted volume
support is broken.
This is only a quick fix that brings back the ability to create
and manage encrypted volumes by switching back to the key
manager that was used before Ocata. It also fixes the following
tempest test cases:
tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_cryptsetup …
=> cinder,nova: use default key manager instead of barbican

chef/cookbooks/ceilometer/attributes/default.rb, chef/cookbooks/ceilometer/recipes/server.rb, chef/cookbooks/ceilometer/recipes/server_ha.rb, chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb, chef/cookbooks/ceilometer/templates/default/pipeline.yaml.erb
According to Pike release notes (https://docs.openstack.org/releasenotes/ceilometer/pike.html):
Collector is no longer supported in this release. The collector introduces lags in pushing data to backend. To optimize the architecture, Ceilometer push data through dispatchers using publishers in notification agent directly.
=> ceilometer: remove deprecated collector

chef/cookbooks/keystone/recipes/server.rb
The SSL file setup needs to be performed before the keystone
WSGI services are started, otherwise they fail the following
apache log error during the restart of the apache service:
```
start_apache2[27198]: AH00526: Syntax error on line 12 of /etc/apache2/vhosts.d/keystone-public.conf:
start_apache2[27198]: SSLCertificateFile: file '/etc/keystone/ssl/certs/signing_cert.pem' does not exist or is empty
systemd[1]: apache2.service: Main process exited, code=exited, status=1/FAILURE
```
```
start_apache2[27312]: AH00526: Syntax error on line 12 of /etc/apache2/vhosts.d/keystone-admin.conf:
start_apache2[27312]: SSLCertificateFile: file '/etc/keystone/ssl/certs/signing_cert.pem' does not exist or is empty
systemd[1]: apache2.service: Main process exited, code=exited, status=1/FAILURE
```
Prior …
=> keystone: generate SSL files before starting WSGI services

chef/cookbooks/nova/recipes/compute.rb
This was a dead lookup anyway, the last user of the variable
was removed 2013.
=> nova: stop using the passwd ohai tree

chef/cookbooks/nova/recipes/config.rb, chef/cookbooks/nova/recipes/placement_api.rb, chef/cookbooks/nova/templates/default/nova-placement.conf.erb
Add the missing SSL parameters to the WSGI configuration for the
nova-placement API service, when SSL is enabled for nova . Also
add the missing [placement]/insecure configuration option to the
nova placement configuration file.
This changeset is required to have nova work properly when SSL is
enabled. Without it, nova-scheduler reports the following error while
trying to contact nova-placement during the creation of a server instance:
```
2017-09-26 09:24:19.684 32469 WARNING keystoneauth.identity.generic.base [req-89ea9888-e1ad-4745-8983-da096309d386 1c3e6c5446e7440e80ca98813f8099ed ff30a0242f8a4ab68f19c49ae2ed1ba1 - default default] Failed to discover available identity versions when contacting https://d52-54-77-77-01-01.virtual.cloud.suse.de:35357. Attempting to parse version from …
```
=> nova: fix SSL configuration for nova-placement

crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
(cherry picked from commit 32bca13ff4e64820802969e6d0585b431d1a551d)
backport of https://github.com/crowbar/crowbar-openstack/pull/1313
=> [4.0] database: Show Insecure SSL flag in the UI

chef/cookbooks/postgresql/recipes/server_redhat.rb, chef/cookbooks/rabbitmq/recipes/default.rb
Originally, crowbar could not restart the postgresql or rabbitmq resource agents. We "fixed" this so that crowbar could properly manage it, but this is really not a safe thing to do for HA services. This PR reverts those commits so that we go back to the original behavior. We don't make either postgresql or rabbitmq highly configurable so neither the original changes nor this revert will have a significant impact on users.
See also this discussion: https://github.com/crowbar/crowbar-openstack/pull/974#pullrequestreview-53856237
=> Revert ha service restarts

chef/cookbooks/nova/templates/default/nova.conf.erb, chef/data_bags/crowbar/template-nova.json
The parameter was made configuable but it wasn't actually written
to the config file.
=> nova: respect image_cache_manager_interval set in proposal (bsc#1057233)

chef/cookbooks/monasca/templates/default/monasca-agent_agent.yaml.erb, chef/cookbooks/monasca/templates/default/monasca-reconfigure-server.erb, chef/cookbooks/monasca/templates/default/monasca-reconfigure.erb
This commit adds domain information to monasca-agent Keystone credentials. On
Pike, monasca-agent will otherwise attempt Keystone authentication without
specifying a domain for either user or project, which causes it to fail
authentication and thus prevents it from ever sending any metrics.
=> Fix monasca-agent on Pike

chef/cookbooks/database/libraries/crowbar.rb
Certificates are usually issued for the FQDN not just the hostname.
(cherry picked from commit 102d79ce3cee46150be722e1e8cea93720467828)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1306
=> [4.0] mysql: Use fqdn for database hostname when using SSL

crowbar_framework/app/models/swift_service.rb
The current default swift replica count value is 3, which results
in a "Replica count of 3.0 requires more than 2 devices" failure
when the swift barclamp is deployed by mkcloud on setups with 3
nodes.
This commit extends that behavior by computing the default value
of the replicas count automatically based on the number of
swift-storage nodes using the formula:
min(1, max(`no-swift-storage-nodes`, 3))
This fix is meant mainly to fix [the DVR SOC8 Jenkins job](https://ci.suse.de/view/Cloud/view/Cloud8/job/cloud-mkcloud8-job-dvr-x86_64/), which
is currently broken.
=> swift: make default replicas count match storage node count

chef/cookbooks/glance/recipes/registry.rb
Fixes an error from the previous PR #1284 , which introduced
loading glance metadefs into the glance database: the 'glance-manage
db_load_metadefs' block is never executed because the ruby_block
that ensures single execution is triggered too quickly.
=> glance: fix loading glance metadefs to database

chef/cookbooks/horizon/templates/default/local_settings.py.erb
SOC6 updated local_settings.py via Crowbar. Because of that, the file will
not be updated during a RPM package update (due to "config(noreplace)").
So explicitly set REST_API_REQUIRED_SETTINGS to get the correct settings.
Note: This fix is not needed for SOC8 because SOC7 will put the config
file into local_settings.d/ as a snippet. So local_settings.py will be
updated (if no user edited the file manually) during a SOC7->SOC8 update.
=> horizon: Explicit set REST_API_REQUIRED_SETTINGS (bsc#1046616)

chef/cookbooks/neutron/attributes/default.rb
We found out that default timeouts for neutron-l3-ha-service were bigger
than Pacemaker default timeout (60s). This lead to a situation where we
tried to gracefully shutdown the service, but since we allowed that much
time, Pacemaker kicked in and fenced the node.
Since Pacemaker will call systemd service to stop the l3-service + tool,
we are reducing the time systemd takes to send a kill signal. Now
systemd will kill the l3-service + tool before Pacemaker tries to fence
the node.
Pacemaker timeout is configured to 60s. We want systemd to send the kill
signal at 55s. The systemd timeout is calculated as the maximum
l3-service :kill timeout + 5s. That's why we are changing the :kill
timeouts to 50s.
=> neutron-l3-ha-service: tweak timeouts

crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml, crowbar_framework/config/locales/database/en.yml
This commit makes max_connections and slow_query_logging configurable
via the UI.
(cherry picked from commit 29b1aa63c798654a28ffbb88187c29a34c4aa5de)
=> [4.0] database: Expose max_connections and slow_query_logging in UI

chef/cookbooks/nova/recipes/compute.rb, chef/data_bags/crowbar/migrate/nova/120_add_remotefs_sshkey.rb, chef/data_bags/crowbar/template-nova.json, chef/data_bags/crowbar/template-nova.schema, crowbar_framework/app/models/nova_service.rb
This was only a marginal security feature to begin with, as
you could just copy the other instance ssh key with one hop
more. Created a followup card to make this more secure.
(cherry picked from commit ae1345b916848af7bade0e170c05b0159ba61d55)
Backport of #648 648
=> nova: reduce excessive node searches on compute role nodes

chef/cookbooks/mysql/templates/default/tuning.cnf.erb
We're already raising innodb_buffer_pool_size, and log_file_size should
be scaled accordingly (typical recommendation is 25% of the buffer pool
size which is what we're doing here). Also tune writeback to O_DIRECT
as this is what upstream is doing:
https://git.openstack.org/cgit/openstack/openstack-ansible-galera_server/tree/templates/my.cnf.j2#n80
=> mysql: tune innodb log size / writeback

chef/cookbooks/postgresql/recipes/server_redhat.rb, chef/cookbooks/rabbitmq/recipes/default.rb
Originally, crowbar could not restart the postgresql or rabbitmq resource agents. We "fixed" this so that crowbar could properly manage it, but this is really not a safe thing to do for HA services. This PR reverts those commits so that we go back to the original behavior. We don't make either postgresql or rabbitmq highly configurable so neither the original changes nor this revert will have a significant impact on users.
Backport of #1301
=> [3.0] Revert ha service restarts

chef/cookbooks/keystone/recipes/server.rb
Without this patch, when the keystone barclamp checks the
updated_password field it first checks for emptiness and then for
nilness. This is incorrect because .nil? is defined on all objects but
.empty? is only defined on iterables, so a value of nil would cause an
error in the first check instead of being caught by the second check.
This patch switches the order to fix this.
This wasn't noticed before because the schema defines the default value
of updated_password as an empty string. This would only be noticed if
the schema wasn't migrated properly. In any case, it's still better form
to check in this order.
=> keystone: Fix updated password check (bsc#1060687)

chef/cookbooks/database/libraries/provider_database_mysql_user.rb, chef/cookbooks/nova/recipes/database.rb
Previous check for privileges always forced new grant action for users that required specific rights (like db_user)
=> database: Check if correct privileges are present before granting 

chef/cookbooks/mysql/templates/default/tuning.cnf.erb
We're already raising innodb_buffer_pool_size, and log_file_size should
be scaled accordingly (typical recommendation is 25% of the buffer pool
size which is what we're doing here). Also tune writeback to O_DIRECT
as this is what upstream is doing:
https://git.openstack.org/cgit/openstack/openstack-ansible-galera_server/tree/templates/my.cnf.j2#n80
(cherry picked from commit f12daf1464d21c08f3773965b8cfdb827582b7a3)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1325
=> [4.0] mysql: tune innodb log size / writeback

chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/nova/recipes/database.rb
It looks like it takes just above 3 minutes to complete using mysql/galera, so we need to raise limits.
=> Extend DB sync timeouts  (bsc#1060421)

chef/cookbooks/neutron/recipes/server.rb
Lately, running openstack CLI commands takes a long time due to
the fact that the CLI data model needs to be loaded from an increasing
number of python packages. This has a negative impact on cookbook
recipes that make extensive use of the openstack CLI, one of which
is the post_install neutron recipe, which evaluates the need to create
and then conditionally creates default objects (networks, routers).
Based on Jenkins HA job logs, an openstack CLI command can take up to
10-15 seconds to complete, which means the founder node is kept
busy for up to 100-150 seconds while evaluating the need to create
these default objects. This delay needs to be addressed in the
neutron cookbook, otherwise it may negatively impact other cookbooks
that are not prepared to handle that long of a delay.
This …
=> neutron: fix HA neutron-agents_before_ha timeout

chef/cookbooks/neutron/recipes/cisco_apic_agents.rb, chef/cookbooks/neutron/recipes/vmware_support.rb, chef/cookbooks/nova/recipes/instances.rb
These services are oneshot, and this is not compatible.
This is not visible in our CI, due to the fact that the code path is
only used for some exotic configuration.
=> neutron, nova: Revert use of Restart= for ovs and nfs

chef/cookbooks/neutron/recipes/server.rb
Fixes the error introduced in #1338 that causes a consistent timeout error in the neutron barclamp:
RuntimeError: crowbar-pacemaker_sync_mark[wait sync mark for neutron default networks] (neutron::server line 451) had an error: RuntimeError: Cluster founder didn't set neutron_default_networks!\n"}
=> neutron: fix neutron_default_networks HA timeout error

chef/cookbooks/neutron/recipes/cisco_apic_agents.rb, chef/cookbooks/neutron/recipes/vmware_support.rb, chef/cookbooks/nova/recipes/instances.rb
These services are oneshot, and this is not compatible.
This is not visible in our CI, due to the fact that the code path is
only used for some exotic configuration.
(cherry picked from commit 28cf45c4519f43bab7a004fa3c7e16006c9d7250)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1357
=> [4.0] neutron, nova: Revert use of Restart= for ovs and nfs

chef/cookbooks/ceilometer/recipes/common.rb, chef/cookbooks/ceilometer/recipes/server.rb, chef/cookbooks/ceilometer/templates/default/event_pipeline.yaml.erb
Before pike you could turn event publishing pipeline
off by removing /etc/ceilometer/event_pipeline.yaml,
but in pike it now defaults to
pipeline/data/event_pipeline.yaml as a fallback
location (see https://review.openstack.org/#/c/441734/)
Since there is no way to turn off event publishing, this
workaround creates a  pipeline which matches no events, which
is a no-op.
Also filed upstream bug https://bugs.launchpad.net/ceilometer/+bug/1720021
=> ceilometer: add no-op events pipeline

chef/cookbooks/neutron/recipes/server.rb
(backported from #1338, because it is also affecting SOC7)
Running openstack CLI commands sometimes takes a long time due to
the fact that the CLI data model needs to be loaded from an increasing
number of python packages. This has a negative impact on cookbook
recipes that make extensive use of the openstack CLI, one of which
is the post_install neutron recipe, which evaluates the need to create
and then conditionally creates default objects (networks, routers).
Based on Jenkins HA job logs, an openstack CLI command can take up to
10-15 seconds to complete, which means the founder node is kept
busy for up to 100-150 seconds while evaluating the need to create
these default objects. This delay needs to be addressed in the
neutron cookbook, otherwise it may negatively impact other …
=> [4.0] neutron: fix neutron ha timeout

chef/cookbooks/neutron/recipes/server.rb, chef/cookbooks/nova/recipes/database.rb
This should help with initial setup of database in galera/mysql case
=> Extend timeouts for db syncs

chef/cookbooks/neutron/attributes/default.rb, chef/cookbooks/neutron/files/default/neutron-l3-ha-service.rb, spec/neutron_l3_ha_service_spec.rb
The neutron-l3-ha-service will log to:
`/var/log/neutron/neutron-l3-ha-service.log`
With a daily rotation, to avoid polluting messages
=> neutron-l3-ha-service: fix logging (bsc#1059460)

chef/cookbooks/neutron/attributes/default.rb, chef/cookbooks/neutron/files/default/neutron-l3-ha-service.rb, spec/neutron_l3_ha_service_spec.rb
backport from https://github.com/crowbar/crowbar-openstack/pull/1343
The neutron-l3-ha-service will log to:
`/var/log/neutron/neutron-l3-ha-service.log`
With a daily rotation, to avoid polluting messages
=> [4.0] Fix neutron ha service logging

chef/cookbooks/mysql/recipes/ha_galera.rb, chef/cookbooks/mysql/templates/default/galera.cnf.erb, chef/cookbooks/mysql/templates/default/logging.cnf.erb, chef/data_bags/crowbar/migrate/database/104_add_expire_logs_days.rb, chef/data_bags/crowbar/migrate/database/203_add_expire_logs_days.rb, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema, crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml, crowbar_framework/config/locales/database/en.yml
This commit makes the expire_logs_days option configurable via crowbar.
More information about the option can be found at
https://mariadb.com/kb/en/library/replication-and-binary-log-server-system-variables/#expire_logs_days.
=> mariadb: Add expire_logs_days config option

chef/cookbooks/mysql/recipes/ha_galera.rb, chef/cookbooks/mysql/templates/default/galera.cnf.erb, chef/cookbooks/mysql/templates/default/logging.cnf.erb, chef/data_bags/crowbar/migrate/database/104_add_expire_logs_days.rb, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema, crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml, crowbar_framework/config/locales/database/en.yml
This commit makes the expire_logs_days option configurable via crowbar.
More information about the option can be found at
https://mariadb.com/kb/en/library/replication-and-binary-log-server-system-variables/#expire_logs_days.
(cherry picked from commit 9632dfa5c183df64f5c64f0dab3d0643700b2934)
Backport of #1366
=> [4.0] mariadb: Add expire_logs_days config option

chef/cookbooks/cinder/recipes/controller_ha.rb, chef/cookbooks/neutron/recipes/server_ha.rb, chef/data_bags/crowbar/migrate/cinder/204_add_rate_limit.rb, chef/data_bags/crowbar/migrate/neutron/205_add_rate_limit.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema, chef/data_bags/crowbar/template-neutron.json, chef/data_bags/crowbar/template-neutron.schema
Adds HA rate limiting options to the raw template for the different
services that depend from neutron and cinder. Defaults to 0 as the values, which means
no rate limiting
=> Add HA rate limiting options to raw template to neutron and cinder

chef/cookbooks/memcached/attributes/default.rb, chef/cookbooks/memcached/recipes/default.rb, chef/cookbooks/memcached/templates/default/memcached.conf.erb, chef/cookbooks/memcached/templates/default/memcached.sysconfig.erb
In a big deployment, the default connections limit for memcached is too
low (1024) so its easy to reach it.
Increase the max connections limit for memcached to 4096 which should be
enough to deal with big deployments.
(cherry picked from commit 530420f5efe413e880d8b93e13193336a707d31f)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1372
=> [4.0] memcached: increase max connections limit

chef/cookbooks/nova/recipes/compute.rb
We found in some situations that when generating a public ssh key from a
private key using stdin, the ssh-keygen command would fail. In those
situations it helps to read the private from the file it was just
writen in the previous code block.
=> nova: get pub key from file instead of stdin

chef/cookbooks/memcached/attributes/default.rb, chef/cookbooks/memcached/recipes/default.rb, chef/cookbooks/memcached/templates/default/memcached.conf.erb, chef/cookbooks/memcached/templates/default/memcached.sysconfig.erb
In a big deployment, the default connections limit for memcached is too
low (1024) so its easy to reach it.
Increase the max connections limit for memcached to 4096 which should be
enough to deal with big deployments.
=> memcached: increase max connections limit

chef/cookbooks/mysql/recipes/server.rb
We only use root access via the unix domain socket so we can remove any
other root user.
Additional fix for https://bugzilla.suse.com/show_bug.cgi?id=1060628
=> mariadb: Drop unneeded root users (bsc#106062)

chef/cookbooks/barbican/recipes/common.rb
By creating the config file before running the initial database sync be
can remove the addtional db connection parameter from the "barbican db
upgrade" call. Which brings the recipe more in sync with how we do
things in the other barclamps.
It also avoid a shell escaping issues with db_connection uri that
contain special character like '&' that would cause issues on the
shell. (e.g. for ssl enabled MariaDB we add some ssl parameters to it
via "&ssl...=")
This should fix the current failures in the ssl CI jobs e.g.: https://ci.suse.de/job/openstack-mkcloud/88868/parsed_console/
=> barbican: reorder config creation and initial db sync 

chef/cookbooks/keystone/recipes/server.rb, chef/data_bags/crowbar/migrate/keystone/204_remove_updated_password.rb, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema, crowbar_framework/app/models/keystone_service.rb, crowbar_framework/app/views/barclamp/keystone/_edit_attributes.html.haml, crowbar_framework/config/locales/keystone/en.yml
Use a node attribute to store a backup copy of the admin password, to be used when the admin password is changed.
This replaces the previous method of managing the admin password change through a dedicated UI `updated_password` attribute and allows the user to change the password by simply modifying the regular `password` UI attribute.
The advantage of having a backup copy of the admin password in the node attributes is that the new password value is immediately available after a password change, even during the chef compilation phase. The implications of this:
- the new password value can immediately be used by all recipes during the chef compilation phase, which removes the need of having to deal with a password change scenario in every openstack cookbook using keystone for …
=> keystone: store old admin password in node attr for update

chef/cookbooks/nova/recipes/compute.rb
backport from https://github.com/crowbar/crowbar-openstack/pull/1379
We found in some situations that when generating a public ssh key from a
private key using stdin, the ssh-keygen command would fail. In those
situations it helps to read the private from the file it was just
writen in the previous code block.
(cherry picked from commit 12b7b58fdc78b2596cef6b4625e9d34e70382e80)
=> [4.0] nova: get pub key from file instead of stdin

chef/cookbooks/neutron/recipes/network_agents_ha.rb
Update the neutron barclamp to use the neutron service user credentials for the neutron-l3-ha/neutron-ha-tool service.
The neutron-l3-ha service was previously configured to use the admin user, which:
1. is not necessary - the neutron service user is more  appropriate
2. is problematic during a keystone admin password update, because it takes some time for the new admin password to reach the neutron barclamps in the chef-run, which means the neutron-l3-ha service may be triggered and run with the old admin password value and ultimately fail.
=> neutron: use service account for neutron-l3-ha service

chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
The FWaaS configuration driven by the neutron barclamp was missing the following L3 agent configuration options:
```
[AGENT]
extensions = fwaas
[fwaas]
agent_version = v1
driver = iptables
enabled = True
```
Because of this, configured fwaas instances were stuck in a PENDING_UPDATE state.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1064057
More info:
- https://docs.openstack.org/ocata/networking-guide/fwaas-v1-scenario.html
- https://bugs.launchpad.net/neutron/+bug/1635180
=> neutron: fix fwaas_v1 configuration (bsc#1064057)

chef/cookbooks/mysql/attributes/server.rb, chef/data_bags/crowbar/migrate/database/204_add_pacemaker_timeouts.rb, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema
In big deployments it might be required to adapt the timeouts according
to the deployments. This change allows the operator to specify the
timeouts which fit best.
=> mariadb: Make HA op timeouts configurable

chef/cookbooks/nova/recipes/flavors.rb
- reusing the output of flavor-list
- subscribes and not_if are independent
as a result the block will always try to create the flavors even if
they exist
This saves about 15-20 secs on non-shared hardware and about 1min on a
loaded CI
=> nova: improve flavors creation performance

chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
(backport of #1386)
The FWaaS configuration driven by the neutron barclamp was missing the following L3 agent configuration options:
```
[AGENT]
extensions = fwaas
[fwaas]
agent_version = v1
driver = iptables
enabled = True
```
Because of this, configured fwaas instances were stuck in a PENDING_UPDATE state.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1064057
More info:
- https://docs.openstack.org/ocata/networking-guide/fwaas-v1-scenario.html
- https://bugs.launchpad.net/neutron/+bug/1635180
=> [4.0] neutron: fix fwaas_v1 configuration (bsc#1064057)

chef/cookbooks/tempest/templates/default/tempest.conf.erb
It seems the heat_plugin needs the "disable_ssl_certificate_validation"
setting as well. See:
http://git.openstack.org/cgit/openstack/heat/tree/heat_integrationtests/common/config.py?h=stable/pike#n82
=> tempest: Fix SSL with self-signed certificates

chef/cookbooks/cinder/recipes/api.rb, chef/cookbooks/cinder/recipes/scheduler.rb, chef/cookbooks/cinder/recipes/volume.rb, chef/cookbooks/horizon/recipes/server.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/postgresql/recipes/server.rb, chef/cookbooks/postgresql/templates/default/limits.erb, chef/cookbooks/rabbitmq/recipes/rabbit.rb, chef/cookbooks/rabbitmq/templates/default/limits.erb, chef/data_bags/crowbar/migrate/cinder/205_add_resource_limits.rb, chef/data_bags/crowbar/migrate/database/204_add_resource_limits.rb, chef/data_bags/crowbar/migrate/horizon/203_add_resource_limits.rb, chef/data_bags/crowbar/migrate/keystone/204_add_resource_limits.rb, chef/data_bags/crowbar/migrate/rabbitmq/200_add_resource_limits.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema, chef/data_bags/crowbar/template-horizon.json, chef/data_bags/crowbar/template-horizon.schema, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema, chef/data_bags/crowbar/template-rabbitmq.json, chef/data_bags/crowbar/template-rabbitmq.schema
Some services require modifications to the system resource limits, such
as the maximum number of open files, that we cannot necessarily predict
a reasonable default for. Without this patch, there is no way to control
those limits from crowbar and they must be changed manually. This patch
adds a resource_limits parameter to a few barclamps to allow
administrators to set these limits for specific services from the
barclamp that controls those services. Currently only the LimitNOFILE
(systemd's name for the maximum number of open files) limit is supported.
This pull request is split into four commits and it will be easiest to review them each one at a time.
- Use utils_systemd_override_limits LWRP for the cinder barclamp.
- Use the same LWRP in the keystone and horizon barclamps to …
=> Add resource limits controls (bsc#1020922) 

chef/cookbooks/cinder/recipes/api.rb, chef/cookbooks/cinder/recipes/scheduler.rb, chef/cookbooks/cinder/recipes/volume.rb, chef/cookbooks/horizon/recipes/server.rb, chef/cookbooks/keystone/recipes/server.rb, chef/cookbooks/postgresql/recipes/server.rb, chef/cookbooks/postgresql/templates/default/limits.erb, chef/cookbooks/rabbitmq/recipes/rabbit.rb, chef/cookbooks/rabbitmq/templates/default/limits.erb, chef/data_bags/crowbar/migrate/cinder/110_add_resource_limits.rb, chef/data_bags/crowbar/migrate/database/105_add_resource_limits.rb, chef/data_bags/crowbar/migrate/horizon/102_add_resource_limits.rb, chef/data_bags/crowbar/migrate/keystone/113_add_resource_limits.rb, chef/data_bags/crowbar/migrate/rabbitmq/102_add_resource_limits.rb, chef/data_bags/crowbar/template-cinder.json, chef/data_bags/crowbar/template-cinder.schema, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema, chef/data_bags/crowbar/template-horizon.json, chef/data_bags/crowbar/template-horizon.schema, chef/data_bags/crowbar/template-keystone.json, chef/data_bags/crowbar/template-keystone.schema, chef/data_bags/crowbar/template-rabbitmq.json, chef/data_bags/crowbar/template-rabbitmq.schema
Some services require modifications to the system resource limits, such
as the maximum number of open files, that we cannot necessarily predict
a reasonable default for. Without this patch, there is no way to control
those limits from crowbar and they must be changed manually. This patch
adds a resource_limits parameter to a few barclamps to allow
administrators to set these limits for specific services from the
barclamp that controls those services. Currently only the LimitNOFILE
(systemd's name for the maximum number of open files) limit is supported.
This pull request is split into four commits and it will be easiest to review them each one at a time.
Use utils_systemd_override_limits LWRP for the cinder barclamp.
Use the same LWRP in the keystone and horizon barclamps to demonstrate …
=> [4.0]  Add resource limits controls (bsc#1020922)

chef/cookbooks/ceilometer/recipes/server.rb, chef/cookbooks/crowbar-openstack/providers/wsgi.rb, chef/cookbooks/crowbar-openstack/resources/wsgi.rb, chef/cookbooks/crowbar-openstack/templates/default/vhost-wsgi.conf.erb, chef/data_bags/crowbar/migrate/ceilometer/202_add_api_timeout.rb, chef/data_bags/crowbar/template-ceilometer.json, chef/data_bags/crowbar/template-ceilometer.schema
When ceilometer works with a large database, the ceilometer-api takes a longer time to respond to client requests. This leads to Gateway Timeout errors.
This commit makes the ceilometer-api wsgi timeout value configurable through the raw barclamp attribute 'api.timeout', which has a default value of 2 minutes.
Fixes: [bsc#1064060](https://bugzilla.suse.com/show_bug.cgi?id=1064060)
Also fixes: [bsc#1061197 (partially)](https://bugzilla.suse.com/show_bug.cgi?id=1061197), [bsc#1046787 (partially)](https://bugzilla.suse.com/show_bug.cgi?id=1046787), [bsc#1064088](https://bugzilla.suse.com/show_bug.cgi?id=1064088)
=> ceilometer: add configurable API timeout attribute (bsc#1064060)

chef/cookbooks/ceilometer/recipes/server.rb, chef/cookbooks/crowbar-openstack/providers/wsgi.rb, chef/cookbooks/crowbar-openstack/resources/wsgi.rb, chef/cookbooks/crowbar-openstack/templates/default/vhost-wsgi.conf.erb, chef/data_bags/crowbar/migrate/ceilometer/105_add_api_timeout.rb, chef/data_bags/crowbar/template-ceilometer.json, chef/data_bags/crowbar/template-ceilometer.schema
(backport for #1397)
When ceilometer works with a large database, the ceilometer-api takes a longer time to respond to client requests. This leads to Gateway Timeout errors.
This commit makes the ceilometer-api wsgi timeout value configurable through the raw barclamp attribute 'api.timeout', which has a default value of 2 minutes.
Fixes: [bsc#1064060](https://bugzilla.suse.com/show_bug.cgi?id=1064060)
Also fixes: [bsc#1061197 (partially)](https://bugzilla.suse.com/show_bug.cgi?id=1061197), [bsc#1046787 (partially)](https://bugzilla.suse.com/show_bug.cgi?id=1046787), [bsc#1064088](https://bugzilla.suse.com/show_bug.cgi?id=1064088)
=> [4.0] ceilometer: add configurable API timeout attribute (bsc#1064060)

chef/cookbooks/mysql/attributes/server.rb, chef/data_bags/crowbar/migrate/database/105_add_pacemaker_timeouts.rb, chef/data_bags/crowbar/template-database.json, chef/data_bags/crowbar/template-database.schema
In big deployments it might be required to adapt the timeouts according
to the deployments. This change allows the operator to specify the
timeouts which fit best.
(cherry picked from commit 2c5d20d15f8e96ad206eddb04d726433b0f2615e)
Backport of #1384
=> [4.0] mariadb: Make HA op timeouts configurable

chef/cookbooks/neutron/recipes/network_agents_ha.rb
(backports #1389)
Update the neutron barclamp to use the neutron service user credentials for the neutron-l3-ha/neutron-ha-tool service.
The neutron-l3-ha service was previously configured to use the admin user, which:
1. is not necessary - the neutron service user is more appropriate
2. is problematic during a keystone admin password update, because it takes some time for the new admin password to reach the neutron barclamps in the chef-run, which means the neutron-l3-ha service may be triggered and run with the old admin password value and ultimately fail.
=> [4.0] neutron: use service account for neutron-l3-ha service

chef/cookbooks/postgresql/recipes/server_redhat.rb, chef/cookbooks/rabbitmq/recipes/default.rb
Originally, crowbar could not restart the postgresql or rabbitmq resource agents. We "fixed" this so that crowbar could properly manage it, but this is really not a safe thing to do for HA services. This PR reverts those commits so that we go back to the original behavior. We don't make either postgresql or rabbitmq highly configurable so neither the original changes nor this revert will have a significant impact on users.
Backport of #1301
=> [4.0] Revert ha service restarts

chef/data_bags/crowbar/migrate/database/204_add_pacemaker_timeouts.rb
We backported the original commit which means that the ha values can
already exist. In the current implementation we should override the
settings.
=> database: Only add pacemaker timeouts if not exists
