crowbar_framework/app/models/swift_service.rb
crowbar_framework/app/models/tempest_service.rb

https://github.com/crowbar/crowbar-core/pull/14 introduced a new OO-style locking API.
Supersedes https://github.com/crowbar/crowbar-openstack/pull/4

[UNTESTED] use the new locking API

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/vmware_support.rb
chef/data_bags/crowbar/bc-template-neutron.json
chef/data_bags/crowbar/migrate/neutron/043_add_ovs_bridge.rb
crowbar_framework/app/models/neutron_service.rb
crowbar_framework/app/models/nova_service.rb

This depends on: https://github.com/crowbar/crowbar-core/pull/33

Let the network barclamp create OVS bridges

---

chef/cookbooks/horizon/attributes/default.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb
chef/data_bags/crowbar/bc-template-horizon.json
chef/data_bags/crowbar/bc-template-horizon.schema
chef/data_bags/crowbar/migrate/horizon/033_remove_use_keystone_v3.rb
chef/data_bags/crowbar/migrate/horizon/034_add_multi_domain_support.rb
crowbar_framework/app/models/horizon.rb

This is  https://github.com/crowbar/barclamp-nova_dashboard/pull/227 ported to the new repo layout

Cleanup keystone v3 attribute and enable multi-domain support

---

chef/cookbooks/swift/recipes/proxy.rb
chef/cookbooks/swift/templates/default/proxy-server.conf.erb

The previous entry point was deprecated in Kilo and
got removed in Liberty

Use ceilometermiddleware for object store integration

---

chef/cookbooks/nova/recipes/docker.rb

We do not need to load docker image explicitely,

---

chef/cookbooks/tempest/recipes/config.rb

tempest: Use glance API v1 also for uploading docker image

---

chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb

* Runs collecstatic command to collect static file
in single location
* Adds COMPRESS_OFFLINE option to local_settings.py
* Runs compress command to compress content outside
of request/response cycle

Runs collecstatic and compress managment commands

---

crowbar_framework/app/models/neutron_service.rb

All compute nodes, even if we don't ourself create bridges on them need ovs
running when the ovs mech driver is selected.

Set flag to install and start openvswitch (bsc#950798)

---

chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb

This reverts commit 7621872681e3731102b367e2ce19fd4e9fd1f540.

Revert "Runs collecstatic and compress managment commands"

---

chef/cookbooks/horizon/recipes/server.rb

Nothing lives in /var/lib/openstack-dashboard...

horizon: Stop creating useless directory

---

chef/data_bags/crowbar/migrate/nova/035_rename_nova_roles.rb

We also need to migrate the elements_expanded attribute

Fix migration of nova-multi-* to nova-* in HA case

---

chef/cookbooks/cinder/recipes/volume.rb
chef/cookbooks/cinder/templates/default/tgt.sysconfig.erb

http://bugzilla.suse.com/show_bug.cgi?id=828214

cinder: Make tgtd listen on admin IP address only (bsc#828214)

---

crowbar_framework/config/docs/openstack.yml
crowbar_framework/config/locales/openstack/en.yml
openstack.yml

**Depends on https://github.com/vuntz/crowbar-core/pull/1 and https://github.com/crowbar/crowbar-core/pull/121**

Restructured documentation on yml config

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/database/recipes/crowbar.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb
chef/cookbooks/manila/templates/default/manila.conf.erb
chef/cookbooks/neutron/templates/default/ml2_conf_cisco.ini.erb
chef/cookbooks/swift/libraries/rack_awareness.rb
chef/data_bags/crowbar/migrate/cinder/031_add_default_availability_zone.rb
chef/data_bags/crowbar/migrate/cinder/033_add_max_min_size_timeout_pool.rb
chef/data_bags/crowbar/migrate/cinder/043_add_rpc_response_timeout.rb
chef/data_bags/crowbar/migrate/horizon/020_add_site_theme.rb
chef/data_bags/crowbar/migrate/horizon/021_add_help_url.rb
chef/data_bags/crowbar/migrate/horizon/034_add_multi_domain_support.rb
chef/data_bags/crowbar/migrate/keystone/020_add_region.rb
chef/data_bags/crowbar/migrate/keystone/031_add_version.rb
chef/data_bags/crowbar/migrate/keystone/032_add_domain_specific_drivers.rb
chef/data_bags/crowbar/migrate/keystone/033_add_token_timeout.rb
chef/data_bags/crowbar/migrate/manila/010_add_manual_backend.rb
chef/data_bags/crowbar/migrate/manila/011_add_max_header_line.rb
chef/data_bags/crowbar/migrate/neutron/022_seperate_ml2_drivers.rb
chef/data_bags/crowbar/migrate/nova/033_add_configdrive.rb
chef/data_bags/crowbar/migrate/nova/034_configure_block_device_allocation.rb

According to our now master of style, Hash#has_key? is deprecated in
favor of Hash#key?. (https://github.com/bbatsov/ruby-style-guide#hash-key)

Avoid HoundCI bitching about has_key?

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

This is a copy of the Liberty tempest.conf.sample
with our current modification.

tempest: update tempest.conf.erb to Liberty

---

chef/cookbooks/keystone/attributes/default.rb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/data_bags/crowbar/migrate/keystone/034_update_default_attributes.rb
chef/data_bags/crowbar/template-keystone.json

Updating keystone.conf template config with OpenStack Liberty

Update keystone.conf config template with Liberty

---

chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/cinder/attributes/default.rb
chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/cinder/recipes/monitor.rb
chef/cookbooks/cinder/recipes/sql.rb
chef/cookbooks/database/recipes/crowbar.rb
chef/cookbooks/glance/attributes/default.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/glance/recipes/common.rb
chef/cookbooks/glance/recipes/monitor.rb
chef/cookbooks/glance/recipes/registry.rb
chef/cookbooks/heat/recipes/server.rb
chef/cookbooks/horizon/attributes/default.rb
chef/cookbooks/horizon/recipes/monitor.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/keystone/recipes/monitor.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/manila/recipes/common.rb
chef/cookbooks/manila/recipes/monitor.rb
chef/cookbooks/manila/recipes/sql.rb
chef/cookbooks/neutron/recipes/database.rb
chef/cookbooks/neutron/recipes/monitor.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/nova/recipes/database.rb
chef/cookbooks/nova/recipes/memcached.rb
chef/cookbooks/postgresql/recipes/server.rb
chef/cookbooks/rabbitmq/recipes/rabbit.rb
chef/cookbooks/swift/recipes/disks.rb
chef/cookbooks/swift/recipes/proxy.rb
chef/cookbooks/swift/recipes/storage.rb

This is mostly about changing "node[:foo] =" to "node.set[:foo] ="

Some work for compatibility with chef 11

---

chef/cookbooks/cinder/recipes/ceph.rb
chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/cinder/recipes/volume.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/glance/recipes/ceph.rb
chef/cookbooks/glance/recipes/setup.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/manila/recipes/setup.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/recipes/vmware_support.rb
chef/cookbooks/nova/recipes/ceph.rb
chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/postgresql/libraries/default.rb
chef/cookbooks/postgresql/recipes/ruby.rb
chef/cookbooks/swift/recipes/dispersion.rb
chef/cookbooks/swift/recipes/proxy.rb
chef/cookbooks/swift/recipes/proxy_ha.rb
chef/cookbooks/swift/recipes/slog.rb
chef/cookbooks/swift/recipes/storage.rb
chef/cookbooks/tempest/recipes/config.rb

The exists? one is deprecated.

Update all usages of ::File.exists? to ::File.exist?

---

chef/cookbooks/ceilometer/recipes/mongodb.rb
chef/cookbooks/ceilometer/recipes/server_ha.rb
chef/cookbooks/cinder/recipes/controller_ha.rb
chef/cookbooks/nova/recipes/controller_ha.rb
chef/cookbooks/postgresql/recipes/ha.rb
chef/cookbooks/postgresql/recipes/ha_storage.rb
chef/cookbooks/rabbitmq/recipes/ha.rb

This depends on https://github.com/crowbar/crowbar-ha/pull/46 (EDIT: already merged)

postgresql, rabbitmq, cinder, nova, ceilometer: Use new pacemaker_transaction LWRP to create pacemaker resources

---

chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/glance/recipes/setup.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/swift/recipes/proxy.rb
chef/cookbooks/tempest/recipes/config.rb

Replaces %x with backticks as per updated
ruby style.

Fixes hound issues for %x

---

chef/cookbooks/glance/recipes/ha.rb
chef/cookbooks/heat/recipes/ha.rb
chef/cookbooks/keystone/recipes/ha.rb

Just for consistency with what we'll do elsewhere.

glance, heat, keystone: Improve name of transaction resources

---

chef/cookbooks/heat/templates/default/heat.conf.erb
chef/cookbooks/keystone/templates/default/keystone.conf.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb

See https://bugs.launchpad.net/nova/+bug/1361360 for the full
story.

Avoid greenthreads hanging endlessly on "slowloris" attack

---

chef/cookbooks/ceilometer/recipes/mongodb.rb
chef/cookbooks/ceilometer/recipes/server_ha.rb
chef/cookbooks/cinder/recipes/controller_ha.rb
chef/cookbooks/glance/recipes/ha.rb
chef/cookbooks/heat/recipes/ha.rb
chef/cookbooks/keystone/recipes/ha.rb
chef/cookbooks/manila/recipes/controller_ha.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb
chef/cookbooks/neutron/recipes/server_ha.rb
chef/cookbooks/nova/recipes/controller_ha.rb
chef/cookbooks/swift/recipes/proxy_ha.rb

~~Depends on https://github.com/crowbar/crowbar-ha/pull/57~~

Set clone-max metadata for clone resources

---

crowbar_framework/app/models/ceilometer_service.rb
crowbar_framework/app/models/cinder_service.rb
crowbar_framework/app/models/database_service.rb
crowbar_framework/app/models/glance_service.rb
crowbar_framework/app/models/heat_service.rb
crowbar_framework/app/models/horizon_service.rb
crowbar_framework/app/models/keystone_service.rb
crowbar_framework/app/models/manila_service.rb
crowbar_framework/app/models/neutron_service.rb
crowbar_framework/app/models/nova_service.rb
crowbar_framework/app/models/rabbitmq_service.rb
crowbar_framework/app/models/swift_service.rb
crowbar_framework/lib/openstack.rb
crowbar_framework/lib/openstack/ha.rb

Depends on https://github.com/crowbar/crowbar-ha/pull/62

Set node attribute for OpenStack-role pacemaker attribute for controller

---

crowbar_framework/app/models/nova_service.rb
crowbar_framework/config/locales/nova/en.yml

nova: Fix call to non existing method (caused by f064ae87)

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

Enables manila tests in tempest if manila service is running.

Enables manila tests

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/data_bags/crowbar/migrate/cinder/045_add_vmware_cluster_name.rb
chef/data_bags/crowbar/migrate/glance/026_add_vmware_multi_datastores.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema
chef/data_bags/crowbar/template-glance.json
chef/data_bags/crowbar/template-glance.schema
crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml
crowbar_framework/app/views/barclamp/glance/_edit_attributes.html.haml
crowbar_framework/config/locales/cinder/en.yml
crowbar_framework/config/locales/glance/en.yml

OpenStack Glance is supporting multi datastores which we would like to have it. It was already tested and works like charm

glance & cinder: Improve VMware integration with multi clusters and datastores

---

chef/cookbooks/swift/recipes/storage.rb
chef/cookbooks/swift/templates/default/container-sync-realms.conf.erb
chef/cookbooks/swift/templates/default/object-expirer.conf.erb
chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb
chef/data_bags/crowbar/migrate/swift/022_add_container_sync.rb
chef/data_bags/crowbar/template-swift.json
chef/data_bags/crowbar/template-swift.schema
crowbar_framework/app/models/swift_service.rb

There's one tempest test at least depending on the container sync.

Configure additional swift services

---

crowbar_framework/lib/openstack/upgrade.rb

Requires https://github.com/crowbar/crowbar-core/pull/188 and https://github.com/crowbar/crowbar-ceph/pull/34
Function like this needs to be called from upgrade wizard

Function to check if additional repos are present after the upgrade of admin node

---

crowbar_framework/lib/openstack/ha.rb

**Note:** this goes hand in hand with https://github.com/crowbar/crowbar-ha/pull/71
Because the pacemaker resources for haproxy and apache are created in
crowbar-pacemaker (from crowbar-ha), we, in theory, shouldn't assume
there that these two services will be used for OpenStack and so we can't
always just add the location constraint to tell pacemaker to only run
these on controller nodes.
So we add a flag for that.

openstack: Add flag to configure haproxy & apache for controller HA only

---

chef/data_bags/crowbar/migrate/neutron/046_infoblox.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

While we don't support the Infoblox integration yet. We need to accept the
attributes here to allow upgrading from Tex.

Add migration for Tex infoblox attributes

---

chef/cookbooks/tempest/templates/default/tempest.conf.erb

The current list of available options is incomplete. Add the
missing options and set some sane defaults.

tempest: Update [share] options in tempest.conf.erb

---

crowbar_framework/lib/openstack/upgrade.rb

This change makes it easier to handle all the diffrent cases in the UI.

Refactor optional repo check

---

chef/cookbooks/tempest/templates/default/tempest.conf.erb

Use the correct variable name in the template.

tempest: Set password in tempest.conf

---

chef/cookbooks/postgresql/recipes/db_restore.rb
chef/cookbooks/postgresql/recipes/server.rb

This adds a recipe to restore the postgresql database and
adds condition to do this when node is an upgraded one.

Restores postgresql database

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/cinder/templates/default/cinder_emc_config.xml.erb
chef/data_bags/crowbar/migrate/cinder/046_update_emc_backend.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema
crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml
crowbar_framework/config/locales/cinder/en.yml

Updating cinder.conf template config with Liberty

Update cinder.conf config template with Liberty

---

chef/cookbooks/nova/attributes/default.rb
chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/compute_ha.rb
chef/roles/nova-compute-ha.rb

This still needs to be plugged in crowbar, but the code can already be used manually by changing the runlists and some attributes.

nova: Add role and recipe for compute nodes HA

---

chef/data_bags/crowbar/migrate/nova/040_add_compute_ha_role.rb
chef/data_bags/crowbar/template-nova.json
chef/roles/nova-ha-compute.rb
crowbar_framework/app/models/nova_service.rb
crowbar_framework/config/locales/nova/en.yml
crowbar_framework/lib/openstack/ha.rb

This is a bit tricky; if the commit messages are not clear enough, I'm happy to improve them -- just tell me how :-)
**Note:** This depends on ~~https://github.com/crowbar/crowbar-ha/pull/70~~, ~~https://github.com/crowbar/crowbar-core/pull/193~~ and ~~https://github.com/crowbar/crowbar-ha/pull/74~~

nova: Add crowbar orchestration for compute HA

---

chef/data_bags/crowbar/migrate/cinder/046_update_emc_backend.rb

we encountered this at the upgrade restore step...

fix typo in cinder migration

---

chef/cookbooks/nova/recipes/ceph.rb

This change is fixing issue with "libvirtError: Secret not found: rbd no secret matches uuid"
For more details please go to https://bugzilla.suse.com/show_bug.cgi?id=963029

Fix issue with "libvirtError: Secret not found" for multi rbd backend,  (bsc#963029)

---

chef/cookbooks/swift/recipes/default.rb

Due to how we assign roles on nodes in crowbar (through the
crowbar-$node role), it can happen that a node is assigned to a role,
but the node doesn't have the role yet (this happens only when
chef-client has run on the node). This is exactly what we hit here.
The first batch of the application of a swift proposal is for storage
nodes. So there's no swift-proxy node yet (unless a storage node is also
a proxy node). However, we search for a proxy node, which unfortunately
doesn't work; but we were using get_instance() for the search, and this
helper is trying to be nice by ensuring we always get a valid node by
falling back to the current node if it doesn't find anything. This gets
nasty when we use HA for swift-proxy because we then try to get the
virtual hostname of the haproxy service, …

swift: Fix chef crash on storage nodes when proxy is HA (bsc#964277)

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

We have set this already in some cookbooks, also do the sam€
for the others.

Set use_stderr=false everywhere

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb

This was added to the wrong place, moving it to the right place.

Cleanup cinder liberty conf rebase

---

chef/cookbooks/nova/templates/default/nova.conf.erb

One should use the auth plugin infrastructure since Kilo.

Stop setting deprecated options

---

chef/cookbooks/nova/attributes/default.rb
chef/cookbooks/nova/recipes/compute_ha.rb
chef/cookbooks/nova/recipes/instances.rb
chef/data_bags/crowbar/migrate/nova/041_setup_shared_instance_storage.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/assets/javascripts/barclamps/nova/application.js
crowbar_framework/app/models/nova_service.rb
crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml
crowbar_framework/config/locales/nova/en.yml

Still WIP, but opening the PR so I don't forget to submit later.

Fixes for compute nodes HA

---

chef/data_bags/crowbar/migrate/keystone/035_pki_uuid_switch.rb

keystone: Add mention of CVE-2015-7546 in the migration for PKI->UUID

---

chef/cookbooks/postgresql/recipes/server_redhat.rb

Before creating new data directory checks if data directory
is present and moves it to another location if it is.

Renames old postgres data dir

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/nova/definitions/nova_package.rb
chef/cookbooks/nova/recipes/compute.rb

**Note:** this depends on https://github.com/crowbar/crowbar-ha/pull/81

Use Chef::Provider::CrowbarPacemakerService for handling services for compute nodes HA

---

chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/swift/recipes/proxy.rb

Even empty files are not valid certificate information.

Check if ssl cert related files are non-empty

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

The L2 agent must start first, and at least before DHCP agent as DHCP
agent depends on it. Otherwise, this can result in port failing to bind.

neutron: Change order of resources in neutron-agents group

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

neutron-ha-tool is using a file to find the password to use to connect
to OpenStack. However, that file was not created before the
synchronization on sync marks, resulting in the resource possibly
starting on a node where the file is missing.
https://bugzilla.suse.com/show_bug.cgi?id=967098

neutron: Fix neutron-ha-tool initial start (bsc#967098)

---

chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb
chef/data_bags/crowbar/migrate/horizon/038_add_use_launch_instance_ng.rb
chef/data_bags/crowbar/template-horizon.json
chef/data_bags/crowbar/template-horizon.schema

It's not the default upstream yet, but people might want to play with
it.

horizon: Add attribute to use new "Launch Instance" dialog

---

chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/templates/default/neutron_zvm_plugin.ini.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/neutron/048_zvm_add_zhcp_nodename.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema

Those need to be in the [DEFAULT] section.

Fix config group of the ZVM related options

---

chef/cookbooks/swift/recipes/dispersion.rb

It was not using the right API version nor the right auth URL.

swift: Fix check for running dispersion or not

---

chef/cookbooks/openstack-database/recipes/api.rb
chef/cookbooks/openstack-database/recipes/conductor.rb
chef/cookbooks/openstack-database/recipes/taskmanager.rb
chef/cookbooks/openstack-database/templates/default/trove-conductor.conf.erb
chef/cookbooks/openstack-database/templates/default/trove-taskmanager.conf.erb
chef/cookbooks/openstack-database/templates/default/trove.conf.erb

I guess rebasing the templates would actually bring many fixes, but for now, this is a small bit.

Improve trove configuration

---

Gemfile

Reverts crowbar/crowbar-openstack#331

Revert "Set rake to version to 10.3.2"

---

chef/cookbooks/openstack-database/recipes/api.rb
chef/cookbooks/openstack-database/recipes/conductor.rb
chef/cookbooks/openstack-database/recipes/taskmanager.rb
chef/cookbooks/openstack-database/templates/default/trove-conductor.conf.erb
chef/cookbooks/openstack-database/templates/default/trove-taskmanager.conf.erb
chef/cookbooks/openstack-database/templates/default/trove.conf.erb

Backport of https://github.com/crowbar/crowbar-openstack/pull/305

[3.0] Improve trove config

---

chef/cookbooks/nova/recipes/compute.rb

We specifically split the use_shared_instance_storage bit from
setup_shared_instance_storage to allow manually configured shared
storage, but we we were still configuring the NFS mount on the compute
nodes when the setup is manual.

nova: Do not setup NFS mount to controller when shared storage is manual (bsc#971546)

---

chef/cookbooks/nova/recipes/compute.rb

We specifically split the use_shared_instance_storage bit from
setup_shared_instance_storage to allow manually configured shared
storage, but we were still configuring the NFS mount on the compute
nodes when the setup is manual.
https://bugzilla.suse.com/show_bug.cgi?id=971546
(cherry picked from commit bd748092f275bf02970fa8e8b919a33a180698db)
Backport of https://github.com/crowbar/crowbar-openstack/pull/336

[3.0] nova: Do not setup NFS mount when shared storage is manual (bsc#971546)

---

chef/cookbooks/neutron/files/default/crowbar-fix-tunnel-networks-mtu
chef/cookbooks/neutron/recipes/network_agents.rb

avoids a bug when a node is neutron-network but not neutron-server
cc @vuntz

pass database connection uri instead of calculating it

---

crowbar_framework/app/models/ceilometer_service.rb
crowbar_framework/app/models/cinder_service.rb
crowbar_framework/app/models/database_service.rb
crowbar_framework/app/models/glance_service.rb
crowbar_framework/app/models/heat_service.rb
crowbar_framework/app/models/horizon_service.rb
crowbar_framework/app/models/keystone_service.rb
crowbar_framework/app/models/neutron_service.rb
crowbar_framework/app/models/nova_service.rb
crowbar_framework/app/models/rabbitmq_service.rb
crowbar_framework/app/models/swift_service.rb
crowbar_framework/app/models/tempest_service.rb
crowbar_framework/app/models/trove_service.rb
crowbar_framework/config/locales/trove/en.yml

~~depends on https://github.com/SUSE-Cloud/automation/pull/879~~

Implement some basic proposal validation (bsc#967684)

---

chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/100_add_zvm_rootpass.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/helpers/barclamp/nova_helper.rb
crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml

This makes it less likely that invalid values are entered.

Various ZVM related fixes

---

chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

* config_drive is disable for the blkid test
* run_validation is disable for the hard reset test

Docker: disable config_drive and run_validation

---

chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/config.rb

This broke with the move to role recipes.

nova: Fix searches to be based on roles, not recipes

---

chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/files/default/crowbar-nova-set-availability-zone
chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/recipes/controller_ha.rb
chef/cookbooks/nova/recipes/database.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/cookbooks/openstack-database/templates/default/trove.conf.erb
chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb
chef/data_bags/crowbar/migrate/nova/101_nova_api_db.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/models/nova_service.rb
crowbar_framework/lib/openstack/upgrade.rb

Various changes to get mitaka openstack deployable

Mitaka porting

---

chef/cookbooks/magnum/recipes/role_magnum_server.rb
chef/cookbooks/magnum/recipes/sql.rb
chef/roles/magnum-server.rb

Change magnum barclamp to use role_<> recipe for simplified role for magnum-server . Depends on the actual barclamp being merged : https://github.com/crowbar/crowbar-openstack/pull/360

Use role recipe for magnum-server

---

chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/compute_ha.rb

Without this, I'm getting http://pastebin.nue.suse.com/16785/src on SP2 compute nodes...
See also http://mailman.suse.de/mlarch/SuSE/cloud-devel/2016/cloud-devel.2016.06/msg00075.html
Requires https://github.com/crowbar/crowbar-openstack/pull/423

Start virtlogd service on compute nodes

---

chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/ceilometer/recipes/common.rb

The db connection string was not correct.

aodh: Fix aodh deployment if mongodb is used

---

crowbar_framework/app/models/magnum_service.rb

This is required to have the API reachable from outside.
The commit also contains the commented out code that is generally used
for HA.

magnum: Allocate a public IP to magnum-server node

---

chef/cookbooks/trove/recipes/default.rb

We should not reference the IP/hostname of a specific controller, but of
the VIP.
https://bugzilla.suse.com/show_bug.cgi?id=970648

trove: Fix configuration when other services are using HA (bsc#970648)

---

crowbar_framework/app/models/nova_service.rb

Required for https://github.com/crowbar/crowbar-core/pull/516

nova: Update for Service.Object.active_update API change

---

chef/cookbooks/cinder/recipes/controller_ha.rb
chef/cookbooks/database/libraries/crowbar.rb
chef/cookbooks/glance/libraries/helpers.rb
chef/cookbooks/manila/recipes/controller_ha.rb
chef/cookbooks/nova/recipes/controller_ha.rb
chef/cookbooks/rabbitmq/libraries/crowbar.rb
crowbar_framework/app/models/horizon_service.rb

Depends on https://github.com/crowbar/crowbar-ha/pull/120

chef, crowbar: Use new HA helpers to fetch the VIP of a hostname

---

chef/cookbooks/heat/recipes/server.rb

Enable stacks global_index search in Heat policy.json,
so that Magnum can use list(global_tenant=True)
https://bugs.launchpad.net/magnum/+bug/1589955

[magnum] Enable global_index search in Heat policy

---

chef/cookbooks/magnum/recipes/setup.rb

During first run of chef-client options `trustee_domain_id`
and `trustee_domain_admin_id` were not saved in magnum.conf.
This was bacuse of order chef resources for ruby_block,
these attributes were saved after chef-client run ends.

Re-write recipe for creating Magnum trustee domain

---

chef/cookbooks/nova/templates/default/nova.conf.erb

Always enable force_config_drive for ZVM

[stable/3.0] Backport #457

---

chef/cookbooks/tempest/recipes/config.rb

keystone CLI is depreacted and will be removed in Newton. So switch
to the replacement which is openstack.
Also simplifiy a bit the getters for ec2 access and secret.

tempest: Replace keystone CLI calls with openstack

---

chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/glance/templates/default/glance-cache.conf.erb
chef/cookbooks/glance/templates/default/glance-manage.conf.erb
chef/cookbooks/glance/templates/default/glance-registry.conf.erb
chef/cookbooks/glance/templates/default/glance-scrubber.conf.erb
chef/data_bags/crowbar/migrate/glance/100_remove_enable_v3_api.rb
chef/data_bags/crowbar/template-glance.json
chef/data_bags/crowbar/template-glance.schema

Update the configuration templates for glance

glance: Update glance config templates for Mitaka

---

chef/cookbooks/cinder/recipes/volume.rb
chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/data_bags/crowbar/migrate/cinder/101_nfs_backend.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema
crowbar_framework/app/helpers/barclamp/cinder_helper.rb
crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml
crowbar_framework/config/locales/cinder/en.yml

Backport to Cloud 6.
https://github.com/crowbar/crowbar-openstack/pull/469

Cinder nfs backend 3.0

---

chef/cookbooks/cinder/recipes/volume.rb
chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/data_bags/crowbar/migrate/cinder/101_nfs_backend.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema
crowbar_framework/app/helpers/barclamp/cinder_helper.rb
crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml
crowbar_framework/config/locales/cinder/en.yml

Reverts crowbar/crowbar-openstack#497

Revert "Cinder nfs backend 3.0"

---

chef/cookbooks/nova/recipes/compute.rb

Reverts crowbar/crowbar-openstack#499

Revert "nova: Start virtlogd also for SLES 12.1 platform"

---

chef/cookbooks/manila/templates/default/manila.conf.erb
chef/data_bags/crowbar/migrate/manila/100_add_hitachi_config.rb
chef/data_bags/crowbar/template-manila.json
chef/data_bags/crowbar/template-manila.schema
crowbar_framework/app/helpers/manila_barclamp_helper.rb
crowbar_framework/app/views/barclamp/manila/_edit_attributes.html.haml
crowbar_framework/config/locales/manila/en.yml

Adds migration, schema+json for new attributes,
haml template for new attributes, driver to manila.conf,
locale entries for new attributes

Add hitachi HNAS driver to manila barclamp

---

chef/cookbooks/tempest/templates/default/tempest.conf.erb

~~* Removes [boto] section as ec2 support is removed~~

Updates tempest config template for Mitaka

---

chef/data_bags/crowbar/migrate/trove/101_add_service_details.rb
chef/data_bags/crowbar/template-trove.json
chef/data_bags/crowbar/template-trove.schema
crowbar_framework/app/models/trove_service.rb

Force the trove service password to be random_password in the
model, to match other services.

Set the trove service password to random

---

chef/cookbooks/magnum/attributes/default.rb
chef/cookbooks/magnum/libraries/helpers.rb
chef/cookbooks/magnum/recipes/api.rb
chef/cookbooks/magnum/recipes/common.rb
chef/cookbooks/magnum/recipes/ha.rb
chef/cookbooks/magnum/recipes/role_magnum_server.rb
crowbar_framework/app/models/magnum_service.rb

This pull request adds HA for magnum-api and magnum-conductor to the Magnum barclamp.

Added plumbing for HA to Magnum barclamp.

---

002_add_service_details.rb
chef/data_bags/crowbar/migrate/trove/001_add_configurable_db_attrs.rb
chef/data_bags/crowbar/template-trove.json
chef/data_bags/crowbar/template-trove.schema
crowbar_framework/app/models/trove_service.rb

Cherry-pick commits 7d9653f2c68720e30ce3a48d7e9c36fb5f99bbd8 and cdaa9ec2243693d36d1a67bb92271ff974b45e6b into stable/3.0

Stable trove random password

---

chef/cookbooks/neutron/libraries/helpers.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/recipes/vmware_support.rb
chef/cookbooks/nova/recipes/instances.rb
crowbar_framework/app/models/neutron_service.rb

This will help have the network info in only one location.
Should go with https://github.com/crowbar/crowbar-core/pull/510

Access network info through API, instead of directly fetching attributes

---

chef/cookbooks/swift/recipes/dispersion.rb

[swift populate-dispersion timeout (Trello)](https://trello.com/c/ZepcSmJ4/223-swift-populate-dispersion-timeout)

Small modifications to dispersion recipe

---

chef/cookbooks/nova/libraries/boot_kernel.rb
chef/cookbooks/nova/recipes/compute.rb

Since SP2 there is no separate XEN Kernel anymore.

Fix XEN Kernel recognition

---

chef/cookbooks/neutron/templates/default/10-opflex-agent-ovs.conf.erb

@mfriesenegger found issue in reading configuration file for opflex agent. This commit fixes that.

[stable/3.0] Backport #549

---

chef/cookbooks/swift/libraries/rack_awareness.rb

We are only interested in interfaces managed by crowbar
An alternative to https://github.com/crowbar/crowbar-openstack/pull/476

Look into crowbar wall for network interfaces.

---

chef/cookbooks/nova/recipes/compute_ha.rb

fence_compute doesn't work with v3 yet, unfortunately.

nova: Use keystone v2.0 for compute HA resources

---

crowbar_framework/app/models/neutron_service.rb
crowbar_framework/config/locales/neutron/en.yml

(cherry picked from commit 95f5bc20efcd6ccc7d82c07007d66d79fed9b5dd)

neutron_service: allows deployment of DVR in a cluster (bsc#974495)

---

chef/cookbooks/tempest/recipes/config.rb

https://bugzilla.suse.com/show_bug.cgi?id=991873

tempest: Don't assume that heat is deployed on tempest node (bsc#991873)

---

chef/cookbooks/barbican/attributes/default.rb
chef/cookbooks/barbican/libraries/helpers.rb
chef/cookbooks/barbican/recipes/api.rb
chef/cookbooks/barbican/recipes/common.rb
chef/cookbooks/barbican/recipes/ha.rb

This proposal never applies due to essential typos

barbican: Fix typos in HA setup

---

chef/cookbooks/nova/recipes/database.rb

@jgrassler I think you can provide some better reasoning for the commit message

nova-manage api_db sync needs to run before nova-manage db sync

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/recipes/server_ha.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/neutron/049_infoblox_update.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema
crowbar_framework/app/models/neutron_service.rb
crowbar_framework/config/locales/neutron/en.yml

This is a backport of https://github.com/crowbar/crowbar-openstack/pull/521 (master). Please do not merge this until https://github.com/crowbar/crowbar-openstack/pull/521 is merged (I don't think there are going to be any more changes to the pull request for `master`, but let's wait for it to land to be on the safe side).

neutron/nova: re-added infoblox support

---

chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/046_add_cross_az_attach.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema

(cherry picked from commit 6fc4f5ae069ccc9e311aa8cc0098ac8aca9ec9b6)

nova: Make "cross_az_attach" configurable

---

chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb

remove or fix parameters against newton config for ceilometer

ceilometer: update conf template to newton

---

chef/cookbooks/trove/recipes/default.rb

We should not reference the IP/hostname of a specific controller, but of
the VIP.
https://bugzilla.suse.com/show_bug.cgi?id=970648
(cherry picked from commit 7ed84719b2dce95b2518b3096b894468dd9f3afd)

[3.0] trove: Fix configuration when other services are using HA (bsc#970648)

---

chef/data_bags/crowbar/template-glance.json

102 was added in https://github.com/crowbar/crowbar-openstack/commit/b31a999614d8ee20881235bf20ef21d7cf7f18c3

glance: Bump the schema revision after latest change

---

chef/cookbooks/manila/templates/default/manila.conf.erb
chef/data_bags/crowbar/migrate/manila/102_modify_hitachi_config.rb
chef/data_bags/crowbar/template-manila.json
chef/data_bags/crowbar/template-manila.schema
crowbar_framework/app/views/barclamp/manila/_edit_attributes.html.haml

http://docs.openstack.org/releasenotes/manila/newton.html#deprecation-notes

manila: Update config file to newton

---

chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/config.rb

Backport of https://github.com/crowbar/crowbar-openstack/pull/663

Decrease amount of searches done in cookbooks for compute nodes

---

chef/cookbooks/heat/recipes/server.rb
chef/cookbooks/heat/templates/default/heat.conf.erb
chef/data_bags/crowbar/migrate/heat/102_drop_convergence.rb
chef/data_bags/crowbar/template-heat.json
chef/data_bags/crowbar/template-heat.schema

the old engine is pretty broken and convergence is anyway the default
since Mitaka.

heat: switch to convergence engine (bsc#1011324)

---

chef/cookbooks/swift/providers/ringfile.rb
chef/cookbooks/swift/recipes/ring-compute.rb
chef/cookbooks/swift/recipes/storage.rb
chef/cookbooks/swift/templates/default/account-server.conf.erb
chef/cookbooks/swift/templates/default/container-server.conf.erb
chef/cookbooks/swift/templates/default/object-server.conf.erb
chef/cookbooks/swift/templates/default/proxy-server.conf.erb

Swift upstream changed from 600x to 620x port range some time ago
in order to avoid port collissions.

swift: Switch to 620x port range

---

aodh.yml
bin/crowbar_aodh
chef/cookbooks/aodh/attributes/default.rb
chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/aodh/recipes/aodh_ha.rb
chef/cookbooks/aodh/recipes/role_aodh_server.rb
chef/cookbooks/aodh/templates/default/aodh.conf.erb
chef/cookbooks/ceilometer/attributes/default.rb
chef/cookbooks/ceilometer/metadata.rb
chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/data_bags/crowbar/migrate/ceilometer/102_remove_alarm_threshold_evaluation.rb
chef/data_bags/crowbar/template-aodh.json
chef/data_bags/crowbar/template-aodh.schema
chef/data_bags/crowbar/template-ceilometer.json
chef/roles/aodh-server.rb
crowbar_framework/app/controllers/aodh_controller.rb
crowbar_framework/app/helpers/barclamp/aodh_helper.rb
crowbar_framework/app/models/aodh_service.rb
crowbar_framework/app/models/ceilometer_service.rb
crowbar_framework/app/views/barclamp/aodh/_edit_attributes.html.haml
crowbar_framework/app/views/barclamp/ceilometer/_edit_attributes.html.haml
crowbar_framework/config/locales/aodh/en.yml
crowbar_framework/config/locales/ceilometer/en.yml

this PR creates a separate barclamp for aodh

aodh: create aodh barclamp

---

chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/047_add_migration_network.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/models/nova_service.rb
crowbar_framework/config/locales/nova/en.yml

This is a backport of pull request #466 .

[3.0] nova: Allow defining on which network live migration happens (bsc#990664)

---

chef/cookbooks/ceilometer/libraries/mongodb.rb
chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/ceilometer/recipes/mongodb.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/cinder/recipes/ceph.rb
chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/manila/recipes/common.rb
chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/recipes/vmware_support.rb
chef/cookbooks/nova/recipes/availability_zones.rb
chef/cookbooks/nova/recipes/ceph.rb
chef/cookbooks/nova/recipes/compute.rb
chef/cookbooks/nova/recipes/compute_ha.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/recipes/monitor.rb
chef/cookbooks/nova/templates/default/nova_nrpe.cfg.erb
chef/cookbooks/sahara/recipes/common.rb
chef/cookbooks/swift/recipes/default.rb
chef/cookbooks/swift/recipes/proxy.rb
chef/cookbooks/swift/recipes/ring-compute.rb
chef/cookbooks/swift/recipes/storage.rb
chef/cookbooks/trove/recipes/api.rb
chef/cookbooks/trove/recipes/conductor.rb
chef/cookbooks/trove/recipes/taskmanager.rb

~~Requires https://github.com/crowbar/crowbar-core/pull/906 (merged)~~

cookbooks: Use new node_search_with_cache helper

---

chef/cookbooks/nova/attributes/default.rb

Apparently noone ever tried to use ec2api so far..

nova: fix ec2api endpoint port

---

chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/templates/default/f5-openstack-agent.ini.erb

Backport of https://github.com/crowbar/crowbar-openstack/pull/790

neutron: Fix F5 config file

---

chef/cookbooks/swift/providers/ringfile.rb

There might be extra strings and newlines

swift: Extend ring file parsing

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/network_agents.rb
chef/cookbooks/neutron/templates/default/f5-openstack-agent.ini.erb
chef/data_bags/crowbar/migrate/neutron/055_f5_ha_type.rb
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema
crowbar_framework/app/helpers/barclamp/neutron_helper.rb
crowbar_framework/app/views/barclamp/neutron/_edit_attributes.html.haml
crowbar_framework/config/locales/neutron/en.yml

Backport of https://github.com/crowbar/crowbar-openstack/pull/788

neutron: Add ability to configure the f5_ha_type option for F5 LBaaS + one fix

---

chef/cookbooks/keystone/recipes/ha.rb

We want other openstack services to start after keystone. However, with
the move to a wsgi app behind apache, we didn't have any resource
specific to keystone in pacemaker, and blindly ordering things after
apache2 doesn't look like a good idea (as it could be hosting just
horizon, for instance).
So we create a dummy resource for keystone that does nothing, but that
can be used for the constraints.

keystone: Create dummy HA resource to allow ordering constraints

---

chef/cookbooks/nova/recipes/flavors.rb

Seems that there may be corner cases in which the not_if
will not work properly and try to retrigger the flavor creation

nova: change the not_if check for flavor creation

---

chef/cookbooks/magnum/recipes/post_install.rb
chef/cookbooks/magnum/recipes/role_magnum_server.rb

This will upload the magnum k8s image to glance by default and create a
magnum flavor.

magnum: Adds some post-install tasks

---

chef/cookbooks/nova/attributes/default.rb

This is @sayalilunkad 's PR, but she is on vacation and it was posted a while ago and jenkins has deleted its UPDATEREPO. I'd like to rebuild it but I can't force push to her branch so I'm resubmitting the PR.

nova: Fix ipaddress attribute

---

chef/cookbooks/neutron/recipes/server_ha.rb

We can not move primitives in/out a group in a maintenance update.
As we don't actually want groups anymore, just remove the bit from
https://github.com/crowbar/crowbar-openstack/pull/588

neutron: avoid adding a g-neutron group (bsc#1030318)

---

chef/cookbooks/glance/templates/default/glance-api.conf.erb

Glance: fix typo in the expression for vmware_api_insecure

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb

This patch reduces LOC by simplifying the use_ssl template variable
definition.

Clean up extraneous variables

---

chef/cookbooks/ceilometer/libraries/mongodb.rb
chef/cookbooks/ceilometer/recipes/common.rb

Introduced by https://github.com/crowbar/crowbar-openstack/pull/666
Seems like that was never tested... but we should have expect something like that with PR which such number, right?

Fix mongodb connection settings

---

chef/cookbooks/horizon/files/default/grafana-openstack.json

Display metrics with average 1 min on System Load graph.

Grafana: modify System Load graph

---

chef/cookbooks/monasca/recipes/log_agent.rb
chef/cookbooks/monasca/templates/default/log-agent.conf.erb

Add multi line pattern to monasca-log-agent for openstack
components.

monasca: Add multi line pattern

---

chef/cookbooks/monasca/recipes/master.rb
chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
chef/cookbooks/monasca/templates/default/monasca-agent_agent.yaml.erb
chef/cookbooks/monasca/templates/default/monasca-reconfigure.erb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema
crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
crowbar_framework/config/locales/monasca/en.yml

This pull requests adds a variety of parameters we are currently missing from the Monasca barclamp.

monasca: Add missing parameters

---

chef/cookbooks/monasca/attributes/default.rb

The attribute is used in some helper funcitons.

monasca: Add the [:ha][:enabled] attribute

---

chef/cookbooks/monasca/recipes/master.rb

This commit fixes the listening address for monasca backend
services (It erroneously contained the Crowbar node's admin
interface address. The services in question do not run on the
Crowbar node, though).

monasca: fix listening address

---

chef/data_bags/crowbar/template-sahara.json

This is tech preview, so it doesn't hurt to expose more things by
default.

sahara: Add MapR and Storm to plugins enabled by default (fate#323275)

---

chef/cookbooks/neutron/recipes/common_agent.rb
crowbar_framework/app/models/neutron_service.rb

With ovs, when the vlan type driver is used, we usually have a br-fixed
network to deal with vlan networks.
However, when the floating network is not using vlan and is on the same
conduit as the fixed network, then the underlying interface for br-fixed
and br-public is going to be the same. And of course it can't be in both
bridges. This results in the interface moving from one to the other
during a chef run, creating some network outage.
The solution is to simply merge br-fixed in br-public for that case.
We only need fixes on the rails side, as the cookbook side was fixed
with https://github.com/crowbar/crowbar-openstack/pull/128
https://bugzilla.suse.com/show_bug.cgi?id=1040396

neutron: Avoid conflict between br-fixed and br-public (bsc#1040396)

---

chef/cookbooks/heat/recipes/server.rb

We were doing calls to keystone during the compile phase
to obtain the domain id for heat. This can cause issues
when changing the keystone endpoint protocol.
This patch moves the gathering of the domain id to the
execution phase and makes the variables for the heat
config template to be lazy, so the execution is delayed
until the template is written.
Here its the example for the proper use of `lazy` for template variables: https://github.com/chef-boneyard/chef-web-docs-2016/blob/master/includes_resources_common/includes_resources_common_lazy_evaluation.rst
Needed for https://github.com/crowbar/crowbar-openstack/pull/859

heat: move keystone-dependant resource to execute phase

---

chef/data_bags/crowbar/migrate/cinder/108_remove_nfs_mount_options.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema

We've mixed 2 changes with migration 107:
- https://github.com/crowbar/crowbar-openstack/pull/883
- https://github.com/crowbar/crowbar-openstack/pull/972

cinder: Fix broken migration

---

chef/cookbooks/heat/templates/default/heat.conf.erb

Tempest seems to pass with this change.

heat: revert to using older config options

---

crowbar_framework/app/models/keystone_service.rb

Before this patch, we modified the role and saved it which
caused the crowbar-revision to inscrease, which could lead to
desynchronization when applying a barclamp to a subset of
the keystone-server nodes.
This patch avoid that by directly saving the endpoint information
to the keystone-server nodes after the chef run, plus as a side
effect simplifies the code by avoiding any role modification
before the chef run is done.

keystone: better keystone http/https change logic (bsc#1044266)

---

crowbar_framework/app/models/keystone_service.rb

Before this patch, we modified the role and saved it which
caused the crowbar-revision to increase, which could lead to
desynchronization when applying a barclamp to a subset of
the keystone-server nodes.
This patch avoids that by directly saving the endpoint information
to the keystone-server nodes after the chef run, plus as a side
effect, simplifies the code by avoiding any endpoint attributes
modification before the chef run is done as its not really needed.
(cherry picked from commit 4d8a928af1be899394b3f9ef56187a060676611c)

[4.0] keystone: better keystone http/https change logic (bsc#1044266)

---

monasca.yml

I think we can flick the switch on this one now.

monasca: show Monasca barclamp

---

chef/cookbooks/monasca/attributes/default.rb
chef/cookbooks/monasca/libraries/helper.rb
chef/cookbooks/monasca/recipes/server.rb

(cherry picked from commit 771c4cdf68324b00e159dd8dadb794b20374bb0b)

monasca: Register logs endpoints in keystone

---

chef/cookbooks/horizon/files/default/grafana-monasca.json
chef/cookbooks/horizon/files/default/grafana-openstack.json

Requires backporting to stable/4.0

monasca: Hardwire grafana timezone to UTC

---

chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/recipes/client.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/mysql/templates/default/my.cnf.erb

Backport of https://github.com/crowbar/crowbar-openstack/pull/1003

Fix mysql cookbook

---

chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/nova/attributes/default.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/recipes/database.rb
chef/cookbooks/nova/recipes/placement_api.rb
chef/cookbooks/nova/recipes/role_nova_controller.rb
chef/cookbooks/nova/templates/default/nova-placement.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/migrate/nova/200_placement_api.rb
chef/data_bags/crowbar/migrate/nova/201_discover_hosts_in_cells_interval.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/models/nova_service.rb

The nova-placement-api service is mandatory in Ocata.

Enable Ocata for SOC8

---

chef/cookbooks/keystone/recipes/server.rb

During the deployment of the keystone barclamp on an
HA cluster, it was observed that the apache service was
being restarted on a controller node (due to a delayed
reload action) while on another controller node the
default users/tenants/domains/etc. were being created.
This caused the second node to fail deploying the barclamp,
because there was a small time window during which the
keystone WSGI entry points on one of the controller nodes
could not be accessed.
This commit fixes this problem by ensuring two things:
- the default users/roles/domains/etc. are only created
by the cluster founder node
- an additional synchronization marker is used at the
beginning of the section that creates the keystone
objects to ensure that keystone services are properly
configured and running on all …

keystone: fix ha race condition during default objects creation

---

chef/cookbooks/magnum/recipes/post_install.rb

Magnum: get insecure values from databag

---

chef/cookbooks/database/libraries/crowbar.rb
chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
crowbar_framework/app/models/database_service.rb

Requires https://github.com/crowbar/crowbar-ha/pull/215

HAProxy setup for mariadb (galera) cluster

---

chef/cookbooks/database/libraries/crowbar.rb
chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
crowbar_framework/app/models/database_service.rb

Backport of https://github.com/crowbar/crowbar-openstack/pull/1123

[stable/4.0] HAProxy setup for mariadb (galera) cluster

---

chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/barbican/recipes/common.rb
chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/ec2-api/recipes/ec2api.rb
chef/cookbooks/glance/recipes/common.rb
chef/cookbooks/heat/recipes/server.rb
chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/magnum/recipes/common.rb
chef/cookbooks/manila/recipes/common.rb
chef/cookbooks/neutron/recipes/database.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/sahara/recipes/common.rb
chef/cookbooks/trove/libraries/helpers.rb
chef/cookbooks/trove/recipes/api.rb
chef/cookbooks/trove/recipes/conductor.rb
chef/cookbooks/trove/recipes/taskmanager.rb

Not tested yet and needs to be done for all barclamps.

database: Move connection string creation to a helper

---

chef/cookbooks/mysql/recipes/server.rb

Backport from https://github.com/crowbar/crowbar-openstack/pull/1112

[4.0] mysql: Drop test database

---

chef/cookbooks/ironic/attributes/default.rb
chef/cookbooks/ironic/libraries/helpers.rb
chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/templates/default/nova.conf.erb
crowbar_framework/app/models/neutron_service.rb

Ironic neutron decouple fp

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/files/default/neutron-l3-ha-service.rb
chef/cookbooks/neutron/libraries/helpers.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb
chef/cookbooks/neutron/templates/default/neutron-l3-ha-service.service.erb
spec/neutron_helpers_spec.rb
spec/neutron_l3_ha_service_spec.rb

Import from https://github.com/crowbar/crowbar-openstack/pull/840

Turn neutron-ha-tool into a service

---

chef/cookbooks/manila/recipes/common.rb

Manila: get insecure values from databag

---

crowbar_framework/app/models/monasca_service.rb

Node with monasca-server deploys its own mariadb instances.
Let's not mix it with OpenStack database (now using mariadb as well).

Do not deploy monasca-server to the node running database cluster

---

crowbar_framework/app/models/monasca_service.rb

Node with monasca-server deploys its own mariadb instances.
Let's not mix it with OpenStack database that can use mariadb as well.
If we'd want to use shared database for both usages, ansible based
monasca-installer has to be adapted.
(cherry picked from commit 417d0578a8ae4a7de3b53faee9146bec0f31a840)
Backport of https://github.com/crowbar/crowbar-openstack/pull/1205

[4.0] monasca: Do not deploy monasca-server to the node running mariadb

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/mysql/templates/default/galera.cnf.erb
chef/data_bags/crowbar/template-database.schema
crowbar_framework/app/models/database_service.rb

Backport of https://github.com/crowbar/crowbar-openstack/pull/1171

[4.0] Set State Snapshot Transfer Settings

---

chef/cookbooks/mysql/recipes/ha_galera.rb

If bootstrapping fails, we have to raise some error and
do not wait in the endless loop.
(cherry picked from commit 7a595f1cdbdf8854fa69b9173d0f7274bba8136a)

[4.0] mysql: Add a timeout to galera bootstrapping

---

chef/cookbooks/keystone/recipes/server.rb

When we do a apache2 restart action, as the apache2 service is declared
on the apache2 cookbook, we have no idea of what triggered the restart
for it.
This makes it a problem to differentiate between the different cookbooks
calling the restart for the service, if we want to introduce a feature
to avoid restarts based on origin/barclamps.
This PR introduces a ruby_block that sets a temporal key on the node
when apache2 is restarted, to flag where the restart was triggered from.
The run_state values are ephemeral so we dont modify the node attributes
at all.
(cherry picked from commit 27150506dad11ff529da81ad261f5633c5a694ed)

[4.0] keystone: Set an origin flag on apache2 restart

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/data_bags/crowbar/migrate/neutron/112_cloud_data_center_id.rb
chef/data_bags/crowbar/template-neutron.json
crowbar_framework/app/models/neutron_service.rb
crowbar_framework/config/locales/neutron/en.yml

Backport of https://github.com/crowbar/crowbar-openstack/pull/1094

[4.0] Fixes for Infoblox (bsc #1047881)

---

chef/cookbooks/mysql/recipes/ha_galera.rb

This way, when haproxy is running on a node, it primarily directs
mariadb database traffic to the same node.

mysql: Set the current node as non-backup server in haproxy config (SCRD-1209)

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/data_bags/crowbar/migrate/cinder/051_add_max_over_subscription_ratio.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema
crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml
crowbar_framework/config/locales/cinder/en.yml

cinder: netapp: add max_over_subscription_ratio

---

chef/cookbooks/database/libraries/provider_database_mysql_user.rb
chef/cookbooks/mysql/recipes/server.rb

Backport of https://github.com/crowbar/crowbar-openstack/pull/1326

[4.0] Drop anonymous MariaDB users (bsc#1060628)

---

chef/cookbooks/nova/templates/default/nova.conf.erb
chef/data_bags/crowbar/template-nova.json

respect image_cache_manager_interval set in proposal
and change the default back to 0
backport of #1243

nova: respect image_cache_manager_interval set in proposal (bsc#1057233)

---

chef/cookbooks/rabbitmq/recipes/default.rb

revert commit https://github.com/crowbar/crowbar-openstack/commit/0dd6cc373e97832e0738bd2c8fe537eb4782cb7f as the underlying problem has been fixed

revert commit 0dd6cc373e97832e0738bd2c8fe537eb4782cb7f 

---

chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/recipes/ha_galera.rb

backport of: https://github.com/crowbar/crowbar-openstack/pull/1250

[4.0] mariadb: Increase timeout for the promote operation

---

chef/cookbooks/barbican/recipes/common.rb

By creating the config file before running the initial database sync we
can remove the addtional db connection parameter from the "barbican db
upgrade" call. Which brings the recipe more in sync with how we do
things in the other barclamps.
It also avoid a shell escaping issues with db_connection uri that
contain special character like '&' that would cause issues on the
shell. (e.g. for ssl enabled MariaDB we add some ssl parameters to it
via "&ssl...=")
(cherry picked from commit f8a60069fd2be27a4a34dcf1811f06bed989778a)
Backport of: https://github.com/crowbar/crowbar-openstack/pull/1377

barbican: reorder config creation and initial db sync

---

chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/barbican/recipes/common.rb
chef/cookbooks/ceilometer/recipes/server.rb
chef/cookbooks/cinder/recipes/sql.rb
chef/cookbooks/database/libraries/provider_database_mysql.rb
chef/cookbooks/database/libraries/provider_database_mysql_user.rb
chef/cookbooks/ec2-api/recipes/ec2api.rb
chef/cookbooks/glance/recipes/common.rb
chef/cookbooks/heat/recipes/server.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb
chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/magnum/recipes/sql.rb
chef/cookbooks/manila/recipes/sql.rb
chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/neutron/recipes/database.rb
chef/cookbooks/nova/recipes/database.rb
chef/cookbooks/sahara/recipes/sql.rb
chef/cookbooks/trove/recipes/sql.rb

backport of https://github.com/crowbar/crowbar-openstack/pull/1289

[stable/4.0] Require SSL connection to database if MariaDB SSL is configured

---

chef/cookbooks/manila/recipes/api.rb

Remove unneeded code, oversight from a copy'n paste excerise. No
functional change

manila: tiny code cleanups after wsgi merge

---

crowbar_framework/app/models/nova_service.rb

By using skip_batch_for_node? we can avoid running chef on nodes that do
not change role and if there is no attribute change for the barclamp.
Does not skip remote HA nodes, nodes that have changed roles, all nodes if
attributes have changed and when deploying the barclamp for the first
time.
(cherry picked from commit ce4e336528e62cb7cf8373e6986069bd4939a008)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1385

[4.0] nova: skip unchanged nodes chef-run

---

crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml

It's really not a setting that people will likely change.

database: Hide mysql datadir setting in UI

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/templates/default/galera.cnf.erb

btw, there's gonna be conflict with https://github.com/crowbar/crowbar-openstack/pull/1410

mysql: Make sure mysqld listens on admin ip for cluster traffic (bsc#1068393)

---

chef/cookbooks/barbican/recipes/ha.rb

Fixes misspelling of keystone-listener in services list

Fixes misspelling of keystone-listener

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/mysql/templates/default/galera.cnf.erb
chef/cookbooks/mysql/templates/default/tuning.cnf.erb
chef/data_bags/crowbar/migrate/database/207_add_more_tuning.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

See http://pastebin.nue.suse.com/18851/src for mysqltuner output

mysql: config file tuning based on mysqltuner suggestions

---

chef/cookbooks/mysql/attributes/server.rb
chef/cookbooks/mysql/recipes/ha_galera.rb

Please don't not merge yet. As this will break 10.1 deployments.

mariadb: Fixes for mariadb 10.2

---

chef/cookbooks/nova/recipes/database.rb

If "nova-manage api_db sync" is called first during the upgrade from Newton, it complains about cell0/cell1 not being prepared.

nova: Call "nova-manage api_db sync" after cell0/cell1 are managed

---

chef/cookbooks/mysql/templates/default/galera.cnf.erb
chef/cookbooks/mysql/templates/default/tuning.cnf.erb
chef/data_bags/crowbar/migrate/database/108_add_innodb_tuning.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema

Backport of https://github.com/crowbar/crowbar-openstack/pull/1445

[4.0] Galera tuning parameters from reading logfiles

---

chef/cookbooks/keystone/recipes/server.rb

if we're unlucky and resources are migrated then we have
more than one rotation per hour:
-rw------- 1 keystone keystone   44 18. Dez 03:15 1432
-rw------- 1 keystone keystone   44 18. Dez 03:30 1433
-rw------- 1 keystone keystone   44 18. Dez 04:30 1434
This is when the node that was previously owning the token
rotation is taken out/rebooted/fenced, so allocate some slack.
[UNTESTED]

keystone: add extra rotation buffer for fernet in HA cluster

---

chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/nova/templates/default/nova.conf.erb

Reduce clogging of database connections

---

chef/cookbooks/neutron/recipes/cisco_apic_agents.rb
chef/cookbooks/neutron/recipes/common_agent.rb
chef/cookbooks/neutron/templates/default/openvswitch_agent.ini.erb

Fixes conditional statements for openvswitch_agent.ini.erb.

[neutron]: backport from #1499

---

chef/cookbooks/ironic/libraries/helpers.rb

Small fix to the env based handling of auth parameters.

ironic: Fix regression in helper

---

chef/cookbooks/keystone/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb

Some followup changes for fernet-keys-sync feature. See commit messages for details.

Fernet keys sync polish

---

chef/cookbooks/neutron/attributes/default.rb
chef/cookbooks/neutron/recipes/cisco_apic_support.rb
chef/cookbooks/neutron/recipes/cisco_support.rb
chef/cookbooks/neutron/recipes/server.rb

This enables people to override values in these files with snippets.
Followup to https://github.com/crowbar/crowbar-openstack/pull/1466

neutron: Put ML2 Cisco config files as snippets in neutron.conf.d

---

chef/cookbooks/nova/attributes/default.rb
chef/cookbooks/nova/definitions/nova_package.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/nova/recipes/controller_ha.rb
chef/cookbooks/nova/recipes/database.rb
chef/cookbooks/nova/recipes/placement_api.rb
chef/cookbooks/nova/recipes/role_nova_controller.rb
chef/cookbooks/nova/templates/default/nova-placement.conf.erb
chef/data_bags/crowbar/migrate/nova/123_placement_api.rb
chef/data_bags/crowbar/template-nova.json
chef/data_bags/crowbar/template-nova.schema
crowbar_framework/app/models/nova_service.rb

[UNTESTED]
The Placement API is a prerequisite for switching to Ocata/Pike ,so we need to release it as a maintenance update for SOC7 in order to enable upgrading to Cloud 8.

[4.0] Backport Nova Placement API

---

chef/cookbooks/neutron/recipes/common_agent.rb
crowbar_framework/app/models/cinder_service.rb
crowbar_framework/lib/openstack/ha.rb

Backport of https://github.com/crowbar/crowbar-openstack/pull/1583

[4.0] Fixes needed for adding a node into existing cluster

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/data_bags/crowbar/migrate/cinder/207_add_pure_backend.rb
chef/data_bags/crowbar/template-cinder.json
chef/data_bags/crowbar/template-cinder.schema
crowbar_framework/app/helpers/barclamp/cinder_helper.rb
crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml
crowbar_framework/config/locales/cinder/en.yml

Adds config to the UI, locale, cinder.conf, cinder schema
and add migration.

cinder: Add Pure Storage FlashArray config to cinder barclamp

---

chef/cookbooks/nova/recipes/database.rb

cell1 was created only during the upgrade, so all instances that existed
before the upgrade need to be explicitely mapped to cell1.
See also: https://jira.prv.suse.net/browse/SCRD-2303

nova: After upgrading controller to Pike, map the instances to cell1

---

chef/cookbooks/cinder/recipes/sql.rb

The Pike release of OpenStack Cinder requires the live migrations
in Ocata to be complete. A check in the database sync at version
97 enforces this.
This patch follows the conventions established in our Nova upgrade:
1. db sync up to version 96
2. Run the required live-migrations
3. Complete the database sync
We are skipping the Ocata release and instead running the migrations
from a Pike codebase. However, Pike's sqlalchemy models include an
extra column to the groups database table that is therefore required
for the live migrations. Thus, we will copy the column creation from                                                                                                                                               
db version 102 into a placeholder at 96. This will ensure the column
is …

upgrade: cinder: run live migrations at correct rev

---

crowbar_framework/app/models/manila_service.rb

Such scenario is not supported by non-disruptive upgrade.
User can still place the role to compute nodes manually, this only
affects automatic allocation.
I think this should fix the problem where upgrade jobs think they are doing disruptive upgrade although the configuration was prepared for non-disruptive one. See https://jira.prv.suse.net/browse/SCRD-4051

Do not automatically put manila-share roles to compute nodes

---

chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/database/attributes/default.rb
chef/cookbooks/database/libraries/crowbar.rb
chef/cookbooks/database/libraries/database_library.rb
chef/cookbooks/database/recipes/role_database_server.rb
chef/cookbooks/database/recipes/role_mysql_server.rb
chef/cookbooks/mysql/recipes/ha_galera.rb
chef/cookbooks/mysql/recipes/server.rb
chef/cookbooks/postgresql/recipes/ha.rb
chef/cookbooks/postgresql/recipes/ha_storage.rb
chef/cookbooks/postgresql/recipes/server.rb
chef/cookbooks/postgresql/recipes/server_debian.rb
chef/cookbooks/postgresql/recipes/server_redhat.rb
chef/data_bags/crowbar/migrate/database/109_separate_db_roles.rb
chef/data_bags/crowbar/template-database.json
chef/data_bags/crowbar/template-database.schema
chef/roles/database-server.rb
chef/roles/mysql-server.rb
crowbar_framework/app/helpers/barclamp/database_helper.rb
crowbar_framework/app/models/database_service.rb
crowbar_framework/app/models/monasca_service.rb
crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
crowbar_framework/config/locales/database/en.yml

This is the extension of https://github.com/crowbar/crowbar-openstack/pull/1691 with followup fixes
Please read the original PR for more details and TODO.

[4.0] split database-server role into backend specific roles

---

chef/cookbooks/horizon/recipes/server.rb

When Horizon in deployed via a autogenerated self certificate, the
current code will generate a different one of each node in the
cluster.
This patch will generate a single certificate in the founder, and
share it with the rest of the cluster via `rsync`.

Synchronize SSL in the cluster (bsc#1081518)

---

chef/cookbooks/horizon/recipes/server.rb

When Horizon in deployed via a autogenerated self certificate, the
current code will generate a different one of each node in the
cluster.
This patch will generate a single certificate in the founder, and
share it with the rest of the cluster via `rsync`.
(cherry picked from commit b264c759f862d4b81e0a67095032e156965a17e3)

[5.0] Synchronize SSL in the cluster (bsc#1081518)

---

chef/cookbooks/nova/recipes/config.rb

nova-placement-api service is behing WGSI (apache2), and in order
to reload it when nova-placement.conf file change, we need to
create a proxy service.
This proxy will signal the WSGI apache modules for a reload,
without a full restart of apache service.
(cherry picked from commit db813e1ce3042eb17214532063ac8de9557fec98)

[4.0] nova: reload nova-placement-api (bsc#1103383)

---

chef/cookbooks/glance/recipes/api.rb

[4.0] glance: Fix ironic related glance code

---

chef/cookbooks/horizon/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/nova/recipes/controller_ha.rb

This is forward port of #1741 with modifications to make it compatible with #1492 and #1240

[5.0] keystone: Always try to rsync keys to new nodes

---

chef/cookbooks/horizon/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/nova/recipes/controller_ha.rb

This is forward port of #1741 with modifications to make it compatible with #1492 and #1240

keystone: Always try to rsync keys to new nodes 

---

chef/cookbooks/nova/recipes/flavors.rb

Instead of creating the flavor list during the compilation
phase, do it on the converge phase as we will get the most
up-to-date list of flavors.
Also, separate the command that obtains the flavor list so its
resilent to temporal failures of the nova api while obtaining the
list of flavors as to not break the flavor creation that follows
(cherry picked from commit 457a94b39708e20ef1242becc96bef8204bcff4d)
Backport-of: https://github.com/crowbar/crowbar-openstack/pull/1507

[4.0] nova: move flavor creation to converge phase

---

chef/cookbooks/cinder/templates/default/cinder.conf.erb
chef/cookbooks/crowbar-openstack/libraries/helpers.rb
chef/cookbooks/glance/templates/default/glance-api.conf.erb
chef/cookbooks/glance/templates/default/glance-registry.conf.erb
chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/cookbooks/nova/templates/default/nova.conf.erb
chef/cookbooks/tempest/recipes/config.rb
chef/data_bags/crowbar/migrate/rabbitmq/205_add_notifications.rb
chef/data_bags/crowbar/template-rabbitmq.json
chef/data_bags/crowbar/template-rabbitmq.schema
crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml
crowbar_framework/config/locales/rabbitmq/en.yml

[5.0] make notifications optional

---

chef/cookbooks/keystone/providers/register.rb
chef/data_bags/crowbar/migrate/keystone/205_remove_updated_password.rb
chef/data_bags/crowbar/template-keystone.json
crowbar_framework/app/models/rabbitmq_service.rb

Backport of #1723, #1740 and fixes an incorrect backport of #1365

[Stable/5.0 pike] Backport keystone, nova, rabbitmq bugfixes

---

chef/cookbooks/neutron/definitions/neutron_metadata.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb

In order to free some connections to rabbitmq the neutron
metadata agent is disabled in computer nodes if the
force_metadata flag is set to true. The pacemaker
primitive is removed as well if exists.
(cherry picked from commit 098b3a478bd9e78bb8c4bf112afd46f2f568846a)
backported from #1762

[4.0] Neutron: disable metadata agent service if not necessary

---

chef/cookbooks/horizon/recipes/server.rb

With those enabled we just have a crash on rendering the
horizon navbar. to be investigated

horizon: disable installing neutron horizon plugins  (bsc#1111421) 

---

crowbar_framework/app/models/ceilometer_service.rb
crowbar_framework/config/locales/ceilometer/en.yml

[4.0] ceilometer: require rabbitmq notifications 

---

chef/cookbooks/keystone/providers/fernet.rb
chef/cookbooks/keystone/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/resources/fernet.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb
chef/cookbooks/nova/recipes/controller_ha.rb

[5.0] keystone: Reorganize HA/fernet code

---

chef/cookbooks/keystone/providers/fernet.rb
chef/cookbooks/keystone/recipes/ha.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/resources/fernet.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb
chef/cookbooks/nova/recipes/controller_ha.rb

forward port of #1772 (with parts from #1852)

keystone: Reorganize HA/fernet code

---

chef/cookbooks/tempest/recipes/install.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

Add the tempest plugins for services we care about at the moment.
barbican, heat, and monasca are being added in #1611.

add tempest plugins

---

chef/cookbooks/nova/recipes/flavors.rb

Use just one client instead of mixing and matching. This makes the code
easier to maintain, but more importantly the OS_ENDPOINT_TYPE does not
work very well with python-openstackclient so it shouldn't be used with
both clients.

nova: Convert flavor recipe to use openstackclient

---

chef/cookbooks/crowbar-openstack/libraries/provider_ssl_setup.rb

This ports the original ACL fix change and the fix for that change.

[5.0] Fix SSL ACL setup

---

chef/cookbooks/cinder/recipes/api.rb
chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
chef/cookbooks/keystone/providers/register.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/recipes/update_endpoint.rb
chef/cookbooks/keystone/resources/register.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/templates/default/nova.conf.erb

Backport of https://github.com/crowbar/crowbar-openstack/pull/1919

[5.0] Fix SSL (bsc#1114851)

---

chef/cookbooks/cinder/recipes/api.rb
chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
chef/cookbooks/keystone/providers/register.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/keystone/recipes/update_endpoint.rb
chef/cookbooks/keystone/resources/register.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/nova/recipes/api.rb
chef/cookbooks/nova/templates/default/nova.conf.erb

Backport of https://github.com/crowbar/crowbar-openstack/pull/1919/

[4.0] Fix SSL (bsc#1114851)

---

chef/cookbooks/keystone/recipes/server.rb
crowbar_framework/lib/openstack/upgrade.rb

This introduces the needed changes in the keystone cookbook for reducing its downtime during the upgrade.  Needs to get merged together with https://github.com/crowbar/crowbar-core/pull/1748

upgrade: reduce keystone downtime

---

chef/cookbooks/horizon/recipes/monasca_ui.rb

In HA clouds, Grafana is started on all controllers. Upon first startup,
Grafana will run database migrations. If this happens concurrently on more than
one node, Grafana's database schema may end up in an inconsistent state. This
pull request ensures Grafana starts on the cluster founder first so the
migrations only happen there.

horizon: fix Grafana in HA clouds (bsc#1116846)

---

crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml

This is a replacement for package patch to simplify future modifications
to the sources without causing conflicts.
(cherry picked from commit 8df86463d039a2cbb6a86dfd155dfbb286d393e1)
port of #1769

database: Hide SSL options from database UI

---

chef/cookbooks/nova/recipes/ceph.rb

These are various fixes to make the ceph integration work better in Cloud 8+

nova: cleanup ceph key handling

---

crowbar_framework/app/assets/javascripts/barclamps/monasca/application.js
crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
crowbar_framework/config/locales/monasca/en.yml

Update Monasca barclamp UI to new configuration option names [e4f9ccbf1b236c1f42a86e04ce4bb395f4aec237] for
notification engine.

monasca: Update notification config in UI

---

chef/cookbooks/monasca/recipes/database.rb
chef/cookbooks/monasca/recipes/monasca_api.rb

Use `monasca_db` schema migration command to install the configuration
database schema for Monasca.

monasca: Use `monasca_db` for installing DB schema (SCRD-7422)

---

bin/crowbar_designate
chef/cookbooks/designate/README.md
chef/cookbooks/designate/attributes/default.rb
chef/cookbooks/designate/definitions/designate_service.rb
chef/cookbooks/designate/libraries/helpers.rb
chef/cookbooks/designate/metadata.rb
chef/cookbooks/designate/recipes/api.rb
chef/cookbooks/designate/recipes/common.rb
chef/cookbooks/designate/recipes/ha.rb
chef/cookbooks/designate/recipes/monitor_monasca.rb
chef/cookbooks/designate/recipes/role_designate_server.rb
chef/cookbooks/designate/recipes/role_designate_worker.rb
chef/cookbooks/designate/recipes/sql.rb
chef/cookbooks/designate/recipes/worker.rb
chef/cookbooks/designate/templates/default/designate.conf.erb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/neutron/templates/default/neutron.conf.erb
chef/data_bags/crowbar/migrate/neutron/305_add_designate_domain.rb
chef/data_bags/crowbar/template-designate.json
chef/data_bags/crowbar/template-designate.schema
chef/data_bags/crowbar/template-neutron.json
chef/data_bags/crowbar/template-neutron.schema
chef/roles/designate-server.rb
chef/roles/designate-worker.rb
crowbar_framework/app/controllers/designate_controller.rb
crowbar_framework/app/models/designate_service.rb
crowbar_framework/app/views/barclamp/designate/_edit_attributes.html.haml
crowbar_framework/config/locales/designate/en.yml
designate.yml

PR #1707 was fairly long, so lets use this to get this merged

Designate barclamp

---

chef/cookbooks/glance/recipes/api.rb

In bdf0cce we removed the glance-registry recipe which also removed the
glance-manage db_sync and glance-manage db_load_metadefs executions. We
didn't notice this was a problem at first because it seems that the
glance API service is capable of running the db sync itself, but the
metadef loading was still not happening. This causes tempest failures
because the contents of GET /v2/metadefs/resource_types will be empty.
This patch fixes the issue by adding back this setup steps for the API
service.

glance: run db sync and load metadefs

---

chef/cookbooks/ceilometer/recipes/central_ha.rb
chef/cookbooks/neutron/recipes/network_agents_ha.rb
chef/cookbooks/nova/recipes/compute_ha.rb

The correct resource to base ordering on is ms-galera not galera.

openstack: Fix depedency ordering name for galera

---

chef/cookbooks/tempest/recipes/config.rb

Print stdout and stderr in case the openstack CLI call fails to get
the floating network ID.
Currently it's difficult to know why getting the floating network ID
fails. The error message is just:
RuntimeError: Cannot fetch ID of floating network
This currently happens in the monasca CI job.

tempest: Improve error message when getting the floating ID

---

chef/cookbooks/monasca/attributes/default.rb
chef/cookbooks/monasca/libraries/cassandra_helper.rb
chef/cookbooks/monasca/libraries/helper.rb
chef/cookbooks/monasca/recipes/cassandra.rb
chef/cookbooks/monasca/recipes/database.rb
chef/cookbooks/monasca/recipes/monasca_api.rb
chef/cookbooks/monasca/recipes/monasca_persister_java.rb
chef/cookbooks/monasca/recipes/role_monasca_server.rb
chef/cookbooks/monasca/templates/default/cassandra.yaml.erb
chef/cookbooks/monasca/templates/default/monasca-api.conf.erb
chef/cookbooks/monasca/templates/default/monasca-persister-java.yaml.erb
chef/data_bags/crowbar/migrate/monasca/314_move_tsdb_setting.rb
chef/data_bags/crowbar/template-monasca.json
chef/data_bags/crowbar/template-monasca.schema
crowbar_framework/app/models/monasca_service.rb
crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
crowbar_framework/config/locales/monasca/en.yml

The change adds the option to install Apache Cassandra as the TSDB.
Currently only single node installation is supported.
Choosing this option implicitly installs Java implementation of
monasca-persister.

monasca: Add Apache Cassandra support (SCRD-6731)

---

chef/cookbooks/database/libraries/provider_database_mysql_user.rb

Currently the create action for mysql database does not check of changed
password.
Without this patch if the admin changes database password, this change
will be applied to the config files however the database is not informed
about this change. As a result that service has looses access to the
database.
This patch relies on the mysql.user table of the database to check of
user existence as well as password hash matching.  Every "input" to
any query is quoted before usage, to avoid any security related error.
An alternate approach to this would be to check if the user connect to
the database with the given credentials, but that requires determining
the correct host string which is not readily available in this context
and will require collecting user specific connection params (including …

database: apply password update (SCRD-8438)

---

chef/cookbooks/neutron/templates/default/neutron_lbaas.conf.erb

Unlikey everywhere else, the key to set is region not region_name

neutron: properly define region (bsc#1128753)

---

chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/horizon/templates/default/local_settings.py.erb

We need to tell horizon that certain features are available
via configuration file.

horizon: properly handle DVR and HA routers in the UI

---

chef/cookbooks/neutron/templates/default/neutron_lbaas.conf.erb

[5.0] Neutron LBaaS fixes

---

chef/cookbooks/ironic/libraries/helpers.rb

**This is just to fix the CI**
Small fix to the env based handling of auth parameters.
(cherry picked from commit 346606f9ef0e66b4d5d76faeb274cf6977fdf9b3)
backport of #1541

[4.0] ironic: Fix regression in helper

---

chef/cookbooks/neutron/recipes/network_agents_ha.rb

Backport of  #2112 and Backport of #2116

[5.0] Fix neutron-ha-tool restart on configuration changes

---

crowbar_framework/lib/openstack/upgrade.rb

Since clone_stateless_services attribute was dropped in
1cf82d3ff3142a700ac0e2c55c20944bf364e868 and implicitly set to false,
we don't need some parts of code which were active when it was set to
true.

Cleanup clone_stateless_services leftovers (SOC-9842)

---

chef/cookbooks/designate/recipes/common.rb
chef/cookbooks/designate/templates/default/designate.conf.erb
chef/data_bags/crowbar/migrate/designate/301_add_resources.rb
chef/data_bags/crowbar/template-designate.json
chef/data_bags/crowbar/template-designate.schema
crowbar_framework/app/models/designate_service.rb
crowbar_framework/app/views/barclamp/designate/_edit_attributes.html.haml
crowbar_framework/config/locales/designate/en.yml

Designate requires a project and a responsible person contact for any
zones it creates, add them into the barclamp configuration with the
first migratation for designate.

designate: Configure resource settings (SOC-9633)

---

chef/cookbooks/designate/recipes/mdns.rb

Designate pools are interesting as they don't use an API, instead
they use a yaml file to manage pools.
The designate barclamp generates a pool file
`/etc/crowbar/pools.crowbar.yaml`, but because we don't know if a user
has modified this file on purpose, we only generate it if it doesn't
already exist.
Further, we need to be careful when we actaully run:
designate-manage pool update
Depending on the pools configured in the yaml file, this could nuke any
settings an admin has gone and changed.
As such, this patch is only running the `pool update` once.
There can me multiple pools, but crowbar is only focused on whatever is
defined in pools.crowbar.yaml.
Running the `pool update` once does mean that if things change in the
dns barclamp, these changes would not get reflected in the designate …

Designate: Update DB pools configuration (SOC-9767)

---

chef/cookbooks/designate/recipes/mdns.rb

Designate pools are interesting as they don't use an API, instead
they use a yaml file to manage pools.
The designate barclamp generates a pool file
`/etc/crowbar/pools.crowbar.yaml`, but because we don't know if a user
has modified this file on purpose, we only generate it if it doesn't
already exist.
Further, we need to be careful when we actaully run:
designate-manage pool update
Depending on the pools configured in the yaml file, this could nuke any
settings an admin has gone and changed.
As such, this patch is only running the `pool update` once.
There can me multiple pools, but crowbar is only focused on whatever is
defined in pools.crowbar.yaml.
Running the `pool update` once does mean that if things change in the
dns barclamp, these changes would not get reflected in the designate …

5.0: Designate: Update DB pools configuration (SOC-9767)

---

chef/cookbooks/aodh/recipes/aodh.rb
chef/cookbooks/barbican/recipes/common.rb
chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/cinder/recipes/common.rb
chef/cookbooks/designate/recipes/common.rb
chef/cookbooks/ec2-api/recipes/ec2api.rb
chef/cookbooks/glance/recipes/api.rb
chef/cookbooks/glance/recipes/registry.rb
chef/cookbooks/heat/recipes/server.rb
chef/cookbooks/horizon/recipes/server.rb
chef/cookbooks/ironic/recipes/server.rb
chef/cookbooks/keystone/recipes/server.rb
chef/cookbooks/magnum/recipes/common.rb
chef/cookbooks/manila/recipes/common.rb
chef/cookbooks/memcached/libraries/helpers.rb
chef/cookbooks/neutron/recipes/common_config.rb
chef/cookbooks/nova/recipes/config.rb
chef/cookbooks/sahara/recipes/common.rb
chef/cookbooks/swift/recipes/proxy.rb
chef/cookbooks/swift/recipes/storage.rb
chef/cookbooks/trove/recipes/api.rb
crowbar_framework/app/models/designate_service.rb

Backport-of: #2164, #2197, #2200

[5.0] horizon: Install designate plugin when configured (SOC-9695)

---

chef/cookbooks/horizon/recipes/monasca_ui.rb

In HA clouds, Grafana is started on all controllers. Upon first startup,
Grafana will run database migrations. If this happens concurrently on more than
one node, Grafana's database schema may end up in an inconsistent state. This
pull request ensures Grafana starts on the cluster founder first so the
migrations only happen there.
(cherry picked from commit 2062cc8d4626f20476fd727e019bca3ce2574e34)
port of #1988

[5.0] horizon: fix Grafana in HA clouds (bsc#1116846)

---

chef/cookbooks/designate/recipes/mdns.rb

Added FQDN for all nodes running dns-server.

designate: Update ns_records with all nameservers (SOC-9636)

---

chef/cookbooks/designate/recipes/mdns.rb

Added public FQDN for all nodes running dns-server. This follows
PR 1887 in crowbar-core which when designate is enabled will made
the dns servers listen on the public network.
(cherry picked from commit a5737d9e8c013252a42c3467ac335551ee07c769)

5.0: designate: Update ns_records with all nameservers (SOC-9636)

---

chef/data_bags/crowbar/migrate/keystone/304_add_federation_openidc.rb

Added missing `?` to `defined`.

Fix OpenID migration (SOC-9616)

---

chef/cookbooks/tempest/files/default/run_filters/ceilometer.txt
chef/cookbooks/tempest/files/default/run_filters/manila.txt

Manila see bug SOC-10395
Ceilometer see bug lp 1673738

[5.0] tempest: Skip failing tests (SOC-9799)

---

chef/cookbooks/neutron/templates/default/neutron_lbaas.conf.erb

This is not really configurable via CLI, and 10 is not a production
default. better have no limit.

neutron-lbaas: remove loadbalancer/pool limit

---

chef/cookbooks/designate/recipes/api.rb
chef/cookbooks/designate/recipes/ha.rb

The previous PR merged before I managed to push up some fixes to silence
Hound, and correct the sync marks.

designate: cleanup producer HA deployment (SOC-9766)

---

chef/cookbooks/designate/recipes/api.rb
chef/cookbooks/designate/recipes/ha.rb

The previous PR merged before I managed to push up some fixes to silence
Hound, and correct the sync marks.
(cherry picked from commit 2520d7372df697b15ef54a1f602fb77d9fb39083)

[5.0] designate: cleanup producer HA deployment (SOC-9766)

---

chef/cookbooks/keystone/recipes/ha.rb

For features such as OpenID Connect and SAML-based federation,
where client interaction with Keystone is stateful and the state information
is persisted in the Keystone instance's local cache, we must use source
load balancing so that the client is talking to the same Keystone instance
for the duration of the session.

Use source load balancing for OpenID Connect (SOC-10551)

---

chef/cookbooks/tempest/files/default/run_filters/designate.txt

Add tempest filter to run designate tests

Add tempest filter for designate (SOC-10288)

---

crowbar_framework/app/models/nova_service.rb

We are no longer supporting Xen, so we shouldn't autoselect those
nodes, because that breaks the proposal apply.

nova: Don't autoselect nodes for Xen (bsc#1147144)

---

chef/cookbooks/nova/templates/default/nova.conf.erb

Add pci passthrough filter to default all filters.

Add pci passthrough filter (SOC-10624)

---

chef/cookbooks/tempest/recipes/config.rb

(backport of #2264)
The way that the tempest chef recipe figures out which OpenStack
services can be tested is by inspecting the openstack service
catalogue to retrieve a list of enabled services, instead of
using the barclamp configuration which is more accurate. Worse
even, it does so in the chef compilation phase, before the
running openstack configuration is updated to reflect changes
in the barclamp configuration.
Sometimes, this results in a tempest configuration that doesn't
reflect the list of services that are actuallly deployed. In some of
the more extreme cases, such as updating the admin password, the
OpenStack CLI command used to retrieve the service catalogue
fails completely and returns an empty list, which results in tempest
disabling all services in its configuration. …

[4.0] tempest: don't rely on service catalogue (SOC-10633)

---

chef/cookbooks/horizon/recipes/server.rb

add horizon reload that were removed accidentally by
f7aa3ce change

horizon: add back horizon service reload (SOC-10191)

---

bin/crowbar_watcher
chef/cookbooks/watcher/README.md
chef/cookbooks/watcher/attributes/default.rb
chef/cookbooks/watcher/definitions/watcher_service.rb
chef/cookbooks/watcher/libraries/helpers.rb
chef/cookbooks/watcher/metadata.rb
chef/cookbooks/watcher/recipes/common.rb
chef/cookbooks/watcher/recipes/ha.rb
chef/cookbooks/watcher/recipes/monitor_monasca.rb
chef/cookbooks/watcher/recipes/role_watcher_server.rb
chef/cookbooks/watcher/recipes/server.rb
chef/cookbooks/watcher/templates/default/watcher-api.conf.erb
chef/data_bags/crowbar/migrate/watcher/300_noop.rb
chef/data_bags/crowbar/template-watcher.json
chef/data_bags/crowbar/template-watcher.schema
chef/roles/watcher-server.rb
crowbar_framework/app/assets/javascripts/barclamps/watcher/application.js
crowbar_framework/app/controllers/watcher_controller.rb
crowbar_framework/app/helpers/barclamp/watcher_helper.rb
crowbar_framework/app/models/watcher_service.rb
crowbar_framework/app/views/barclamp/watcher/_edit_attributes.html.haml
crowbar_framework/config/locales/watcher/en.yml
watcher.yml

This PR supersedes https://github.com/crowbar/crowbar-openstack/pull/2132
as it has incorporated the changes from that one alread.

create watcher barclamp (SOC-4183)

---

chef/cookbooks/mysql/recipes/ha_galera.rb

mysql_install_db will attempt to acquire various exclusive
locks on files in /var/lib/mysql before it bootstraps the
database. If the mysql service is already running, it will
hold these same locks, thus preventing mysql_install_db from
working.
This situation can occur if the critical section guarded by
node[:database][:galera_bootstrapped] fails between start and
stop of the temporary mysqld server. This commonly happens if
WSREP replication fails during user creation. In this case,
subsequent barclamp runs will fail due to mysql_install_db
being unable to acquire the locks the leftover mysqld holds.

mysql: stop service for mysql_install_db (SOC-10717)

---

chef/cookbooks/mysql/recipes/ha_galera.rb

This pull request backports the fixes for two bugs breaking Database barclamp deployment under some circumstances/preventing recovery from interrupted deployments:
* https://github.com/crowbar/crowbar-openstack/pull/2285
* https://github.com/crowbar/crowbar-openstack/pull/2288

[5.0] C8 wsrep fixes

---

chef/data_bags/crowbar/migrate/neutron/308_add_opflex_access_integration_bridge.rb

Commit that introduces the problem: cb5347d6a47565c2ef1aebf10ef80d980114e046
This tries to fix the problem introduced with https://github.com/crowbar/crowbar-openstack/pull/2218
~However it's  possibly not good enough as it only checks first entry in the list...~

Fix the migration that tried to access Array as a Hash

---

chef/cookbooks/designate/recipes/common.rb

To avoid weird problems such as race conditions due to
changing Keystone endpoint protocols, admin password, etc.

designate: move keystone resource lookup to convergence (SOC-10887)

---

chef/cookbooks/nova/recipes/compute.rb

Postpone the command into the convergence phase and make
sure it is executed when the input file is there.
Also, postpone the authorized_keys file creation with the use
of lazy evaluation of the variable that was adapted in convergence
phase.
(cherry picked from commit 921e931aea4ce758b3601e465f245a41408fdcf8)

[4.0] Make sure the input file with ssh key exists (SOC-10133)

---

chef/cookbooks/mysql/recipes/ha_galera.rb

This is a Cloud 7 backport of https://github.com/crowbar/crowbar-openstack/pull/2295
This pull request backports the fixes for two bugs breaking Database barclamp deployment under some circumstances/preventing recovery from interrupted deployments:
#2285
#2288
The problem occurs on Cloud 7 as well, which makes the Cloud 7 deployments we still need for upgrade and bugfix testing a game of chance more often than not.

[4.0 Cloud 7 WSREP fixes

---

crowbar_framework/app/views/barclamp/octavia/_edit_attributes.html.haml
crowbar_framework/config/locales/octavia/en.yml

Adds missing SSL attributes section to the Octavia barclamp UI.

octavia: add SSL section to the UI (SOC-10906)

---

chef/cookbooks/designate/attributes/default.rb
chef/cookbooks/designate/recipes/api.rb
chef/cookbooks/designate/templates/default/designate.conf.erb
chef/cookbooks/horizon/recipes/server.rb
chef/data_bags/crowbar/migrate/designate/302_add_ssl_attributes.rb
chef/data_bags/crowbar/template-designate.json
chef/data_bags/crowbar/template-designate.schema
crowbar_framework/app/helpers/barclamp/designate_helper.rb
crowbar_framework/app/views/barclamp/designate/_edit_attributes.html.haml
crowbar_framework/config/locales/designate/en.yml

This change adds support for configuring designate with SSL enabled.

designate: add support for SSL (SOC-10877)

---

chef/cookbooks/tempest/files/default/run_filters/designate.txt

Add tempest filter to run designate tests.

[5.0] Add tempest filter for designate (SOC-10288)

---

chef/cookbooks/designate/recipes/common.rb

To avoid weird problems such as race conditions due to
changing Keystone endpoint protocols, admin password, etc.
(cherry picked from commit 10bc525c770a8b9dc136e71b41b25bfb582392d0)

[5.0] designate: move keystone resource lookup to convergence (SOC-10887)

---

chef/cookbooks/horizon/recipes/server.rb

Adds the Octavia horizon dashboard if Octavia is deployed.
Because the Octavia dashboard and the neutron lbaas dashboard
cannot co-exist, the lbaas dashboard needs to be removed when
Octavia is deployed.
NOTE: this needs the `openstack-horizon-plugin-octavia-ui` to be
created/added to the product first.

horizon: add Octavia horizon dashboard (SOC-10833)

---

chef/cookbooks/tempest/files/default/run_filters/octavia.txt
chef/cookbooks/tempest/recipes/config.rb
chef/cookbooks/tempest/templates/default/tempest.conf.erb

Add a tempest test run filter for the octavia tempest plugin
test cases and adjust the tempest configuration for it.

octavia: enable octavia tempest plugin test cases (SOC-8743)

---

chef/cookbooks/octavia/definitions/octavia_conf.rb

The current logic in the Octavia barclamp does not detect cases where
the IDs of Octavia related resources has changed, but the names of
those resources hasn't. This happens for instance, if the user
deletes the management network for some reason.

octavia: Update configuration parameters (SOC-10904)

---

chef/cookbooks/heat/recipes/server.rb

The code contained some workarounds for openstack client bugs which
were not needed anymore.

heat: Simplify domain registration code + timeout increase (SOC-11103)

---

chef/cookbooks/heat/recipes/server.rb

[5.0]  heat: Simplify domain registration code + timeout increase (SOC-11103) 

---

chef/cookbooks/neutron/libraries/helpers.rb
chef/cookbooks/neutron/recipes/post_install_conf.rb
chef/cookbooks/neutron/recipes/server.rb
chef/cookbooks/neutron/templates/default/ml2_conf.ini.erb
chef/cookbooks/octavia/recipes/nova.rb
crowbar_framework/app/models/neutron_service.rb
crowbar_framework/app/models/octavia_service.rb

Add lb-mgmt-net for Octavia (SOC-10904)

---

octavia.yml

Reverts crowbar/crowbar-openstack#2237

Revert "Octavia: Hide UI until complete (SOC-10550)"

---

chef/cookbooks/magnum/attributes/default.rb
chef/cookbooks/magnum/recipes/common.rb
chef/cookbooks/magnum/templates/default/magnum.conf.erb
chef/data_bags/crowbar/migrate/magnum/202_add_ssl_attributes.rb
chef/data_bags/crowbar/template-magnum.json
chef/data_bags/crowbar/template-magnum.schema
crowbar_framework/app/helpers/barclamp/magnum_helper.rb
crowbar_framework/app/views/barclamp/magnum/_edit_attributes.html.haml
crowbar_framework/config/locales/magnum/en.yml

[5.0] magnum: Add SSL support (SOC-9849)

---

chef/cookbooks/ceilometer/attributes/default.rb
chef/cookbooks/ceilometer/recipes/common.rb
chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
chef/data_bags/crowbar/migrate/ceilometer/303_api_cleanup.rb
chef/data_bags/crowbar/template-ceilometer.json
chef/data_bags/crowbar/template-ceilometer.schema
crowbar_framework/app/helpers/barclamp/ceilometer_helper.rb
crowbar_framework/app/views/barclamp/ceilometer/_edit_attributes.html.haml

Followup for Ceilometer API removal changes from
d7601a374d148033935cb26b183fb7212860a3f6.

ceilometer: Post API removal cleanup (SOC-10124)

---

chef/cookbooks/magnum/recipes/post_install.rb

The conditional to check if the image already exists its not working
properly. There are cases where the openstack command is executed while
the openstack services are restarting causing the command to fail. When
the command fails it means that the image does not exist (which is not
the case) and the image is created again.
This changes decouple the conditional checking of if the image/flavor
exists by moving it to a dedicated ruby block which also do retries (in case
the services are restarting). If for some reason the command fails the
barclamp will also fail.

[4.0] Fix create magnum k8s image and flavor (SOC-11251)

---

chef/cookbooks/magnum/recipes/post_install.rb

Getting current images/flavors needs to be executed at the end of the
barclamp execution (delayed) as there are cases (e.g. changing keystone
api protocol to/from http/https) where the services (glance, nova) needs
to be restarted before running the checks to update its configuration or
it will fail.

[4.0] magnum: fix check for image/flavor (SOC-11251)

---

crowbar_framework/app/models/monasca_service.rb

Pacemaker could fence a cluster node for some reason and having
monasca-server running there would mean monasca going down (bsc#1118759)
(cherry picked from commit 19f2d4e47748e170d207accc1f32f4d9686215ac)
port of #1928

[5.0] monasca: Prevent deploying monasca-server to the node in pacemaker cluster (SOC-6354)

---

chef/cookbooks/monasca/recipes/agent.rb
chef/cookbooks/monasca/recipes/kibana.rb

In the course of the Kibana update from 4.6.3 to 4.6.6,
automatic service restart will not work. Hence, Crowbar needs
to ensure Kibana is restarted.
Note: this forward port also rearranges the permission fixing
code a bit to make it more bullet proof in the presence of two
service resources for kibana (not needed in Cloud 8 since
monasca-installer handles the main legwork of permission fixes
and starting the Kibana service).
(cherry picked from commit bb14b5a328880cdc0687cb92104f6cc0c643fa6a)

monasca: restart Kibana on update (bsc#1044849)
